### ISSUE TITLE
invproj and invgeod symlinks not created by cmake install target

### ISSUE THREAD

**Issue by rouault** [OSGeo/proj.4#2852]
Autoconf builds create a invproj symlink to proj and a invgeod symlink to geod. We don't do this for cmake builds. Is it intentional ?

**Comment by kbevers** [comment]
I don't think that's intentional. I've always found the inv-symlinks a bit weird but if people are using them we should try to recreate it with CMake.

**Comment by mwtoews** [comment]
This could be part of #2688 and I'll investigate, otherwise I'm also ok to not see these with future releases. Windows doesn't do these, for instance.

**Comment by kbevers** [comment]
>  Windows doesn't do these, for instance.

That's a good point. Adding them to Windows would be less painful for users than removing them from everything else though.
