### ISSUE TITLE
Name clash with hdfeos5 include file

### ISSUE THREAD

**Issue by zklaus** [OSGeo/proj.4#2873]
#### Example of problem
[HDFEOS5](https://wiki.earthdata.nasa.gov/display/DAS/Toolkit+Downloads) also uses `proj.h`, which sometimes leads to a clash when both packages are installed.

```c
#include <proj.h>

PJ *P;
```
leading to
```
error: unknown type name 'PJ'; did you mean 'PS'?
```
#### Problem description
The problem really is a simple name clash. This is mitigated by some packagers by moving the hdfeos5 file out of the way, for example in [debian](https://salsa.debian.org/science-team/hdf-eos5/-/blob/debian/master/debian/libhe5-hdfeos-dev.install).
But given that both projects live in a similar space and that hdfeos5 has had the file since 2010, it might be worth considering a more unique file in the future. Alternatively, this could be merely documented and/or discussed with the hdfeos5 people.

#### Environment Information
 - PROJ version >=5

#### Installation method
This is in principle independent of the installation method, but shows up as a problem in conda.

**Comment by rouault** [comment]
From my testing, this is no longer an issue with the latest release of hdfeos5, release v2.0 : https://git.earthdata.nasa.gov/projects/DAS/repos/hdfeos5/raw/hdf-eos5-2.0-src.tar.gz?at=refs%2Fheads%2FHDFEOS5_2.0 . proj.h is no longer in the installed headers:

```
# Headers to install
include_HEADERS = HE5_HdfEosDef.h HE5_GctpFunc.h

EXTRA_DIST = cfortHdf.h cproj.h ease.h HE5_HdfEosDef.h isin.h proj.h tutils.h hdfeos5.inc hdfeos5_64.inc
```

whereas in the previous release v5.1.16 which is the one used by Debian it was:
```
# Headers to install
include_HEADERS = HE5_GctpFunc.h HE5_HdfEosDef.h HE5_config.h cproj.h ease.h \
                  isin.h proj.h tutils.h cfortHdf.h

```
So this is a matter of distributions to upgrade to hdfeos5 v2.0

**Comment by zklaus** [comment]
Fair enough, that resolves the clash. Thanks!
