### ISSUE TITLE
Discrepancy of coordinate transform accuracies

### ISSUE THREAD

**Issue by ghemann** [OSGeo/proj.4#2874]
This may be more of a question than an issue.

I'm digging into coordinate transforms and trying to resolve issues where we have multiple transforms available.  I've been using [this](https://desktop.arcgis.com/en/arcmap/latest/map/projections/pdf/geographic_transformations.pdf) ArcGIS document to understand the accuracies of all the transformations.  I've noticed that while many of the accuracies that are over 1 meter seem to line up with what is in PROJ, I'm not seeing anything correct under 1 meter.

For example, the transform from [2462](https://epsg.io/2462) to 4326 is transformation 7834, and when I run the following
`projinfo -s EPSG:2462 -t EPSG:4326 --spatial-test intersects`
I see OPERATIONACCURACY as 1.0, not as 0.2 as in the document.

Am I looking in the right spot?  Is OPERATIONACCURACY not the same as the accuracy in this document?
Is this document correct?  Are accuracies less than 1 meter rounded?
I'm running with Proj 8.1.0

Any help is appreciated, thanks!

**Comment by rouault** [comment]
PROJ uses the accuracy published in the version of the EPSG dataset that it includes, and https://epsg.org/transformation_7834/Albanian-1987-to-WGS-84-1.html indicates a 1 m accuracy. So either Esri has estimated that it is better than that for their needs, or EPSG has changed the accuracy over versions (but I don't see this by a quick looking)

> Are accuracies less than 1 meter rounded?

No, PROJ displays centimer level accuracy for some transformations

**Comment by ghemann** [comment]
Thanks @rouault , so I'm still seeing some discrepancies though I believe.

For 2881 -> 4326, there are three possible transforms (from epsg.org):
[1580](https://epsg.org/transformation_1580/NAD83-HARN-to-WGS-84-1.html?sessionkey=c43gcvn65l): 2m
[1900](https://epsg.org/transformation_1900/NAD83-HARN-to-WGS-84-2.html?sessionkey=c43gcvn65l): 1m
[1901](https://epsg.org/transformation_1901/NAD83-HARN-to-WGS-84-3.html?sessionkey=c43gcvn65l): 1m

But when running `projinfo -s EPSG:2881 -t EPSG:4326 --spatial-test intersects` and looking at OPERATIONACCURACY for each transform (proj 8.1.0):
1580: 1m
1900: (doesn't show up)
1901: 1m

According to [ESRI](https://desktop.arcgis.com/en/arcmap/latest/map/projections/pdf/geographic_transformations.pdf), they are (which I understand is not what PROJ uses, just here for reference):
1580: 1m
1900: 0.1m
1901: 0.1m

And this [site](https://epsg.io/transform#s_srs=2881&t_srs=4326), which says epsg, but not sure where it pulls from, says accuracy 0.1m.  Is this actually ESRI then?

The key issue I'm trying to identify is why 1901 becomes the default transform for platforms that use the ESRI database but 1580 with PROJ.   The discrepancy between 2m from EPSG and 1m in PROJ for the 1580 transformation is suspicious.   Am I looking at this right?

**Comment by rouault** [comment]
For 1580 going from 1m to 2m, this is related to changeset https://epsg.org/closed-change-request/browse/id/2021.082 . Latest PROJ master with the latest EPSG dataset also reports 2m for 1580.
1900 doesn't show up by default because it was superseded by 1901. If you add ``--show-superseded``, you'll see it.

epsg.io is *not* a reference for EPSG dataset. It is maintained by another team and used an older snapshot of the EPSG dataset.

With latest PROJ master, 1901 is the default
