### ISSUE TITLE
NZTM to WGS84 swaps x and y coordinates

### ISSUE THREAD

**Issue by Deguerre** [OSGeo/proj.4#2875]
#### Example of problem

```c
% echo "1320000 4950000 0" | cs2cs -d 12 EPSG:2193 EPSG:4326
-59.112466467034        -117.473822099122 0.000000000000
% echo "4950000 1320000 0" | cs2cs -d 12 EPSG:2193 EPSG:4326
-45.547192902785        169.413042467151 0.000000000000
```

#### Problem description

Converting NZTM to WGS84 gives an incorrect answer when coordinates are given in XY order. To get the expected output, coordinates must be given in YX order.

projinfo shows an incorrect axisswap step at the start of the pipeline:

```c
% projinfo -q -o proj -s EPSG:2193 -t EPSG:4326
+proj=pipeline +step +proj=axisswap +order=2,1 +step +inv +proj=tmerc +lat_0=0 +lon_0=173 +k=0.9996 +x_0=1600000 +y_0=10000000 +ellps=GRS80 +step +proj=unitconvert +xy_in=rad +xy_out=deg +step +proj=axisswap +order=2,1
```

#### Expected Output

```c
% echo "1320000 4950000 0" | cs2cs -d 12 EPSG:2193 EPSG:4326
-45.547192902785        169.413042467151 0.000000000000
```

For reference, [EPSG.io link](https://epsg.io/transform#s_srs=2193&t_srs=4326&x=1320000&y=4950000).

#### Environment Information
 - proj 7.1.0
 - ubuntu:20.10 Docker container

#### Installation method
 - apt-get install -y proj-bin

**Comment by busstoptaktik** [comment]
NZTM has axis order YX, so this is as expected.

Avoid epsg.io - look it up at epsg.org, where you a.o. can read that it is "Cartesian 2D CS. Axes: **northing, easting (N,E)**. Orientations: north, east. UoM: m"
