### ISSUE TITLE
CRS Equality with PROJ parameter order (REMARK in WKT?)

### ISSUE THREAD

**Issue by snowman2** [OSGeo/proj.4#2886]
From: https://github.com/pyproj4/pyproj/issues/968

Possibly related to #2812 and #2809

#### Example of problem
Only difference is changing order of `+no_rot` and `+alpha`. The difference between using integer versus float values can cause equality issues as well.

```c
PJ_CONTEXT* context = proj_context_create();
PJ* pj = proj_create(
    context,
     "+proj=omerc +lat_0=50 +alpha=50.0 +no_rot +a=6378144.0 +b=6356759.0 +lon_0=8.0 +type=crs"
);
PJ* pj2 = proj_create(
    context,
     "+proj=omerc +lat_0=50 +no_rot +alpha=50.0 +a=6378144.0 +b=6356759.0 +lon_0=8.0 +type=crs"
);
PJ* pj_wkt = proj_create(
    context,
    proj_as_wkt(
        context,
        pj,
        PJ_WKT2_2019,
        nullptr
    )
);
PJ* pj2_wkt = proj_create(
    context,
    proj_as_wkt(
        context,
        pj2,
        PJ_WKT2_2019,
        nullptr
    )
);
proj_is_equivalent_to_with_ctx(context, pj, pj2, PJ_COMP_EQUIVALENT); //false
proj_is_equivalent_to_with_ctx(context, pj_wkt, pj2_wkt, PJ_COMP_EQUIVALENT); //false
proj_is_equivalent_to_with_ctx(context, pj, pj_wkt, PJ_COMP_EQUIVALENT); //false
proj_is_equivalent_to_with_ctx(context, pj2, pj2_wkt, PJ_COMP_EQUIVALENT); //false
proj_destroy(pj);
proj_destroy(pj2);
proj_destroy(pj_wkt);
proj_destroy(pj2_wkt);
proj_context_destroy(context);

```
#### Problem description

Since PROJ 8.1.1 the PROJ parameter order is producing false negatives. It is possible that REMARKS may be causing CRS equality false negatives.

**Comment by rouault** [comment]
I've added " +type=crs" in your PROJ string, as from the pyproj ticket, this was using CRS instanciation

**Comment by snowman2** [comment]
Thanks @rouault 👍

**Comment by djhoese** [comment]
Thanks @rouault! I see that 8.2.0 is planned for November right? Any chance you have the extra time to backport this fix to a 8.1.2 release? If not or if you weren't planning on a 8.1.2 release then no problem. Thank you for the quick fix either way.

**Comment by rouault** [comment]
yes 8.2.0 Nov 1st.  No 8.1.2 planned as far as I know. I see this as a relatively minor issue to be honest

**Comment by djhoese** [comment]
No problem. 8.1.1 is causing issues for the pyresample library in CI because we have a few tests that compare a CRS before and after it goes through some conversion steps. I've worked around a couple of them and I can probably figure out something for the others too. Thanks again.
