### ISSUE TITLE
BUG: concatenated operation + proj_normalize_for_visualization + proj_as_wkt rountrip error

### ISSUE THREAD

**Issue by snowman2** [OSGeo/proj.4#2890]
From: https://github.com/pyproj4/pyproj/issues/967

#### Example of problem

```c
PJ_CONTEXT* context = proj_context_create();
PJ* transform = proj_create_crs_to_crs_from_pj(
    context,
    "EPSG:4326",
    "EPSG:3857",
    nullptr,
    nullptr
);
PJ* xy_transform = proj_normalize_for_visualization(context, transform);
proj_destroy(transform);
PJ* pj_wkt = proj_create(
    context,
    proj_as_wkt(
        context,
        xy_transform,
        PJ_WKT2_2019,
        nullptr
    )
);
proj_destroy(xy_transform);
proj_destroy(pj_wkt);
proj_context_destroy(context);
```
#### Problem description

Error from PROJ:
```
proj_create: Cannot build concatenated operation: At least one of the operation lacks a source and/or target CRS)
```

This does not produce an issue if `proj_normalize_for_visualization` is not used.

#### Environment Information
 - PROJ version 7.2.1 & 8.1.1
 - Linux-5.11.0-37-generic-x86_64-with-glibc2.29

**Comment by direvus** [comment]
I think this is a bug in ConcatenatedOperation::create().  src/iso19111/operation/concatenatedoperation.cpp L173 pukes if any of the steps are lacking a sourceCRS or targetCRS.

However, looking at the WKT grammar, a step can be any of:
- coordinate operation
- point motion operation
- map projection
- deriving conversion

Of these, only coordinate and point motion operations are required to have a source & target CRS.  So map projections and deriving conversions should both be exempt from the check at L173.

I am intending to prepare a PR for this.

**Comment by direvus** [comment]
Actually I was barking up the wrong tree a little with my original idea.  The WKT parser can already handle steps consisting of map projections and deriving conversions (and there is already a unit test to prove this).

The code in ConcatenatedOperation::create() is relying on ::fixStepsDirection() having fully populated a source and target CRS into each of the steps.

There is something in particular about the way normalize_for_visualisation sets up the operations that is causing ::fixStepsDirection() to fail at populating the CRSs into the steps, and then this in turn causes ::create() to throw.

The hunt continues.

**Comment by direvus** [comment]
Confirmed, fixStepsDirection() is not able to populate the intermediate CRS as the target of the first step and the source of the second step.

What we end up with in the internal representation, after fixStepsDirection() has run, is this:

Step 1: axis-swapped EPSG:4326 -> (swap axes) -> ?
Step 2: ? -> (project to pseudo-mercator) -> EPSG:3857

What we need is this:

Step 1: axis-swapped EPSG:4326 -> (swap axes) -> EPSG:4326
Step 2: EPSG:4326 -> (project to pseudo-mercator) -> EPSG:3857

I can see two different routes to solving the problem.  We could teach fixStepsDirection() to detect axis-swap operations, and give them special treatment.  It could create an intermediate CRS by swapping the axes of the source CRS (similar to what CRS::normalizeForVisualisation() does).

The other route would be for normalize_for_visualisation to produce a "derived" source CRS that includes the original, non-swapped CRS as its base.  If the source CRS is derived, I think that fixStepsDirection() would be able to handle it, but I still need to test this to make sure.

**Comment by direvus** [comment]
I just hacked up a WKT with a derived version of the source CRS and it worked just fine:

[axis.wkt.txt](https://github.com/OSGeo/PROJ/files/7308852/axis.wkt.txt)

**Comment by busstoptaktik** [comment]
> The other route would be for normalize_for_visualisation to produce a "derived" source CRS that includes the original, non-swapped CRS as its base.

I would much prefer this approach: It is the *clean* solution, clearly stressing that a CRS definition *comprises the entire definition*: If you swap the axes, essentially, you define another CRS (as also shown by your example). So by letting the instantiation logic actually do this, its action is closest to the geodetic reality of the CRS.

**Comment by rouault** [comment]
DerivedGeographicCRS could probably work, but it remains a rather exotic object, and could cause issues with downstream consumers, or other parts of PROJ that might not fully support it.
And we have the same issue with Projected CRS to which we apply axis order normalization (like EPSG:3040 "ETRS89 / UTM zone 28N (N-E)"). So we would have to generate a DerivedProjectedCRS, which is an even more exotic beast, and which has the unfriendly property of, in general, not being a ProjectedCRS ! (for axis order reversal, it would remain one) See https://docs.ogc.org/as/18-005r5/18-005r5.html#33 9.2.2 : " The term ‘derived projected CRS’ is used for consistency in the UML modelling. A derived projected CRS is not a projected CRS - ‘derived from projected CRS’ would be a more accurate description"
Anyway, as the WKT as output currently by PROJ are valid, I opted to fix supporting them, and indeed as spotted by @direvus fixStepsDirection() is a good place for that.

**Comment by busstoptaktik** [comment]
> Anyway, as the WKT as output currently by PROJ are valid, I opted to fix supporting them

Hard to argue with (or against) a working fix :-)

**Comment by snowman2** [comment]
Thanks @direvus & @rouault 👍
