### ISSUE TITLE
Fail of identity transformation when using geoid grids

### ISSUE THREAD

**Issue by gwmato** [OSGeo/proj.4#2901]
#### Example of problem
The identity transformation failed when a geoid grids is set:
```
$> echo 5 45 0 | cs2cs -f %f +proj=latlong +geoidgrids=egm96_15.gtx +to +proj=latlong +geoidgrids=egm96_15.gtx
*	* inf
```

#### Problem description
Usually there is no problem with identity transformation, like:
```
$> echo 5 45 0 | cs2cs -f %f +proj=latlong +to +proj=latlong
5.000000	45.000000 0.000000
```

It may seem unnecessary to do this kind of conversion, but in practice we do not always know that the input reference systems are the same.
Note that transformation between 2 different geoids is working well:
```
$> echo 5 45 0 | cs2cs -f %f +proj=latlong +geoidgrids=grs80.gtx +to +proj=latlong +geoidgrids=egm96_15.gtx
5.000000	45.000000 1.639992
```
The error occurs only when the same geoid is given as input and output vertical reference, and does not seem be related to the projection:
```
echo 5 45 0 | cs2cs -f %f +proj=latlong +geoidgrids=dgm96_15.gtx +to +init=epsg:32631 +geoidgrids=egm96_15.gtx
*	* inf
```

#### Expected Output
Conversion on same geoids should work an returns same altitude.

#### Environment Information
 - PROJ version (`proj`): "Rel. 7.2.1, January 1st, 2021"
 - Operation System Information: CentOS Linux release 7.9.2009 (Core)

#### Installation method
 - manually compiled from GitHub release

**Comment by rouault** [comment]
Your use case works with PROJ 8.1.1. There must have been a fix since 7.2.1
