### ISSUE TITLE
Default to nearest triangle in tinshift transformation

### ISSUE THREAD

**Issue by josch** [OSGeo/proj.4#2903]
Hi,

I'm using proj and tinshift to render openstreetmap with mapnik. One problem I'm facing is, that mapnik doesn't like there to be points that cannot be transformed because they are not inside any of the triangles I specify as input to the tinshift transformation. Would it be an acceptable feature to add a flag to tinshift, that will fall back to the closest triangle for points that are not inside any triangle? I'm willing to try and write code that does exactly that but first wanted to bring this up with you to ask whether this is something you'd consider adding to proj.

Thanks!

**Comment by rouault** [comment]
I'm wondering if it should be an option of the +proj=tinshift operation, or some option in the .json file itself. No strong opinion.

**Comment by busstoptaktik** [comment]
@josch I think you have resolved  this yourself with #2907, so this could probably be closed?

**Comment by josch** [comment]
Yes, thank you all for your the help and advice!! :+1:
