### ISSUE TITLE
PROJ is not able to be built as a subdirectory

### ISSUE THREAD

**Issue by Cazadorro** [OSGeo/proj.4#2905]
#### Example of problem

```
#include <proj.h>
#include <iostream>
int main(){
    return 0;
}
```

```
cmake_minimum_required(VERSION 3.13)
project(test)
set(CMAKE_CXX_STANDARD 17)

add_subdirectory(external/PROJ)
add_executable(test main.cpp)
target_link_libraries(test PRIVATE PROJ::proj)
```
```
-- PROJ: Configured 'dist' target
-- Configuring done
  Target "test" links to target "PROJ::proj" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
```

with out alias target

```
cmake_minimum_required(VERSION 3.13)
project(test)
set(CMAKE_CXX_STANDARD 17)

add_subdirectory(external/PROJ)
add_executable(test main.cpp)
target_link_libraries(test PRIVATE proj) 
```
```
/home/user/projects/test/main.cpp:2:10: fatal error: proj.h: No such file or directory
 #include <proj.h>
          ^~~~~~~~
```

#### Problem description
Using PROJ as a sub directory is not possible, this creates issues with many workflows, especially if one is not using a package manager with PROJ, which is very likely now that VCPKG only supports pre 8.0 versions of proj and does not support geotiff builds. 

PROJ currently creates an alias target for `PROJ::proj`, but only during installs, and it doesn't appear as if any usable target, however this is not a big deal as long as *a* target exists.  Currently it appears as if `proj` is that target, however it doesn't appear to properly propagate it's own `target_include_directories`, so it can't be used in isolation. 

#### Expected Output

The above example should compile with out error. 

#### Environment Information
 - PROJ version 8.2.0
 - Operation System Information
 Centos 7
#### Installation method
 - from source

**Comment by rouault** [comment]
Can you provide a pull request to improve this ?

**Comment by Cazadorro** [comment]
@rouault I think I just fixed this, let me make sure, I'll attempt to make a PR

**Comment by Cazadorro** [comment]
@rouault, I'm having trouble getting proj.db to actually generate without installing, but technically I can still build everything and run (the library just doesn't actually find a proj.db to use at runtime), should I submit a PR and discuss that there?

**Comment by rouault** [comment]
> should I submit a PR and discuss that there?

sure
