### ISSUE TITLE
After the install Proj 8.1.1 I cant used same application of QGIS and R

### ISSUE THREAD

**Issue by fco-aguirre** [OSGeo/proj.4#2909]
#### Problem description

After the installing Proj 8.1.1 I cant used same application of QGIS and R

![Screenshot from 2021-10-19 11-47-09](https://user-images.githubusercontent.com/46607160/138147755-fe9f9b92-cded-4ff4-9085-94e5a4b9db93.png)

And also:

In R:
dem_30_UTM <- projectRaster(dem, res=30, crs=CRS("+init=epsg:32719"), method = 'ngb')
Error in projectRaster(dem, res = 30, crs = CRS("+init=epsg:32719"), method = "ngb") : 
  input projection is NA

#### Environment Information
 - PROJ 8.1.1
 - Ubuntu 20.04

#### Installation method
from Source CMake and Make

It is possible to remove and start from zero? 
How I can fix it??
Thanks for your help!!!

**Comment by rouault** [comment]
You have a mismatch in your configuration. The PROJ library used by your QGIS installation is likely using the proj.db file of another version of PROJ. Check if the PROJ_LIB environment variable is not set and would point to the proj.db of another PROJ version.

**Comment by fco-aguirre** [comment]
Thanks,
and @rouault , How I can Check it?? Can you give me an example?
Thanks!
