### ISSUE TITLE
DOC: Add list of keys for proj_context_get_database_metadata

### ISSUE THREAD

**Issue by snowman2** [OSGeo/proj.4#2924]
It would be useful to be able to get the database version of EPSG|ESRI|etc. through the C-API for informational purposes. That way the user can see what version(s) the current PROJ database is using.

**Comment by rouault** [comment]
This is covered by using proj_context_get_database_metadata and querying the keys of https://github.com/OSGeo/PROJ/blob/master/data/sql/metadata.sql

**Comment by snowman2** [comment]
Perfect! Thanks :+1:

**Comment by snowman2** [comment]
Reopening because it is missing the ESRI database version in there. Any other database versions that would be good to add?

**Comment by snowman2** [comment]
Looks like ESRI 12.8? https://github.com/OSGeo/PROJ/pull/2717

**Comment by rouault** [comment]
The ESRI specific metadata is set in https://raw.githubusercontent.com/OSGeo/PROJ/master/data/sql/esri.sql
Simlarly for https://raw.githubusercontent.com/OSGeo/PROJ/master/data/sql/ignf.sql
Perhaps those known keys should be documented in proj_context_get_database_metadata()

**Comment by snowman2** [comment]
Would it make sense to move the versions to `sql/metadata.sql` and add a note in the other files to update `sql/metadata.sql`?

**Comment by rouault** [comment]
> Would it make sense to move the versions to `sql/metadata.sql` and add a note in the other files to update `sql/metadata.sql`?

the versions set in esri.sql and ignf.sql are done by their respective import scripts. I believe it is better if the import script set the versions as part as the import process to avoid (forgetting to) updating them manually.

**Comment by snowman2** [comment]
Makes sense to me. I updated the issue title.
