### ISSUE TITLE
ESRI Projection Engine 2.9 update available

### ISSUE THREAD

**Issue by nyalldawson** [OSGeo/proj.4#2929]
See https://github.com/Esri/projection-engine-db-doc/commit/93c99a600de88e085f8d8c7349fa22129debd607 -- looks like the structure has changed a little and scripts will need tweaking

**Comment by nyalldawson** [comment]
(I'm working on this)

**Comment by rouault** [comment]
there might be "hysterisis" phenomenon (particularly with the "area" table) when updating the ESRI objects. The best is to first empty data/sql/esri.sql and rebuild proj.db from that. And then run the import script.

**Comment by nyalldawson** [comment]
Thanks @rouault !

Two (hopefully quick) questions:

- is it safe to replace the WKT definition of a projected CRS in the projected_crs table directly with a WKT2 definition? Or would that have potential flow-on effects?
- there was an assert to ensure 'PARAMETER["Vertical_Shift",0.0]' was present in the WKT1 definition of a vertical cs. This same parameter isn't present in any of the WKT2 definitions. Do you have any insights into the history of this?

**Comment by rouault** [comment]
>     * is it safe to replace the WKT definition of a projected CRS in the projected_crs table directly with a WKT2 definition? 

Unfortunately, not. ProjectedCRS::_exportToWKT() when exporting to WKT1_ESRI has special processing to see that if the text_definition column starts with PROJCS[] and the object is under the ESRI authority, then it will use the WKT1_ESRI from text_definition directly. This guarantees perfect round-tripping. In the ideal situation where we could map all ESRI WKT projection methods & parameters to "OGC WKT", we could no longer need that. That said a number of the WKT1_ESRI present in text_definition could potentially be mapped. It is just it was tedious to do in the import script so I did it for the 90% most common projections.

> there was an assert to ensure 'PARAMETER["Vertical_Shift",0.0]' was present in the WKT1 definition of a vertical cs. [...]Do you have any insights into the history of this?

Unfortunately not
