### ISSUE TITLE
cross compile for android

### ISSUE THREAD

**Issue by zsr8512** [OSGeo/proj.4#2942]
hello ,could you give me some suggests or  tutorials about compiling proj6+ 4 android.  i try it,but.always failed.thanks

**Comment by rouault** [comment]
github issues are not for usage issue.
you can likely have a look at https://github.com/opengisch/OSGeo4A/blob/master/recipes/proj/recipe.sh

**Comment by zsr8512** [comment]
but 	for - arm64-v8a is just&nbsp; experimental,i built failed
for arm64-v8




---Original---
From: "Even ***@***.***&gt;
Date: Mon, Nov 15, 2021 23:38 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [OSGeo/PROJ] cross compile for android (Issue #2942)




 
github issues are not for usage issue.
 you can likely have a look at https://github.com/opengisch/OSGeo4A/blob/master/recipes/proj/recipe.sh
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
