### ISSUE TITLE
Unexpected results for BNG to LAEA

### ISSUE THREAD

**Issue by filipkral** [OSGeo/proj.4#2955]
#### Example of problem
I am using the OsGeo.OSR interface in MaxRev.gdal to project British National Grid to LAEA on ETRS 1989 datum.
```cs
using MaxRev.Gdal.Core;
using OSGeo.OSR;
using System;
using System.Threading.Tasks;
using Xunit;

namespace DHI.WaterData.Projections.Provider.Test.WKTS
{
    public class MatchWKTStringsTest
    {
        [Fact]
        public async Task TransformPointIsOk()
        {
            var x = 826158.063;
            var y = 2405844.125;

            var sourceWkt =
                "PROJCS[\"OSGB 1936 / British National Grid\",GEOGCS[\"OSGB 1936\",DATUM[\"OSGB_1936\",SPHEROID[\"Airy 1830\",6377563.396,299.3249646,AUTHORITY[\"EPSG\",\"7001\"]],TOWGS84[446.448,-125.157,542.06,0.15,0.247,0.842,-20.489],AUTHORITY[\"EPSG\",\"6277\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4277\"]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"latitude_of_origin\",49],PARAMETER[\"central_meridian\",-2],PARAMETER[\"scale_factor\",0.9996012717],PARAMETER[\"false_easting\",400000],PARAMETER[\"false_northing\",-100000],UNIT[\"metre\",1,AUTHORITY[\"EPSG\",\"9001\"]],AXIS[\"Easting\",EAST],AXIS[\"Northing\",NORTH],AUTHORITY[\"EPSG\",\"27700\"]]";
            var targetWkt =
                "PROJCS[\"ETRS89 / LAEA Europe\",GEOGCS[\"ETRS89\",DATUM[\"European_Terrestrial_Reference_System_1989\",SPHEROID[\"GRS 1980\",6378137,298.257222101,AUTHORITY[\"EPSG\",\"7019\"]],TOWGS84[0,0,0,0,0,0,0],AUTHORITY[\"EPSG\",\"6258\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4258\"]],PROJECTION[\"Lambert_Azimuthal_Equal_Area\"],PARAMETER[\"latitude_of_center\",52],PARAMETER[\"longitude_of_center\",10],PARAMETER[\"false_easting\",4321000],PARAMETER[\"false_northing\",3210000],UNIT[\"metre\",1,AUTHORITY[\"EPSG\",\"9001\"]],AUTHORITY[\"EPSG\",\"3035\"]]";
            
            Proj6.Configure();
            
            var sourceSr = new SpatialReference(string.Empty);
            sourceSr.ImportFromWkt(ref sourceWkt);
            sourceSr.SetAxisMappingStrategy(AxisMappingStrategy.OAMS_TRADITIONAL_GIS_ORDER);
            
            var targetSr = new SpatialReference(string.Empty);
            targetSr.ImportFromWkt(ref targetWkt);
            targetSr.SetAxisMappingStrategy(AxisMappingStrategy.OAMS_TRADITIONAL_GIS_ORDER);
            
            var transformation = new CoordinateTransformation(sourceSr, targetSr);
            if (transformation == null)
                throw new ArgumentException("Invalid projection WKT");

            var projected = new double[3];
            transformation.TransformPoint(projected, x, y, 0.0);
            var px = projected[0];
            var py = projected[1];

            var ex = 4316131D;
            var ey = 5330926D;
            Assert.Equal(ex, px, 0);
            Assert.Equal(ey, py, 0);
        }
    }
}
```
#### Problem description
When we updated to proj 7.x one our test started failing and I am looking for an explanation we could provide our clients.
I've been researching about PROJ (and the changes in version 4, 6, and onwards), but nothing really fully explained this discrepancy.
I suspect the datum transformation is not applied because when I changed the TOWGS parameters of the British National Grid WKT string to all zeros, I got exactly the same results. Also the `SetAxisMappingStrategy` calls have no impact in this case.
It may also be that we are missing the transformation grids needed for this transformation. 
I downloaded and copied the OSTN15_NTv2_OSGBtoETRS.gsb grid shift file to `C:\Users\<user>\AppData\Local\proj` and also to indicates `ProjeSearchPath` `...\bin\Debug\net5.0\runtimes\win-x64\native\maxrev.gdal.core.libshared` but it had no effect.

#### Expected Output
 coord |   British n. grid    |   expected projected  |    actual projected   |
--------|-------------------|-------------------------|----------------------|
   x       |   826158.063      |     4316131.0               |     4316331.549       |
   y       |  2405844.125     |     5330926.0               |     5331101.982       |

The expected projected coordinates come from:
https://epsg.io/transform#s_srs=27700&t_srs=3035&x=826158.0630000&y=2405844.1250000
The expected projected coordinates were also retuned from another, proprietary. transformation library I used.

#### Environment Information
 - PROJ version (`proj`) 7.2.0
 - Operation System : Windows 10 and Windows 11

#### Installation method
 - Visual Studio NuGet package https://www.nuget.org/packages/MaxRev.Gdal.Core/ and https://www.nuget.org/packages/MaxRev.Gdal.WindowsRuntime.Minimal/

**Comment by rouault** [comment]
ok, this is a bit tricky. GDAL has a behaviour into which if a WKT string has a EPSG code, and that the definition of the WKT, *ignoring* TOWGS84, is equivalent to the EPSG code, it will use the definition of the EPSG code. Hence in your situation the TOWGS84[] node will be ignored. If you remove AUTHORITY[\"EPSG\",\"27700\"] and AUTHORITY[\"EPSG\",\"3035\"], you'll get the result you expect.
Why don't you get any datum shift when using EPSG:27700 and EPSG:3035 ? The reason is that EPSG only lists the method based on the OSTN15_NTv2 grid as candidate, but the point you want to transform (71d7'37.295"N	9d52'21.307"E) is outside the validity area of that grid, hence PROJ ends up doing no datum shift.
So GDAL and PROJ behave as designed here.
That said, I can see your use case might be valid, and in https://github.com/OSGeo/gdal/pull/4891, I'm adding a GDAL configuration option where the WKT will be used as it, with its TOWGS84[] node

**Comment by filipkral** [comment]
Thank you for such a prompt and clear answer and the fix.
