### ISSUE TITLE
PROJ 8 in EPEL

### ISSUE THREAD

**Issue by MosGeo** [OSGeo/proj.4#2975]
PROJ 8+ is still not EPEL repo (https://docs.fedoraproject.org/en-US/epel/). I am not sure if there is a blocking issue or not, but now that more packages (e.g., cartopy) are depending on it, I think it is a good idea to have it there.

**Comment by kbevers** [comment]
This is an issue you'll have to raise with the EPEL guys. We aren't responsible for keeping various package repositories up to date. Closing this issue as it's out of scope for the project. If getting a recent PROJ on your system I recommend you build it from source until your package manager offers a version of PROJ you are satisfied with.

**Comment by MosGeo** [comment]
@kbevers great! Thanks for the info. I was not sure who is responsible for this.
