### ISSUE TITLE
PROJ_DLL change breaks downstream usage

### ISSUE THREAD

**Issue by dg0yt** [OSGeo/proj.4#2999]
#### Example of problem

With PROJ 8.2.1, using the static Windows lib fails for some consuming packages with errors like
~~~
error LNK2001: unresolved external symbol __imp_proj_context_create
~~~

#### Problem description

With #2912, the setup of `PROJ_DLL` in `proj.h` was modified in order to no longer require `PROJ_MSVC_DLL_IMPORT` definition when using the *Windows DLL*.

However, AFAIU when building PROJ as a *static Windows library*, `PROJ_DLL` is now an empty string at build time, but expands to `__declspec(dllimport)` in consuming projects. This means that consuming projects now need to pre-define `PROJ_DLL` to an empty string when using the static Windows lib. This is carried in CMake config files, but this doesn't reach all packages: Apart from not using CMake, some packages may just consume gdal or libspatialite via pkg-config.

(Maybe the `__GNUC__` visibility definition needs similar attention.)

#### Expected Output

I'm not sure if it is possible to go without an external definition to equally serve static library and import library with the same header.
But in any case, patch release should not require downstream changes.

#### Environment Information
 - PROJ 8.2.1
 - Windows

#### Installation method
 - vcpkg (https://github.com/microsoft/vcpkg/pull/22283, [2380f58](https://github.com/microsoft/vcpkg/pull/22283/commits/2380f58bffe2501eb972c55b7906f43ae4ff5ba8))

In vcpkg, headers are usually modified to carry the right configuration, so I can resolve it there (https://github.com/microsoft/vcpkg/pull/22283/commits/260f89ed1958fcbcd7097b1124aba5a9d7431a3b).

**Comment by kbevers** [comment]
> But in any case, patch release should not require downstream changes.

I'm not able to comment on the actual issue, I just want to make it clear that the linked PR was included in 8.2.0 and not 8.2.1. Do you see the same thing with 8.2.0?

**Comment by dg0yt** [comment]
TBH I actually can't talk about PROJ 8.2.0 and Windows. It caused other issues...

**Comment by kbevers** [comment]
In that case I'm just going to ignore the comment about the patch release requiring downstream changes, I don't think there's any merit to that statement.

**Comment by dg0yt** [comment]
> In that case I'm just going to ignore the comment about the patch release requiring downstream changes, I don't think there's any merit to that statement.

Fair enough. However, there is also no hint in the release notes for 8.2.0. So opening this issue still seems appropriate to report the problem.

**Comment by rouault** [comment]
The change in 8.2.0 was intended. It makes it easier for PROJ users of the .dll, which is the more frequent use cases. It makes it is a bit slightly inconvenient for users of static builds, who don't use the cmake config files, but static linking is always more painful.

> However, there is also no hint in the release notes for 8.2.0. So opening this issue still seems appropriate to report the problem.

fair enough. I'll propose a PR improving news.rst

**Comment by dg0yt** [comment]
> .dll, which is the more frequent use cases

In that case, why is default Windows config static?

https://github.com/OSGeo/PROJ/blob/11c7d0c511806e48866bb2feef7da66de995f749/src/lib_proj.cmake#L7-L13

**Comment by rouault** [comment]
> In that case, why is default Windows config static?

no idea, just history probably... This might be something worth changing for PROJ 9 (to be discussed in a separate ticket)
