### ISSUE TITLE
Issue while compiling on WSL/Debian 11.2

### ISSUE THREAD

**Issue by jvsnap** [OSGeo/proj.4#3008]
I got a WSL/Debian running on my computer with installed dependencies.

```shell
apt install git cmake make g++ libtiff5 libtiff5-dev libtiff-dev sqlite3 libsqlite3-dev libcurl4-gnutls-dev
```

I'm following steps to compile.

```shell
wget https://download.osgeo.org/proj/proj-8.2.1.tar.gz
tar xzf proj-8.2.1.tar.gz && cd proj-8.2.1
./configure
```

But I got errors during configuration.

```shell
checking for SQLITE3... yes
checking for sqlite3... yes
checking for TIFF... configure: error: Package requirements (libtiff-4) were not met:

No package 'libtiff-4' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables TIFF_CFLAGS
and TIFF_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

It seems that is not locating libtiff `No package 'libtiff-4' found`

**Comment by rouault** [comment]
Following your instructions, I can't reproduce the issue with a Linux Docker debian:11.2 image, so it seems something WSL/Debian specific.
Perhaps you can try with a cmake build instead ? 8.2.1 was the last version to support autoconf builds, there won't be any further 8.2.x patches, and 9.0.0 will have cmake builds only.

**Comment by rouault** [comment]
I've just tried with Debian 9.13 under WSL and it works for me (I had to install the pkg-config package as well). I'm not sure how to install 11.2

**Comment by jvsnap** [comment]
Thanks, using cmake solves the issue.
