### ISSUE TITLE
[Peirce Quincuncial] `+proj=peirce_q +type=crs` is now an error.

### ISSUE THREAD

**Issue by rhuijben** [OSGeo/proj.4#3011]
#### Example of problem
Trying to create a simple minimal projection for testing with

`+proj=peirce_q +type=crs` used to work in 8.1.1, but now returns an error in 8.2.1.
(I skipped 8.2.0 for other issues, but I think it worked ok there)

I'm not sure if this change in behavior is intended. (It probably is, if I look at the file changes), but it may be a change not really fit for a patch release.

My test code automatically checks the definition information to see if there are required arguments, but in this case the projection doesn't document any.

def.Details = "\tMisc Sph No inv"
(without a second line that documents arguments)

I would welcome a way to automatically find what is required now, but that discussion is already open in another pull request.

**Comment by rhuijben** [comment]
![image](https://user-images.githubusercontent.com/2271549/148387966-ff143a82-a7b3-4d41-a8bd-7cbd152edcec.png)

This now 'bad' proj string used to be the example string before 5fe037f86a7ed040893c3406aed8bffebbb722f6

**Comment by rouault** [comment]
hum, indeed we completely overlooked that +type=crs was reserved in generic PROJ code...@tcwilkinson we must rename the +type parameter to something else, maybe +shape ?

**Comment by rhuijben** [comment]
This issue appears to break calculations against ESRI:54090 and ESRI:54091, "Peirce_quincuncial_North_Pole*".

**Comment by tcwilkinson** [comment]
Sorry - slow to this party, but `shape` seems a good solution to this problem.
Thanks!
