### ISSUE TITLE
significant deltas between PROJ 7.1.1 and 7.2.0 when projecting EPSG:4326 > EPSG:3444

### ISSUE THREAD

**Issue by spolloni** [OSGeo/proj.4#3021]
#### Example of problem

I swept PROJ versions 6.x.x through 8.x.x and this is the only precision discrepancy I could find. It's not immediately clear from the [7.2.0 release notes](https://www.osgeo.org/foundation-news/announce-release-of-proj-7-2-0-and-proj-data-1-3/) why this would occur, but maybe I overlooked something?

PROJ 7.1.0:
```
❯ echo -89.081099 42.254514 | cs2cs +init=epsg:4326 +to +init=epsg:3444
2590467.50	2037141.27 0.0
```

PROJ 7.1.1:
```
❯ echo -89.081099 42.254514 | cs2cs +init=epsg:4326 +to +init=epsg:3444
2590467.50	2037141.27 0.00
```

PROJ 7.2.0
```
❯ echo -89.081099 42.254514 | cs2cs +init=epsg:4326 +to +init=epsg:3444
2590469.18	2037138.43 0.00
```

PROJ 7.2.1
```
❯ echo -89.081099 42.254514 | cs2cs +init=epsg:4326 +to +init=epsg:3444
2590469.18	2037138.43 0.00
```

I am also seeing this for other "NAD83(HARN) / {STATE} (ftUS)" EPSG codes such as 3443 and 3445. 

#### Environment Information
 - I Initially found these  inconsistencies by comparing pyproj output to PostGIS `ST_Transform`, but the example above was done by pinning different PROJ versions in a conda environment with the conda-forge channel.
 - macOS 11.6

**Comment by rouault** [comment]
You can figure out the reason by looking at the output of "projinfo -s EPSG:4326 -t EPSG:3444" in the various versions. Before 7.2.0, the first operation returned was "Inverse of NAD83(HARN) to WGS 84 (1) + SPCS83 Illinois West zone (US Survey feet)", which assumed that NAD83(HARN) ~= WGS 84, and the next one was "Inverse of NAD83(HARN) to WGS 84 (3) + SPCS83 Illinois West zone (US Survey feet)", which uses a Helmert transformation to model a datum shift between NAD83(HARN) and WGS 84. Both transformations are advised with a 1 m accuracy ! Before PROJ 7.2.0, the choice was to select the operation whose name comes before, in lexical order!, the other one, hence (1) < (3).
In 7.2.0, this was reversed https://github.com/OSGeo/PROJ/commit/75074ce863e36299ec39b39decdd435eed15ad63 based on the assumption that higher numbers means more recent data. Which is also arbitrary, but probably give more expected results, generally.
Which answer is the good one ? No one knows... You can decide yourself by using the PROJ pipeline of your choice reported by projinfo and use it with cct, or just rely on (changing) defaults of PROJ.

with "Inverse of NAD83(HARN) to WGS 84 (1) + SPCS83 Illinois West zone (US Survey feet)" (no datum shift):

```
$ echo 42.254514 -89.081099  0 | bin/cct -d 2 +proj=pipeline +step +proj=axisswap +order=2,1 +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=tmerc +lat_0=36.6666666666667 +lon_0=-90.1666666666667 +k=0.999941177 +x_0=699999.99998984 +y_0=0 +ellps=GRS80 +step +proj=unitconvert +xy_in=m +xy_out=us-ft
   2590467.50     2037141.27          0.00           inf
```

with "Inverse of NAD83(HARN) to WGS 84 (3) + SPCS83 Illinois West zone (US Survey feet)" (with datum shift):
```
$ echo 42.254514 -89.081099  0 | bin/cct -d 2  +proj=pipeline +step +proj=axisswap +order=2,1 +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=push +v_3 +step +proj=cart +ellps=WGS84 +step +inv +proj=helmert +x=-0.991 +y=1.9072 +z=0.5129 +rx=-0.0257899075194932 +ry=-0.0096500989602704 +rz=-0.0116599432323421 +s=0 +convention=coordinate_frame +step +inv +proj=cart +ellps=GRS80 +step +proj=pop +v_3 +step +proj=tmerc +lat_0=36.6666666666667 +lon_0=-90.1666666666667 +k=0.999941177 +x_0=699999.99998984 +y_0=0 +ellps=GRS80 +step +proj=unitconvert +xy_in=m +xy_out=us-ft
   2590469.18     2037138.43          0.00           inf
```

so not a bug / works as expected

**Comment by spolloni** [comment]
thanks @rouault  for this thorough explanation, much appreciated as always.
