### ISSUE TITLE
Minimal proj.db

### ISSUE THREAD

**Issue by jvail** [OSGeo/proj.4#3022]
Is there a possibility to either create only a "minimal" (most important epsg codes - whatever that exactly is) proj.db or a recommended way to remove "exotic" entries? The size of the db (~8 MB) is a quite large to include it into a web application and I would like to reduce its size a bit.

Either I'd write a custom scrip (hints welcome) or it could be a feature of PROJ.

Thank you,
Jan

**Comment by kbevers** [comment]
What's exotic to you is someone else's bread and butter. I don't see us maintaining a minimal version of `proj.db`, the content is quite fluid with regular updates from the EPSG, IAU and other CRS authorities and it will be a big job to keep it up to date.

You could probably purge a lot of the content of the database yourself without sacrificing the integrity of the CRS's and transformations you have an interest in. I wouldn't advice it but I think it is possible.

Have you considered setting up a backend that does the transformations server-side instead of client-side?

**Comment by rouault** [comment]
I think we could welcome a Python script in our scripts/ directory that would strip down the database using the Python sqlite3 module. I guess It could take as arguments filtering by authority, bounding box or extent name. You'll need to study the dependencies between tables expressed in https://github.com/OSGeo/PROJ/blob/master/data/sql/proj_db_table_defs.sql and the final integrity checks done in https://github.com/OSGeo/PROJ/blob/master/data/sql/commit.sql

**Comment by jvail** [comment]
Thanks for the quick responses.

> What's exotic to you is someone else's bread and butter.

Yes, of course - I did not want to suggest a list what I might think is relevant or not. Though I assume it would be possible to have a smaller list of transformations that is sufficient for many users. 

> Have you considered setting up a backend that does the transformations server-side instead of client-side?

That is the problem - there is no backend. All client side.

> I think we could welcome a Python script in our scripts/ directory that would strip down the database using the Python sqlite3 module.

Thank you for the hints! I'll look into it and maybe I can suggest a script to strip some parts of the db.

**Comment by jvail** [comment]
Sorry for not following up on this. But I have tried another, simpler idea:

Why not add an `ON DELETE CASCADE` to all foreign key constraints. I gave it a try and removed all non WGS84 and non EPSG from some top-level tables. Then proj.db has 5.7 instead of 8.2 MB - not perfect but much better. It seems a lot of space is consumed by just 2-3 tables (e.g. `usage`).

What do you think? I guess removing entries then is save (if foreign keys are enabled) and it can be done with any SQL clause (including extent, auth name etc.) without maintaining another script.

**Comment by rouault** [comment]
> Why not add an `ON DELETE CASCADE` to all foreign key constraints.

that sounds good

> It seems a lot of space is consumed by just 2-3 tables (e.g. usage).

you can cleanup useless records with:
```
DELETE FROM usage WHERE (object_table_name, object_auth_name, object_code) IN (
  SELECT object_table_name, object_auth_name, object_code FROM usage WHERE NOT EXISTS (
     SELECT 1 FROM object_view o WHERE
         o.table_name = object_table_name AND
         o.auth_name = object_auth_name AND
         o.code = object_code))
```

**Comment by jvail** [comment]
> > Why not add an `ON DELETE CASCADE` to all foreign key constraints.
> 
> that sounds good

Great! I guess filing a PR for this is too trivial?

> > It seems a lot of space is consumed by just 2-3 tables (e.g. usage).
> 
> you can cleanup useless records with:

Many thanks - I'll try.

**Comment by kbevers** [comment]
> Great! I guess filing a PR for this is too trivial?

Absolutely not. Any help is appreciated

**Comment by rouault** [comment]
> I guess filing a PR for this is too trivial?

PR are the only way to make code changes (even "trivial" ones, and that one is not trivial) if you want your proposed change to be included in a future release.

**Comment by jvail** [comment]
> Absolutely not. Any help is appreciated

Alright - I'll file one.
