### ISSUE TITLE
Proj 7.0.1 : build of proj.db failed

### ISSUE THREAD

**Issue by Laurent-777** [OSGeo/proj.4#3039]
Os x: Lion 10.7.5
Compiler : Gcc 11.2.0, built with Gcc 4.9.4 also built.
Previous successful versions : proj.4,prij.5,prij.6
Configure us used, not Cmake.

Datain data (in source) : datumgrid, datumgrid-world.

Issue : make fails as this :
Make proj.db
rm -f proj.db
Error : near line 41979: near "." : syntax error
Build of proj.db failed

Encl. 3 log files if I succeeds for sending them (config.log, my-configure.log, my-make.log).

Kind regards,

**Comment by rouault** [comment]
proj 7 is no longer supported. please update to latest 8.2.1 version

**Comment by Laurent-777** [comment]
OK. I keep on to built proj7 versions, then proj8. I remember I failed too some months ago.
Thank you.

**Comment by rouault** [comment]
You didn't enclose any file by the way. The sqlite3 version you use may also be relevant. And I'd suggest you to use CMake builds (at least with 8.2.1) as they will soon be the only available build system

**Comment by Laurent-777** [comment]
I failed to enclose the files with my mobile phone. Don't see how to do it. Sorry.

**Comment by Laurent-777** [comment]
0For Sqlite, I guess I have the last version, or almost. It works well.

**Comment by Laurent-777** [comment]
``

>
