### ISSUE TITLE
Proj.8 8.2.1 & OS X Lion : Build of proj.db failed

### ISSUE THREAD

**Issue by Laurent-777** [OSGeo/proj.4#3040]
#### Example of problem
Demonstrate the problem you have found, either by using PROJ tools like `cs2cs`, `cct` or `projinfo` **or** add a code snippet that highlights the problem using the PROJ C/C++ API.
A "Minimal, Complete and Verifiable Example" will make it much 
#### Problem description
The step : Make failed. 
Last and bottom message issued : Build of proj.db failed. 

#### Expected Output
Compilation OK, as for proj.4, proj.5, and proj.6.

#### Environment Information
 - PROJ version (`proj`) : 8.2.1
 - Operation System Information Mac os x Lion 10.7.5.
 - Compiler : GCC 11.2.0, built with Gcc 4.9.4, also built. 

#### Installation method
 - conda, apt-get, from source, etc.. : autotools (yours : configure, make, etc.). 
 -
Enclosed files (if I succeed to send them with my mobile phone, otherwise next Tuesday) : 3 (config.log, my-configure.log, my-make.log).

Kind regards, 
[config.log](https://github.com/OSGeo/PROJ/files/8011013/config.log)
[my-configure.log](https://github.com/OSGeo/PROJ/files/8011014/my-configure.log)
[my-make.log](https://github.com/OSGeo/PROJ/files/8011018/my-make.log)

**Comment by mwtoews** [comment]
Hi @Laurent-777, PROJ 8.2.1 was the last planned version to support autotools. Are you able to build PROJ using CMake?

**Comment by rouault** [comment]
The ``Error: near line 18: near "WITHOUT": syntax error`` suggests that you use a sqlite3 binary which doesn't have support for the WITHOUT ROWID feature, which was added in SQLite 3.8.2. SQLite 3.11.0 is the minimum version required by PROJ.

**Comment by Laurent-777** [comment]
Please find enclosed the pkg- config file (zip compressed) 
[sqlite3.pc.zip](https://github.com/OSGeo/PROJ/files/8017534/sqlite3.pc.zip)
of Sqlite I installed. You may kindly note the version. Again, Proj 4, 5, and 6 were successfully installed. The matter begins with Proj 7.
Thank you.

**Comment by Laurent-777** [comment]
Yes, I can build with Cmake. Besides, note that the step proj.db were successful with Proj 4, 5, and 6. Probably, the code for this step would have been modified since Proj 7 (that failed too).

**Comment by Laurent-777** [comment]
PS Besides, osx Lion is not the best Mac operating system...

**Comment by rouault** [comment]
> Probably, the code for this step would have been modified since Proj 7 (that failed too).

I'm confused. The use of WITHOUT ROWID was introduced in https://github.com/OSGeo/PROJ/commit/ee04c2725f0f8b163ae242935a2ca21dbcc17620 which was released as PROJ 8.1.0. I can't explain why you would get that error with Proj 7.. Anyway if you can build with cmake, that's what matters given that we won't release any new version using autotools. Can this be closed ?

**Comment by Laurent-777** [comment]
Cmake (in fact, make built by Cmake) failed too with a proj.db generation error.
Enclosed :  2 log files (one issued by Cmake, the other one by make). 
Thank you. 
[CMakeOutput.log](https://github.com/OSGeo/PROJ/files/8017815/CMakeOutput.log)
[CMake-make-8_2_1_failure.log](https://github.com/OSGeo/PROJ/files/8017819/CMake-make-8_2_1_failure.log)

**Comment by Laurent-777** [comment]
No it can't be closed. This is a major error. Maybe a Compiler uncompatibility. This is a regression from Proj.6, which was built with the same Sqlite version (with parameters found with pkg config).
I my opinion, it should be a source code new modification that makes the compilation failing. 
Thank you very much.

**Comment by rouault** [comment]
> Cmake failed too with a proj.db generation error.
> Enclosed : 2 log files (one issued by Cmake, the other one by make).

Check in your CMakeCache.txt which SQLite3 binary is selected:
``grep EXE_SQLITE3 CMakeCache.txt``

Then start that sqlite3 binary with the full path displayed by the above command ("/usr/bin/sqlite3" on my Linux system for example), and report the version it displays

**Comment by Laurent-777** [comment]
Investigation in progress. I'll let you know about it. Probably tomorrow. Your kind comments help (me) greatly. This is the goal of such report I guess. Thank you!

**Comment by Laurent-777** [comment]
In progress currently. It seems it works with Cmake, but not with autotools anymore. I'm going to send you a report, after that, it could be closed.
Kind regards.
NB Currently installing new versions of Gdal.

**Comment by rouault** [comment]
Closing as no longer relevant

**Comment by Laurent-777** [comment]
Last (delayed too long...) comment, and "bug" fixed ->
In fact, for PROJ.7, PROJ.8, and PROJ.9 at this date, autotools (configure and so on), for PROJ.x using this IDE, building PROJ fails.

And what it works, is CMake. So, PROJ.7.x, PROJ.8.x, and PROJ.9.x was correctly built, installed, and tested (but some tests fail : SIGTRAP error).

Some comments however : 
1/ clang (from XCode), GCC 4.7.x fail to build PROJ. I (we ?) need now at least GCC 4.9.x (NB Not yest tested with, for example, GCC 6.5.x, and GCC 11.3.0, the last one, built with my Mac resources only) ;
2/ google gtest downloading is somewhat annoyung from for own opinion. In fact, I downloaded the source code, and installed it (and, as everytime, installed in a non-standard location, namely not in /usr/local, in an external hard-drive);
3/ eventually, the PROJ data are not automatically installed, as in older versions. One should untar the archived file, and move the data in [...]/share/proj. Ideally, one must have the ability to choose to save the PROJ data manually or by CMake.

Eventually, PROJ.- was well installed with OS X Lion (10.7.5) and GCC 4.9.x. So, it is fixed.

Kind regards,
