### ISSUE TITLE
West Australian authority and projected CRSs

### ISSUE THREAD

**Issue by ErixenCruz** [OSGeo/proj.4#3059]
Hello, we would like to use some CRSs that aren't in `proj.db` at the moment. The Government of Western Australia has published a set of Transverse Mercator projected CRSs [here](https://www0.landgate.wa.gov.au/business-and-government/specialist-services/geodetic/project-grids). There is a csv file there with the projection parameters and extent of each. Would it be appropriate to open a PR adding this csv file and python script for adding the projections to `proj.db`? Thanks.

**Comment by rouault** [comment]
(FYI @nyalldawson )

From a quick look, it seems that all the GDA2020 based projected CRS are in EPSG and proj.db:
```
INSERT INTO "projected_crs" VALUES('EPSG','8013','GDA2020 / ALB2020',NULL,'EPSG','4400','EPSG','7844','EPSG','7993',NULL,0);
INSERT INTO "projected_crs" VALUES('EPSG','8014','GDA2020 / BIO2020',NULL,'EPSG','4400','EPSG','7844','EPSG','7994',NULL,0);
INSERT INTO "projected_crs" VALUES('EPSG','8015','GDA2020 / BRO2020',NULL,'EPSG','4400','EPSG','7844','EPSG','7995',NULL,0);
INSERT INTO "projected_crs" VALUES('EPSG','8016','GDA2020 / BCG2020',NULL,'EPSG','4400','EPSG','7844','EPSG','7996',NULL,0);
INSERT INTO "projected_crs" VALUES('EPSG','8017','GDA2020 / CARN2020',NULL,'EPSG','4400','EPSG','7844','EPSG','7997',NULL,0);
INSERT INTO "projected_crs" VALUES('EPSG','8018','GDA2020 / CIG2020',NULL,'EPSG','4400','EPSG','7844','EPSG','7998',NULL,0);
INSERT INTO "projected_crs" VALUES('EPSG','8019','GDA2020 / CKIG2020',NULL,'EPSG','4400','EPSG','7844','EPSG','7999',NULL,0);
INSERT INTO "projected_crs" VALUES('EPSG','8020','GDA2020 / COL2020',NULL,'EPSG','4400','EPSG','7844','EPSG','8000',NULL,0);
INSERT INTO "projected_crs" VALUES('EPSG','8021','GDA2020 / ESP2020',NULL,'EPSG','4400','EPSG','7844','EPSG','8001',NULL,0);
INSERT INTO "projected_crs" VALUES('EPSG','8022','GDA2020 / EXM2020',NULL,'EPSG','4400','EPSG','7844','EPSG','8002',NULL,0);
INSERT INTO "projected_crs" VALUES('EPSG','8023','GDA2020 / GCG2020',NULL,'EPSG','4400','EPSG','7844','EPSG','8003',NULL,0);
INSERT INTO "projected_crs" VALUES('EPSG','8024','GDA2020 / GOLD2020',NULL,'EPSG','4400','EPSG','7844','EPSG','8004',NULL,0);
INSERT INTO "projected_crs" VALUES('EPSG','8025','GDA2020 / JCG2020',NULL,'EPSG','4400','EPSG','7844','EPSG','8005',NULL,0);
INSERT INTO "projected_crs" VALUES('EPSG','8026','GDA2020 / KALB2020',NULL,'EPSG','4400','EPSG','7844','EPSG','8006',NULL,0);
INSERT INTO "projected_crs" VALUES('EPSG','8027','GDA2020 / KAR2020',NULL,'EPSG','4400','EPSG','7844','EPSG','8007',NULL,0);
INSERT INTO "projected_crs" VALUES('EPSG','8028','GDA2020 / KUN2020',NULL,'EPSG','4400','EPSG','7844','EPSG','8008',NULL,0);
INSERT INTO "projected_crs" VALUES('EPSG','8029','GDA2020 / LCG2020',NULL,'EPSG','4400','EPSG','7844','EPSG','8009',NULL,0);
INSERT INTO "projected_crs" VALUES('EPSG','8030','GDA2020 / MRCG2020',NULL,'EPSG','4400','EPSG','7844','EPSG','8010',NULL,0);
INSERT INTO "projected_crs" VALUES('EPSG','8031','GDA2020 / PCG2020',NULL,'EPSG','4400','EPSG','7844','EPSG','8011',NULL,0);
INSERT INTO "projected_crs" VALUES('EPSG','8032','GDA2020 / PHG2020',NULL,'EPSG','4400','EPSG','7844','EPSG','8012',NULL,0);
```
The GDA94 and AGD84 are indeed apparently missing, but are they needed ? We try to minimize the number of sources for proj.db and thus favor using EPSG as the main source.

**Comment by ErixenCruz** [comment]
Yes. Some of our users are still using the older versions and are not interested in the 2020 versions. I understand if adding another source is not a good idea.

**Comment by rouault** [comment]
> Some of our users are still using the older versions and are not interested in the 2020 versions.

Perhaps you could first try to check with the contact at the bottom of the page you indicated, if they could register the older versions with EPSG.

**Comment by ErixenCruz** [comment]
Thanks @rouault. In the mean time, we can edit `proj.db` ourselves. That means adding rows to `extent`, `conversion_table`, and `projected_crs` right?

**Comment by rouault** [comment]
> `extent`, `conversion_table`, and `projected_crs` right?

The extents are probably the same as the GDA2020. But you need entries in `usage` as well to link the conversion and projected_crs to their extent and scope

**Comment by nyalldawson** [comment]
(Thanks for the ping @rouault  -- I'm happy to continue this discussion if you'd like. )


> Perhaps you could first try to check with the contact at the bottom of the page you indicated, if they could register the older versions with EPSG.

@ErixenCruz if you have no luck with those contact details, let me know -- I've a few contacts at Landgate who may be able to assist otherwise.
