### ISSUE TITLE
CMake: proj.pc is installed to system root dir under windows

### ISSUE THREAD

**Issue by shawnlaffan** [OSGeo/proj.4#3078]
It seems that ```CMAKE_INSTALL_LIBDIR``` can be undefined when the build system reaches the proj.pc install step.  This results in it being created as ```C:\pkgconfig\proj.pc```, and no proj.pc is installed in the target directory.

Adding a defined check to CMakeLists.txt is a workaround (see below) but perhaps there is a better way.

https://github.com/OSGeo/PROJ/blob/65c84b6e2a40ec8e6b8d1de86bcd556d01ef2aeb/CMakeLists.txt#L326-L333

Workaround (cribbed from [here](https://opensource.apple.com/source/X11libs/X11libs-60.1/libpng14/libpng-1.4.8/CMakeLists.txt.auto.html)):
```cmake
################################################################################
# pkg-config support
################################################################################
configure_proj_pc()

if(NOT DEFINED CMAKE_INSTALL_LIBDIR)
  set(CMAKE_INSTALL_LIBDIR lib)
endif(NOT DEFINED CMAKE_INSTALL_LIBDIR)

install(FILES
  ${CMAKE_CURRENT_BINARY_DIR}/proj.pc
  DESTINATION ${CMAKE_INSTALL_LIBDIR}/pkgconfig)
```

For context, the [build system](https://github.com/shawnlaffan/perl-alien-proj) I'm using is part of the stack used for the GDAL Perl bindings.  It uses [Alien::Build](https://metacpan.org/pod/Alien::Build), which runs the various build steps through an msys shell so the problem is not strictly windows.  This issue cropped up when porting from autotools to cmake.

I can work up a PR if needed.

Shawn.

**Comment by mwtoews** [comment]
Note that part of this change was from #2988 -- before it was only installed within a `if(UNIX OR MINGW)` block.

**Comment by SpaceIm** [comment]
The problem is that inclusion of `GNUInstallDirs` is quite obfuscated in a file: `ProjInstallPath.cmake`. But `GNUInstallDirs` is not included if Windows (which is odd), so `CMAKE_INSTALL_*` variables are never defined.
