### ISSUE TITLE
Wrong Projection between 27700 and 4326.

### ISSUE THREAD

**Issue by ghost** [OSGeo/proj.4#3079]
#### Example of problem

I am not sure this is where I should post this issue, but I have some trouble with a PostGIS transformation which I assume comes from PROJ. 

I use a remote postgreSQL DB where various polygons  are stored in British National Grid. For this example I will focus on the following point, which should lie on a wall of a building:

```sql
  select st_geometryfromtext('POINT(624161 308459.58)', 27700) ;
```

When I transform the point to 4326, I get these coordinates:

1.310709885004937, 52.62757895156674

```sql
  select st_transform(st_geometryfromtext('POINT( 624161 308459.58)', 27700), 4326); 
```

The point seems to be shifted and completely misaligned with the base map layer (point does not fall on the wall). 

![image](https://user-images.githubusercontent.com/10170044/156328307-4bf1fa7f-ea55-4350-b1a7-cacb3712279f.png)

I assume that PostGIS is using one default transformation which is not very accurate. 

However, when I load the same point to QGIS (which uses  local version of PROJ), I am able to pick the transformation that will be used. I picked OSTN15 (which has been installed locally), and the transformed point is:

 1.3107334884090227, 52.62760352059889 

and it seems to be in the expected position:

![image](https://user-images.githubusercontent.com/10170044/156328464-4bc14d80-310c-4f8c-96fc-1084d20ee49e.png)

This is the comparison of the 2 points:
![image](https://user-images.githubusercontent.com/10170044/156327480-dc4a5a12-f80b-4d42-aaf0-a6357df0b145.png)

#### Problem description

This 'shift' appears to affect all the polygons.

Question: Is this a known bug or is PROJ using a less accurate transformation than OSTN15?
Does a later version of PROJ use OSTN15? Is there a way to perform the correct transformation in the remote DB?

#### Expected Output

Original point in 27700:  624161 308459.58
What I get in 4326:  1.310709885004937 52.62757895156674
What I expect in 4326: 1.3107334884090227, 52.62760352059889

#### Environment Information

Remote DB:

PostgreSQL 11.12

POSTGIS="2.5.2 r17328" [EXTENSION] 
PGSQL="110" GEOS="3.7.0-CAPI-1.11.0 673b9939" 
PROJ="Rel. 5.2.0, September 15th, 2018" 
GDAL="GDAL 2.3.1, released 2018/06/22" 
LIBXML="2.9.1" LIBJSON="0.12.1"
 LIBPROTOBUF="1.3.0" TOPOLOGY RASTER

**Comment by rouault** [comment]
> Question: Is this a known bug or is PROJ using a less accurate transformation than OSTN15?

From the result you get, PostGIS is likely using the "OSGB36 to WGS 84 (6)" transformation which uses a Helmert transformation. This is not surprising given that your PostGIS version uses a "antiquated" PROJ version. Either update to a more recent PostGIS + PROJ, or add a custom entry in the spatial_ref_sys table with a PROJ.4 strings that refer to the OSTN15 grid. In any case, this isn't a PROJ bug as the following (which will use the OSTN15 grid through the network) gives the result you expect:
```
echo 624161 308459.58 | PROJ_NETWORK=ON bin/cs2cs -d 8 EPSG:27700  EPSG:4326
52.62760352	1.31073349 0.00000000
```
