### ISSUE TITLE
manpage directory is hard coded. doesn't respect -DCMAKE_INSTALL_MANDIR

### ISSUE THREAD

**Issue by ArTourter** [OSGeo/proj.4#3080]
#### Example of problem
configuring compilation using

```bash
mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_MANDIR=/usr/man ..
make
make install
```
this installs the man pages in `/usr/share/man/...` and not in `/usr/man/...`

The path in indeed harcoded in man/CMakeLists.txt

#### Problem description

I am the maintainer for the slackbuilds.org repository for proj and the manpages in slackware are located in /usr/man not /usr/share/man. 
Until now the autotools version supported setting the manpages paths with the `--mandir=` flag but with autotoold phased out in v9.0.0, I have to use cmake.

The following patch should allow the use of the -DCMAKE_INSTALL_MANDIR flag while still keeping the default path as <PREFIX>/share/man  as specified by the  GNUInstallDirs default:

```diff
diff -Naur proj-9.0.0/man/CMakeLists.txt proj-9.0.0-new/man/CMakeLists.txt
--- proj-9.0.0/man/CMakeLists.txt       2022-02-23 18:51:04.000000000 +0000
+++ proj-9.0.0-new/man/CMakeLists.txt   2022-03-02 16:22:14.979350892 +0000
@@ -6,4 +6,4 @@
   man1/gie.1
   man1/projinfo.1
   man1/projsync.1
-  DESTINATION share/man/man1)
+  DESTINATION ${CMAKE_INSTALL_MANDIR}/man1)
```
I can submit a PR if you are ok with it.

#### Environment Information
 - PROJ version (`proj-9.0.0`)
 - Slackware Linux 15.0

#### Installation method
 - from source

**Comment by mwtoews** [comment]
Thanks for the detailed report and patch. It should appear for PROJ 9.0.1 currently planned for June 2022.
