### ISSUE TITLE
Error with lon_wrap on EPSG:2193 transformation

### ISSUE THREAD

**Issue by ondave** [OSGeo/proj.4#3095]
Maybe I am misunderstanding something, but there appears to be an error when applying lon_wrap to a transformation of coordinates in EPSG:2193 CRS. However lon_wrap works correctly for other projections. Is this because EPSG:2193 has the coordinates in the opposite sense (northing,easting)?

#### Example of problem
Correct:
```
echo 5000000 2400000 | cs2cs epsg:2193 +to +proj=longlat +ellps=WGS84
176d54'6.504"W	44d42'16.899"S 0.000
```
Wrong:
```
echo 5000000 2400000 | cs2cs epsg:2193 +to +proj=longlat +ellps=WGS84 +lon_wrap=180
229d40'28.234"E	54d20'55.484"S 0.000
```
However for other transformations it works as expected
Correct:
```
echo -40 -177 | cs2cs epsg:4326 +to +proj=lonlat +ellps=WGS84 +lon_wrap=180
183dE	40dS 0.000
```
Correct (UTM01S):
```
echo 500000 5572242 | cs2cs epsg:32701 +to +proj=lonlat +ellps=WGS84
177dW	40d0'0.025"S 0.000
```
Correct (UTM01S):
```
echo 500000 5572242 | cs2cs epsg:32701 +to +proj=lonlat +ellps=WGS84 +lon_wrap=180
183dE	40d0'0.025"S 0.000
```

#### Environment Information
 - PROJ version 9.0.0
 - osgeo/proj docker

**Comment by rouault** [comment]
> Is this because EPSG:2193 has the coordinates in the opposite sense (northing,easting)?

yes exactly. fix queued in PR #3108
