### ISSUE TITLE
test 19 - ngk fails building proj 9.0.0

### ISSUE THREAD

**Issue by okanisis** [OSGeo/proj.4#3121]
Building in a clean chroot using arch linux.

The output of `ctest --output-on-failure --test-dir build` reports the following:
```
      Start 19: nkg
19/58 Test #19: nkg ..............................***Failed    3.42 sec
-------------------------------------------------------------------------------
Reading file '/build/proj/src/proj-9.0.0/test/gie/nkg.gie'
     -----
     FAILURE in nkg.gie(211):
     expected: 3275753.9111 321110.8658 5445041.8822 2020.0
     got:      3275753.909377121367   321110.862629641255   5445041.881752743   2020.000000000
     deviation:  3.635866 mm,  expected:  0.100000 mm
     -----
     FAILURE in nkg.gie(215):
     expected: 2391774.5535 615614.9100 5860965.8138 2020.0
     got:      2391774.548114618286   615614.906333823106   5860965.818464150   2020.000000000
     deviation:  8.012333 mm,  expected:  0.100000 mm
     -----
     FAILURE in nkg.gie(219):
     expected: 2107889.5097 895603.2085 5933242.3152 2020.0
     got:      2107889.501365525648   895603.205471481429   5933242.320781169   2020.000000000
     deviation:  10.477825 mm,  expected:  0.100000 mm
-------------------------------------------------------------------------------
total: 28 tests succeeded,  0 tests skipped,  3 tests FAILED!
-------------------------------------------------------------------------------
```

**Comment by mwtoews** [comment]
Thanks for the report, this issues was fixed with #3106

**Comment by kbevers** [comment]
I've been doing a bit of digging around since failures in the NKG transformations is a big concern of mine. 

My first observation is that ctest does not pick up the `nkg` gie file in all versions 8.0.0 and 9.0.0. I suspect something to do with network connectivity being disabled or not being able to pick up the necessary grid files. Not sure which it is at this point. I didn't investigate this thoroughly, might be a problem on my end.

With that in mind I've been testing with

```
PROJ_LIB=data/for_tests PROJ_NETWORK=ON bin/gie ../repo/test/gie/nkg.gie
```

and established that the error was introduced between 8.0.0 and 8.0.1. The above seems like a likely explanation as to why it wasn't discovered then. With the improved tests for CMake added in 9.0.0 the problem surfaced. Bisecting with git leads to the following commit being the offender:

```
$ git bisect bad
eeb9fef28aed4f7e5d62d8c5064f96e1090ee348 is the first bad commit
commit eeb9fef28aed4f7e5d62d8c5064f96e1090ee348
Author: Sveinung Himle <56073535+himsve@users.noreply.github.com>
Date:   Thu Mar 11 10:48:49 2021 +0100

    Database: Additions to the norwegian NKG2020 transformation (#2548), and NGO48 to ETRS89 TIN transfrm (#2554)

    * Correction grid NKG:ETRF14 to EPSG:7922

    * Added NKG:ITRF_TO_NO GIE test

    * Correction grid no_kv_NKGETRF14_EPSG7922_2000 added to grid_alternatives.sql

    * proj_method 'velocity_grid' added in check_grid_alternatives_proj_method. NKG velocity grid added to grid_alternatives.sql

    * also include follow-up fix to master #2548: e10a849cd01c5b15e3123da1f6df845006322843

    * Add NGO48 (EPSG:4273) to ETRS89 (EPSG:4258) triangulation-based transformation (#2554)

    Co-authored-by: Even Rouault <even.rouault@spatialys.com>

 data/Makefile.am                         |   3 +-
 data/sql/grid_alternatives.sql           |   6 +
 data/sql/nkg.sql                         | 191 ++++++++++++++++++++++++++++---
 data/sql/nkg_post_customizations.sql     |  13 +++
 data/sql/other_transformation_custom.sql |  16 +++
 data/sql/proj_db_table_defs.sql          |   4 +-
 data/sql_filelist.cmake                  |   3 +-
 test/cli/testprojinfo                    |   4 +
 test/cli/testprojinfo_out.dist           |   5 +
 test/gie/nkg.gie                         |  17 +++
 10 files changed, 245 insertions(+), 17 deletions(-)
 create mode 100644 data/sql/nkg_post_customizations.sql
```

So, the issue seem to be localized in Norway and my interest in the problem is a bit lower than a couple of hours ago but I'm sure @himsve will take up the gauntlet from here :-) I'm not sure if the adjusted coordinates in #3106 is the correct solution of the problem is elsewhere.

**Comment by rouault** [comment]
> PROJ_LIB=data/for_tests PROJ_NETWORK=ON bin/gie ../repo/test/gie/nkg.gie

you'll need to clear the local grid cache in ~/.local/share/proj/cache.db first to get the new version of the grid.

**Comment by kbevers** [comment]
> ~/.local/share/proj/cache.db

I don't seem to have one of those. This is on Mac, should I look for it elsewhere? Nothing obvious comes to mind

**Comment by rouault** [comment]
> This is on Mac, should I look for it elsewhere?

Likely $HOME/Library/Application Support : https://github.com/OSGeo/PROJ/blob/2235bef8a9de0f032722d1117f86752cd5f907e2/src/filemanager.cpp#L1191

**Comment by kbevers** [comment]
Yeah, that was it. Same results when deleting `cache.db` for every `git bisect` step.

**Comment by rouault** [comment]
> Same results when deleting `cache.db` for every `git bisect` step.

when running with ctest, a specific user writable directory is used, in $build_dir/tmp_user_writable_dir . You'll also need to wipe it.

**Comment by kbevers** [comment]
> when running with ctest, a specific user writable directory is used, in $build_dir/tmp_user_writable_dir . You'll also need to wipe it.

Same results still. For every git bisect step I run the following commands:

```
$ rm -rf tmp_user_writable_dir/ ; rm ~/Library/Application\ Support/proj/cache.db ; cmake --build . -j16
$ PROJ_LIB=data/for_tests PROJ_NETWORK=ON bin/gie ../repo/test/gie/nkg.gie
```

These are run from `~/dev/proj/build`. The git repo is in `~/dev/proj/repo`. I initiate the git bisection with

```
git checkout 8.0.1
git bisect start
git bisect good 8.0.0
git bisect bad
```

Are there any other temporary files I need to wipe? :-)

**Comment by rouault** [comment]
I'm not sure what you are issue is, but it looks to me that your bisect attempt is bound to not bring anything. Basically the new test points were added in 8.0.1, but with the new grid data updated a few days ago in https://github.com/OSGeo/PROJ-data/pull/79 (PROJ-data, not PROJ), the expected results of that time no longer work and need the update of https://github.com/OSGeo/PROJ/pull/3106 . You'd need to bisect both PROJ, PROJ-data and the cdn.proj.org content at the same time, which is not doable

**Comment by kbevers** [comment]
> I'm not sure what you are issue is,

obviously, this:

> Basically the new test points were added in 8.0.1, but with the new grid data updated a few days ago in https://github.com/OSGeo/PROJ-data/pull/79 (PROJ-data, not PROJ), the expected results of that time no longer work and need the update of https://github.com/OSGeo/PROJ/pull/3106

I think I missed (forgot, really) the changes in PROJ-data. I was looking for a code change that would explain the differences. I guess everything is in order. And as a bonus I now understand why that is :-) It would be cool if the cdn supported fetching the specific grid version that is needed by a specific PROJ version but that sounds like a pain in the ass to maintain.

**Comment by julienlau** [comment]
I opened a duplicate ticket and this problem is not restricted to version 9.0.0 because 8.2.1 has the exact same bug !
version 7.2.1 pass all unit tests.
https://github.com/OSGeo/PROJ/issues/3178
