### ISSUE TITLE
Interrupted Mollweide projection

### ISSUE THREAD

**Issue by lukegre** [OSGeo/proj.4#3122]
Hi, I'm an oceanographer and often make maps of the global ocean. 
One of the things I'd love to be able to do is plot my data with an interrupted Mollweide projection. 
There is currently the Interrupted Goode Homolosine projection; however, for the ocean focus, there is a slight discontinuity between the Mollweide and Sinusoidal projections. This can be distracting. 
Would it be possible to implement an interrupted Mollweide projection as shown in the figure below?

![interrupted projections](https://www.researchgate.net/profile/Bernhard-Jenny/publication/315857917/figure/fig3/AS:482571982249988@1492065534454/Examples-of-interrupted-projections-for-mapping-continents-top-and-oceans-bottom_W640.jpg)

Unfortunately, I've never worked with projections, nor have I worked in C++, which it seems the projections are written in, so it might be a bit of a stretch for me to take a stab at this.

**Comment by rouault** [comment]
You're probably looking for https://proj.org/operations/projections/igh_o.html
