### ISSUE TITLE
Plz update old ARM64 apt package to PROJ 6.1 or higher!!

### ISSUE THREAD

**Issue by arics2020** [OSGeo/proj.4#3131]
Sys: Ubuntu 18, ARM64

(1)
Trying to install pyproj on ARM64 gives me:

pip3 install pyproj==2.2.0
Collecting pyproj==2.2.0
  Downloading https://files.pythonhosted.org/packages/73/ef/53a7e9e98595baf4d7212aa731fcec256b432a3db60a55b58a027a4d9d47/pyproj-2.2.0.tar.gz (378kB)
    100% |████████████████████████████████| 378kB 1.4MB/s 
    Complete output from command python setup.py egg_info:
    **ERROR: Minimum supported proj version is 6.1.0, installed version is 4.9.3.**

(2)
Updating PROJ via apt gives me:
sudo apt-get install proj-bin

proj-bin is already the newest version (4.9.3-2).

Plz update old ARM64 apt package to PROJ 6.1 or higher!!

**Comment by rouault** [comment]
This is a packaging related issue (and even then, I don't think it is a bug. You just need to update to a more recent Ubuntu version), not a PROJ upstream bug
