### ISSUE TITLE
Cannot find sqlite3 during configure

### ISSUE THREAD

**Issue by 4535jacks** [OSGeo/proj.4#3143]
I am trying to install Proj 8.1.0 on Raspberry OS 64-bit so I can install Cartopy.  Using sudo apt-get install proj-bin installs version 7.2.1 which is too old.

I have downloaded and extracted Proj 8.1.0. Using the terminal, I am trying to configure then install the package but it cannot find sqlite3 even  though is installed and listed as an installed package.

I am unable to install conda to install that way.

#### Problem description

During configure, it returns the following error:

_checking for SQLITE3... configure: error: Package requirements (sqlite3 >= 3.11) were not met:

No package 'sqlite3' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables SQLITE3_CFLAGS
and SQLITE3_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details._

sqlite3 is installed.  When I enter sqlite3 --version, the following is returned:

3.34.1 2021-01-20 14:10:07 10e20c0b43500cfb9bbc0eaa061c57514f715d87238f4d835880cd846b9ealt1

#### Expected Output
The configure process should be completed successfully since sqlite3 is installed.

#### Environment Information
 - PROJ version (`proj`) - 8.1.0
 - Raspberry OS 64-bit

#### Installation method
 - I have dowloaded and extracted the source code and ran configure using ./configure

**Comment by rouault** [comment]
you also need to install the sqlite3 development package. The sqlite3 binary is required, but not sufficient
