### ISSUE TITLE
Incorrect coordinate operations in the presence of bound and compund CRSs

### ISSUE THREAD

**Issue by hernando** [OSGeo/proj.4#3152]
#### Example of problem

I have a legacy WKT1 string that contains a TOWGS84 field. This is coming from existing data that I was using for testing purposes.
The string is this:
```
ch1903lv03_bound='PROJCS["CH1903 / LV03",GEOGCS["CH1903",DATUM["CH1903",SPHEROID["Bessel 1841",6377397.155,299.1528128,AUTHORITY["EPSG","7004"]],TOWGS84[674.4,15.1,405.3,0,0,0,0],AUTHORITY["EPSG","6149"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4149"]],PROJECTION["Hotine_Oblique_Mercator_Azimuth_Center"],PARAMETER["latitude_of_center",46.95240555555556],PARAMETER["longitude_of_center",7.439583333333333],PARAMETER["azimuth",90],PARAMETER["rectified_grid_angle",90],PARAMETER["scale_factor",1],PARAMETER["false_easting",600000],PARAMETER["false_northing",200000],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Y",EAST],AXIS["X",NORTH]]'
```
I'm trying to convert a coordinate in this system either promoted to 3D or compound with EPSG:5728 to EPSG:4326+3855 and I see all sorts of strange candidate operations in the list provided by `projinfo`. In fact, I tested a few transformations with or without grids available and I get as much 4 significantly different horizontal coordinates in the output. The report will be already long so for brevity I will omit the description of all these experiments, but I can provide more details on demand.

For testing purposes I promoted the CRS above to 3D doing this:
```
ch1903lv03_3d_bound=$(projinfo "${ch1903lv03_bound}" --single-line -o WKT2:2019 -q --3d)
```
and I obtained the compound with 5728 doing this:
```
ch1903lv03_ln02_bound=$(projinfo EPSG:21781+5728 -o WKT1:GDAL --boundcrs-to-wgs84 -q --single-line)
```
(and then tweaking the TOWGS84 parameters to be the same).
From here on I assume that using WKT1:GDAL or WKT2:2019 for statement above makes no difference.

I will provide a few examples of the output from `projinfo -s "$ch1903lv03_ln02_bound" -t EPSG:4326+3855 -o PROJ --spatial-test intersects` and  `projinfo -s "$ch1903lv03_3d_bound" -t EPSG:4326+3855 -o PROJ --spatial-test intersects` that I found incorrect.

For the 3D promoted:
```
Operation No. 1:
unknown id, Inverse of unnamed + CH1903 to WGS 84 (3) + WGS 84 to EGM2008 height (1), 2.5 m, Liechtenstein; Switzerland.

PROJ string:
+proj=pipeline
  +step +inv +proj=somerc +lat_0=46.9524055555556 +lon_0=7.43958333333333 +k_0=1
        +x_0=600000 +y_0=200000 +ellps=bessel
  +step +proj=hgridshift +grids=ch_swisstopo_CHENyx06_ETRS.tif
  +step +inv +proj=vgridshift +grids=us_nga_egm08_25.tif +multiplier=1
  +step +proj=unitconvert +xy_in=rad +xy_out=deg
  +step +proj=axisswap +order=2,1
```
Here the grid is used despite it shouldn't. The name says "Inverse of unnamed", but that operation appears nowhere.
That fact that this is the first candidate in the list is a bit problematic. This is the most important observation I would like to make, you can skip the rest until the problem description if you don't want to be bothered by less important details.

```
Operation No. 5:

unknown id, Inverse of unnamed + Inverse of Ballpark geographic offset from WGS 84 to CH1903 + WGS 84 to EGM2008 height (1), unknown accuracy, World, has ballpark transformation

PROJ string:
+proj=pipeline
  +step +inv +proj=somerc +lat_0=46.9524055555556 +lon_0=7.43958333333333 +k_0=1
        +x_0=600000 +y_0=200000 +ellps=bessel
  +step +inv +proj=vgridshift +grids=us_nga_egm08_25.tif +multiplier=1
  +step +proj=unitconvert +xy_in=rad +xy_out=deg
  +step +proj=axisswap +order=2,1
```
This operation mentions "Inverse of unnamed" but it contains a ballpark geographic offset instead (as mentioned in the name).

```
Operation No. 8:

unknown id, Inverse of unnamed + Inverse of Transformation from EGM2008 height to CH1903 (ballpark vertical transformation, without ellipsoid height to vertical height correction) + Inverse of Ballpark geographic offset from WGS 84 to CH1903, unknown accuracy, World, has ballpark transformation

PROJ string:
+proj=pipeline
  +step +inv +proj=somerc +lat_0=46.9524055555556 +lon_0=7.43958333333333 +k_0=1
        +x_0=600000 +y_0=200000 +ellps=bessel
  +step +proj=unitconvert +xy_in=rad +xy_out=deg
  +step +proj=axisswap +order=2,1
```
As before this one says something about the bound, but it doesn't contain it.
The most problematic aspect of this one is that it's the first operation in the list that doesn't require any grids. So in case the EGM2008 geoid is not available, this is the transformation that will be preferred over the next one, despite being completely incorrect for the horizontal part.

```
Operation No. 9:

unknown id, Inverse of unnamed + Inverse of Transformation from EGM2008 height to CH1903 (ballpark vertical transformation, without ellipsoid height to vertical height correction) + CH1903 to WGS 84 (2), unknown accuracy, Liechtenstein; Switzerland., has ballpark transformation

PROJ string:
+proj=pipeline
  +step +inv +proj=somerc +lat_0=46.9524055555556 +lon_0=7.43958333333333 +k_0=1
        +x_0=600000 +y_0=200000 +ellps=bessel
  +step +proj=push +v_3
  +step +proj=cart +ellps=bessel
  +step +inv +proj=helmert +x=-674.374 +y=-15.056 +z=-405.346
  +step +inv +proj=cart +ellps=WGS84
  +step +proj=pop +v_3
  +step +proj=unitconvert +xy_in=rad +xy_out=deg
  +step +proj=axisswap +order=2,1
  ```
  There's nothing wrong with this one when there are no grids available, but it's the last one instead of being preferred over operation 8 which contains more ballpark transformations.
  
 For the compound case, if grids are available the first candidate transformation looks quite good.
 Then we have:
 ```
Operation No. 2:

unknown id, Inverse of Swiss Oblique Mercator 1903M + CH1903 to WGS 84 (2) + Inverse of ETRS89 to WGS 84 (1) + Inverse of ETRS89 to LN02 height + Inverse of CH1903 to ETRS89 (2) + CH1903 to WGS 84 (2) + WGS 84 to EGM2008 height (1), unknown accuracy, Liechtenstein; Switzerland.

PROJ string:
+proj=pipeline
  +step +inv +proj=somerc +lat_0=46.9524055555556 +lon_0=7.43958333333333 +k_0=1
        +x_0=600000 +y_0=200000 +ellps=bessel
  +step +proj=push +v_3
  +step +proj=cart +ellps=bessel
  +step +proj=helmert +x=674.374 +y=15.056 +z=405.346
  +step +inv +proj=cart +ellps=GRS80
  +step +proj=pop +v_3
  +step +proj=vgridshift +grids=ch_swisstopo_chgeo2004_ETRS89_LN02.tif
        +multiplier=1
  +step +inv +proj=hgridshift +grids=ch_swisstopo_CHENyx06_ETRS.tif
  +step +proj=cart +ellps=bessel
  +step +proj=helmert +x=674.374 +y=15.056 +z=405.346
  +step +inv +proj=cart +ellps=WGS84
  +step +inv +proj=vgridshift +grids=us_nga_egm08_25.tif +multiplier=1
  +step +proj=unitconvert +xy_in=rad +xy_out=deg
  +step +proj=axisswap +order=2,1
 ```
 I can't judge if this one is correct or not but I find strange that after applying the first Helmert transformation with the parameters in the TOWGS84, it then applies the grid and then another Helmert transformation.
 The 3rd operation does the same but reversing the order and using inverses.
 The pattern repeats with combinations for the other EGM2008 grid and no EGM2008 grid at all.
 
In this list there are no alternatives for the case of not having any vertical grid.
Despite the transformation could be reasonable without grids because both the input and output are orthometric heights and there's a explicit Helmert transformation with the bounding, my experiments show that the transformation is a no transformation at all.
 

#### Problem description

Horizontal grids used when they shouldn't.
The name of the operation contains unnamed in cases there the bounding was not applied.
No grid-less alternatives for compound with bound to compound.

#### Expected Output

The minimum I would expect, no matter the case, is that if the CRS is bound, no horizontal grids are applied to the input coordinates, as that defeats the purpose of the bounding, doesn't it?
(maybe it makes sense for intermediary steps, but I don't think PROJ tries to create pipelines with so many stages for this to happen).

#### Environment Information
 - PROJ master as commit b1d2fcb2cfa0612ed1a61c6218030ab7df8c35cd
 - Ubuntu 20.04

#### Installation method
 - Compiled from source

**Comment by rouault** [comment]
> The name says "Inverse of unnamed",

'unnamed' here is just the name of the CONVERSION[] / Map projection. Artifact of using WKT1.

For the rest, fixes/improvements in https://github.com/OSGeo/PROJ/pull/3153. This approaches, and perhaps goes already beyond, to the point where I can understand my own code.

**Comment by hernando** [comment]
I've tested it and the output of `projinfo` now looks much better, thanks.
I would like to test the transformation for real, but that will take a bit longer.
