### ISSUE TITLE
seeking advice for proj_create_crs_to_crs and tinshift transform

### ISSUE THREAD

**Issue by josch** [OSGeo/proj.4#3161]
Dear Proj maintainers,

thanks a lot for your amazing help with implementing the `fallback_strategy` option for `tinshift` in #2903 and #2907. I'm using this to warp maps and render them with mapnik. This all worked well until mapnik added support for more recent proj >= 7 and with it added a call to `proj_create_crs_to_crs`: https://github.com/mapnik/mapnik/commit/88241b32eeaccdc9eda7b92b7e7b6d4deac88e12#diff-3817884b302c98d6b02df071fa796efda25b53389fcedf28f6b7c200a7ed5efdR130

My tinshift pipeline `+proj=pipeline +step +proj=webmerc +step +proj=tinshift +file=/tmp/tinshift.json` is not a crs so with mapnik from git, my code will fail with `proj_create_operations: source_crs is not a CRS`.

Unfortunately I'm still a proj noob and while I found `+type=crs` in the docs, adding it to my pipeline didn't solve the problem.

So my question to you is: is there a way to turn my proj string into a crs? And if not, what should mapnik replace `proj_create_crs_to_crs` with so that it still works with a non-crs source?

Thank you!

**Comment by rouault** [comment]
> So my question to you is: is there a way to turn my proj string into a crs?

no


> And if not, what should mapnik replace `proj_create_crs_to_crs` with so that it still works with a non-crs source?

it could offer the possibility to handle a PROJ transformation pipeline by using `proj_create`

**Comment by josch** [comment]
Thanks! Do you know of existing code using `proj_create` to allow non-crs input? When searching for code examples it seems that the world moved to `proj_create_crs_to_crs`. :(

Do I also understand it correctly, that to get a single transformation for use with `proj_trans` from source to target with my source containing a pipeline would result in a nested pipeline?

**Comment by snowman2** [comment]
> Do you know of existing code using proj_create to allow non-crs input?

pyproj may be a useful reference:
- `proj_create`: [Transformer.from_pipeline](https://github.com/pyproj4/pyproj/blob/a5cdc60e2db44acdc7b6b09a1632e348d206e0e2/pyproj/_transformer.pyx#L1025-L1054)
- `proj_create_crs_to_crs`: [Transformer.from_crs](https://github.com/pyproj4/pyproj/blob/a5cdc60e2db44acdc7b6b09a1632e348d206e0e2/pyproj/_transformer.pyx#L948-L1004)

**Comment by josch** [comment]
Than you @snowman2, I asked the same question on the ML and got a very helpful reply from @rouault: https://lists.osgeo.org/pipermail/proj/2022-April/010597.html

I'll reply to that mail and update my [question on stackoverflow](https://stackoverflow.com/questions/71823105/migrating-to-proj-api-6-without-forcing-crs-input) once I have some code. :)
