### ISSUE TITLE
PROJ binary compatibility

### ISSUE THREAD

**Issue by whuaegeanse** [OSGeo/proj.4#3162]
PROJ built via CMake, should be binary compatible regardless of the version of Visual Studio (above 2015).
Issue reported here https://github.com/microsoft/vcpkg/issues/24035

The relevant code is here https://github.com/OSGeo/PROJ/blob/master/cmake/project-config-version.cmake.in#L38-L45

Change the relevant  code from
 ```
elseif (MSVC AND NOT (
    # toolset version must be at least as great as @PROJECT_NAME@'s
    MSVC_TOOLSET_VERSION GREATER_EQUAL @MSVC_TOOLSET_VERSION@
    # and major versions must match
    AND MSVC_TOOLSET_MAJOR EQUAL @MSVC_TOOLSET_MAJOR@ ))
   # Reject if there's a mismatch in MSVC compiler versions
   set (REASON "MSVC_TOOLSET_VERSION = @MSVC_TOOLSET_VERSION@")
   set (PACKAGE_VERSION_UNSUITABLE TRUE)
```
to 
 ```
elseif (MSVC AND (MSVC_TOOLSET_VERSION LESS 140)  NOT (
   # toolset version must be at least as great as @PROJECT_NAME@'s
    MSVC_TOOLSET_VERSION GREATER_EQUAL @MSVC_TOOLSET_VERSION@
    # and major versions must match
    AND MSVC_TOOLSET_MAJOR EQUAL @MSVC_TOOLSET_MAJOR@ ))
   # Reject if there's a mismatch in MSVC compiler versions
   set (REASON "MSVC_TOOLSET_VERSION = @MSVC_TOOLSET_VERSION@")
   set (PACKAGE_VERSION_UNSUITABLE TRUE)
```

**Comment by rouault** [comment]
I'm not sure there is a bug. Reading https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=msvc-170#restrictions first paragraph, it seems to me that if you wanted to link a PROJ built by with toolset 143 / MSVC 2022  to an application built with an older MSVC version, you need to ensure you use at least toolset >= 143, which is exactly what we enforce currently

**Comment by whuaegeanse** [comment]
@rouault Thanks. Sorry for my misunderstanding about binary compatibility.
