### ISSUE TITLE
nkg test fails on RH 8

### ISSUE THREAD

**Issue by justbennet** [OSGeo/proj.4#3164]
#### Three of the nkg tests are failing for numerical differences

All other tests passed, except these three.

```
$ ctest --rerun-failed --output-on-failure
Test project /tmp/bennetsw/build/proj-9.0.0/build
    Start 19: nkg
1/1 Test #19: nkg ..............................***Failed    0.16 sec
-------------------------------------------------------------------------------
Reading file '/tmp/bennetsw/build/proj-9.0.0/test/gie/nkg.gie'
     -----
     FAILURE in nkg.gie(211):
     expected: 3275753.9111 321110.8658 5445041.8822 2020.0
     got:      3275753.909377121367   321110.862629641255   5445041.881752743   2020.000000000
     deviation:  3.635866 mm,  expected:  0.100000 mm
     -----
     FAILURE in nkg.gie(215):
     expected: 2391774.5535 615614.9100 5860965.8138 2020.0
     got:      2391774.548114618286   615614.906333823106   5860965.818464150   2020.000000000
     deviation:  8.012333 mm,  expected:  0.100000 mm
     -----
     FAILURE in nkg.gie(219):
     expected: 2107889.5097 895603.2085 5933242.3152 2020.0
     got:      2107889.501365525648   895603.205471481429   5933242.320781169   2020.000000000
     deviation:  10.477825 mm,  expected:  0.100000 mm
-------------------------------------------------------------------------------
total: 28 tests succeeded,  0 tests skipped,  3 tests FAILED!
-------------------------------------------------------------------------------
```

#### Expected Output

Passing tests

#### Environment Information
 - PROJ version : 9.0.0
 - Red Hat 8.5, GCC 10.3.0

#### Installation method
 - from source
 
 Using GCC 10.3.0 compiled from source; using `libtiff.so.5.7.0` compiled with the same GCC and sqlite3 installed by the OS.

I have also tried this with the `libtiff` installed by the OS and with the GCC 8.5.0 installed by the OS with the same results.

**Comment by rouault** [comment]
duplicate of https://github.com/OSGeo/PROJ/issues/3121

**Comment by julienlau** [comment]
I opened the duplicate ticket and this problem is not restricted to version 9.0.0 and 8.2.1 has the exact same bug !

**Comment by kbevers** [comment]
The gist of it all is that the changes were made to some Norwegian transformations (accessed via the NKG authority) and we forgot to update the test suite to reflect the changes in the transformation. You can ignore the failing test. If you really care a lot about the test suite not failing you can create a patch from the most recent version of the NKG test files.

PROJ doesn't have plugins so disabling is not an option.

**Comment by julienlau** [comment]
thanks I care a lot about unit tests so I'll stick to v7.2.1 until the patch is released
