### ISSUE TITLE
Inverse transformation for Winkel Tripel

### ISSUE THREAD

**Issue by kannes** [OSGeo/proj.4#3179]
The inverse projection of Winkel Tripel (ESRI:54042) is not supported in PROJ yet: https://proj.org/operations/projections/wintri.html

This leads to e.g. QGIS not being able to display raster files in this projection. For reference: the inverse of Winkel 2 was added following a report over at https://github.com/qgis/QGIS/issues/35512

I would jump in circles if Proj had support for the inverse projection of Winkel Tripel. :)

**Comment by rouault** [comment]
> I would jump in circles if Proj had support for the inverse projection of Winkel Tripel. :)

you can jump in circles. PROJ has actually support for inverse wintri for a long time
$ echo 2 49 | bin/proj +proj=wintri +lat_1=45 | bin/proj +proj=wintri +lat_1=45 -I
2dE	49dN

This is just a documentation issue. Fix in https://github.com/OSGeo/PROJ/pull/3195

**Comment by mwtoews** [comment]
This was added in 2015 for PROJ 4.9.1 484aa69e1509c9716bd8c5b38c94664ef03785c9
