### ISSUE TITLE
MNT: 9.0 branch - update version to 9.0.1

### ISSUE THREAD

**Issue by snowman2** [OSGeo/proj.4#3192]

**Comment by rouault** [comment]
isn't that a pyproj ticket ?

**Comment by snowman2** [comment]
> isn't that a pyproj ticket ?

https://github.com/OSGeo/PROJ/blob/a8b6143574a2a79d74164680210b5e0cea3143d7/docs/source/conf.py#L80

**Comment by rouault** [comment]
> version = '9.0.0'

that's appropriate until 9.0.1 has been released. Updating it is part of the release procedure.

**Comment by snowman2** [comment]
I noticed this commit (https://github.com/OSGeo/PROJ/commit/4fbe193257004d458d548f4f75feb67700aedc10) and thought it was missed.

The reason why I brought it up was because the `osgeo/proj:latest` image says it is 9.0.0. However, that is misleading as it is built using the `9.0` branch with the `9.0.1` features.

This may be a separate issue then. The mechanism that is publishing to `osgeo/proj:latest` may need to be updated to prevent publishing to `latest` without a release.

**Comment by kbevers** [comment]
> that's appropriate until 9.0.1 has been released. Updating it is part of the release procedure.

The reason for this is that whatever is pushed to the current maintenance branch (9.0 in this case) is puslished on proj.org. We obviously don't want to advertise a version number that hasn't been released yet.

**Comment by snowman2** [comment]
Thanks for the information :+1:
