### ISSUE TITLE
proj_coordoperation_get_grid_used out_full_name empty when PROJ_NETWORK=ON

### ISSUE THREAD

**Issue by snowman2** [OSGeo/proj.4#3201]
From: https://github.com/pyproj4/pyproj/issues/1078

Relevant pseudo code:
```c
        PJ* coord_operation_pj = proj_create_from_database(
            context,
            "EPSG",
            "1312",
            PJ_CATEGORY_COORDINATE_OPERATION,
            true,
            NULL,
        )
        const char *out_short_name
        const char *out_full_name
        const char *out_package_name
        const char *out_url
        int direct_download = 0
        int open_license = 0
        int available = 0
        proj_coordoperation_get_grid_used(
            context,
            coord_operation_pj,
            0,
            &out_short_name,
            &out_full_name,
            &out_package_name,
            &out_url,
            &direct_download,
            &open_license,
            &available
        )
```

Since this commit: 5298fc0bfe3b73a994f0ff668f3392b803af45e5 `proj_coordoperation_get_grid_used(): make it work more reliably when networking is enabled (fixes #3176)`

`out_full_name` is now an empty string. It used to have the filename. Is this the intended behavior of the change?

**Comment by rouault** [comment]
> `out_full_name` is now an empty string. It used to have the filename. Is this the intended behavior of the change?

if the file is not available on your system, yes this is the indented behavior. Previously when considerKnownGridsAsAvailable==True (which is the case when networking was enabled), out_full_name was set with the (short) file name, which doesn't seem appropriate to me.

**Comment by snowman2** [comment]
Perfect, thanks for clarifying :+1:
