### ISSUE TITLE
Non-Earth projections (e.g. Mars) in proj 7.2.1

### ISSUE THREAD

**Issue by All4Gis** [OSGeo/proj.4#3227]
Hi

I don't know if I should ask it here, or in postgis, QGIS or in some mailing list, but since it's related to proj, if not, could you tell me the best place to ask? I ask it here

When we upgraded postgis 3.2.1 , also updates the version of proj to the 7.2.1 version, 

`POSTGIS="3.0.5 df5f8b7" [EXTENSION] PGSQL="130" GEOS="3.9.2-CAPI-1.14.3" PROJ="7.2.1" LIBXML="2.9.1" LIBJSON="0.11" LIBPROTOBUF="1.0.2" WAGYU="0.4.3 (Internal)"`

The problem is with the definition of a projection system on Mars.The definition we had with proj 5 (old postgis version) of the mars reference system was like this and is working well with Proj 5:

```
INSERT into spatial_ref_sys (srid, auth_name, auth_srid, proj4text, srtext) values ( 949900, 'IAU2000', 49900, 
'+proj=longlat +a=3396190 +b=3376200 +no_defs ', 
'GEOGCS["Mars 2000",DATUM["D_Mars_2000",SPHEROID["Mars_2000_IAU_IAG",3396190.0,169.89444722361179]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]');
```

But it gives an error in Postgis 3.2.1

`could not form projection (PJ) from 'srid=949900' to 'srid=4326'
`
The Postgis code part is : https://github.com/paulyc/postgis/blob/2ee8e58e5f2401951cd9cd9765274100c324376d/libpgcommon/lwgeom_transform.c#L452

I have updated the projection definition based on some values that QGIS returned to me to and use this

```
INSERT into spatial_ref_sys (srid, auth_name, auth_srid, proj4text, srtext) values ( 949900, 'IAU2000', 49900, 
'+proj=longlat +a=3396190 +rf=169.894447223612 +no_defs +type=crs', 
'GEOGCRS["Mars 2000",
    DATUM["D_Mars_2000",
        ELLIPSOID["Mars_2000_IAU_IAG",3396190,169.894447223612,
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]],
    PRIMEM["Reference meridian",0,
        ANGLEUNIT["degree",0.0174532925199433,
            ID["EPSG",9122]]],
    CS[ellipsoidal,2],
        AXIS["longitude",east,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]],
        AXIS["latitude",north,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]]]');
```

but it still fails.

And the postgres log say:

```
proj_create: crs not found
proj_create: crs not found
proj_create: crs not found
proj_create_operations: Source and target ellipsoid do not belong to the same celestial body
proj_create_operations: Source and target ellipsoid do not belong to the same celestial body
proj_create_operations: Source and target ellipsoid do not belong to the same celestial body
proj_create_operations: Source and target ellipsoid do not belong to the same celestial body
proj_create_operations: Source and target ellipsoid do not belong to the same celestial body
proj_create_operations: Source and target ellipsoid do not belong to the same celestial body
ERROR:  could not form projection (PJ) from 'srid=949900' to 'srid=4326'
```

My **question** is:, Proj 7.2.1 is compatible with non-earth projections?, or maybe I'm defining projection wrong?

**Comment by rouault** [comment]
Newer PROJ version don't allow to do coordinate operations between a non-Earth and a Earth CRS, for obvious physical reasons.
