### ISSUE TITLE
Question about proj.db file location

### ISSUE THREAD

**Issue by willcohen** [OSGeo/proj.4#3232]
Hello --

I'm working on compiling PROJ to webassembly via emscripten, so it's usable in javascript, but am having some issues getting the webassembly version (or wasm2js javascript) to properly open the `proj.db` file. As best as I understand it, `emscripten` generally creates a fake filesystem mounted at `"/"` which native code can access (https://emscripten.org/docs/porting/files/file_systems_overview.html), and I've successfully mounted the database file in that environment at, say, `/data/proj.db`. 

Generally speaking, in a case like this, am I understanding correctly that the process to have proj use a db file in that location would be to:

1. create a context using `proj_context_create()`,
2. then modify that context `proj_context_set_database_path(context, "/data/proj.db")`, 
3. and from that point on, running other commands context should correctly access the database in this new location?

**Comment by rouault** [comment]
yes to your question
why tagging this as "bug" ? (if so, that should be demonstrated with a simple C reproducer using just PROJ API, not the WASM port)

**Comment by willcohen** [comment]
Not meant to be tagged as a bug! Wasn't sure which template to pick for feature request versus bug report, and I didn't realize the label came with. Would remove the label but not sure how.

Many thanks!

**Comment by pfw** [comment]
@willcohen How'd you going getting the wasm build running? Is that something you have in a repo somewhere that can be looked at?

**Comment by busstoptaktik** [comment]
@pfw  if your needs for wasm-based transformation functionality are modest, you may take a look at the experimental [Rust Geodesy](https://github.com/busstoptaktik/geodesy), which may be an easier target than PROJ - both by being much smaller (<5000 lines of code), and by being written in Rust, which presumably natively supports compilation to wasm (although I have never tried it myself)

**Comment by pfw** [comment]
@busstoptaktik Thanks, I'll take a look, Rust certainly makes this simpler. Ideally we could use PROJ directly given existing process and understanding.

**Comment by willcohen** [comment]
Apologies for missing this a while back @pfw -- I hit a pretty big blocker which was that one of the possible targets I needed to try to hit was graalwasm, which had no bulk memory, which meant that all the file i/o was basically impossible, and I was also struggling with getting the compiled wasm to transpile, so I was stuck. That seems to be implemented with a latest release, so I'm going to try to pick this back up and see if I can get this working in a non-browser environment. I may also end up needing to explore sqlite's recent work with working with wasm and file IO, though it sounds like there's really no good way to deal with this unless emscripten's filesystem emulation is used. I think that'll work with graal because I will see if I can use both graaljs and graalwasm. If you need to use WASI exclusively etc, the tooling may not quite be there yet!

**Comment by willcohen** [comment]
For what it's worth, progress on this suggests that JS is still a prerequisite. That said, the WASM build (with emscripten wrapper) now successfully works on both the browser and the JVM via graal.
<img width="1198" alt="Screenshot 2023-01-03 at 2 04 03 PM" src="https://user-images.githubusercontent.com/5185341/210424427-567f4223-9b80-4539-b8cf-00b8506b3fb3.png">

My next task is to get this cleaned up. This should mean I'm able to wrap upstream PROJ, targeting both the JVM and JS universally using both native interop for common platforms on the JVM and WASM as a fallback for the JVM and as the normal target for the browser.

@kbevers
