### ISSUE TITLE
proj_grid_info returns only name for grids mapped via proj.db

### ISSUE THREAD

**Issue by gaige** [OSGeo/proj.4#3238]
#### Example of problem

```c
char *gridname = "stlrnc";
setenv( "PROJ_DEBUG", "4", 1); 
PJ_GRID_INFO info = proj_grid_info(gridname);
if (strcmp(info.format,"gtiff")==0) {
   printf("Not using TIFF");
}
```

Meanwhile with `grid name` above set to `us_noaa_stlrnc.tif` (which is the mapped file), the full data is presented.

#### Problem description

`proj_grid_info` no longer returns full information on grids that were coerced using the LUT in proj.db.  In this case, the problem was triggered when running some automated tests we had based on using older proj formats.  The result is that anything entries such as `stlrnc`, which can be resolved into a grid set (`us_noaa_stlrnc.tif`) by using the LUT in `proj.db` were returning only `.name` because `pj_find_file()` does not perform the same lookup as is done by `NS_PROJ::HorizontalShiftGridSet::open()`.  At the time of the call to `fillGridInfo()`, the `gridset` contains the full path for these types of grids, available in `gridset->name()`, but isn't passed in.

Before the call to `fillGridInfo()`, the `gridset` contains:

```c
 osgeo::proj::Grid = {
    m_name = "<thepath>/us_noaa_stlrnc.tif"
    m_width = 81
    m_height = 41
    m_extent = {
      isGeographic = true
      west = -3.001966313430247
      south = 1.0821041362364843
      east = -2.9321531433504737
      north = 1.1170107212763709
      resX = 0.00087266462599716479
      resY = 0.00087266462599716479
      invResX = 1145.9155902616465
      invResY = 1145.9155902616465
    }
  }
  m_children = size=0 {}
}
```
However, the returned data is:

```c
(PJ_GRID_INFO) grinfo = {
  gridname = "stlrnc"
  filename = ""
  format = ""
  lowerleft = (lam = 0, phi = 0)
  upperright = (lam = 0, phi = 0)
  n_lon = 0
  n_lat = 0
  cs_lon = 0
  cs_lat = 0
}
```

#### Expected Output

Prior to the changes in https://github.com/OSGeo/PROJ/pull/3072/commits/bc34a84eab410b82a14e181da3eec598309e7312, the data structure was complete.

Existing tests in `gie_self_tests.cpp` do not test for the situation where the grid is mapped from an old proj string.

There seems to be minimal use outside of `gie`, and the tests there are specifically for either directly-named grids. 

#### Environment Information
 - 9.0.1 (built from source using cmake)
 - macOS 12.4

#### Installation method
 - built from source

**Comment by rouault** [comment]
In master, FileManager::open_resource_file() (called by HorizontalShiftGridSet::open(()) now calls  pj_find_file() by disabling networking, so the scope of the bug in master was reduced to querying information on remote known grids, compared to the 9.0 branch.

**Comment by gaige** [comment]
Thank you for the speedy confirmation and fix! I replaced my initial fix with this one and it is working well.
