### ISSUE TITLE
Proj8 is much slower than proj6 transforming NZMG.

### ISSUE THREAD

**Issue by captain-igloo** [OSGeo/proj.4#3240]
#### Example of problem
Proj 8 is much slower than proj 6 transforming NZMG when using the proj string "+proj=nzmg +lat_0=-41 +lon_0=173 +x_0=2510000 +y_0=6023150 +ellps=intl +datum=nzgd49 +units=m +no_defs".  This proj string is from https://spatialreference.org/ref/epsg/27200/proj4/ .  If I use the proj string from https://epsg.io/27200 then proj8 is fast.

See https://github.com/captain-igloo/proj8-slow for a demonstration.

```
git clone https://github.com/captain-igloo/proj8-slow
cd proj8-slow

docker build -t test-proj6 -f proj6.Dockerfile .
docker build -t test-proj8 -f proj8.Dockerfile .

# takes 3 seconds
time docker run test-proj6 /proj-slow/a.out
# takes 18 seconds
time docker run test-proj8 /proj-slow/a.out
```

#### Problem description

Proj version 8 is much slower (say 600%) than proj version 6.

#### Expected Output

Proj 8 should not be that slow.

#### Environment Information
 - 8.2.1 and 6.3.1
 - ubuntu jammy and ubuntu focal

#### Installation method
 - apt

**Comment by rouault** [comment]
when you use the PROJ string "+proj=nzmg +lat_0=-41 +lon_0=173 +x_0=2510000 +y_0=6023150 +ellps=intl +datum=nzgd49 +units=m +no_defs", the nzgd2kgrid0005 grid will be used.
In PROJ 7, grid handling was rewritten, with a focus on handling grids in geotiff format, and we are indeed aware that performance with older formats such as NTv2 might have suffered. I suspect you must still have the nzgd2kgrid0005.gsb NTv2 grid around in your PROJ resource directory if you use PROJ from the Ubuntu packages (Debian/Ubuntu packagers still ship the older grids).  You may want to download the https://raw.githubusercontent.com/OSGeo/PROJ-data/master/nz_linz/nz_linz_nzgd2kgrid0005.tif equivalent grid in TIFF format, and put in your PROJ data directory (also available in the big archive http://download.osgeo.org/proj/proj-data-1.10.tar.gz)

**Comment by mwtoews** [comment]
Try these modifications
```diff
 diff --git a/proj8.Dockerfile b/proj8.Dockerfile
index 63ebed9..1610d07 100644
--- a/proj8.Dockerfile
+++ b/proj8.Dockerfile
@@ -5,6 +5,7 @@ COPY test-proj.cpp /proj-slow/
 RUN apt update \
     && apt install -y --no-install-recommends \
     g++ \
-    libproj-dev \
+    libproj-dev proj-bin ca-certificates \
     && cd /proj-slow \
-    && g++ test-proj.cpp -lproj
+    && g++ test-proj.cpp -lproj \
+    && projsync --file nzgd2kgrid0005.tif
```
Results should get closer to proj6 speeds. See [projsync](https://proj.org/apps/projsync.html) for further info.

**Comment by captain-igloo** [comment]
Thank you, that works perfectly.
