### ISSUE TITLE
Providing access to CRS definitions via an S3 resource

### ISSUE THREAD

**Issue by rowanwins** [OSGeo/proj.4#3258]
I've recently been using the epsg.io website to access some projection information based on a CRS code, they offer a web service where you can make a http request that returns the CRS info in a variety of formats, eg
https://epsg.io/4326.proj4
https://epsg.io/4326.wkt

I was wondering if it was within scope for the PROJ project to perhaps do something similar and put the equivalent CRS information as assets in S3? It would be nice to know that I was pulling the info from the most up-to-date source.

Does that sound feasible?

**Comment by kbevers** [comment]
This sounds like a nice and simple community project. After all, you're basically just asking for a wrapper for `projinfo`. I don't really want to put more obligations on the PROJ team, there's plenty of work in keeping things running as is.

Both @hobu and I have played around with something similar. Mine is https://github.com/SDFIdk/WEBPROJ and Howard called his henzuru.io but I am not sure what the state of that is. They serve different purposes but demonstrate that you can achive what you want fairly quickly.

**Comment by rouault** [comment]
The rejuvenated https://spatialreference.org/ offers what is requested here
