### ISSUE TITLE
Support geocentric coordinate reference system as BOUNDCRS source

### ISSUE THREAD

**Issue by hernando** [OSGeo/proj.4#3262]
According to https://docs.opengeospatial.org/is/18-010r7/18-010r7.html#63, clause 20.1, last paragraph, the source CRS of a bound CRS should conform to a full CRS as described in clause 8. Clause 8 refers to geodetic or geographic CRSs. A geodetic CRS may have a 3D Cartesian coordinate system (clause 8.3).

Having the possibility of supporting geocentric CRS as bound source would allow to describe transformations for so-called site calibrations using a WKT string such as:
```
BOUNDCRS[
    SOURCECRS[
        GEODCRS["Local site",
            DATUM["Local site",
                ELLIPSOID["GRS 1980",6378137,298.257222101,
                    LENGTHUNIT["metre",1]]],
            PRIMEM["Greenwich",0,
                ANGLEUNIT["degree",0.0174532925199433]],
            CS[Cartesian,3],
                AXIS["(X)",geocentricX,
                    ORDER[1],
                    LENGTHUNIT["metre",1]],
                AXIS["(Y)",geocentricY,
                    ORDER[2],
                    LENGTHUNIT["metre",1]],
                AXIS["(Z)",geocentricZ,
                    ORDER[3],
                    LENGTHUNIT["metre",1]]]],
    TARGETCRS[
        GEOGCRS["WGS 84",
            DATUM["World Geodetic System 1984",
                ELLIPSOID["WGS 84",6378137,298.257223563,
                    LENGTHUNIT["metre",1]]],
            PRIMEM["Greenwich",0,
                ANGLEUNIT["degree",0.0174532925199433]],
            CS[ellipsoidal,2],
                AXIS["latitude",north,
                    ORDER[1],
                    ANGLEUNIT["degree",0.0174532925199433]],
                AXIS["longitude",east,
                    ORDER[2],
                    ANGLEUNIT["degree",0.0174532925199433]],
            ID["EPSG",4326]]],
    ABRIDGEDTRANSFORMATION["Local to global",
        METHOD["Geocentric translations (geog2D domain)",
            ID["EPSG",9603]],
        PARAMETER["X-axis translation",674.374,
            ID["EPSG",8605]],
        PARAMETER["Y-axis translation",15.056,
            ID["EPSG",8606]],
        PARAMETER["Z-axis translation",405.346,
            ID["EPSG",8607]]]]
```

Right now if that string is fed to `projinfo`, it complains with:
```
input string: parsing of user string failed: Cannot find GeographicCRS or VerticalCRS in sourceCRS
```

**Comment by rouault** [comment]
This is possible, but if the source CRS is geocentric, the implementation requires the target CRS to also be geocentric, and the tranfsformation should use METHOD["Geocentric translations (geocentric domain)", ID["EPSG",1031]]

example:
```
$ projinfo "+proj=geocent +towgs84=1,2,3 +type=crs"
PROJ.4 string:
+proj=geocent +ellps=WGS84 +towgs84=1,2,3,0,0,0,0 +units=m +no_defs +type=crs

WKT2:2019 string:
BOUNDCRS[
    SOURCECRS[
        GEODCRS["unknown",
            DATUM["World Geodetic System 1984",
                ELLIPSOID["WGS 84",6378137,298.257223563,
                    LENGTHUNIT["metre",1]],
                ID["EPSG",6326]],
            PRIMEM["Greenwich",0,
                ANGLEUNIT["degree",0.0174532925199433],
                ID["EPSG",8901]],
            CS[Cartesian,3],
                AXIS["(X)",geocentricX,
                    ORDER[1],
                    LENGTHUNIT["metre",1,
                        ID["EPSG",9001]]],
                AXIS["(Y)",geocentricY,
                    ORDER[2],
                    LENGTHUNIT["metre",1,
                        ID["EPSG",9001]]],
                AXIS["(Z)",geocentricZ,
                    ORDER[3],
                    LENGTHUNIT["metre",1,
                        ID["EPSG",9001]]]]],
    TARGETCRS[
        GEODCRS["WGS 84",
            DATUM["World Geodetic System 1984",
                ELLIPSOID["WGS 84",6378137,298.257223563,
                    LENGTHUNIT["metre",1]]],
            PRIMEM["Greenwich",0,
                ANGLEUNIT["degree",0.0174532925199433]],
            CS[Cartesian,3],
                AXIS["(X)",geocentricX,
                    ORDER[1],
                    LENGTHUNIT["metre",1]],
                AXIS["(Y)",geocentricY,
                    ORDER[2],
                    LENGTHUNIT["metre",1]],
                AXIS["(Z)",geocentricZ,
                    ORDER[3],
                    LENGTHUNIT["metre",1]],
            ID["EPSG",4978]]],
    ABRIDGEDTRANSFORMATION["Transformation from unknown to WGS84",
        METHOD["Geocentric translations (geocentric domain)",
            ID["EPSG",1031]],
        PARAMETER["X-axis translation",1,
            ID["EPSG",8605]],
        PARAMETER["Y-axis translation",2,
            ID["EPSG",8606]],
        PARAMETER["Z-axis translation",3,
            ID["EPSG",8607]]]]
```

**Comment by hernando** [comment]
Interesting, where is this restriction specified in the standard? I couldn't find it.

**Comment by hernando** [comment]
And another question. This requires having target coordinates in a geocentric CRS. Since the idea is to use this for site calibrations, the reference points are assumed to be measured using a RTK/PPK rover, so the target CRS will be a regional CRS (e.g. NAD83(2011)). Is there any fool-proof way of finding the matching geocentric CRS given a geographic one and what are the chances of not finding any?

**Comment by rouault** [comment]
> Interesting, where is this restriction specified in the standard?

I don't think the WKT standard specifies that level of detail, but it seems more logical to me that the objects are of the same nature / compatible. The BoundCRS written this way is very close to the COORDINATEOPERATION[] that would describe the transformation from the source to the target.

> Is there any fool-proof way of finding the matching geocentric CRS given a geographic one and what are the chances of not finding any?

generally the geographic 2D, 3D and geocentric CRS share the same name, so it is a matter of specifing PJ_TYPE_GEOCENTRIC_CRS to proj_create_from_name()

**Comment by hernando** [comment]
Thanks for the replies.

> > Interesting, where is this restriction specified in the standard?
> 
> I don't think the WKT standard specifies that level of detail, but it seems more logical to me that the objects are of the same nature / compatible. The BoundCRS written this way is very close to the COORDINATEOPERATION[] that would describe the transformation from the source to the target.
>
Since some operations require converting from geographic to geocentric, I naively assumed that I could mix geographic and geocentric in the target/source. But doing a bit of search in epsg.org I've learned that operations specify a domain that may imply geographic to geocentric conversions when necessary (for example, I didn't know there were 3 variations of Position Vector Transformation). And I don't see any operation mixing geocentric and geodetic coordinates, so you're expectation is right.
 
> > Is there any fool-proof way of finding the matching geocentric CRS given a geographic one and what are the chances of not finding any?
> 
> generally the geographic 2D, 3D and geocentric CRS share the same name, so it is a matter of specifing PJ_TYPE_GEOCENTRIC_CRS to proj_create_from_name()

I already found a CRS for which there's no geocentric equivalent (CH1903+). Let's see how far I get with this information.

I will close the ticket.
