### ISSUE TITLE
different cs2cs results between anaconda prompt and powershell, but same environment

### ISSUE THREAD

**Issue by ryan101** [OSGeo/proj.4#3267]
**Description**
When using the cs2cs command in a conda environment with only PROJ installed, I get different results depending on if I execute the command in the conda prompt or windows powershell. This extends to IDEs that use powershell internally. Tests were run on windows 11 with conda 4.13.0, python 3.9, and PROJ 9.01. 

**Steps to reproduce**
Create a new conda environment with python 3.9
`conda create --name projtest python=3.9`

Activate the new conda environment and install any version of PROJ >= 7.0.0 (which is the first version I observed this issue)
`conda install -c conda-forge proj=9.0.1`

In the anaconda prompt activate the projtest environment and run:
`echo 347775 5467809 | cs2cs +init=epsg:26915 +to +init=epsg:6933`
Result: -917543**7.08**     555946**6.20** 0.00

In windows powershell activate the projtest environment and run:
`echo @"`  
`347775 5467809`  
`"@ | cs2cs +init=epsg:26915 +to +init=epsg:6933 `  
Result: -917543**5.26**     555946**5.77** 0.00

Expected result:
Identical coordinates

Actual result:
Differences of 1 to 2 meters (in bold above)

While investigating this I noticed that the output results from powershell were identical when the input epsg was either 26915 or 32615. When the input epsg was set to 32615 in the anaconda prompt, the results matched those of powershell. EPSG:26915 is UTM15N NAD83 datum whereas epsg:32615 is UTM15N WGS84 datum.  

Furthermore, when I create a new conda environment and install PROJ 6.2.1 and repeat the test, the anaconda prompt results change to match those from powershell with later versions of PROJ:
-9175435.26     5559465.77 0.00

I'm having trouble figuring out which value is correct because of the interplay between PROJ version, datums, and execution environment.

**Comment by rouault** [comment]
I get the same difference locally on Linux whether I enable access to PROJ grids or not with PROJ_NETWORK=ON. I assume your environment is slightly different in the 2 cases
```
even@even-ThinkPad-P15v-Gen-1:~/proj/proj/build_cmake$ echo 347775 5467809 | bin/cs2cs +init=epsg:26915 +to +init=epsg:6933
-9175435.26	5559465.77 0.00
even@even-ThinkPad-P15v-Gen-1:~/proj/proj/build_cmake$ echo 347775 5467809 | PROJ_NETWORK=ON bin/cs2cs +init=epsg:26915 +to +init=epsg:6933
-9175437.08	5559466.20 0.00
```
PROJ in Conda should set the PROJ_NETWORK=ON environemnt variable according to https://github.com/conda-forge/proj.4-feedstock/blob/782aa9dbea84e3c61f6f05a645b6c00d6fbd418f/recipe/scripts/activate.bat
Probably some bad interaction with that and Powershell. Try setting it manually. If you believe there's an issue with the Conda package, report it to https://github.com/conda-forge/proj.4-feedstock
