### ISSUE TITLE
Incorrect target ellipsoid used when converting from projected to cartesian coordinates without +nadgrids=@null

### ISSUE THREAD

**Issue by Chippiewill** [OSGeo/proj.4#3272]
#### Example of problem

I encountered a weird problem when using Proj and I'm not entirely sure where the problem lies, but I'm most tempted to say in Proj itself. I found a very large change in behavior depending on whether or not `+nadgrids=@null` was present in the source proj string when converting from projected to cartesian coordinates where the projected CRS is a sphere and the cartesian CRS is an ellipsoid.

```
# with nadgrids=@null
$ echo 0 0 | docker run -i --rm osgeo/proj cs2cs +proj=tmerc +x_0=0 +y_0=-5430329.64144626 +lon_0=8.920207297374926 +a=6378137 +b=6378137 +no_defs +k=1.0 +units=m +nadgrids=@null +to +proj=cart
4159816.72	652913.07 4774580.95

# without
$ echo 0 0 | docker run -i --rm osgeo/proj cs2cs +proj=tmerc +x_0=0 +y_0=-5430329.64144626 +lon_0=8.920207297374926 +a=6378137 +b=6378137 +no_defs +k=1.0 +units=m +to +proj=cart 
4151931.11	651675.37 4797647.22
```

This difference corresponds to the difference between geocentric and geodetic latitude.

I can't say I fully understand nadgrids well enough to know if this is ought to be correct behaviour, however this specifically came up because the proj string in question got round-tripped via DotSpatial which removes `+nadgrids=@null` when it's present: https://github.com/DotSpatial/DotSpatial/blob/85c5c0ec59d45556e43694fefd302c1d47f5f497/Source/Core/DotSpatial.Projections/ProjectionInfo.cs#L1157-L1166 so my assumption is that it ought to be a no-op.

If I manually add an intermediary step of going to geodetic coordinates (`+proj=latlong`) then I get the expected behaviour (the value when `+nadgrids=@null` is present).

#### Problem description

Curiously when using PROJ_DEBUG=3, the generated pipeline is quite different when `+nadgrids=@null` is used .Aside from the addition of a `hgridshift` step, it also correctly uses the ellipsoid defined in the target for the output rather than using the source ellipsoid (this applies regardless of whether `+ellps` or similar is provided as an explicit argument to `+proj=cart` or even an EPSG code).

```diff
--- /tmp/a	2022-08-01 12:25:19.393920177 +0100
+++ /tmp/b	2022-08-01 12:25:27.613930775 +0100
@@ -1,5 +1,6 @@
-echo 0 0 | PROJ_DEBUG=3 cs2cs +proj=tmerc +x_0=0 +y_0=-5430329.64144626 +lon_0=8.920207297374926 +a=6378137 +b=6378137 +no_defs +k=1.0 +units=m +to +proj=cart               
+echo 0 0 | PROJ_DEBUG=3 cs2cs +proj=tmerc +x_0=0 +y_0=-5430329.64144626 +lon_0=8.920207297374926 +a=6378137 +b=6378137 +no_defs +k=1.0 +units=m +nadgrids=null +to +proj=cart
 pj_open_lib(proj.db): call fopen(/usr/share/proj/proj.db) - succeeded
+pj_open_lib(null): call fopen(null) - failed
 pipeline: pj_ellipsoid - final: a=6378137.000 f=1/  0.000, errno=0
 pipeline: pj_ellipsoid - final:    
 pipeline: Pipeline: Building arg list for step no. 0
@@ -11,18 +12,21 @@
 pipeline:     x_0=0
 pipeline:     y_0=-5430329.64144626
 pipeline:     R=6378137
-pipeline: Pipeline: Step 0 (inv) at 0x55f86af80bf0
-pipeline: Pipeline at [0x55f86af801b0]:    step at [0x55f86af80bf0] (inv) done
+pipeline: Pipeline: Step 0 (inv) at 0x562c6f9961b0
+pipeline: Pipeline at [0x562c6f74e1f0]:    step at [0x562c6f9961b0] (inv) done
 pipeline: Pipeline: Building arg list for step no. 1
-pipeline: Pipeline: init - inv, 3
-pipeline:     proj=longlat
-pipeline:     R=6378137
-pipeline: Pipeline: Step 1 (inv) at 0x55f86af811c0
-pipeline: Pipeline at [0x55f86af801b0]:    step at [0x55f86af811c0] (inv) done
+pipeline: Pipeline: init - proj=hgridshift, 2
+pipeline:     grids=null
+hgridshift: pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
+hgridshift: pj_ellipsoid - final:    ellps=GRS80
+pipeline: Pipeline: Step 1 (proj=hgridshift) at 0x562c6f996780
+pipeline: Pipeline at [0x562c6f74e1f0]:    step at [0x562c6f996780] (proj=hgridshift) done
 pipeline: Pipeline: Building arg list for step no. 2
 pipeline: Pipeline: init - proj=cart, 2
-pipeline:     R=6378137
-pipeline: Pipeline: Step 2 (proj=cart) at 0x55f86af816a0
-pipeline: Pipeline at [0x55f86af801b0]:    step at [0x55f86af816a0] (proj=cart) done
+pipeline:     ellps=WGS84
+cart: pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
+cart: pj_ellipsoid - final:    ellps=WGS84
+pipeline: Pipeline: Step 2 (proj=cart) at 0x562c6f996cc0
+pipeline: Pipeline at [0x562c6f74e1f0]:    step at [0x562c6f996cc0] (proj=cart) done
 pipeline: Pipeline: 3 steps built. Determining i/o characteristics
-4151931.11	651675.37 4797647.22
+4159816.72	652913.07 4774580.95
```

It's also worth noting that the `+nadgrids` value doesn't even need to be `null`, it can also be any non-existent option with the optional flag like `+nadgrids=@does-not-exist`

#### Expected Output

I would expect specification of nadgrids=null to be a no-op in this situation.

#### Environment Information

Run from latest docker image (osgeo/proj 9.1.0)

**Comment by rouault** [comment]
This is more a usage issue than a PROJ issue, although PROJ behavior is indeed a bit surprising
The main issue here is that your target CRS has no datum specification, and in the case where your source CRS has no nadgrids=@null parameter, then PROJ just doesn't do any datum shift at all, and will just do the inverse cart operation on the R=6378137 sphere
When nadgrids=@null is specified, then PROJ will consider that the coordinates after the inverse tmerc operation are in the WGS84 ellipsoid, and thus the inverse cart operation will be done done on that ellipsoid.
PROJ behaves like expected here: behaviour when explicit datum specification (that is presence of +towgs84, +nadgrids or +datum) is lacking in one or both source/target CRS is rarely the one you want.

**Comment by Chippiewill** [comment]
Cheers for the response, that makes a lot of sense.

I guess if PROJ were being designed today then it would probably produce an error in these situations (where there's no datum in just one of the CRS feels like it should always be a mistake) but legacy behavior's always an odd one :)

**Comment by Chippiewill** [comment]
One thing that's still unclear from your explanation is why this wouldn't have the same impact when converting between two projected CRSs rather than cartesian (In this case projecting to UTM with the airy ellipsoid for whatever bizarre reason):

```
echo 0 0 | docker run -i --rm -e PROJ_DEBUG=3 osgeo/proj cs2cs +proj=tmerc +x_0=0 +y_0=-5430329.64144626 +lon_0=8.920207297374926 +a=6378137 +b=6378137 +no_defs +k=1.0 +units=m +to +proj=utm +zone=31 +ellps=airy
pj_open_lib(proj.db): call fopen(/usr/share/proj/proj.db) - succeeded
934765.80	5419691.65 0.00
pipeline: pj_ellipsoid - final: a=6378137.000 f=1/  0.000, errno=0
pipeline: pj_ellipsoid - final:    
pipeline: Pipeline: Building arg list for step no. 0
pipeline: Pipeline: init - inv, 8
pipeline:     proj=tmerc
pipeline:     lat_0=0
pipeline:     lon_0=8.92020729737493
pipeline:     k=1
pipeline:     x_0=0
pipeline:     y_0=-5430329.64144626
pipeline:     R=6378137
pipeline: Pipeline: Step 0 (inv) at 0x55611e562120
pipeline: Pipeline at [0x55611e561c40]:    step at [0x55611e562120] (inv) done
pipeline: Pipeline: Building arg list for step no. 1
pipeline: Pipeline: init - proj=utm, 3
pipeline:     zone=31
pipeline:     ellps=airy
utm: pj_ellipsoid - final: a=6377563.396 f=1/299.325, errno=0
utm: pj_ellipsoid - final:    ellps=airy
pipeline: Pipeline: Step 1 (proj=utm) at 0x55611e5626f0
pipeline: Pipeline at [0x55611e561c40]:    step at [0x55611e5626f0] (proj=utm) done
pipeline: Pipeline: 2 steps built. Determining i/o characteristics
```

Surely it should encounter the same problem of the source CRS not having a datum and just reusing the source sphere when projecting back?
