### ISSUE TITLE
curl and libtiff is not optional as stated

### ISSUE THREAD

**Issue by mrx23dot** [OSGeo/proj.4#3278]
Cant install from source without curl and libtiff as stated in readme.md.

**Comment by kbevers** [comment]
At build time you need to explicitly state that you don't want to use those dependencies. See [`ENABLE_CURL`](https://proj.org/install.html#cmdoption-arg-ENABLE_CURL) and [`ENABLE_TIFF`](https://proj.org/install.html#cmdoption-arg-ENABLE_TIFF).
