### ISSUE TITLE
can't find webp.dll

### ISSUE THREAD

**Issue by just-ads** [OSGeo/proj.4#3285]
I tried reinstalling

![image](https://user-images.githubusercontent.com/50706050/184574272-d0f59b3a-e4eb-44a9-afdd-31caffebafff.png)

**Comment by rouault** [comment]
This isn't a PROJ issue, but a OSGeo4W one (or usage of it)

**Comment by lucadelu** [comment]
@rouault my colleague got the same problem using conda as described in [the documentation](https://proj.org/install.html)

**Comment by rouault** [comment]
perhaps check that there isn't in the PATH another directory than the Conda one with a webp.dll

**Comment by xakod** [comment]
@rouault I have the same problem. I cleared path before OSGeo4W.bat.
![изображение](https://github.com/OSGeo/PROJ/assets/26579016/fdbdef57-6184-45a1-b043-b17c8761f401)
C:\OSGeo4W does not contain webp.dll so there is no path problem. Looks like missing dll.
