### ISSUE TITLE
proj_create_crs_to_crs_from_pj can't set accuracy in options

### ISSUE THREAD

**Issue by GeorgGrebenyuk** [OSGeo/proj.4#3293]
Hello, I have a disunderstanding about function ```ACCURACY=*``` in options argument in ```proj_create_crs_to_crs_from_pj```. When I try set an high accuracy (f.e. =8), end result is leave as standard 4-symbols after point ...
That problem is looks like as that closed case ... https://github.com/OSGeo/PROJ/issues/2874

Or may be there is other way to getting more accuracy-result ...
#### Example of problem
Example code I wrote below. 

```cpp
	PJ_CONTEXT* C = proj_context_create();
	PJ* P_source = proj_create(C, "WGS 84 / UTM zone 36N");
	PJ* P_target = proj_create(C, "EPSG:4326");
	const char* const options[] = { "ACCURACY=8", nullptr };
	PJ* P_convert = proj_create_crs_to_crs_from_pj(C, P_source, P_target, NULL, options);
	if (0 == P_convert) {
		fprintf(stderr, "Failed to create transformation object.\n");
	}

	PJ_COORD a, b;
	//353803,6638030,0.0
	a = proj_coord(353803.154, 6638039.012, 0.0, 0.0);
	b = proj_trans(P_convert, PJ_FWD, a);
	std::cout << "recalced " << b.enu.e << " " << b.enu.n << std::endl;

	proj_destroy(P_convert);
	proj_destroy(P_source);
	proj_destroy(P_target);
	proj_context_destroy(C);

```

```
        _returned:_
        recalced 59.8541 30.39
```

#### Expected Output
```59.85398246 30.3899775```

#### Environment Information
 - PROJ version (`proj`) 9.0.1 (downloaded as binary dev.version by OSGeo4W)

**Comment by rouault** [comment]
You are confusing the accuracy of the transformation, which is a sort of statistical evaluation of the error (think to the standard deviation of the result got from the transformation with the "real" one), and the precision of display of results. The precision of display of results is entirely under your control with https://en.cppreference.com/w/cpp/io/manip/setprecision

**Comment by GeorgGrebenyuk** [comment]
Thank you for advice; it's helped me! 

```... << std::fixed << std::setprecision(14) << ...;```
