### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by conanlee88** [OSGeo/proj.4#3309]
#### Problem description
```c
[ 75%] Built target proj
make: *** [all] Error 2
[  0%] Built target create_tmp_user_writable_dir
[  1%] Generating proj.db
CMake Error at generate_proj_db.cmake:22 (message):
  SQLite3 failed

make[2]: *** [data/proj.db] Error 1
make[1]: *** [data/CMakeFiles/generate_proj_db.dir/all] Error 2
make: *** [all] Error 2
```
i build source code with cmake, but it failed with error msg as shown above.

#### Expected Output
Build proj success.

#### Environment Information
 - PROJ version (`9.2.0`)
 - qlite3 version (`3.38.2`)
 - Operation System Information  (`macOS Monterey with intel processor`)

#### Installation method
 - source with cmake.

**Comment by conanlee88** [comment]
it is my own problem, i forget to set local path for my own buildscript.

**Comment by mht2953658596** [comment]
are you add SQLITE3_LIBRARY  to cmake,and sovle this problem? i meet the same problem😭

**Comment by dg0yt** [comment]
> are you add SQLITE3_LIBRARY to cmake,and sovle this problem? i meet the same problem😭

No, you need to make sure that the `sqlite3` program can be found by cmake.
