### ISSUE TITLE
Transformations with same horizontal datum but different vertical datum outputs the same Z value

### ISSUE THREAD

**Issue by fullonic** [OSGeo/proj.4#3323]
Hi!

Accordingly with this [geoid calculator](https://geographiclib.sourceforge.io/cgi-bin/GeoidEval?input=39.9320+3.9856), there is a ~2 meters difference between the EGM96 and the EGM84 for the coordinates `39.9320, 3.9856`. However, when using the `gdaltransform` CLI, the `Z` output value is the same as the input.

## Expected behavior and actual behavior.

If I'm correct, the `Z` output value should reflect this ~2 meters difference

## Steps to reproduce the problem.
```bash
$ echo "3.9856 39.9320 52.422000885009766" | gdaltransform --debug on -s_srs EPSG:4326+5773 -t_srs EPSG:4326+5798
>> 3.9856 39.932 52.4220008850098
```

## Operating system

Ubuntu 20.04 64 bit

## GDAL version and provenance

GDAL 3.5.1, released 2022/06/30, built with CMake

Thanks

**Comment by rouault** [comment]
Transfering as a PROJ issue

PROJ doesn't bundle the EGM84 geoid, so you get a null transformation between EGM84 and EGM96. Is EGM84 still used for real ?

**Comment by fullonic** [comment]
Hey, @rouault thanks for your answer. Actually, I'm not using the EGM84. The thing is that I tried with other geoids but the result Z is always the same as the Z input. And because according to the geoid calculator results, the difference between EGM84 and EGM96 is more notable, I give the example with the EGM84. However, it fails as well for EGM2008 (3855):
```bash
$ echo "3.9856 39.9320 52.422000885009766" | gdaltransform --debug on -s_srs EPSG:4326+5773 -t_srs EPSG:4326+3855
>> 3.9856 39.932 52.4220008850098
```
In this case, we should have a difference of ~0.2, right?

**Comment by fullonic** [comment]
I see the issue here, the geoid EGM2008 is neither included in the PROJ bundle
Using the below code works
```bash
$ echo "3.9856 39.9320 52.422000885009766" | gdaltransform --debug on -s_srs EPSG:4326+5773 -t_srs '+proj=longlat +datum=WGS84 +no_defs +geoidgrids=us_nga_egm08_25.tif'
3.9856 39.932 52.1222475054199
```

**Comment by rouault** [comment]
You need to have both the EGM96 and EGM2008 grids installed locally. See https://proj.org/resource_files.html#external-resources-and-packaged-grids
Or you can enable PROJ networking capabilities: https://proj.org/usage/network.html
```
$ echo "3.9856 39.9320 52.422000885009766" | PROJ_NETWORK=ON gdaltransform -s_srs EPSG:4326+5773 -t_srs EPSG:4326+3855
3.9856 39.932 52.1222475054199
```

**Comment by fullonic** [comment]
@rouault after using your recommendation by using the `PROJ_NETWORK=ON`, I found that still, some geoids don't work and return the same Z input value. 

For example:
Genoa 1942 height
```bash
$ echo "14.995 37.755 3357" | PROJ_NETWORK=ON gdaltransform --debug on -s_srs "EPSG:4326+5773" -t_srs "EPSG:32632+5214"
>> 1028333.73796622 4195591.29690422 3357
```
N2000
```bash
$ echo "25.15296 62.50195 269" | PROJ_NETWORK=ON gdaltransform --debug on -s_srs "EPSG:4326+5773" -t_srs "EPSG:3067+3900"
>> 404861.868388335 6931460.32557422 269
```
EVRF2007 
```bash
$ echo "27.059167 57.714444 318" | PROJ_NETWORK=ON gdaltransform --debug on -s_srs "EPSG:4326+5773" -t_srs "EPSG:3301+5621"
>> 682284.606829111 6401087.4159131 318
```
Thanks for your help
