### ISSUE TITLE
CMake Configure option "TIFF_LIBRARY_RELEASE" doesn't take effect

### ISSUE THREAD

**Issue by aangelcc** [OSGeo/proj.4#3326]
Hi PROJ developers and thank you for maintaining such a great library!

When trying to build PROJ 9.1.0 from source using CMake as explained in https://proj.org/install.html, I wanted to provide the path where `libtiff` could be found. This is done using the CMake configure option `TIFF_LIBRARY_RELEASE`.

However I couldn't manage to make it find the `libtiff` library. Instead I set the `TIFF_LIBRARY` configure option to the `libtiff` location and it indeed worked. So definitely there is a mismatch between the docs and the way the project can be configured as of now.

Also when searching into the source code for `TIFF_LIBRARY_RELEASE` I get no results, whereas if I search for `TIFF_LIBRARY` there is a result in `src/lib_proj.cmake` at line 462.

Thank you for your hard work!

Greetings,

Antonio

**Comment by dg0yt** [comment]
`TIFF_LIBRARY_RELEASE` is an input variable (aka cache variable), i.e. a variable which can be set by the user. Together with `TIFF_LIBRARY_DEBUG`, the macro `select_library_configuration` takes care of merging these values into the result variable `TIFF_LIBRARY`.
That is, with a recent enough version of CMake which provides that capability in `FindTIFF.cmake`. These particular input variables are documented since CMake 3.19. Older versions just use `TIFF_LIBRARY` as input and result variable.

**Comment by aangelcc** [comment]
Thank you so much @dg0yt for your detailed explanation :) I just followed the instructions from https://proj.org/install.html#compilation-and-installation-from-source-code (which apply to the current release 9.1.0), and downloaded the linked current release from there (v9.1.0) as well. When looking into the `.cmake` files I don't find any reference to `select_library_configuration`. So probably the published docs are ahead of the current 9.1.0 release?

**Comment by dg0yt** [comment]
You missed one point in my answer: "with a recent enough version of CMake which provides that capability in FindTIFF.cmake". So you don't have to look at PROJ but at CMake:
https://github.com/Kitware/CMake/blob/cabba23ab270eb5cc672c43265f9eb3cb7dda8cc/Modules/FindTIFF.cmake#L79-L82
So the PROJ docs provide convenience instructions based on current versions of CMake. But your Linux distribution may come with an a much older version.

**Comment by aangelcc** [comment]
You are completely right :) Thank you for the guidance. I was compiling proj using Android's NDK so it may come with a not so new CMake implementation. :)
