### ISSUE TITLE
PROJ 9.1.0: Issues transforming to CGVD28 height (EPSG:5713)

### ISSUE THREAD

**Issue by AlexBass05** [OSGeo/proj.4#3328]
I'm running into some issues in `PROJ 9.1.0` when transforming to CGVD28 height (EPSG:5713) that are not observable in `PROJ 9.0.1`. Below I'm going to state the initial issue and outline some of the investigations I did in trying to understand what is going, which unfortunately only lead to some follow-up issues:

#### The initial issue
Doing the following transformation fails in `PROJ 9.1.0`:
```c
$ echo 55.735000 -100.370000 0.000000 | PROJ_NETWORK=ON ./cs2cs EPSG:4326+5773 EPSG:4326+5713 -d 12
```
In `PROJ 9.0.1`: `55.734999999921	-100.369999999891 0.002552292625`
In `PROJ 9.1.0`: `*	* inf`

I know I'm using the WGS84 ensemble here and I'm aware of some of the implications in doing so (e.g. with respect to the accuracy of the transformation etc.). What I don't understand is, why `PROJ 9.1.0` is failing to transform the coordinates and is not even using a ballpark transformation.

#### Follow-up issue 1: `PROJ 9.1.0` is not attempting to use cdn.proj.org
Running the above command with `PROJ_DEBUG=2` I get something sensible in `PROJ 9.0.1` but this in `PROJ 9.1.0`:
```
pj_open_lib(proj.ini): call fopen(/.../PROJ/9.1.0/install/share/proj/proj.ini) - succeeded
pj_open_lib(proj.db): call fopen(/.../PROJ/9.1.0/install/share/proj/proj.db) - succeeded
pj_open_lib(us_nga_egm96_15.tif): call fopen(us_nga_egm96_15.tif) - failed
pj_open_lib(egm96_15.gtx): call fopen(egm96_15.gtx) - failed
pj_open_lib(HT2_1997_CGG2013a.byn): call fopen(HT2_1997_CGG2013a.byn) - failed
pj_open_lib(HT2_2002v70_CGG2013a.byn): call fopen(HT2_2002v70_CGG2013a.byn) - failed
pj_open_lib(ca_nrc_HT2_2010v70_CGG2013a.tif): call fopen(ca_nrc_HT2_2010v70_CGG2013a.tif) - failed
pj_open_lib(HT2_1997.byn): call fopen(HT2_1997.byn) - failed
pj_open_lib(HT2_2002v70.byn): call fopen(HT2_2002v70.byn) - failed
pj_open_lib(ca_nrc_HT2_2010v70.tif): call fopen(ca_nrc_HT2_2010v70.tif) - failed
pj_open_lib(HT2_2010v70.gtx): call fopen(HT2_2010v70.gtx) - failed
pj_open_lib(ca_nrc_NB7783v2.tif): call fopen(ca_nrc_NB7783v2.tif) - failed
pj_open_lib(NB7783v2.GSB): call fopen(NB7783v2.GSB) - failed
pj_open_lib(ca_nrc_NS778302.tif): call fopen(ca_nrc_NS778302.tif) - failed
pj_open_lib(NS778302.GSB): call fopen(NS778302.GSB) - failed
pj_open_lib(ca_nrc_PE7783V2.tif): call fopen(ca_nrc_PE7783V2.tif) - failed
pj_open_lib(PE7783V2.GSB): call fopen(PE7783V2.GSB) - failed
pj_open_lib(NS778301.gsb): call fopen(NS778301.gsb) - failed
pj_open_lib(NAD83v6VG.gvb): call fopen(NAD83v6VG.gvb) - failed
pj_open_lib(ca_nrc_SK83-98.tif): call fopen(ca_nrc_SK83-98.tif) - failed
pj_open_lib(SK83-98.GSB): call fopen(SK83-98.GSB) - failed
pj_open_lib(ABCSRSV7.GSB): call fopen(ABCSRSV7.GSB) - failed
pj_open_lib(ca_nrc_ABCSRSV4.tif): call fopen(ca_nrc_ABCSRSV4.tif) - failed
pj_open_lib(ABCSRSV4.GSB): call fopen(ABCSRSV4.GSB) - failed
pj_open_lib(us_noaa_emhpgn.tif): call fopen(us_noaa_emhpgn.tif) - failed
pj_open_lib(emhpgn.gsb): call fopen(emhpgn.gsb) - failed
pj_open_lib(us_noaa_wmhpgn.tif): call fopen(us_noaa_wmhpgn.tif) - failed
pj_open_lib(wmhpgn.gsb): call fopen(wmhpgn.gsb) - failed
pj_open_lib(us_noaa_WO.tif): call fopen(us_noaa_WO.tif) - failed
pj_open_lib(WO): call fopen(WO) - failed
pj_open_lib(NAD83v70VG.gvb): call fopen(NAD83v70VG.gvb) - failed
*	* inf
```
To my surprise I see a long list of necessary grid files that are not found locally but PROJ doesn't seem to make an attempt to obtain the from cdn.proj.org. (I'm missing logs like this: `Using https://cdn.proj.org/us_nga_egm96_15.tif`)

Why is `PROJ 9.1.0` not attempting to use cdn.proj.org? Or is it failing before getting to that point?

#### Follow-up issue 2: `PROJ 9.1.0` finds a lot of operations
I then tried to understand better which transformation PROJ is using:
```
./projinfo -s EPSG:4326+5773 -t EPSG:4326+5713 -o proj --spatial-test intersects
```
In `PROJ 9.0.1`: Find 2 possible operations
In `PROJ 9.1.0`: Finds 171 possible operations 

Where are all these operations coming from? Is `PROJ 9.1.0` trying every entry of the WGS84 ensemble?

#### Follow-up issue 3: `PROJ 9.1.0`: Mismatch between `projinfo` and `cs2cs`
I then tried to use something different than the WGS84 datum ensemble and use the Canadian horizontal CRS NAD83(CSRS) (`EPSG:4617`):
```
echo 55.735000 -100.370000 0.000000 | PROJ_NETWORK=ON ./cs2cs EPSG:4617+5773 EPSG:4617+5713 -d 12
```
In `PROJ 9.0.1`: `55.735000000000	-100.370000000000 0.002555035390`
In `PROJ 9.1.0`: `55.735000000000	-100.370000000000 -0.531729302978`
Different values for the vertical component but so far so good (after all https://github.com/OSGeo/PROJ-data/pull/84/files introduced a vertical grid shift in `PROJ 9.1.0`). What is confusing to me however is the output of `projinfo` for this transformation:
```
./projinfo -s EPSG:4617+5773 -t EPSG:4617+5713 --spatial-test intersects -o proj
```
In `PROJ 9.0.1`: Finds 2 operations out of with the first one seems to be used for the transformation above
In `PROJ 9.1.0`: Find only one ballpark transformation:
```
Candidate operations found: 1
-------------------------------------
Operation No. 1:

unknown id, Transformation from EGM96 height to CGVD28 height (ballpark vertical transformation), unknown accuracy, unknown domain of validity, has ballpark transformation

PROJ string:
+proj=noop
```

Why is `projinfo` predicting a ballpark transformation while `cs2cs` is actually doing something else?

Side note: When replacing `EPSG:4617` with `EPSG:8255` (i.e. NAD83(CSRS)v7) `PROJ 9.1.0` is able to find a non-ballpark transformation.

Sorry for this lengthy bug report and thanks in advance for any help on this topic.

#### Environment Information
 - PROJ version: 9.1.0 and 9.0.1
 - Operation System Information: Ubuntu 20.04
 - Built from source using the respective git tags

**Comment by rouault** [comment]
Fix in https://github.com/OSGeo/PROJ/pull/3333

The reason for the regression is that EPSG has deprecated the EPSG:9123 "NAD83(CSRS) to CGVD28 height (1)" grid transformation. The remaining transformations use other variants of NAD83(CSRS) whose transformations to EPSG:4326 have likely not as wide area of use
