### ISSUE TITLE
proj_create_crs_to_crs_from_pj with option FORCE_OVER not working for ESRI:53029 (Sphere_Van_der_Grinten_I) 

### ISSUE THREAD

**Issue by alphaandromeda** [OSGeo/proj.4#3348]
#### Example of problem
proj_create_crs_to_crs_from_pj with option FORCE_OVER does not work for transformer (ESRI:53029 (PCS) to its GCS).

#### Problem description

GCS to PCS: 220°, 45° -> 15401302,8601272, 6233355,09308686 
PCS to GCS:  15401302,8601272, 6233355,09308686 -> 147°, 45° (wrapped - not forced-over!)

#### Expected Output

PCS to GCS:  15401302,8601272, 6233355,09308686 -> 220°, 45° 

#### Environment Information
 - PROJ version 9.1.
 - Windows 11 64bit
#### Installation method
- Direct C-api-call (proj.h and proj_9_1.dll)

**Comment by rouault** [comment]
Due to its own nature, Van der Grinten projection doesn't have a wrap around mode at antimeridians like Mercator. There are only a few projections that work in +over mode (Mercator, Equidistant Cylindrical)
I've adressed this by a doc improvement in https://github.com/OSGeo/PROJ/pull/3351
