### ISSUE TITLE
Attempting to transform coordinates with an invalid forward transformation produces misleading error message

### ISSUE THREAD

**Issue by DalePAtSafe** [OSGeo/proj.4#3358]
When attempting a coordinate transformation with a custom transformation definition that does not correctly define a transformation PROJ tools will produce the error message "No inverse operation" even when a forward transformation is being attempted. While this error message is technically correct it doesn't really convey the true nature of the problem. This led us down completely the wrong path when trying to debug a non-functioning transformation sent to us by a customer.

Example:
```
$ NOT_A_TRANSFORMATION="GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984 (G2139)",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]"

$ echo 50.014 -121.83 | cct -z0 -t0 $NOT_A_TRANSFORMATION
# Record 0 TRANSFORMATION ERROR: 50.014 -121.83
 (No inverse operation)
```

A message that more accurately describes the problem such as "Invalid operation" or "Object definition is not a transformation" would be more helpful feedback from PROJ. 

#### Environment Information
 - PROJ 9.1.0
 - Ubuntu 22.04

#### Installation method
 - built from source

**Comment by DalePAtSafe** [comment]
I think I could have been a bit more clear in my description. I see that you've added an extra check to `cct` for this case, but this problem is more general than that. Just using the PROJ API can produce this.

```c++
const char* WKT = R"wkt(GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984 (G2139)",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]
)wkt"

PJ* P = proj_create(nullptr, WKT);
PJ_COORD coord = proj_coord(50.014, -121.83, 0.0, 0.0)

coord = proj_trans(P, PJ_FWD, coord);

int ec = proj_errno(P);

std::cout << proj_errno_string(ec) << std::endl; // Prints "No inverse operation"
```

Apologies for not being more clear, I was just using `cct` as a simple repro.

**Comment by rouault** [comment]
> but this problem is more general than that. Just using the PROJ API can produce this.

good point. I've added an extra commit to the PR.
