### ISSUE TITLE
Default GRS80 ellipsoid ignored by `PROJStringParser`

### ISSUE THREAD

**Issue by ethantkoenig** [OSGeo/proj.4#3404]
I've noticed behavior in the [`PROJStringParser::createFromPROJString`](https://github.com/OSGeo/PROJ/blob/8af84f9d770fd8e64991c1968acfa5ca83204f33/src/iso19111/io.cpp#L11154) method that I think is a bug, though I'm not 100% sure.

The method [parses the `projString` argument and stores the parsed parameters in `d->steps_`](https://github.com/OSGeo/PROJ/blob/8af84f9d770fd8e64991c1968acfa5ca83204f33/src/iso19111/io.cpp#L11168-L11169).

`createFromPROJString` later [calls `pj_create_internal`](https://github.com/OSGeo/PROJ/blob/8af84f9d770fd8e64991c1968acfa5ca83204f33/src/iso19111/io.cpp#L11480-L11484), which may result in the addition of parameters not present in `projString`. For example, [`append_default_ellipsoid_to_paralist` adds an `ellps=GRS80` parameter](https://github.com/OSGeo/PROJ/blob/8af84f9d770fd8e64991c1968acfa5ca83204f33/src/init.cpp#L352) (called via `pj_create_internal` -> `pj_create_argv_internal` -> `pj_init_ctx_with_allow_init_epsg`). However, `d->steps_` is never updated to reflect these newly-added parameters. (There is [code that modifies `d->steps_`](https://github.com/OSGeo/PROJ/blob/8af84f9d770fd8e64991c1968acfa5ca83204f33/src/iso19111/io.cpp#L11488-L11536) after the `pj_create_internal` call, but it only removes parameters that are not present in `pj`.)

#### Example

```cc
#include <iostream>

#include "proj.h"

int main(int argc, char* argv[]) {
  auto* ctx = proj_context_create();
  auto* pj = proj_create(ctx, "+proj=utm +zone=55 +type=crs");
  std::cout << proj_as_proj_string(ctx, pj, PJ_PROJ_4, nullptr) << "\n";
  return 0;
}
```

The above code prints `+proj=utm +zone=55 +datum=WGS84 +units=m +no_defs +type=crs`. I think(?) the `+datum=WGS84` part is unexpected, because IIUC the default ellipsoid is GRS80 (as of 1230114). I believe the `+datum=WGS84` in the output comes from [this line](https://github.com/OSGeo/PROJ/blob/8af84f9d770fd8e64991c1968acfa5ca83204f33/src/iso19111/io.cpp#L10188) (note that the `PROJStringParser::Private::buildDatum` method would have returned earlier if `step` included the `ellps=GRS80` param added in `append_default_ellipsoid_to_paralist`)

#### Environment Information

I'm using a Debian-based Linux distribution, and installed PROJ via the `libproj-dev` Debian package (version 9.1.0-1).

**Comment by rouault** [comment]
I recognize there is an inconsistency here, but I'm not sure we want to change that at that point. In any case, specifying a CRS without an explicit datum is a bad idea. Just adding +ellps=GRS80 would prevent any datum transformation. So +datum=WGS84 is a reasonable default for a CRS.  I'm not sure which GRS80 based *datum* could be selected instead. +ellps=GRS80 was selected as a default more for transformations/pipelines.
@kbevers  any opinion ?

**Comment by kbevers** [comment]
I believe the purpose of `proj_as_proj_string()` is to emulate proj-strings as they used to be in the olden PROJ.4 days. The change of default ellipsoid was done for PROJ 6. So I don't think it is wrong to add the `+datum=WGS84` when trying to create and old style proj-string from a new style transformation pipeline (although a very simple one).

I'm not in favour of making changes here. I also acknowledge that it might seem weird but that's the price of using legacy functionality. Luckily the WGS84 and GRS80 ellipsoids are *very* similar so I doubt this will cause any problems in real world usage.

**Comment by ethantkoenig** [comment]
Thanks for the quick responses!

Okay, sounds like this behavior is a mix of "intended" and "not worth changing". Feel free to close the issue.

**Comment by schwehr** [comment]
Thank you @rouault and @kbevers for your quick responses with really helpful comments.  We are exciting to be getting out of the land of legacy.
