### ISSUE TITLE
Issues using PROJ with SAD69 brazilian CRS.

### ISSUE THREAD

**Issue by henriquesobral** [OSGeo/proj.4#3410]
Hi, 

I'm facing some issues using PROJ with SAD69 brazilian CRS. 

SAD69 has one update in 1996 and EPSG Authority defines codes for both versions, ex: "SAD69 / UTM zone 22S" (EPSG:29192) and "SAD69(96) / UTM zone 22S" (EPSG:5858).
Many clients with old projects still use the old versions of SAD69 (29192), but when I use PROJ or GDAL via EPSG code instead of WKT, dosent matter which epsg code I use, PROJ always offers the newer SAD69(96) transformation.

I asked for PROJ to show transformation from 29192 to 3857, and it shows me 3 options:  the first option is SAD69(96), even though specifing the SAD69 EPSG code (29192)

#### Environment Information
 - PROJ version 9.1.0
 - Docker osgeo/gdal:alpine-normal-latest, under MacOS 12.6

```c
/ # projinfo -s EPSG:29192 -t EPSG:3857 -o PROJ
Candidate operations found: 3
Note: using '--spatial-test intersects' would bring more results (6)
-------------------------------------
Operation No. 1:

unknown id, Inverse of UTM zone 22S + SAD69 to WGS 84 (16) + Popular Visualisation Pseudo-Mercator, 5 m, Brazil - onshore and offshore. Includes Rocas, Fernando de Noronha archipelago, Trindade, Ihlas Martim Vaz and Sao Pedro e Sao Paulo.

PROJ string:
+proj=pipeline
+step +inv +proj=utm +zone=22 +south +ellps=aust_SA
+step +proj=push +v_3
+step +proj=cart +ellps=aust_SA
+step +proj=helmert +x=-67.35 +y=3.88 +z=-38.22
+step +inv +proj=cart +ellps=WGS84
+step +proj=pop +v_3
+step +proj=webmerc +lat_0=0 +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84

-------------------------------------
Operation No. 2:

unknown id, Inverse of UTM zone 22S + SAD69 to WGS 84 (14) + Popular Visualisation Pseudo-Mercator, 5 m, Brazil - onshore and offshore. Includes Rocas, Fernando de Noronha archipelago, Trindade, Ihlas Martim Vaz and Sao Pedro e Sao Paulo.

PROJ string:
+proj=pipeline
+step +inv +proj=utm +zone=22 +south +ellps=aust_SA
+step +proj=push +v_3
+step +proj=cart +ellps=aust_SA
+step +proj=helmert +x=-66.87 +y=4.37 +z=-38.52
+step +inv +proj=cart +ellps=WGS84
+step +proj=pop +v_3
+step +proj=webmerc +lat_0=0 +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84

-------------------------------------
Operation No. 3:

unknown id, Inverse of UTM zone 22S + SAD69 to WGS 84 (1) + Popular Visualisation Pseudo-Mercator, 19 m, South America - onshore north of 45°S excluding Amazonia.

PROJ string:
+proj=pipeline
+step +inv +proj=utm +zone=22 +south +ellps=aust_SA
+step +proj=push +v_3
+step +proj=cart +ellps=aust_SA
+step +proj=helmert +x=-57 +y=1 +z=-41
+step +inv +proj=cart +ellps=WGS84
+step +proj=pop +v_3
+step +proj=webmerc +lat_0=0 +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84
```

It needs enforce the transformation to the SAD69 (operation 2).

Thanks

**Comment by rouault** [comment]
PROJ just uses what is in the EPSG dataset. Both https://epsg.org/transformation_5882/SAD69-to-WGS-84-16.html and https://epsg.org/transformation_1877/SAD69-to-WGS-84-14.html transformations are documented as valid for SAD69 to WGS84, and with the same accuracy. Having no other clues, PROJ selects the one that has the highest number in parenthesis, as a hint it might be more recent. You may try to issue a change request to https://epsg.org/dataset-change-requests.html , but I suspect they won't see any need for change.
You may potentially tune the proj.db to change the priority to meet your needs, for example by slightly decreasing the (in)accuracy value with
```
sqlite3 /path/to/proj.db "update helmert_transformation_table set accuracy = 4.99 where name = 'SAD69 to WGS 84 (14)'"
```

**Comment by henriquesobral** [comment]
@rouault Thank you. This workaround solved my problem.
