### ISSUE TITLE
Replace remaining 4 calls to `sprintf` with `snprintf`

### ISSUE THREAD

**Issue by seanm** [OSGeo/proj.4#3423]
After https://github.com/OSGeo/PROJ/pull/3421 there are still 4 uses of `sprintf` that should be replaced with `snprintf`.

**Comment by kbevers** [comment]
Could you point out where they are and why they are complicated to get rid of?

**Comment by seanm** [comment]
All 4 are in `rtodms`. The complication is:

1. `rtodms` takes a buffer (`s`), but not its size. The function signature should probably change to take the size of the `s` buffer too.
2. `s` gets aliased to `ss`
3. there is pointer arithmetic on `ss`
4. `ss` is what's passed to `sprintf`
