### ISSUE TITLE
BOUNDCRS with a derived geographic as SOURCECRS doesn't work as expected

### ISSUE THREAD

**Issue by hernando** [OSGeo/proj.4#3428]
#### Example of problem

I'm trying to express vertical offsets over different types of CRSs as well defined WKT2 strings. This time is the turn of a bound CRS. It seems that a derived of a bound is not accepted by the WKT2 grammar (to be confirmed independently), so I tried to turn the definition around and write a bound of a base derived and conventional target.

```
TGT='
BOUNDCRS[
    SOURCECRS[
        GEOGCRS["CH1903+ with height offset",
            BASEGEOGCRS[
                "CH1903+",
                DATUM["CH1903+",
                    ELLIPSOID["Bessel 1841",6377397.155,299.1528128,
                        LENGTHUNIT["metre",1]]],
                PRIMEM["Greenwich",0,
                    ANGLEUNIT["degree",0.0174532925199433]]],
            DERIVINGCONVERSION["Ellipsoidal to gravity related height",
                METHOD["Geographic3D offsets",
                    ID["EPSG",9660]],
                PARAMETER["Latitude offset",0,
                    ANGLEUNIT["degree",0.0174532925199433],
                    ID["EPSG",8601]],
                PARAMETER["Longitude offset",0,
                    ANGLEUNIT["degree",0.0174532925199433],
                    ID["EPSG",8602]],
                PARAMETER["Vertical Offset",10,
                    LENGTHUNIT["metre",1],
                    ID["EPSG",8603]]],
            CS[ellipsoidal,3],
                AXIS["geodetic latitude (Lat)",north,
                    ORDER[1],
                    ANGLEUNIT["degree",0.0174532925199433,
                        ID["EPSG",9122]]],
                AXIS["geodetic longitude (Lon)",east,
                    ORDER[2],
                    ANGLEUNIT["degree",0.0174532925199433,
                        ID["EPSG",9122]]],
                AXIS["ellipsoidal height (h)",up,
                    ORDER[3],
                    LENGTHUNIT["metre",1]]]],
   TARGETCRS[
       GEOGCRS["WGS 84",
           ENSEMBLE["World Geodetic System 1984 ensemble",
               MEMBER["World Geodetic System 1984 (Transit)"],
               MEMBER["World Geodetic System 1984 (G730)"],
               MEMBER["World Geodetic System 1984 (G873)"],
               MEMBER["World Geodetic System 1984 (G1150)"],
               MEMBER["World Geodetic System 1984 (G1674)"],
               MEMBER["World Geodetic System 1984 (G1762)"],
               MEMBER["World Geodetic System 1984 (G2139)"],
               ELLIPSOID["WGS 84",6378137,298.257223563,
                   LENGTHUNIT["metre",1]],
               ENSEMBLEACCURACY[2.0]],
           PRIMEM["Greenwich",0,
               ANGLEUNIT["degree",0.0174532925199433]],
           CS[ellipsoidal,3],
               AXIS["geodetic latitude (Lat)",north,
                   ORDER[1],
                   ANGLEUNIT["degree",0.0174532925199433]],
               AXIS["geodetic longitude (Lon)",east,
                   ORDER[2],
                   ANGLEUNIT["degree",0.0174532925199433]],
               AXIS["ellipsoidal height (h)",up,
                   ORDER[3],
                   LENGTHUNIT["metre",1]],
           USAGE[
               SCOPE["Geodesy. Navigation and positioning using GPS satellite system."],
               AREA[""],
               BBOX[-90,-180,90,180]],
           ID["EPSG",4979]]],
   ABRIDGEDTRANSFORMATION["CH1903+ to WGS 84 (1)",
       VERSION["BfL-CH"],
       METHOD["Geocentric translations (geog2D domain)",
           ID["EPSG",9603]],
       PARAMETER["X-axis translation",674.374,
           ID["EPSG",8605]],
       PARAMETER["Y-axis translation",15.056,
           ID["EPSG",8606]],
       PARAMETER["Z-axis translation",405.346,
           ID["EPSG",8607]],
       USAGE[
           SCOPE[""],
           AREA["Liechtenstein; Switzerland."],
           BBOX[45.82,5.96,47.81,10.49]],
       ID["EPSG",1676],
       REMARK[""]]]
'
```
#### Problem description

This WKT2 string is accepted by projinfo, which just repeats it without changes when given as input. However, `cs2cs` doesn't like it:
```
$ echo 46.9524055555556 7.43958333333333 400 | cs2cs EPSG:4326 "$TGT" --3d -d 12
*	* inf
```

#### Expected Output

The output I was expecting was:
```
46.953728416653	7.440534363306 350.382078166120
```
But maybe this is not even well defined and it's not expected to work anyway.

#### Environment Information
 - PROJ master at commit dd1ce7d589b6424db9335b3673bb24a7ff513995
 - Ubuntu 20.04

#### Installation method
 - Compiled from source

**Comment by rouault** [comment]
what is a bit confusing in this WKT is to which CRS the ``ABRIDGEDTRANSFORMATION["CH1903+ to WGS 84 (1)",`` is supposed to be applied to ? Is it to CH1903+ or to "CH1903+ with height offset" ?
There is likely a bug in PROJ, but if it was fixed, it should likely apply the transformation to  "CH1903+ with height offset" which is the soureCRS.

**Comment by hernando** [comment]
> what is a bit confusing in this WKT is to which CRS the `ABRIDGEDTRANSFORMATION["CH1903+ to WGS 84 (1)",` is supposed to be applied to ?

Yes, I'm not sure about that either, that's why I've also asked about it in coordtran.wg.
The abridged transformation is defined from the source datum to the target datum, but the source datum is derived, which in my opinion has technical implications regarding the conversion to geocentric coordinates.
In this particular instance, it doesn't look technically sound to apply the geographic to geocentric conversion without undoing the vertical shift first, because otherwise you would be displacing the ellipsoid in relation to what your GEOGCRS is truly defining, don't you think?
Without doing a case by case analysis, it seems technically simpler to resolve the ambiguity agreeing that derivation must be undone before applying the abridged transformation. Furthermore, I would say that ignoring the derivation makes this construction useless and it shouldn't be allowed to avoid confusion.

**Comment by rouault** [comment]
related discussion thread on coordtan.wg mailing list: http://lists.ogc.org/pipermail/coordtran.wg/2022-November/thread.html#2715

**Comment by hernando** [comment]
@rouault, what's you view on the the last reply I wrote here? The same comment has been posted in coordtran, but the discussion is not making any progress there.

**Comment by rouault** [comment]
We are likely stretching BoundCRS beyond what it was intended for. There could be use cases where the AbridgedTransformation applies to the DerivedGeographicCRS itself, and others where on its baseCRS (what you want), but it is not obvious how PROJ could guess automatically which hypothesis applies. Here the only hint would be the name of the AbridgedTransformation "CH1903+ to WGS 84 (1)" and the EPSG:1676 that has CH1903+ as source CRS, that would lend to think that one should apply this transformation to the baseCRS (so when doing "CH1903+ with height offset" to EPSG:4979, you would undo the "Ellipsoidal to gravity related height" derived conversion and then the "CH1903+ to WGS 84 (1)" transformation). But who knows if some users wouldn't want to extend the transformation to the DerivedGeographicCRS itself (unlikely though), taking literaly "In a bound CRS the abridged coordinate transformation is applied to the source CRS with the target CRS being the common or hub system.". What you want here would be an extension of the mention "If the source CRS type is projected and the abridged coordinate transformation operates in the geodetic CRS domain, the transformation is deemed to operate on the projected CRS's base CRS but the projected CRS shall be described." where you would replace "projected" by "derived geographic".
@kbevers any opinion ?

**Comment by kbevers** [comment]
> @kbevers any opinion ?

Not really. Looks like limitations within WKT standard to me. I don't have a good solution on hand.

**Comment by hernando** [comment]
I thought that abridged transformations were only allowed to be of very limited types and always operate in the geodetic CRS domain. But rereading the standard I found that valid transformations are explained in clause 17 and they exclude map projections and deriving conversions, but include the vertical offset and slope, which is more ambiguous.

> What you want here would be an extension of the mention "If the source CRS type is projected and the abridged coordinate transformation operates in the geodetic CRS domain, the transformation is deemed to operate on the projected CRS's base CRS but the projected CRS shall be described." where you would replace "projected" by "derived geographic".

Yes, that's it. And following the same reasoning applied to the projected case, it seems totally logical to me. But without having a clear specification in the standard it feel risky to extrapolate to deriving geographic (and projected for that matter).

Independently, I found this text in the specification:
```
Subclause 20.2, derived engineering CRS (ISO 19162:2015, 18.2.2)

The constraint on coordinate operation methods that are permitted in an abridged transformation has been removed.
```
Maybe this is all I need after all!
I'll test that and if it's satisfactory I will close this issue.

In any case, maybe PROJ should throw or at least warn when trying to do a transformation with a BOUNDCRS such as a above.

**Comment by hernando** [comment]
I totally misunderstood the purpose of the derived engineering CRS. It is meant to derive an engineering CRS based on another engineering CRS, so It doesn't help me at all.

**Comment by rouault** [comment]
Proposition: if the value of the REMARK[] node of the ABRIDGEDTRANSFORMATION[] is "SOURCECRS=CH1903+", then PROJ would consider that CH1903+ is the source CRS of the AbridgedTransformation. The name after SOURCECRS= must be either the top name of the BoundCRS SOURCECRS[] or its base CRS.
Obviously this is a hack and no interoperability is to be expected with other coordinate transformation software.

**Comment by hernando** [comment]
Thanks for showing interest in resolving this issue.
To me, even an API only solution is also fine. I was using WKT strings for illustrative purposes in the issue, but in the end I want to use this creating a CRS using the C++ API and eventually extract a PROJ pipeline.
An API solution seems cleaner, but then I don't know what should be the default behavior when receiving a WKT string.

**Comment by rouault** [comment]
The API solution already exists. When you call BoundCRS::create() make sure that the passed transformation uses CH1903+ as the source CRS. But I don't know if the pipeline computation logic correctly deals with that with a DerivedGeographicCRS.

**Comment by hernando** [comment]
If I understood correctly, that should work, thanks!
I'll be off until Tuesday, I will let you know once I'm back and I test it.

**Comment by rouault** [comment]
> But I don't know if the pipeline computation logic correctly deals with that with a DerivedGeographicCRS.

I've verified this actually works.
In https://github.com/OSGeo/PROJ/pull/3454, I propose to extend PROJJSON to add an option source_crs in the transformation of a bound_crs

**Comment by hernando** [comment]
I can confirm this works for `DerivedGeographicCRS`, but I'm having issues with `DerivedProjectedCRS` even without a bound CRS. It looks like an independent issue, I will investigate a bit more and submit a separate issue if necessary.

**Comment by hernando** [comment]
False alarm. I thought I could use a vertical offset conversion for a `DerivedProjectedCRS`, but it seems the only way to apply a vertical offset on a projected CRS is to use a PROJ-based operation method with an affine transformation.

**Comment by hernando** [comment]
While testing I've noticed that the `IJSONExportable` and the `IWKTExportable` classes implementations don't behave consistently with regard to bound CRSs. The WKT export can take a `BoundCRS` given as `baseCRSWithCanonicalBoundCRS` and it will output a BOUNDCRS, but the JSON export will output the base CRS. Arguably, either way could be considered correct, but they shouldn't be different.

**Comment by rouault** [comment]
> The WKT export can take a `BoundCRS` given as `baseCRSWithCanonicalBoundCRS` and it will output a BOUNDCRS, but the JSON export will output the base CRS

I don't understand what you are refering to. Can you point at the relevant code, or perhaps better, submit a pull request aligning behavior of json export with wkt export ?

**Comment by hernando** [comment]
I'll try to write a PR.

From my side you can close this issue.

It's still not clear how PROJ should handle such a WKT string, but the solution you proposed together with the addition to PROJJSON work for me (in fact, the addition to PROJJSON is crucial, otherwise I don't know how to create the `PJ*` objects to pass to `proj_create_crs_to_crs_from_pj`).

**Comment by rouault** [comment]
> otherwise I don't know how to create the `PJ*` objects

look at proj_experimental.h (not actually that "experimental" given that it has shipped for a long time now, to be understood more as "advanced") that has function like proj_crs_create_bound_crs(), proj_create_transformation() etc.

**Comment by hernando** [comment]
> > The WKT export can take a `BoundCRS` given as `baseCRSWithCanonicalBoundCRS` and it will output a BOUNDCRS, but the JSON export will output the base CRS
> 
> I don't understand what you are refering to. Can you point at the relevant code, or perhaps better, submit a pull request aligning behavior of json export with wkt export ?

I started changing PROJ's unit tests to verify the difference but I didn't find any. Coming back to my code I found out that for WKT I was exporting the result of calling `baseCRSWithCanonicalBoundCRS`. This was concealed behind a function call so I didn't realize until I dug a bit more.

In short, nothing to fix in PROJ.
