### ISSUE TITLE
Cassini-Soldner easting difference

### ISSUE THREAD

**Issue by eriksorngard** [OSGeo/proj.4#3432]
Hello,

While stress testing our forward Cassini-Soldner projection, implemented from EPSG documentation and not dependend on PROJ, I notice an increasing difference between PROJ's easting output and ours, with increasing longitudal distance.

The only other software I know that allows me to configure an arbitrary Cassini-Soldner independently of PROJ and project arbitrary coordinates is SurvCE, which yields the same results as our software.

I can recreate PROJ's results by adapting line 45 and 46 in cass.cpp to build with our source code:

```c
    xy.x = nu * A * (1. - A2 * T *
        (C1 - (8. - T + 8. * C) * A2 * C2));
```

Optimizing EPSG's expression for calculating E (which appears to be the same as Snyder's 13-7) to match PROJ's implementation, i notice a different sign after C1:

```c
    xy.x = nu * A * (1. - A2 * T *
        (C1 + (8. - T + 8. * C) * A2 * C2));

```

#### Test results

`cs2cs -I -f "%.5f" +proj=cass +lat_0=57 +lon_0=18 +x_0=0 +y_0=0 +ellps=GRS80`

|              	|               	|      PROJ     	|     PROJ     	|     "EPSG"    	|    "EPSG"    	| Difference  	| Difference   	|
|:------------:	|:-------------:	|:-------------:	|:------------:	|:-------------:	|:------------:	|-------------	|--------------	|
| **Latitude** 	| **Longitude** 	|  **Easting**  	| **Northing** 	|  **Easting**  	| **Northing** 	| **Easting** 	| **Northing** 	|
|      57      	|       18      	|             0 	|            0 	|             0 	|            0 	|           0 	|            0 	|
|      57      	|       15      	| -182257.97503 	|   4003.72144 	| -182257.94813 	|   4003.72144 	|     0.02690 	|            0 	|
|      60      	|       18      	|             0 	| 334158.93324 	|             0 	| 334158.93334 	|           0 	|      0.00010 	|

Should the sign in cass.cpp be flipped?

Best regards,
Erik

#### Environment Information
 - PROJ version (`9.1.0`)
 - Ubuntu 22.04, running under Windows 11

#### Installation method
 - Built from source

**Comment by rouault** [comment]
totally agree with your diagnostic (good spotting!). Fix in https://github.com/OSGeo/PROJ/pull/3433
