### ISSUE TITLE
Overprinting in proj.pdf

### ISSUE THREAD

**Issue by jidanni** [OSGeo/proj.4#3436]
![20221106T081626](https://user-images.githubusercontent.com/1230959/200175995-9d4d4065-45b8-4441-a7b9-10026253afd4.jpg)
Overprinting and truncation. Seen in Chrome browser on Linux.

**Comment by mwtoews** [comment]
This is a known issue from [breathe](https://github.com/breathe-doc/breathe). There are a few possible ideas, but I've started a discussion at https://github.com/breathe-doc/breathe/discussions/867 to explore them. The easiest would be to try setting `printindex` to different defaults (e.g. removing it, 1-column layout, different font, etc.)
