### ISSUE TITLE
proj_coordoperation_get_grid_used doesn't return any info for certain grids even if the grid is found.

### ISSUE THREAD

**Issue by DalePAtSafe** [OSGeo/proj.4#3444]
When using `proj_coordoperation_get_grid_used` to find what grids were used in a transformation certain grids will not have any information returned in either the `out_full_name` or `out_url` parameters even though the grid was found and used. So far we have only observed this with `is_lmi_ISN_vel_beta.tif`, but there may be others. Possibly this is also related to the use of the `deformation` operation?

```c
// is_lmi_ISN_vel_beta.tif doesn't get it's information returned from proj_coordoperation_get_grid_used
const char* proj_string = "proj=deformation t_epoch=2011 grids=is_lmi_ISN_vel_beta.tif inv";

PJ* P = proj_create(nullptr, proj_string);
PJ_COORD coord = proj_coord(2586896.87472207, -1042138.18358239, 5716838.59438683, 2020.0);

proj_trans(P, coord); // Succeeds

const char* shortName   = nullptr;
const char* fullName    = nullptr;
const char* packageName = nullptr;
const char* url         = nullptr;
int directDownload = 0;
int openLicense    = 0;
int available      = 0;

proj_coordoperation_get_grid_used(nullptr, P, 0, &shortName, &fullName,
                                  &packageName, &url, &directDownload, &openLicense, &available);

std::cout << shortName << std::endl; // Prints "is_lmi_ISN_vel_beta.tif"

// One of these two should be non-empty after a successful transformation

std::cout << fullName << std::endl; // Prints ""
std::cout << url << std::endl; // Prints ""
```

The expected output here would be either the location on disk in `fullName` or the CDN URL in `url` depending on where the grid was found.

#### Environment Information
 - PROJ 9.1.0
 - Ubuntu 22.04

#### Installation method
 - Built from source

**Comment by rouault** [comment]
This affected the grids that are available in PROJ-data but don't have a corresponding transformation record in proj.db. Fix in https://github.com/OSGeo/PROJ/pull/3446

**Comment by DalePAtSafe** [comment]
So while I was doing additional investigation into this I discovered that it wasn't actually the first call to `proj_coordoperation_get_grid_used` that would fail to return information, but subsequent calls with transformations using the same grid would then return nothing for the full name or URL.

For example:

Pre-condition: `is_lmi_ISN_vel_beta.tif` is available on disk in location PROJ can find.

```c
const char* proj_string_inv = "proj=deformation t_epoch=2011 grids=is_lmi_ISN_vel_beta.tif inv";

PJ* P_inv = proj_create(nullptr, proj_string_inv);
PJ_COORD coord = proj_coord(2586896.87472207, -1042138.18358239, 5716838.59438683, 2020.0);

proj_trans(P_inv, coord); // Succeeds

const char* shortName   = nullptr;
const char* fullName    = nullptr;
const char* packageName = nullptr;
const char* url         = nullptr;
int directDownload = 0;
int openLicense    = 0;
int available      = 0;

proj_coordoperation_get_grid_used(nullptr, P_inv, 0, &shortName, &fullName,
                                  &packageName, &url, &directDownload, &openLicense, &available);

std::cout << shortName << std::endl; // Prints "is_lmi_ISN_vel_beta.tif"

// The first time around the location of the grid on disk is found

std::cout << fullName << std::endl; // Prints path to `is_lmi_ISN_vel_beta.tif` location on disk
std::cout << url << std::endl; // Prints ""

const char* proj_string_fwd = "proj=deformation t_epoch=2011 grids=is_lmi_ISN_vel_beta.tif";

PJ* P_fwd = proj_create(nullptr, proj_string_fwd);
PJ_COORD coord2 = proj_coord(2586896.87472207, -1042138.18358239, 5716838.59438683, 2020.0);

proj_trans(P_fwd, coord2); // Succeeds

proj_coordoperation_get_grid_used(nullptr, P_fwd, 0, &shortName, &fullName,
                                  &packageName, &url, &directDownload, &openLicense, &available);

std::cout << shortName << std::endl; // Prints "is_lmi_ISN_vel_beta.tif"

// The second time around the fullName is empty

std::cout << fullName << std::endl; // Prints ""
std::cout << url << std::endl; // Prints ""
```

Now this particular case is fixed by adding the grid to the PROJ database, but what about the case of a completely custom grid? It would be ideal for the location on disk to be reported consistently in that case. Or even if someone is running their own CDN that serves custom grids, the correct URL should be reported in that case too correct? Or is that not supposed to be a supported use case?

**Comment by rouault** [comment]
> Now this particular case is fixed by adding the grid to the PROJ database, but what about the case of a completely custom grid? It would be ideal for the location on disk to be reported consistently in that case. Or even if someone is running their own CDN that serves custom grids, the correct URL should be reported in that case too correct? Or is that not supposed to be a supported use case?

both issues should be fixed with https://github.com/OSGeo/PROJ/pull/3448
