### ISSUE TITLE
Non-symmetric omerc parameters

### ISSUE THREAD

**Issue by jidanni** [OSGeo/proj.4#3464]
Question: For proj=+omerc, is
```
+lonc =<value> Longitude of projection center.

+lat_0=<value> Latitude  of the central point.
+lon_0=<value> Longitude of the central point.
```
correct? Or,
```
+lonc =<value> Longitude of the central point.

+lat_0=<value> Latitude  of the central point.
+lon_0=<value> Longitude of projection center.
```

The documentation has the latter, which seems like a typo.

**Comment by snowman2** [comment]
Thought this may be a helpful reference point:
```python
>>> from pyproj.crs.coordinate_operation import HotineObliqueMercatorBConversion
>>> cc
<Coordinate Operation: Conversion>
Name: unknown
Method: Hotine Oblique Mercator (variant B)
Area of Use:
- undefined
>>> print(cc.to_wkt(pretty=True))
CONVERSION["unknown",
    METHOD["Hotine Oblique Mercator (variant B)",
        ID["EPSG",9815]],
    PARAMETER["Latitude of projection centre",1,
        ANGLEUNIT["degree",0.0174532925199433],
        ID["EPSG",8811]],
    PARAMETER["Longitude of projection centre",2,
        ANGLEUNIT["degree",0.0174532925199433],
        ID["EPSG",8812]],
    PARAMETER["Azimuth of initial line",3,
        ANGLEUNIT["degree",0.0174532925199433],
        ID["EPSG",8813]],
    PARAMETER["Angle from Rectified to Skew Grid",4,
        ANGLEUNIT["degree",0.0174532925199433],
        ID["EPSG",8814]],
    PARAMETER["Scale factor on initial line",1,
        SCALEUNIT["unity",1],
        ID["EPSG",8815]],
    PARAMETER["Easting at projection centre",0,
        LENGTHUNIT["metre",1],
        ID["EPSG",8816]],
    PARAMETER["Northing at projection centre",0,
        LENGTHUNIT["metre",1],
        ID["EPSG",8817]]]
>>> print(cc.to_proj4(pretty=True))
+proj=omerc +lat_0=1 +lonc=2 +alpha=3 +gamma=4 +k=1 +x_0=0 +y_0=0
```

**Comment by jidanni** [comment]
@snowman2 But
```
$ projinfo omerc|egrep PARAMETER\|ID.*EP.*,8
        PARAMETER["Latitude of natural origin",0,
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",0,
            ID["EPSG",8802]],
        PARAMETER["False easting",0,
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            ID["EPSG",8807]]],
```
Totally different.

**Comment by rouault** [comment]
> Totally different.

Look at the full output of "projinfo omerc". You just hit a bit too optimistic fuzzy string lookup of CRS names where "WGS 84 / Pseudo-Mercator" is an approximate match for your input "omerc".

**Comment by jidanni** [comment]
Thanks for updating, but  now +lon_0 is mentioned exactly one time on the page,

$ w3m -dump https://proj.org/operations/projections/omerc.html | grep lon_0
    override the +lon_0 parameter, so the latter should not be specified as it

So users wouldn't be using in the first place!?

**Comment by rouault** [comment]
> So users wouldn't be using in the first place!?

sorry I don't understand what you mean. I believe the message is quite clear: "don't set +lon_0 as the code is going to override it with a different value". If you can come up with a clearer formulation than mine, please issue a pull request

**Comment by jidanni** [comment]
All I know is currently the only mention of +lon_0 on https://proj.org/operations/projections/omerc.html is where you say not to use it.

So you might as well not mention it at all. That way users wouldn't even know about it.

And if they randomly use undocumented parameters, that would be their own fault.

Or, mention it is a **legacy parameter** that should not be used anymore.

**Comment by rouault** [comment]
lon_0 is a generic parameters that work for at least > 90% of other projection methods, so it is exceptional it should not be used, hence the mention not to use it.
It is not "legacy", as for this projection method, it should have never been used. The mention of it in the doc was most certainly just a copy&paste from another projection method, as I said lon_0 is used everywhere else
