### ISSUE TITLE
Table of Contents inaccessible from PDF sidebar

### ISSUE THREAD

**Issue by jidanni** [OSGeo/proj.4#3469]
Chrome:
![sidebarCR](https://user-images.githubusercontent.com/1230959/202433455-3b379c82-9f2a-47bf-ad24-5bd741b3275a.jpg)
Firefox:
![sidebarFF](https://user-images.githubusercontent.com/1230959/202433469-af746809-f50e-44b4-bea6-8f59fa1f54ae.jpg)

The Table of Contents is an important part of the manual, much richer than the sidebar itself, and should not be missing from the sidebar.

**Comment by kbevers** [comment]
I don't understand what this issue is about. The PDF has both a table of contents and bookmarks that can be navigated from your PDF-viewers interface. In Acrobat Reader that's the sidebar and most other apps will do it similarly.

**Comment by jidanni** [comment]
Rich hyperlinked listing like
```
7.1.2 Adams World in a Square I . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 99
7.1.2.1 Parameters . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 99
7.1.3 Adams World in a Square II . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 101
7.1.3.1 Parameters . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 101
7.1.4 Albers Equal Area . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 103
7.1.4.1 Options . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 103
7.1.5 Azimuthal Equidistant . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 105
7.1.5.1 Options . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 106
7.1.6 Airy . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 107
7.1.6.1 Options . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 108
7.1.7 Aitoff . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 109
7.1.7.1 Parameters . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 109
7.1.8 Modified Stereographic of Alaska . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 110
7.1.8.1 Options . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 111
7.1.9 Apian Globular I . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 111
7.1.9.1 Options . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 112
7.1.10 August Epicycloidal 
```
cannot be found anywhere on the website. Nor can it be found in when viewing on desktop Chrome PDF viewer or same with Firefox... if one thinks that the entire manual is accessible through the sidebar. 

The only way to ever see such a rich table of  contents is to start from the very beginning of the pdf, and then go down page by page. You'll hit it around page two or three. Maybe Acrobat shows the table of contents in its sidebar, but I didn't test that. I only tested those two web browsers.

Yes, it is possible to go through life without such a rich table of contents, but then it takes a lot of scrolling to find out all the items.

**Comment by kbevers** [comment]
Closing as this is a non-issue. The website presents the information differently that the PDF - we like it that way. If your PDF-viewer doesn't show a table of contents or provide you with a navigable set of bookmarks I suggest you find yourself a better PDF-viewer. The provided PDF includes everything you are asking for.

**Comment by mwtoews** [comment]
PDF contents should now look something like this:
![image](https://user-images.githubusercontent.com/895458/202583867-95c48f0c-e185-4454-ae26-fda282874644.png)
