### ISSUE TITLE
simple update to DOI syntax for IAU codes

### ISSUE THREAD

**Issue by thareUSGS** [OSGeo/proj.4#3498]
https://github.com/OSGeo/PROJ/blob/5e8ce5c1f829e8b483165c9d1fe506dc142e3bf8/scripts/build_db_from_iau.py#L28
per this related issue, https://github.com/pdssp/csvforwkt/issues/2#event-7971408430, can this line (linked above)
`SOURCE_IAU = "Source of IAU Coordinate systems: doi://10.1007/s10569-017-9805-5"`
 **be update to**:
`SOURCE_IAU = "Source of IAU Coordinate systems: https://doi.org/10.1007/s10569-017-9805-5"`

There is no rush on this minor syntax update. I assume once the update is applied, it will show-up during the next release.

I think this is the only change required for this but I wanted to make sure others agreed.

**Comment by rouault** [comment]
> I think this is the only change required for this but I wanted to make sure others agreed.

the data/sql/iau.sql file will also have to be regenerated (or just modified with find&replace to replicate the change). Will you do a pull request with that ?
