### ISSUE TITLE
Version update no longer supports the old version of pipeline(proj5.2 -> proj7.2.1)

### ISSUE THREAD

**Issue by threecat-up** [OSGeo/proj.4#3506]
Hi,
   I browsed the update functions of issue and proj versions and searched on Google, but I didn't find my answer, so I asked for help here.
  I want to convert the projection coordinate system. In Proj5.2, I defined EPSG as follows: `+proj=pipeline +step +proj=tmerc +lat_0=0 +lon_0=114 +k=1 +x_0=500000 +y_0=0 +a=6378137 +b=6356752.314 +units=m +no_defs +step +proj=helmert convention=coordinate_frame x=-740 y=-33 s=1.00 theta=34.8 `(This is the conversion of 4 parameters. I know there are 7 parameters now, but for many reasons, I still need to use 4 parameters.), but when I upgraded the proj version to 7.2.1, I found that this could not be used.
  This writing method cannot be used in versions higher than 5.2. I am puzzled. Under normal circumstances, upgrading should adapt to the old version.
  Thank you for your answer, and wish you a happy life!
other Information:
 - PROJ version (`proj=7.2.1`)
 - Operation System Information(centOS 7)

**Comment by rouault** [comment]
It depends with which API you use this , but you have inconsistent use of the '+' character (missing in the last part of your string)
The following works with all versions:
```
cct +proj=pipeline +step +proj=tmerc +lat_0=0 +lon_0=114 +k=1 +x_0=500000 +y_0=0 +a=6378137 +b=6356752.314 +units=m +no_defs +step +proj=helmert +convention=coordinate_frame +x=-740 +y=-33 +s=1.00 +theta=34.8
```

**Comment by threecat-up** [comment]
> It depends with which API you use this , but you have inconsistent use of the '+' character (missing in the last part of your string) The following works with all versions:
> 
> ```
> cct +proj=pipeline +step +proj=tmerc +lat_0=0 +lon_0=114 +k=1 +x_0=500000 +y_0=0 +a=6378137 +b=6356752.314 +units=m +no_defs +step +proj=helmert +convention=coordinate_frame +x=-740 +y=-33 +s=1.00 +theta=34.8
> ```

---
Thank you very much for your answer. I created ESPG as you said, but in postgis The transform() conversion does not take effect, and an error is reported as follows:
> ERROR: could not form projection (LWPROJ) from 'srid=38600' to 'srid=4326'(38600EPSG is defined according to the way you provide)


In the postgis version: POSTGIS="3.0.2 2fb2a18" [EXTENSION] PGSQL="120" GEOS="3.7.1-CAPI-1.11.1 27a5e771" PROJ="Rel. 5.2.0, September 15th, 2018" LIBXML="2.9.4" LIBJSON="0.12.1" LIBPROTOBUF="1.3.1" WAGYU="0.4.3 (Internal)" takes effect

In the postgis version: POSTGIS="3.3.2 4975da8" [EXTENSION] PGSQL="120" GEOS="3.9.0-CAPI-1.16.2" PROJ="7.2.1" LIBXML="2.9.10" LIBJSON="0.15" LIBPROTOBUF="1.3.3" WAGYU="0.5.0 (Internal)" TOPOLOGY
The above error occurred.

I think it may be the proj version(5.2 -> 7.2.1), maybe I was wrong.

Thank you again for your answer and wish you a happy life.

**Comment by threecat-up** [comment]
Thank you very much for your answer. I created ESPG as you said, but in postgis The transform() conversion does not take effect, and an error is reported as follows:
&gt;ERROR: could not form projection (LWPROJ) from 'srid=38600' to 'srid=4326'(38600EPSG is defined according to the way you provide)


In the postgis version: POSTGIS="3.0.2 2fb2a18" [EXTENSION] PGSQL="120" GEOS="3.7.1-CAPI-1.11.1 27a5e771" PROJ="Rel. 5.2.0, September 15th, 2018" LIBXML="2.9.4" LIBJSON="0.12.1" LIBPROTOBUF="1.3.1" WAGYU="0.4.3 (Internal)" takes effect


In the postgis version: POSTGIS="3.3.2 4975da8" [EXTENSION] PGSQL="120" GEOS="3.9.0-CAPI-1.16.2" PROJ="7.2.1" LIBXML="2.9.10" LIBJSON="0.15" LIBPROTOBUF="1.3.3" WAGYU="0.5.0 (Internal)" TOPOLOGY, the above error occurred.


I think it may be the proj version(5.2 -&gt; 7.2.1), maybe I was wrong.


Thank you again for your answer and wish you a happy life.
&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Even ***@***.***&gt;; 
发送时间: 2022年12月13日(星期二) 上午9:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [OSGeo/PROJ] Version update no longer supports the old version of pipeline(proj5.2 -&gt; proj7.2.1) (Issue #3506)





 
It depends with which API you use this , but you have inconsistent use of the '+' character (missing in the last part of your string)
 The following works with all versions:
 cct +proj=pipeline +step +proj=tmerc +lat_0=0 +lon_0=114 +k=1 +x_0=500000 +y_0=0 +a=6378137 +b=6356752.314 +units=m +no_defs +step +proj=helmert +convention=coordinate_frame +x=-740 +y=-33 +s=1.00 +theta=34.8
