### ISSUE TITLE
Error in PostGIS executing custom EPSG conversion (ST_Transform(), it depends on proj)

### ISSUE THREAD

**Issue by threecat-up** [OSGeo/proj.4#3507]
First of all, I'm very sorry to mention issue here. Sorry again for any interruption.
 I read all the answers and Google(I also tried to ask questions on stackoverflow. Unfortunately, no one has responded to me at present.), but I didn't find the answer, so I asked for help here.

  I have customized the EPSG srid=38599. Its proj4text is as follows:
```+proj=pipeline +step +proj=tmerc +lat_0=0 +lon_0=114 +k=1 +x_0=500000 +y_0=0 +a=6378137 +b=6356752.314 +units=m +no_defs +step +proj=helmert +convention=coordinate_frame +x=-74.45 +y=-339.8231 +s=1.0009 +theta=34.82```

Tried the following command but got error:

```SELECT ST_AsText(ST_Transform(ST_GeomFromText('POLYGON((743238 2967416,743238 2967450,743265 2967450,743265.625 2967416,743238 2967416))',38599),4326)) As wgs_geom```
> ERROR:  could not form projection (LWPROJ) from 'srid=38599' to 'srid=4326'

Runnning postgis_full_version(); 
gives the following output
```POSTGIS="3.3.2 4975da8" [EXTENSION] PGSQL="120" GEOS="3.9.0-CAPI-1.16.2" PROJ="7.2.1" LIBXML="2.9.10" LIBJSON="0.15" LIBPROTOBUF="1.3.3" WAGYU="0.5.0 (Internal)" TOPOLOGY```

Operation System Information(centOS 7)

---
But I am effective in other versions(execute st_ Transform() function), It prints the result as:
```POLYGON((116.463503985322 26.8118281074345,116.463510038861 26.812134398896,116.463781114813 26.8121300851691,116.463781335435 26.8118236939094,116.463503985322 26.8118281074345))```

Runnning postgis_full_version(); 
gives the following output
```POSTGIS="3.0.2 2fb2a18" [EXTENSION] PGSQL="120" GEOS="3.7.1-CAPI-1.11.1 27a5e771" PROJ="Rel. 5.2.0, September 15th, 2018" LIBXML="2.9.4" LIBJSON="0.12.1" LIBPROTOBUF="1.3.1" WAGYU="0.4.3 (Internal)"```

I am very confused and hope to get answers. 
Thank you very much and I really appreciate your help..

**Comment by rouault** [comment]
you'll likely have to update to PostGIS 3.4 and use https://postgis.net/docs/manual-3.4/ST_TransformPipeline.html
PROJ 5.2 accidentally supported "+proj=pipeline" strings as CRS, but this was more an accident than a design decision. PROJ >= 6 restricts CRS strings to be "simple" PROJ.4 CRS strings or WKT CRS strings, which is what ST_Transform() uses.

**Comment by threecat-up** [comment]
> you'll likely have to update to PostGIS 3.4 and use https://postgis.net/docs/manual-3.4/ST_TransformPipeline.html PROJ 5.2 accidentally supported "+proj=pipeline" strings as CRS, but this was more an accident than a design decision. PROJ >= 6 restricts CRS strings to be "simple" PROJ.4 CRS strings or WKT CRS strings, which is what ST_Transform() uses.

---
@rouault I really appreciate your patient answer, which really helps me a lot. Thank you again for your help and wish you a happy day and happy life. I will try to use Postgis 3.4 or convert it to 7 parameters. In short, your answers are very helpful to me and solve my doubts. Once again, I would like to express my sincere thanks to you.
