### ISSUE TITLE
proj_create_from_database

### ISSUE THREAD

**Issue by KarenChen9999** [OSGeo/proj.4#3518]
I came across this issue when calling the function in parallel processing 

"ERROR 1: PROJ proj_create_from _database: Open of /apps/opt/miniconda3/envs/bhf/share/proj failed".

With the same function, if I call it sequentially, I don't have this issue. However, I do need to run this function parallelly. Any suggestions that I could fix that issue?

#### Environment Information
 - PROJ version (`proj`): 9.1.0
 - Operation System Information: linux-64
- Other information
active environment: bhf
active env location : /apps/opt/miniconda3/envs/bhf
shell level : 2
user config file : /apps/home/devuser/.condarc
populated config files : /apps/home/devuser/.condarc
/apps/opt/miniconda3/envs/bhf/.condarc
conda version : 22.11.1
conda-build version : not installed
python version : 3.9.12.final.0
virtual packages : __archspec=1=x86_64
__glibc=2.17=0
__linux=3.10.0=0
__unix=0=0
base environment : /apps/opt/miniconda3  (writable)
conda av data dir : /apps/opt/miniconda3/etc/conda
conda av metadata url : None
channel URLs : https://conda.anaconda.org/conda-forge/linux-64
https://conda.anaconda.org/conda-forge/noarch
https://repo.anaconda.com/pkgs/main/linux-64
https://repo.anaconda.com/pkgs/main/noarch
https://repo.anaconda.com/pkgs/r/linux-64
https://repo.anaconda.com/pkgs/r/noarch
package cache : /apps/opt/miniconda3/pkgs
/apps/home/devuser/.conda/pkgs
envs directories : /apps/opt/miniconda3/envs
/apps/home/devuser/.conda/envs
platform : linux-64
user-agent : conda/22.11.1 requests/2.28.1 CPython/3.9.12 Linux/3.10.0-1160.80.1.el7.x86_64 centos/7.9.2009 glibc/2.17
UID:GID : 1025:1025
netrc file : None
offline mode : False

**Comment by rouault** [comment]
> however, I do need to run this function parallelly. Any suggestions that I could fix that issue?

use one PJ_CONTEXT* per thread: https://proj.org/development/reference/functions.html#c.proj_context_create

**Comment by KarenChen9999** [comment]
I don't know how I can change that. I didn't use proj_create_from_database directly. I think it was called when I ran zonal_stats.  I can run zonal_stats correctly without any errors outside of parallelly processing.

**Comment by rouault** [comment]
> zonal_stats correctly without any errors outside of parallelly processing.

You should report to the authors of the zonal_stats module (or any underlying code that ultimately use PROJ) that they must use a dedicated PJ_CONTEXT for each thread in their usage of the PROJ API.

**Comment by KarenChen9999** [comment]
> > zonal_stats correctly without any errors outside of parallelly processing.
> 
> You should report to the authors of the zonal_stats module (or any underlying code that ultimately use PROJ) that they must use a dedicated PJ_CONTEXT for each thread in their usage of the PROJ API.

ok, thank you, I will do that then
