### ISSUE TITLE
Discrepancy between cs2cs and PROJ API for NAD83 (HARN)

### ISSUE THREAD

**Issue by EZChe-EZDataMD** [OSGeo/proj.4#3519]
I was using PROJ API and following the example in the quick start (https://proj.org/development/quickstart.html). But I found the result of the coordinate conversion is different from the result I got running the cs2cs. The transformation is from EPSG:2913 (NAD83(HARN) / Oregon North (ft) ) to EPSG:26910 (NAD83 / UTM zone 10N).

# Your code here

API code: 
#include <stdio.h>
#include "proj.h"

void main()
{
	PJ_CONTEXT* C = proj_context_create();
	PJ* P = proj_create_crs_to_crs(C, "EPSG:2913", "EPSG:26910", NULL);
	PJ_COORD a = proj_coord(7849953.54, 694171.59, 854.05, 0);
	PJ_COORD b = proj_trans(P, PJ_FWD, a);

	printf("\n%lf %lf %lf", b.xyz.x, b.xyz.y, b.xyz.z);
	getchar();
}

result: 587794.376670 5046056.178233 854.050000

cs2cs cmd:
C:\OSGeo4W\bin\cs2cs.exe EPSG:2913 EPSG:26910
7849953.54 694171.59 854.05 0

result: 587795.43       5046055.99 854.05 0

#### Problem description

The result from the API is more similar to the 2913 -> 32610. 

 C:\OSGeo4W\bin\cs2cs.exe EPSG:2913 EPSG:32610
7849953.54 694171.59 854.05 0
587794.38       5046056.18 854.05 0

I am wondering if there is something wrong in the API handling the datum NAD83(HARN). 

#### Expected Output

The coordinate output from cs2cs and the API should be the same.  

#### Environment Information
 - PROJ version (`proj 9.1.1`)
 - Operation System Information (Windows 11)

#### Installation method
 - OSGeo4W

**Comment by rouault** [comment]
Cf https://github.com/rouault/PROJ/commit/44bddc8bc3ac3203936f3ce81dd5e873869edb0f. Some PROJ operations require grids from the PROJ-data package (https://proj.org/resource_files.html#external-resources-and-packaged-grids),  to be installed to have the most accurate results

**Comment by EZChe-EZDataMD** [comment]
Thanks Even,
That solves the problem. Now there is another issue popping up with the
conversion to NAD83(2011) UTM (EPSG:6339).

Input                   (EPSG: 2913): 7849953.55, 694171.58
Expected output (EPSG: 6339): 587795.55, 5046055.71  (Some rounding errors
are expected)

CS2CS:
1. EPSG: 2913 -> 6339
587794.38       5046056.18 0.00

2. EPSG: 2913 -> 3740 -> 6339
587795.50       5046055.57 (3740, NAD83(HARN))
587794.38       5046056.18 (6339, NAD83(2011))

3. EPSG: 2913 -> 3717 -> 6339
587795.50       5046055.57 (3717, NAD83(NSRS2007))
587795.50       5046055.57 (6339, NAD83(2011))

As shown in the result, I think there is no high-accuracy transformation
between NAD83(HARN) and NAD83(2011) while converting NAD83 HARN to NAD83
and NAD83 (2007) seem to work fine.

I also noticed there are a few more files available on the CDN
server (us_noaa_nadcon5_*). I'm wondering if those are supposed to fix the
issue that I have. But it doesn't seem to make a difference in my case. Any
idea what can go wrong?
[image: image.png]


Thanks,
Ezra

**Comment by rouault** [comment]
> I also noticed there are a few more files available on the CDN server (us_noaa_nadcon5_*). I'm wondering if those are supposed to fix the issue that I have.

yes, this is work from just 5 days ago. you need to use PROJ master for that: https://github.com/OSGeo/PROJ/pull/3510

**Comment by EZChe-EZDataMD** [comment]
I see. Thank you so much.

**Comment by EZChe-EZDataMD** [comment]
I built the proj 9.2 from PROJ master in Visual Studio 2019 (note: the
libcurl, tiff, and other libraries are linked from proj 9.1).
I tested the cs2cs and got the same result with some issue converting
between NAD83 (HARN) and NAD83 (2011).

Because I don't have much insight in the proj, I couldn't really dig into
the code at this point.
But I did some testing with NAD83 (HARN) -> NAD as I knew this conversion a
bit better in terms of which file it is using for high accuracy
transformation.

When I converted from state plane NAD83(HARN) [2913] to UTM NAD83 [26910],
I found the cs2cs is using *us_noaa_WO.tif* rather than *us_noaa_wohpgn.tif
*(I think it is essentially the same as us_noaa_WO.tif?) or*
us_noaa_nadcon5_nad83_1986_nad83_harn_conus.tif
*because I tried removing us_noaa_WO.tif from the proj folder and it fell
back to the low accuracy transformation results.

Best,
Ezra

**Comment by randal-baumgarden** [comment]
It is helpful to enable logging to see where PROJ is looking for files (and whether it is succeeding in opening them).  You can do so by adding the following line after creating your context.

`proj_log_level(C, PJ_LOG_LEVEL::PJ_LOG_TRACE);`

It's likely PROJ doesn't know where your grid files are, but the logging should shed some light on what issues you are having.

**Comment by EZChe-EZDataMD** [comment]
Thanks! This is very helpful.
Here is what I found in a few tests and notes:
*1. State Plane NAD83(HARN) to UTM NAD83*

*PS C:\Users\erzhu> C:\OSGeo4W\bin\cs2cs.exe EPSG:2913 --3d EPSG:26910 --3d
-D 3*
pj_open_lib(proj.ini): call fopen(C:\OSGeo4W/share/proj/proj.ini) -
succeeded
pj_open_lib(proj.db): call fopen(C:\OSGeo4W/share/proj/proj.db) - succeeded
pj_open_lib(nadcon5.nad83_1986.nad83_harn.conus.lat.trn.20160901.b): call
fopen(nadcon5.nad83_1986.nad83_harn.conus.lat.trn.20160901.b) - failed
pj_open_lib(nadcon5.nad83_1986.nad83_harn.conus.lon.trn.20160901.b): call
fopen(nadcon5.nad83_1986.nad83_harn.conus.lon.trn.20160901.b) - failed
pj_open_lib(us_noaa_WO.tif): call fopen(us_noaa_WO.tif) - failed
pj_open_lib(WO): call fopen(WO) - failed
...
Using coordinate operation Inverse of SPCS83 Oregon North zone
(International feet) + Inverse of NAD83 to NAD83(HARN) (28) + UTM zone 10N
pj_open_lib(us_noaa_WO.tif): call
fopen(C:\OSGeo4W/share/proj/us_noaa_WO.tif) - succeeded


*Note: I purposely removed us_noaa_WO.tif from the proj folder to see what
other options PROJ is looking for. It didn't look for
us_noaa_wohpgn.tif (although it seems to be a duplicate in the database).
Also the file names such
as nadcon5.nad83_1986.nad83_harn.conus.lat.trn.20160901.b look odd. Maybe
they are deprecated from the previous versions?*


*2. State Plane NAD83(HARN) to UTM NAD83(2011)*

*PS C:\Users\erzhu> C:\OSGeo4W\bin\cs2cs.exe EPSG:2913 --3d EPSG:6339 --3d
-D 3*
pj_open_lib(proj.ini): call fopen(C:\OSGeo4W/share/proj/proj.ini) -
succeeded
pj_open_lib(proj.db): call fopen(C:\OSGeo4W/share/proj/proj.db) - succeeded
...
Using coordinate operation Inverse of SPCS83 Oregon North zone
(International feet) + NAD83(HARN) to WGS 84 (3) + Inverse of NAD83(2011)
to WGS 84 (1) + UTM zone 10N


*Note: In this case, it looks like PROJ didn't even try looking for the new
grids from nadcon5 (us_noaa_nadcon5_xxxx), but rather taking WGS84 as the
middle ground.*

All the database and grid files are in the same directory.

Would this be enough to provide some hints for the issues?

If you can point me to the corresponding source files/functions, I am also
more than willing to look into this to the best I can.

Best,
Ezra

**Comment by rouault** [comment]
> us_noaa_wohpgn.tif (although it seems to be a duplicate in the database). Also the file names such as nadcon5.nad83_1986.nad83_harn.conus.lat.trn.20160901.b look odd. Maybe they are deprecated from the previous versions?*

no, they are just the original filenames of the original NOAA .b files, as registered in EPSG. But currently released PROJ versions (I suspect you might "only" use PROJ 9.1 through OSGeo4W) cannot used NADCON5 grids, so they will skip those records. This is available only in PROJ master 9.2dev unreleased + using the us_noaa_nadcon5_*.tif grids of https://github.com/OSGeo/PROJ-data/tree/master/us_noaa converted from the original NOAA .b files

**Comment by EZChe-EZDataMD** [comment]
I built the library and program with PROJ-master (Dec 22, 2022) as you
suggested last year.
I can confirm the cs2cs.exe is using proj_9_2.dll that was built from that
source.

Best,
Ezra

**Comment by EZChe-EZDataMD** [comment]
This was resolved. Thanks!
