### ISSUE TITLE
proj_is_derived_crs seems to always derived for projected CRS?

### ISSUE THREAD

**Issue by snowman2** [OSGeo/proj.4#3525]
Related: https://github.com/pyproj4/pyproj/issues/1182

#### Example of problem
https://github.com/OSGeo/PROJ/blob/23ffb4ba179a9b3bf1debd2749e92f1862b51536/src/iso19111/c_api.cpp#L1951

```c
PJ_CONTEXT* context = proj_context_create()
PJ* crs = proj_create(context, "EPSG:6933")
bint is_derived = proj_is_derived_crs(context, crs)
pyproj_context_destroy(context)
proj_destroy(crs)
```

#### Problem description

The Projected CRS WKT looks like this:
```
'PROJCRS["WGS 84 / NSIDC EASE-Grid 2.0 Global"...
```
and the result says it is derived. Is that correct?

I noticed in the PROJ tests that this is the WKT beginning for a derived projected CRS:
```
DERIVEDPROJCRS["derived projectedCRS" ...
```
#### Expected Output

Is there supposed to be a difference? Or is this behavior expected?

#### Environment Information
 - PROJ version: 9.2
 - Operation System Information: Ubuntu 22

#### Installation method
 - From source

**Comment by snowman2** [comment]
Discovered when looking into #3488.

**Comment by rouault** [comment]
cf https://docs.opengeospatial.org/as/18-005r4/18-005r4.html#33 : "A projected CRS is a coordinate reference system which is derived from a base geographic CRS [...]" and "Figure 10: UML diagram — Derived Coordinate Reference Systems" that shows that ProjectedCRS implements DerivedCRS.

**Comment by snowman2** [comment]
Interesting - so this function isn't going to be helpful to differentiate between a Derived Projected CRS and a Projected CRS. From what I can tell, it should work for all other types (i.e. geographic, vertical, etc..) to differentiate between the derived version and the base version. Is that correct?

**Comment by rouault** [comment]
A Derived Projected CRS is a derived CRS of a derived CRS.  proj_get_type() will never return PJ_TYPE_PROJECTED_CRS for a DerivedProjectedCRS, since a DerivedProjectedCRS isn't a ProjectedCRS. It will return PJ_TYPE_DERIVED_PROJECTED_CRS in PROJ 9.2 and PJ_TYPE_OTHER_CRS in current versions (in those versions, proj_get_type() == PJ_TYPE_OTHER_CRS && proj_is_derived() should only be true on a DerivedProjectedCRS)

**Comment by snowman2** [comment]
Thanks for the explanation @rouault, that was very helpful :+1:
