### ISSUE TITLE
Use of PROJ_NETWORK affects results

### ISSUE THREAD

**Issue by oleg-alexandrov** [OSGeo/proj.4#3530]
Running PROJ can give different results depending on whether  PROJ_NETWORK is on or off. 

I think that's a bad thing. It would be better if the tool failed altogether if it can't find its resources, on the network or locally. As it is, it simply uses a wrong value for the datum semiaxes, and continues as if nothing happened. 

I tried to understand this more by running PROJ in debug mode. With this variable off, it uses pj_ellipsoid - final: a=6378137.000. With it on, it uses pj_ellipsoid - final: a=6378206.400 (this is for NAD27 to WGS84 conversions).

Such gotchas are hard to understand and debug for an end user.  Even if PROJ_NETWORK is on, likely the software will give different results when there's no net access, which happens when submitting supercomputer jobs.

**Comment by hobu** [comment]
> Running PROJ can give different results depending on whether PROJ_NETWORK is on or off.

Use [projsync](https://proj.org/apps/projsync.html) to pull all of the grids locally so as to not depend upon the network. 

> Even if PROJ_NETWORK is on, likely the software will give different results when there's no net access, which happens when submitting supercomputer jobs.

PROJ_NETWORK is a convenience. Most people don't need all of the grids. If you're in a supercomputer scenario, set up your own CDN locally, copy all of the grids to a common network location and point `PROJ_DATA` at it, or ship all of the grids you need to every job in your PROJ install's `PROJ_DATA` directory.

**Comment by oleg-alexandrov** [comment]
You closed this fast but you haven't addressed the issue. 

This tool can give wrong results with no warning and no error. The user need not know all these intricacies and the software wouldn't tell you. This is just sitting on a mine waiting to go off on you. That's not how sound software is written.

**Comment by hobu** [comment]
> You closed this fast but you haven't addressed the issue.

Is the bug report about PROJ_NETWORK or NAD27 <=> WGS84? Please note that @rouault added NADCON support in #3510 for the next PROJ release, so things should be improving some more but they have the potential to be different.

> This tool can give wrong results with no warning and no error. 

Please define "wrong results" in the context of geodetic estimation of position. "More accurate", certainly, but it is not so black and white to be just right or wrong. There are often many transformation pathways that are possible, and users must use expertise and experience with tools like PROJ to get what they want. 

>  The user need not know all these intricacies and the software wouldn't tell you. 

If you turn on the debug logging, you will see PROJ telling you it can't find the grids. It is a warning, not an error. The situation is geodetic transformations are necessarily intricate, and PROJ cannot paper over all of it for you. 

> That's not how sound software is written.

If you have a proposal to make sound software, please write up a [PROJ RFC](https://proj.org/community/rfc/index.html) describing how you would like to change this behavior, socialize it within the [community](https://proj.org/community/channels.html), and get the community to support it with a vote in favor of your implementation.

**Comment by rouault** [comment]
The utilities and API have already a provision for the user to be able to ask coordinate operations to fail if no datum transformation can be found:
- https://proj.org/apps/cs2cs.html#cmdoption-cs2cs-no-ballpark
- https://proj.org/development/reference/functions.html#c.proj_operation_factory_context_set_allow_ballpark_transformations
- https://proj.org/development/reference/functions.html#c.proj_create_crs_to_crs_from_pj with ALLOW_BALLPARK=NO option

This will not guarantee that the "best" transformation is used, but at least you'll get a transformation that has a known accuracy (using a Helmert transformation or a grid)

**Comment by oleg-alexandrov** [comment]
Thank you for the additional comments. 

> Please define "wrong results" in the context of geodetic estimation of position

If I ask for a NAD27 to WGS84 conversion, and the software quietly uses instead of NAD27 say WGS84 itself, that is as wrong as it gets. 

I think it must be mandatory that if the software was asked in no uncertain terms to transform from coordinate system A to coordinate system B, and coordinates of A can't be found, that must be a fatal error, or at least a warning. Or just return Inf instead of values off by tens of meters. 

Here's how crazy it can get. I wrote a code which was working fine. It failed in an overnight test. I spent 3 hours doubting my sanity and searching for bugs everywhere, till I realized my conda environment was quietly turning on the network mode in my dev enviroment.

> If you have a proposal to make sound software, please write up a [PROJ RFC]

I could. For now I hope this issue is at least kept open. You folks know a lot more things than what I do. If this issue doesn't pique your interest as it is, I won't spend time convincing anybody.

**Comment by oleg-alexandrov** [comment]
To add, I know that, for example, there are many (evolving) standards for how to convert between two coordinate systems, there can be time dependence, etc, so PROJ will never be foolproof. Yet, if a lookup table is needed, and it is missing, simply continuing without it can't be right.

**Comment by rouault** [comment]
cf https://github.com/OSGeo/PROJ/issues/3533 for a discussion related to this topic
