### ISSUE TITLE
PROJ.9 (7 and 8 too) : Asking for a clarification for PROJ DATA installation (CMake compilation)

### ISSUE THREAD

**Issue by Laurent-777** [OSGeo/proj.4#3539]
WISH : complete description in the README file or in the PDF documentation for PROJ.9 (PROJ.7 and PROJ.8 too) about how to correctly install PROJ DATA (for example, proj-data-1.12) when, in particular, when we use CMake now.

In fact, I'am asking some questions, possibilities are offered to my mind : 
1. May I untar the proj-data file inside a dedicated folder of the PROJ source folder ? How ? Where ?; or
2. Do I need to specify, with CMake options/entries, where is untarred PROJ DATA ? Besides, are they installed in the final destination in this case ? or
3. Do I need to untar the PROJ DATA inside a dedicated folder inside the PROJ final installation ? How ? Where ? ; or
4. Whatsoever you may find.
Eventually, please kindly note that almost every softwares are not located in the "standard" location (/usr/local in particular), but in an external HD, so I need to use strongly configuration parameters such as : CPPFLAGS, LDFLAGS, PKG_CONFIG_PATH.
Kind regards,

**Comment by kbevers** [comment]
I believe it's all adressed in the [installation instructions](https://proj.org/install.html#installation-from-package-management-systems). See the last steps:

![image](https://user-images.githubusercontent.com/13132571/210578032-3978fdf9-7d20-4ab3-a4cf-427d71a221da.png)

So,

1. Yes. Tell PROJ where that is using the `PROJ_DATA` environment variable or put the files in one of [the default locations used on your platform](https://proj.org/resource_files.html#where-are-proj-resource-files-looked-for)
2. No
3. No
