### ISSUE TITLE
Request to have example for converting geodetic to projected coordinates

### ISSUE THREAD

**Issue by oleg-alexandrov** [OSGeo/proj.4#3546]
The documentation at https://proj.org/development/quickstart.html lacks an example for how, given a proj string with a datum, it converts from geodetic to projected coordinates for that datum, and vice-versa. 

I believe this falls squarely within what PROJ is meant to do.  I spent a lot of time figuring out how to do that as the doc is no help.

The example should work with an arbitrary projection, in EPSG, WKT, or proj string format, not just when proj="+utm" and then one can do crs_to_crs with a second "+longlat" projection. 

My own attempt at adding to the doc was shot down. See https://github.com/OSGeo/PROJ/pull/3515.

I hope the community can come up with an alternative example. Please don't tell me that I have a  PROJ.4 mentality. Please don't offer handwaving like @kbevers does. 

I am hoping for a spelled out code a developer can use. Input: any string supported by this library. Desired: code to convert lonlat in degrees to projection and vice-versa. Thank you.

**Comment by snowman2** [comment]
Here is the getting started guide for pyproj [ref](https://pyproj4.github.io/pyproj/stable/examples.html#transformations-from-crs-to-crs). The `Transformer` class uses `proj_create_crs_to_crs_from_pj` under the hood and should be equivalent to using the `cs2cs` program. Using that function, you can select your source CRS and target CRS to transform to. This function handles transformations between datums.

Here is a warning with examples about using `Proj` which is equivalent to using the `proj` command line program or the `proj_create` function [ref](https://pyproj4.github.io/pyproj/stable/gotchas.html#proj-not-a-generic-latitude-longitude-to-projection-converter). EDIT: You can use `proj_crs_get_geodetic_crs` to get the geodetic CRS of a base CRS.

**Comment by oleg-alexandrov** [comment]
This is very helpful, thank you. The key step seems to be "Retrieve the geodetic CRS based on original CRS" using the function "geodetic_crs". Then one does: "Transformer.from_crs(crs.geodetic_crs, crs)". 

As you say, the C/C++ analog to get the geodetic CRS is "proj_crs_get_geodetic_crs()". Then one can use proj_create_crs_to_crs(). 

In C++, likely additional code is needed, to populate the PJ_COORD struct which is not obvious given its many use cases, then convert it to radians. Likely one does not need to use proj_normalize_for_visualization() as that's another thing to worry about deallocating. Then, after an inverse transform from easting/northing to geodetic, one can convert again from radians to degrees.

Will any kind soul be willing to review and iterate with me on some code which can do the job, and then have the ability to actually merge it in?

**Comment by oleg-alexandrov** [comment]
@rouault: Any advice on appropriateness of adding to the PROJ C++ dev doc an example illustrating how to transform from projected to geodetic coordinates? Any preferences on whether proj_create() or proj_crs_get_geodetic_crs() together with proj_create_crs_to_crs() would make more sense? It is same to me, as long as filling the current hole in the doc is done.

**Comment by rouault** [comment]
> Any preferences on whether proj_create() or proj_crs_get_geodetic_crs() together with proj_create_crs_to_crs() would make more sense?

Something like proj_create_crs_to_crs_from_pj(ctxt, crs, proj_crs_get_geodetic_crs(crs)) would make sense, as it is the real canonical way for being converting between geodetic and projected cordinates on the same datum.

**Comment by oleg-alexandrov** [comment]
Thank you. One note. Doing:

PJ *P = proj_create(C, "+proj=utm +zone=32 +datum=WGS84");
PJ *G = proj_crs_get_geodetic_crs(C, P);

gave the error: Object is not a CRS. 

I read one has to append " +type=crs" but that defeats the purpose of being able to use an arbitrary string to make a projection. How can one trick any input projection to be "CRS"? Are WKT and EPGS projections automatically "CRS"?

Apart from that, things work, but one need not do a conversion to radians if using proj_create_crs_to_crs_from_pj(), even though the conversion was needed with plain proj_create().

Here's what I've got so far: https://github.com/OSGeo/PROJ/pull/3515/files

Here's the output, which I verified to be correct:

Input longitude: 12, latitude: 55 (degrees)
Output easting: 691876, northing: 6.09891e+06 (meters)
Inverse applied. Longitude: 12, latitude: 55 (degrees)

Thanks a lot.

**Comment by snowman2** [comment]
`+type=crs` is only needed for PROJ strings. It helps to differentiate between a CRS and a coordinate operation (pyproj code [ref](https://github.com/pyproj4/pyproj/blob/9283f962e4792da2a7f05ba3735c1ed7f3479502/pyproj/crs/crs.py#L102)).

**Comment by oleg-alexandrov** [comment]
I checked that the pdf doc is created correctly. Recommendations from the community were sought and implemented. Pyproj already has analogous examples and docs.

What is next? More reviews?

**Comment by oleg-alexandrov** [comment]
No more feedback after one week. @rouault: Would it be a reasonable request to ask you to merge this in? (https://github.com/OSGeo/PROJ/pull/3515/files) It is a straightforward adaptation of the pyproj example for the C API.

**Comment by oleg-alexandrov** [comment]
Got fixed in https://github.com/OSGeo/PROJ/pull/3515.
