### ISSUE TITLE
Update WKT import to support WKT2 corrigendum

### ISSUE THREAD

**Issue by rouault** [OSGeo/proj.4#3571]
18-010r10_CRS_WKT_Corrigendum.pdf and 18-005r7_AS_Topic_2_Referencing_by_Coordinates-1.pdf add:
- ANCHOREPOCH[] in static geodetic and vertical reference frame
- AXISMINVALUE[], AXISMAXVALUE[], RANGEMEANING[] in AXIS[]

**Comment by jjimenezshaw** [comment]
Thanks. Where can those documents be found?

**Comment by rouault** [comment]
> Where can those documents be found?

I believe they are only available to OGC members for now. I believe they should surface publicly in a few weeks once approved (or maybe for a public comment phase)
