### ISSUE TITLE
cs2cs outputs a different result when using EPSG code vs. PROJ.4 string

### ISSUE THREAD

**Issue by cschwarz** [OSGeo/proj.4#3572]
#### Example of problem
cs2cs outputs a different result when using EPSG:5514 vs. PROJ.4 string, even if projinfo prints the same PROJ.4 string for that EPSG code.

```c
> echo 14.413719 50.085346   | cs2cs +init=epsg:4326 +to +init=epsg:5514
-743375.94      -1043172.85 0.00

> echo 14.413719 50.085346   | cs2cs +init=epsg:4326 +to +proj=krovak +lat_0=49.5 +lon_0=24.8333333333333 +alpha=30.2881397527778 +k=0.9999 +x_0=0 +y_0=0 +ellps=bessel +towgs84=589,76,480,0,0,0,0 +units=m +no_defs +type=crs
-743382.17      -1043180.54 0.00

> projinfo epsg:5514
PROJ.4 string:
+proj=krovak +lat_0=49.5 +lon_0=24.8333333333333 +alpha=30.2881397527778 +k=0.9999 +x_0=0 +y_0=0 +ellps=bessel +towgs84=589,76,480,0,0,0,0 +units=m +no_defs +type=crs
```

#### Environment Information
 - PROJ version 9.1.1
 - Windows 10

#### Installation method
 - conda

**Comment by rouault** [comment]
This is a bit subtile...

The PROJ.4 string returned for EPSG:5514 inludes a +towgs84 transformation that is valid for the whole area of use of EPSG:5514 which is Czechia and Slovakia, which is EPSG:15965 "S-JTSK to WGS 84 (3)" which has a 6m accuray
But the point you transform is in  Czechia, hence this is the EPSG:1623 "S-JTSK to WGS 84 (1)" transformation which is used, which has a 1m accuracy

You can see it by enabling PROJ_DEBUG=2
```
$ echo 14.413719 50.085346   | PROJ_DEBUG=2 cs2cs +init=epsg:4326 +to +init=epsg:5514
[...]
Using coordinate operation axis order change (2D) + Inverse of S-JTSK to WGS 84 (1) + Krovak East North (Greenwich)
-743375.99	-1043172.83 0.00
```

So PROJ behaves here as designed, even if a bit surprising

You can see all candidate transformations with ``projinfo -s EPSG:4326 -t EPSG:5514 --spatial-test intersects``

**Comment by cschwarz** [comment]
Got it, thank you for the detailed explanation.
