### ISSUE TITLE
Proj build link is pointing at travis

### ISSUE THREAD

**Issue by robe2** [OSGeo/proj.4#3592]
On the ReadMe, the "Build Passing" image is linked to https://www.travis-ci.com/OSGeo/PROJ which gives a 404 error.

I think this should be changed to the github actions?  Although not sure those are actually running as the only green I see is for AppVeyor which is a No-op.

**Comment by mwtoews** [comment]
Thanks, fixed by 73d7254d1615a61e803e1ad797275dac11e4718e
