### ISSUE TITLE
Vertical datum reprojection inverted.

### ISSUE THREAD

**Issue by ktheijs** [OSGeo/proj.4#3602]
#### Example of problem
I am trying to reproject to the Ostend height vertical coordinate system, but it seems to do it in the reverse direction.

I give one example below, but it happens between every coordinate system that I have tested and (to/from) "Belge 1972 / Belgian Lambert 72 + Ostend height".

```
echo 210233.664 187487.165 -4.144 | cs2cs "Belge 1972 / Belgian Lambert 72" "Belge 1972 / Belgian Lambert 72 + Ostend height" --3d
```
The result I get is 
```
210233.66	187487.16 -47.18
```

However, the result should be 
```
210233.66	187487.16 38.90
```

The Z value seems to have subtracted 43.04 instead of added it.

#### Environment Information
I am using PROJ 9.1.1 on Windows 11.
All relevant grid/geoid files are present and can be found by PROJ.

#### Installation method
I am using the version provided on gisinternals https://www.gisinternals.com/query.html?content=filelist&file=release-1930-x64-gdal-3-5-3-mapserver-8-0-0.zip

**Comment by jjimenezshaw** [comment]
hi @ktheijs 
Assuming the formula `H = h - N` or `orthometric height = ellipsoidal height - geoid undulation`, I think the transformation is correct.
The geoid undulation in Belgium is about +44 m. 
So converting -4 m ellipsoidal height to orthometric height (that is what I understand you are doing), the orthometric height should be around -48 m

**Comment by rouault** [comment]
I concur this works as expected. This gives consistent result with WGS 84 <--> EGM2008
```
even@even-ThinkPad-P15v-Gen-1:~/proj/proj/build_cmake$ echo 50.99447619 5.22674858 -4.144 | PROJ_NETWORK=ON bin/cs2cs -d 8 "Belge 1972" "Belge 1972 + Ostend height" --3d
50.99447619	5.22674858 -47.18351425

even@even-ThinkPad-P15v-Gen-1:~/proj/proj/build_cmake$ echo 50.99447619 5.22674858 -4.144 | PROJ_NETWORK=ON bin/cs2cs -d 8 EPSG:4979 EPSG:4326+3855
50.99447619	5.22674858 -49.73357397
```

**Comment by ktheijs** [comment]
Thank you for the input. I still believe that something strange is going on with this transformation.

Some other findings:

```
echo 50.95 5.21 170 | cs2cs "WGS 84" "Belge 1972 / Belgian Lambert 72" --3d
209114.01	182526.32 126.71

echo 50.95 5.21 170 | cs2cs "WGS 84" "Belge 1972 / Belgian Lambert 72 + Ostend height" --3d
209113.95	182526.18 126.84

echo 182526.32 209114.01 126.71 | cs2cs "Belge 1972 / Belgian Lambert 72" "Belge 1972 / Belgian Lambert 72 + Ostend height" --3d
182526.32	209114.01 84.17
```

In the above commands you can see that the elevation is only slightly different when transforming from WGS84 to Belgian Lambert72 and from WGS84 to Belgian Lambert + Ostend height. But when you transform the resulting coordinates from the first transform to Belgian Lambert + Ostend height, you get a big difference.

Furthermore I noticed that Geoid model hGB18 is used to make the transitions 
from heights in vertical CRS (EPSG:5710 - Ostend height) to heights above the ellipsoid in ETRS89 (EPSG:4937).

Belgian Lambert72 uses [BD72](https://epsg.io/4313) as geographics CRS and not ETRS89. It seems like the geoid offset is directly applied to the ellipsoidal heights of Belgian Lambert72 instead of first transforming to ETRS89 ellipsoidal height.

**Comment by jjimenezshaw** [comment]
@ktheijs why are you swapping the coordinates in the last command? The first output is `209114.01	182526.32 126.71` but then you type `echo 182526.32 209114.01 126.71`.

@rouault Something similar happened we I added the Swiss geoid file. The Swiss geoid model in PROJ-dat is respect to ETRS89. When the system CH1903+ was used, it was ignoring the Helmert transfromation from ETRS89 to CH1903+ to apply the geoid height. You did a fix for that (I think it is here: https://github.com/OSGeo/PROJ/issues/2588)

**Comment by ktheijs** [comment]
@jjimenezshaw you are right. In my original tests using GDAL I did it right. When replicating it in command I mixed up the coordinates. The transformations should be as shown below. The conclusion remains the same though.

```
echo 50.95 5.21 170 | cs2cs "WGS 84" "Belge 1972 / Belgian Lambert 72" --3d
209114.01	182526.32 126.71

echo 50.95 5.21 170 | cs2cs "WGS 84" "Belge 1972 / Belgian Lambert 72 + Ostend height" --3d
209113.95	182526.18 126.84

echo 209114.01 182526.32 126.71 | cs2cs "Belge 1972 / Belgian Lambert 72" "Belge 1972 / Belgian Lambert 72 + Ostend height" --3d
209114.01	182526.32 83.55
```

**Comment by rouault** [comment]
Looking at projinfo output helps to reason about what PROJ does:

```
$ bin/projinfo -s "WGS 84" -t "Belge 1972 / Belgian Lambert 72" --3d  --spatial-test intersects

unknown id, Inverse of BD72 to WGS 84 (3) + Belgian Lambert 72, 1 m, Belgium - onshore.

PROJ string:
+proj=pipeline
  +step +proj=axisswap +order=2,1
  +step +proj=unitconvert +xy_in=deg +z_in=m +xy_out=rad +z_out=m
  +step +proj=cart +ellps=WGS84
  +step +inv +proj=helmert +x=-106.8686 +y=52.2978 +z=-103.7239 +rx=-0.3366
        +ry=0.457 +rz=-1.8422 +s=-1.2747 +convention=coordinate_frame
  +step +inv +proj=cart +ellps=intl
  +step +proj=lcc +lat_0=90 +lon_0=4.36748666666667 +lat_1=51.1666672333333
        +lat_2=49.8333339 +x_0=150000.013 +y_0=5400088.438 +ellps=intl
```

```
$ bin/projinfo -s "WGS 84" -t  "Belge 1972 / Belgian Lambert 72 + Ostend height" --3d --spatial-test intersects

unknown id, Inverse of ETRS89 to WGS 84 (1) + ETRS89 to Ostend height (1) + Inverse of BD72 to ETRS89 (3) + Belgian Lambert 72, 1.03 m, Belgium - onshore., at least one grid missing

PROJ string:
+proj=pipeline
  +step +proj=axisswap +order=2,1
  +step +proj=unitconvert +xy_in=deg +xy_out=rad
  +step +inv +proj=vgridshift +grids=be_ign_hBG18.tif +multiplier=1
  +step +inv +proj=hgridshift +grids=be_ign_bd72lb72_etrs89lb08.tif
  +step +proj=lcc +lat_0=90 +lon_0=4.36748666666667 +lat_1=51.1666672333333
        +lat_2=49.8333339 +x_0=150000.013 +y_0=5400088.438 +ellps=intl
```

```
$ bin/projinfo -s  "Belge 1972 / Belgian Lambert 72" -t "Belge 1972 / Belgian Lambert 72 + Ostend height" --3d  --spatial-test intersects:

unknown id, Inverse of Belgian Lambert 72 + ETRS89 to Ostend height (1) using BD72 to ETRS89 (3) + Belgian Lambert 72, 0.04 m, Belgium - onshore., at least one grid missing

PROJ string:
+proj=pipeline
  +step +inv +proj=lcc +lat_0=90 +lon_0=4.36748666666667 +lat_1=51.1666672333333
        +lat_2=49.8333339 +x_0=150000.013 +y_0=5400088.438 +ellps=intl
  +step +proj=push +v_1 +v_2
  +step +proj=hgridshift +grids=be_ign_bd72lb72_etrs89lb08.tif +omit_inv
  +step +inv +proj=vgridshift +grids=be_ign_hBG18.tif +multiplier=1
  +step +inv +proj=hgridshift +grids=be_ign_bd72lb72_etrs89lb08.tif +omit_fwd
  +step +proj=pop +v_1 +v_2
  +step +proj=lcc +lat_0=90 +lon_0=4.36748666666667 +lat_1=51.1666672333333
        +lat_2=49.8333339 +x_0=150000.013 +y_0=5400088.438 +ellps=intl
```

What is probably questionable is the WGS 84 <--> "Belge 1972 / Belgian Lambert 72" transformation. It uses the EPSG:15929 Helmert transformation, whose remark is "Parameter values from BD72 to ETRS89 (2) (code 15928) assuming that ETRS89 is equivalent to WGS 84 within the accuracy of the tfm". So there are 2 potential issues: considering that ETRS89 ~= WGS 84, and probably the main issue is to extend the Helmert transformation to the 3D scope, whereas BD72 has no official 3D geographic CRS. This means that ellipsoidal heights on BD72 are probably not well defined. So in fact not only the first transformation is questionable, but the 3d one as well. The second transformation  "WGS 84"  <--> "Belge 1972 / Belgian Lambert 72 + Ostend height" is likely OK if we one considers ETRS89 ~= WGS 84
I do believe that PROJ behaves here as best as it can given the available input transformations it has access to.
