### ISSUE TITLE
Promote to 3D

### ISSUE THREAD

**Issue by davidvargasaguilera** [OSGeo/proj.4#3651]
Hi,

I'm using PROJ v9.1.1 and I've detected that **proj_create_operations** function doesn't promote to 3D as it's documented: 

When one of the source or target CRS has a vertical component but not the other one, the one that has no vertical
component is automatically promoted to a 3D version, where its vertical axis is the ellipsoidal height in metres,
using the ellipsoid of the base geodetic CRS.

For instance: EPSG:23030+EPSG:3855 to EPSG:32630

Thanks.

**Comment by rouault** [comment]
This is actually a documentation issue, as the behaviour was changed in 3e7984f3b26e408e69b960f8e0d03b6ac0576188 to no longer auto promote to 3D

**Comment by davidvargasaguilera** [comment]
Thank you for your quick response. 

I know that the transformation could be done using a pipeline, right? but, would it be possible to define the source or target CRS with ellipsoidal height? For instance, EPSG:23030+Ellipsoidal height

I'm using C API, and I can see that **proj_crs_promote_to_3D** function is in experimental API. Can I use this function? will it be in final API? Should I use CRS::promoteTo3D function from C++ API?

**Comment by rouault** [comment]
> I'm using C API, and I can see that **proj_crs_promote_to_3D** function is in experimental API. Can I use this function?

yes, the "experimental" in the proj_experimental.h name is a bit overcautious. We should probably migrate all those functions into the main proj.h

**Comment by davidvargasaguilera** [comment]
I need this functionality, so I'll use the experimental C API.

Thanks again for your support.
