### ISSUE TITLE
Cross Compile for Android and iOS

### ISSUE THREAD

**Issue by alionteo** [OSGeo/proj.4#3660]
Please share the process to cross compile PROJ for android and iOS. Thanks

**Comment by kbevers** [comment]
We don't have one. Contributions are welcome.

**Comment by alexbejann** [comment]
@alionteo how did you approach this? If you've solved it. 
@kbevers any plans for this in the future?
I do see this fork https://github.com/ngageoint/PROJ, they created the projections-ios library, open-sourced under the same organization. But I can't get the libtiff working in it, as I have pipelines that require grids. Any suggestions for this?

**Comment by kbevers** [comment]
> @kbevers any plans for this in the future?

Not that I am aware of. If it is important for you I suggest you lead the effort or find funding for the development. 

> Any suggestions for this?

No.

**Comment by alexbejann** [comment]
Thanks for the answer @kbevers! Can I reach out to you by email regarding the budget for development?

**Comment by kbevers** [comment]
> Can I reach out to you by email regarding the budget for development?

This is outside of my area of expertise. I wouldn't have the time to do it even if I had. I suggest you ask on the [mail list](https://proj.org/en/9.4/community/channels.html#mailing-list). There's at least a few independant contractors subscribed who is likely to have the skills to do this. If you are lucky one them is also interested in such a contract.

**Comment by dg0yt** [comment]
The basic cross build process is simple: Use a CMake toolchain file for the desired target. This is standard CMake, no extra instructions needed. Similar for the dependencies.

AFAICT the proj port in vcpkg is used with android and ios.

There may be a more challenging task after the cross build: deploying and loading resources.

**Comment by jjimenezshaw** [comment]
There is one detail to take into consideration. During the build process, proj.db should be generated with the sqlite3 application in the building OS. But the sqlite3 library packaged should be for the target OS.

**Comment by dg0yt** [comment]
`proj.db` is the key resource I was refering to: It also needs to be deployed and loaded.

**Comment by alexbejann** [comment]
Thanks guys for the suggestions! I was able to achieve what I wanted to do.  

I released a version of PROJ with libtiff enabled on Cocoapods if anyone wants to use it in their iOS project. I called it [PROJ-LibTIFF](https://github.com/CocoaPods/Specs/commit/b4ca408df55672d93b1a1fad02f6d6e385e5ca89)
[libtiff](https://github.com/CocoaPods/Specs/commit/be93337d2b886b781f0aa0ca8c7af2e0caed587f)

If anyone wants to use these libraries in their app in the upcoming weeks I will create packages for both.

**Comment by saurebchaudary** [comment]
Is there any stepwise guide/tutorial available on using PROJ in an android app?

**Comment by kbevers** [comment]
> Is there any stepwise guide/tutorial available on using PROJ in an android app?

We don't have one. Contributions are welcome.

**Comment by rouault** [comment]
you can refer to https://gdal.org/en/latest/download.html#android and replace ``gdal`` by ``proj``

**Comment by vikaspizone** [comment]
> you can refer to https://gdal.org/en/latest/download.html#android and replace `gdal` by `proj`

HI @rouault ,

I have installed the PROJ packages as per your instructions. However, when I run the make command in the build folder, it fails due to an incorrect file format for libsqlite3.a.
