### ISSUE TITLE
When using example getting error

### ISSUE THREAD

**Issue by alionteo** [OSGeo/proj.4#3663]
Hi, I am trying to run the example [cs2cs](https://github.com/OSGeo/PROJ/blob/master/examples/crs_to_geodetic.c), but ended up with the error below. 

`Undefined symbols for architecture arm64:
  "_proj_context_create", referenced from:
      _main in crs_to_geodetic-7fddd1.o
  "_proj_context_destroy", referenced from:
      _main in crs_to_geodetic-7fddd1.o
  "_proj_create", referenced from:
      _main in crs_to_geodetic-7fddd1.o
  "_proj_create_crs_to_crs_from_pj", referenced from:
      _main in crs_to_geodetic-7fddd1.o
  "_proj_crs_get_geodetic_crs", referenced from:
      _main in crs_to_geodetic-7fddd1.o
  "_proj_destroy", referenced from:
      _main in crs_to_geodetic-7fddd1.o
  "_proj_trans", referenced from:
      _main in crs_to_geodetic-7fddd1.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

cc : @rouault 
Need bit help to simple run this basic application, please guide if I am missing something. Thanks

**Comment by rouault** [comment]
> Need bit help to simple run this basic application, please guide if I am missing something. Thanks

given your error, that's likely an issue in how you've built PROJ . Perhaps a CMake usage issue, something related to cross compilation. I cannot help more

**Comment by alionteo** [comment]
For example I simple test [cs2cs](https://github.com/OSGeo/PROJ/blob/master/examples/crs_to_geodetic.c), standalone , not with any CMake, then I again get same error as below, This is purely using PROJ and no cross compilation. 

`Undefined symbols for architecture arm64:
  "_proj_context_create", referenced from:
      _main in crs_to_geodetic-ced226.o
  "_proj_context_destroy", referenced from:
      _main in crs_to_geodetic-ced226.o
  "_proj_create", referenced from:
      _main in crs_to_geodetic-ced226.o
  "_proj_create_crs_to_crs_from_pj", referenced from:
      _main in crs_to_geodetic-ced226.o
  "_proj_crs_get_geodetic_crs", referenced from:
      _main in crs_to_geodetic-ced226.o
  "_proj_destroy", referenced from:
      _main in crs_to_geodetic-ced226.o
  "_proj_trans", referenced from:
      _main in crs_to_geodetic-ced226.o
ld: symbol(s) not found for architecture arm64`

Please help. Thanks

**Comment by rouault** [comment]
you probably just need to set the DYLD_LIBRARY_PATH environment variable to the directory where libproj.dylib is installed.  Or perhaps build with cmake -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON or any of the rpath magic variables (cf https://dev.my-gate.net/2021/08/04/understanding-rpath-with-cmake/ and other resources)

**Comment by alionteo** [comment]
Okay I did according to you suggested , upon building proj project inside build/lib folder I find libproj.dylib, now I just want to include this into my existing cpp file to use cs2cs functions, sorry but I am completely new to c and ++ and configurations stuff. I would need your help to consume this dylib file. Many thanks

**Comment by alionteo** [comment]
Hi Can please guide where i can find libproj.so file ?

**Comment by mwtoews** [comment]
`pkgconf proj --variable=libdir`

Also try `export LDFLAGS="${LDFLAGS} -Wl,-rpath,$(pkg-config proj --variable=libdir)"` for your project to set the rpath.

**Comment by alionteo** [comment]
@mwtoews Thanks a bunch for reaching out, I am sorry absolutely have no idea where to set these totally new to proj, can share some more detailed steps. Thanks

**Comment by alionteo** [comment]
@rouault can do me a favour, share one sample cmakeLists file and the command to run? To eventually generate .so file. I think that will solve issue and you wont be bothered more :) Thanks

**Comment by kbevers** [comment]
@alionteo I think you are better of learning some basics of unix like operating systems, build and packaging tools. The questions you are asking are not specific to PROJ and are thoroughly difficult to answer since you don't provide enough detail (and when asked about the details are seemingly unaware of them). 

We are usually happy to provide guidance with the use of PROJ but this isn't a general helpdesk for all you computing related problems. I suggest you install PROJ via your operating system's package manager. See https://proj.org/install.html#installation-from-package-management-systems for more details.

**Comment by alionteo** [comment]
Thanks @kbevers for asking the issue. Let me share my need actually. We are building a flutter app for ios and android which just need to convert one coordinate system to another. Simply this is needed. My RnD shown that there is something called FFI that support using native libs to be consumed in android and ios. Also find out that .so file is used on android side and .dylib file is used on iOS side. For now I have created a simple test cpp file and able to communicate with flutter via ffi but now struggling to generate .so file for android. I however find the way to get dylib already inside build/lib folder . Thanks for help.

**Comment by alionteo** [comment]
`/lib/arm64/libproj.so" is for EM_X86_64 (62) instead of EM_AARCH64` So help plz

**Comment by Pourfex** [comment]
@alionteo Did you manage to build the Dll for iOS and android ? Been searching into the issues and you seemed to have tried it.
