### ISSUE TITLE
SQLite3 dependencies not found error in windows machine

### ISSUE THREAD

**Issue by muhammaduzair-hub** [OSGeo/proj.4#3664]
I have Installed Sqlite3 and **sqlite3 --version** working fine, but when i try to build the proj 9.2.0 using **cmake ..**  i got error

CMake Error at CMakeLists.txt:181 (message):
  sqlite3 dependency not found!

I have tried many ways, one of these is

- add path of sqlite3 in CMAKElists.txt before the 181 line.

**Comment by rouault** [comment]
Cf https://proj.org/install.html#cmake-configure-options
Set the EXE_SQLITE3, SQLITE3_INCLUDE_DIR and SQLITE3_LIBRARY CMake options

**Comment by muhammaduzair-hub** [comment]
I am using Linux and have sqlite3 installed. When I do which sqlite3 it gives me /usr/bin/sqlite3. when i run cmake .. it gives me error that sqlite3 dependencies not found. I got to know that there is some way to set custom installation paths for sqlite3 by this way
set(DSQLITE3_INCLUDE_DIR "usr/bin/sqlite3")
set(DSQLITE3_LIBRARY "usr/bin/sqlite3")

but this again does not work and same error, please guide what should be path values according to my installation path. Thanks

**Comment by mwtoews** [comment]
You don't need to modify any files; just specify these options as a command-line, e.g. `cmake -D<var>=<value>`. Normally this is done in a clean subdirectory, and be aware to clear any CMakeCache.txt files. Discovery of sqlite3 runtime executable, library and development headers on Windows vs Linux are different, so I'm not sure how it is the same error.
