### ISSUE TITLE
Possible to access the topocentric transformation ?

### ISSUE THREAD

**Issue by stefangachter** [OSGeo/proj.4#3666]
Dear all,
I am converting cartesian geographic coordinates to topocentric ones as described here
https://proj.org/operations/conversions/topocentric.html
I have not only positions but also velocities to convert including the associated uncertainty covariances.
Converting the velocities could be done the same way as positions. But I am not aware if the covariances could be converted with proj.
However, if I can access the translation vector and rotation matrix of the geographic to topocentric conversion, then I could do it "manually".
Is it possible to access the transformation, e.g. as 4x4 isomorph transformation matrix? Or, any suggestion on how to convert "uncertainties" with proj?

**Comment by stefangachter** [comment]
Following the instructions here https://epsg.io/9836-method and comparing with the implementation here https://github.com/OSGeo/PROJ/blob/master/src/conversions/topocentric.cpp I came up with the following "reversed engineered" solution:

```
import numpy as np
import pyproj
    
Xo = 3652755.3058
Yo = 319574.6799
Zo = 5201547.3536

trnsf = pyproj.transformer.Transformer.from_pipeline("proj=pipeline step inv proj=cart ellps=WGS84")
Lo, Po, h = trnsf.transform(Xo, Yo, Zo, radians=True)

X = 3771793.968
Y = 140253.342
Z = 5124304.349

U = -(X-Xo)*np.sin(Lo) + (Y-Yo)*np.cos(Lo)
V = -(X-Xo)*np.sin(Po)*np.cos(Lo) - (Y-Yo)*np.sin(Po)*np.sin(Lo) + (Z-Zo)*np.cos(Po)
W =  (X-Xo)*np.cos(Po)*np.cos(Lo) + (Y-Yo)*np.cos(Po)*np.sin(Lo) + (Z-Zo)*np.sin(Po)

```
This results in the same coordinates as in the referenced example. Thus, I can derive the transformation matrix herewith. Would there be a more elegant solution?

**Comment by kbevers** [comment]
> Is it possible to access the transformation, e.g. as 4x4 isomorph transformation matrix? Or, any suggestion on how to convert "uncertainties" with proj?

Unfortunately not. It is a bit out of scope for PROJ, I think.

**Comment by stefangachter** [comment]
Thanks for the feedback. Yes, it is a bit out of socpe. Would have been a "nice to have" for me.

**Comment by otofoto** [comment]
Other definitions
The following syntax may be used to define local East-North-Up (ENU) systems: ENU:LAT,LON (for instance ENU:41.57231,2.26157).
