### ISSUE TITLE
Sudo Make Installation Stucks

### ISSUE THREAD

**Issue by 0xCakin** [OSGeo/proj.4#3669]
I am trying to setup GDAL in AWS Linux 2 which requires PROJ. I keep stucking `sudo make` step. 

See the ref doc here: [Installing GDAL 3.2.1 on Amazon Linux 2](https://gist.github.com/abelcallejo/e75eb93d73db6f163b076d0232fc7d7e#2-installation-of-proj)

Screenshot below.
![image](https://user-images.githubusercontent.com/35246326/226150884-633ada28-7865-45a6-9a2e-729b682a3745.png)

**Comment by rouault** [comment]
we no longer support those older versions. My assumption is that your AWS machine has not enough RAM to compile coordinateoperation.cpp.  the file was split in smaller parts in later versoins
