### ISSUE TITLE
Issue Sqlite3 binary not found

### ISSUE THREAD

**Issue by alionteo** [OSGeo/proj.4#3670]
I am using linux and have sqlite3 installed. When i do which sqlite3 it gives me /usr/bin/sqlite3. when i run cmake .. it gives me error that sqlite3 binary not found. I got to know that there is some way to set custom installation paths for sqlite3 by this way
set(DSQLITE3_INCLUDE_DIR "usr/bin/sqlite3")
set(DSQLITE3_LIBRARY "usr/bin/sqlite3")

but this again does not work and same error, please guide what should be path values according to my installation path. Thanks

**Comment by jjimenezshaw** [comment]
Do you have the dev package installed? `sudo apt-get install libsqlite3-dev` (or however it is in your distro)

**Comment by alionteo** [comment]
yes I do have installed it and when i try to run it again it gives me this message, libsqite3-dev is already the newest version 3.37.2-2ubuntu0.1

**Comment by rouault** [comment]
you need to install both ``sqlite3`` and ``libsqlite3-dev`` packages.  And don't define SQLITE3_INCLUDE_DIR  and SQLITE3_LIBRARY as your above values are wrong. And remove the existing CMakeCache.txt

**Comment by alionteo** [comment]
I did both of them and still issue is there `sqlite3 dependency not found`
