### ISSUE TITLE
.so is for EM_X86_64 instead of EM_AARCH64 android cmake

### ISSUE THREAD

**Issue by alionteo** [OSGeo/proj.4#3671]
Hi, I have generated .so files under /lib when trying to use for android it give me error

.so is for EM_X86_64 instead of EM_AARCH64 android cmake

While android support these architectures 

arm64-v8a , armeabi-v7a , x86 , x86_64 

The question is how many i define/declare these above architectures in Cmake to build respective .so files. Thanks

**Comment by rouault** [comment]
> The question is how many i define/declare these above architectures in Cmake to build respective .so files

That's not a PROJ specific issue. You need to teach yourself with generic CMake documentation. You may find some inspiration in https://github.com/OSGeo/gdal/blob/master/.github/workflows/android_cmake/start.sh , but take it with a grain of salt as I'm not an expert in CMake cross-compilation topics.
