### ISSUE TITLE
build failure under centos7 

### ISSUE THREAD

**Issue by sendreams** [OSGeo/proj.4#3680]
gcc version: 
> [root@SERVER-GIS2-CENTOS build]# gcc --version
gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

centos version: 
> [root@SERVER-GIS2-CENTOS build]# cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)

cmake version:
> [root@SERVER-GIS2-CENTOS build]# cmake3 --version
cmake3 version 3.17.5

CMake suite maintained and supported by Kitware (kitware.com/cmake).

build step: 

> mkdir build
cd build
cmake3 .. -DSQLITE3_INCLUDE_DIR=/usr/include -DSQLITE3_LIBRARY=/usr/lib64/libsqlite3.so -DENABLE_CURL=OFF -DENABLE_TIFF=OFF -DBUILD_PROJSYNC=OFF -DBUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS="-lpthread" -DBUILD_CCT=OFF -DBUILD_CS2CS=OFF -DBUILD_GEOD=OFF -DBUILD_GIE=OFF -DBUILD_PROJ=OFF -DCMAKE_C_FLAGS=-fPIC -DCMAKE_CXX_FLAGS=-fPIC

errors:

> Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /root/apps/proj-9.2.0/build/CMakeFiles/CMakeTmp
Run Build Command(s):/opt/rh/devtoolset-7/root/usr/bin/gmake cmTC_9001d/fast && /opt/rh/devtoolset-7/root/usr/bin/gmake  -f CMakeFiles/cmTC_9001d.dir/build.make CMakeFiles/cmTC_9001d.dir/build
gmake[1]: 进入目录“/root/apps/proj-9.2.0/build/CMakeFiles/CMakeTmp”
Building C object CMakeFiles/cmTC_9001d.dir/src.c.o
/opt/rh/devtoolset-7/root/usr/bin/gcc   -lpthread -DCMAKE_HAVE_LIBC_PTHREAD   -std=c99 -o CMakeFiles/cmTC_9001d.dir/src.c.o   -c /root/apps/proj-9.2.0/build/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_9001d
/usr/bin/cmake3 -E cmake_link_script CMakeFiles/cmTC_9001d.dir/link.txt --verbose=1
/opt/rh/devtoolset-7/root/usr/bin/gcc -lpthread -DCMAKE_HAVE_LIBC_PTHREAD    CMakeFiles/cmTC_9001d.dir/src.c.o  -o cmTC_9001d 
CMakeFiles/cmTC_9001d.dir/src.c.o：在函数‘main’中：
src.c:(.text+0x6a)：对‘pthread_atfork’未定义的引用
collect2: error: ld returned 1 exit status
gmake[1]: *** [CMakeFiles/cmTC_9001d.dir/build.make:107：cmTC_9001d] 错误 1
gmake[1]: 离开目录“/root/apps/proj-9.2.0/build/CMakeFiles/CMakeTmp”
gmake: *** [Makefile:141：cmTC_9001d/fast] 错误 2
Source file was:
#include <pthread.h>
void* test_func(void* data)
{
  return data;
}
int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_cancel(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);
  return 0;
}
Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /root/apps/proj-9.2.0/build/CMakeFiles/CMakeTmp
Run Build Command(s):/opt/rh/devtoolset-7/root/usr/bin/gmake cmTC_4a9f8/fast && /opt/rh/devtoolset-7/root/usr/bin/gmake  -f CMakeFiles/cmTC_4a9f8.dir/build.make CMakeFiles/cmTC_4a9f8.dir/build
gmake[1]: 进入目录“/root/apps/proj-9.2.0/build/CMakeFiles/CMakeTmp”
Building C object CMakeFiles/cmTC_4a9f8.dir/CheckFunctionExists.c.o
/opt/rh/devtoolset-7/root/usr/bin/gcc   -lpthread -DCHECK_FUNCTION_EXISTS=pthread_create   -std=c99 -o CMakeFiles/cmTC_4a9f8.dir/CheckFunctionExists.c.o   -c /usr/share/cmake3/Modules/CheckFunctionExists.c
Linking C executable cmTC_4a9f8
/usr/bin/cmake3 -E cmake_link_script CMakeFiles/cmTC_4a9f8.dir/link.txt --verbose=1
/opt/rh/devtoolset-7/root/usr/bin/gcc -lpthread -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_4a9f8.dir/CheckFunctionExists.c.o  -o cmTC_4a9f8  -lpthreads 
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: 找不到 -lpthreads
collect2: error: ld returned 1 exit status
gmake[1]: *** [CMakeFiles/cmTC_4a9f8.dir/build.make:107：cmTC_4a9f8] 错误 1
gmake[1]: 离开目录“/root/apps/proj-9.2.0/build/CMakeFiles/CMakeTmp”
gmake: *** [Makefile:141：cmTC_4a9f8/fast] 错误 2

**Comment by rouault** [comment]
I strongly suspect something weird / incorrect with your build environment.
https://stackoverflow.com/questions/64514666/what-does-performing-test-cmake-have-libc-pthread-failed-actually-mean suggests that CMAKE_HAVE_LIBC_PTHREAD related failures come from find_package(Threads) which we do use in src/lib_proj.cmake
Perhaps something wrong with the CMake version you use
Closing as likely not a PROJ bug

**Comment by sendreams** [comment]
@rouault 
thanks. i use the latest cmake, and it's ok.
