### ISSUE TITLE
Derived VCRS with -EPSG code for Horizontal CRS- in PROJJSON

### ISSUE THREAD

**Issue by jjimenezshaw** [OSGeo/proj.4#3689]
#### Problem description
Converting in C++ a CRS into PROJJSON I am getting an exception. The problem is that I am using the conversion `Vertical Offset and Slope`, `EPSG:1046`, that has the parameter `EPSG code for Horizontal CRS`, `EPSG:1037`
https://epsg.org/coord-operation-method_1046/Vertical-Offset-and-Slope.html
I am using the value `6318`, as an integer (I assume that it is an integer).

The exception is thrown in this point:
```c++
UnitOfMeasure JSONParser::getUnit(const json &j, const char *key) {
    if (!j.contains(key)) {
        throw ParsingException(std::string("Missing \"") + key + "\" key");
    }
```
And it is the case, that parameter (measure?) does not have unit. But must every parameter have a unit? Is every parameter a "measure"?

Looking that the json squema, I understand that unit is not mandatory in a parameter, but maybe I misunderstood it.

The output in PROJJSON and WKT2 are these (only two parameters added to make it smaller)

```json
{
  "$schema": "https://proj.org/schemas/v0.7/projjson.schema.json",
  "type": "DerivedVerticalCRS",
  "name": "Derived vertCRS",
  "base_crs": {
    "type": "VerticalCRS",
    "name": "ODN height",
    "datum": {
      "type": "VerticalReferenceFrame",
      "name": "Ordnance Datum Newlyn"
    },
    "coordinate_system": {
      "subtype": "vertical",
      "axis": [
        {
          "name": "Gravity-related height",
          "abbreviation": "H",
          "direction": "up",
          "unit": "metre"
        }
      ]
    },
    "id": {
      "authority": "EPSG",
      "code": 5701
    }
  },
  "conversion": {
    "name": "Conv Vertical Offset and Slope",
    "method": {
      "name": "Vertical Offset and Slope",
      "id": {
        "authority": "EPSG",
        "code": 1046
      }
    },
    "parameters": [
      {
        "name": "Ordinate 1 of evaluation point",
        "value": 40.5,
        "unit": "degree",
        "id": {
          "authority": "EPSG",
          "code": 8617
        }
      },
      {
        "name": "EPSG code for Horizontal CRS",
        "id": {
          "authority": "EPSG",
          "code": 1037
        }
      }
    ]
  },
  "coordinate_system": {
    "subtype": "vertical",
    "axis": [
      {
        "name": "Gravity-related height",
        "abbreviation": "H",
        "direction": "up",
        "unit": "metre"
      }
    ]
  }
}
```
```
VERTCRS["Derived vertCRS",
    BASEVERTCRS["ODN height",
        VDATUM["Ordnance Datum Newlyn",
            ID["EPSG",5101]]],
    DERIVINGCONVERSION["Conv Vertical Offset and Slope",
        METHOD["Vertical Offset and Slope",
            ID["EPSG",1046]],
        PARAMETER["Ordinate 1 of evaluation point",40.5,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8617]],
        PARAMETER["EPSG code for Horizontal CRS",6318,
            ID["EPSG",1037]]],
    CS[vertical,1],
        AXIS["gravity-related height (H)",up,
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]]
```

The value of the problematic parameter is missing. After patching the function
```c++
    void OperationParameterValue::_exportToJSON(
...
    } else if (l_value->type() == ParameterValue::Type::INTEGER) {
        writer->AddObjKey("value");
        writer->Add(l_value->integerValue());
```

The value now appears in the JSON
```json
      {
        "name": "EPSG code for Horizontal CRS",
        "value": 6318,
        "id": {
          "authority": "EPSG",
          "code": 1037
        }
      }
```

However, the exception of missing unit key is still thrown when the projjson is read.

I have seen a function `dealWithEPSGCodeForInterpolationCRSParameter`, that makes me think that this parameter is already problematic.

I was preparing a PR to fix it... but I do not know how to fix it really. Do I simply remove the need of a unit when parsing the Json?
All the parameters of the conversion are considered "measures", and this is not the case.

Should I make more detailed the management of the values in
```c++
ConversionNNPtr JSONParser::buildConversion(const json &j)
...
values.emplace_back(ParameterValue::create(getMeasure(param)));
```

This is the unit test I am using to see some outputs and throw the exception (I will adapt finally in the PR)
```c++
TEST(crs, derivedVerticalCRS_projjson) {
    auto epsgProp = [] (const std::string& name, int code) {
        return PropertyMap().set(Identifier::CODESPACE_KEY, "EPSG")
            .set(Identifier::CODE_KEY, code)
            .set(IdentifiedObject::NAME_KEY, name);
    };

    std::vector<OperationParameterNNPtr> operationParameters;
    std::vector<ParameterValueNNPtr> parameterValues;

    operationParameters.push_back(OperationParameter::create(epsgProp("Ordinate 1 of evaluation point", 8617)));
    parameterValues.push_back(ParameterValue::create(Measure(40.5, UnitOfMeasure::DEGREE)));
    operationParameters.push_back(OperationParameter::create(epsgProp("EPSG code for Horizontal CRS", 1037)));
    parameterValues.push_back(ParameterValue::create(6318));


    auto derivingConversion = Conversion::create(
        PropertyMap().set(IdentifiedObject::NAME_KEY, "Conv Vertical Offset and Slope"),
        epsgProp("Vertical Offset and Slope", 1046),
        operationParameters,
        parameterValues);

    auto vert =  DerivedVerticalCRS::create(
        PropertyMap().set(IdentifiedObject::NAME_KEY, "Derived vertCRS"),
        createVerticalCRS(), derivingConversion,
        VerticalCS::createGravityRelatedHeight(UnitOfMeasure::METRE));

    auto formatter = JSONFormatter::create();
    formatter->setMultiLine(true);
    auto json = vert->exportToJSON(formatter.get());
    std::cout << json << std::endl;

    auto formatterWkt2 = WKTFormatter::create();
    formatterWkt2->setMultiLine(true);
    auto wkt2 = vert->exportToWKT(formatterWkt2.get());
    std::cout << wkt2 << std::endl;

    auto dbContext = DatabaseContext::create();
    auto fromWkt2 = createFromUserInput(wkt2, dbContext);
    auto fromJson = createFromUserInput(json, dbContext);
}
```

Fun fact:
If I use the wkt2 above, call createFromUserInput and export as projjson, that parameter appears as
```json
      {
        "name": "EPSG code for Horizontal CRS",
        "value": 6318,
        "unit": {
          "type": "Unit",
          "name": "",
          "conversion_factor": 1
        },
        "id": {
          "authority": "EPSG",
          "code": 1037
        }
      }
```
Should I just create that parameter as a measure with units, and forget about this? That projjson does not throw on import.

#### Expected Output
Not throw an exception

#### Environment Information
 - PROJ version (`proj`): master
 - Operation System Information: Ubuntu 22.04

#### Installation method
 - from source

**Comment by jjimenezshaw** [comment]
I decided to do this:
```c++
        if (param.contains("unit")) {
            values.emplace_back(ParameterValue::create(getMeasure(param)));
        } else {
            const int value = static_cast<int>(getNumber(param, "value"));
            values.emplace_back(ParameterValue::create(value));
        }
```
~PR coming soon~.

**Comment by jjimenezshaw** [comment]
After researching more the code I see that WKT2 parser is expecting a measure, not an integer.
In particular the method `dealWithEPSGCodeForInterpolationCRSParameter`.
To be consistent the change should be something like:
```c++
        if (param.contains("unit")) {
            values.emplace_back(ParameterValue::create(getMeasure(param)));
        } else {
            const auto measure = Measure(getNumber(param, "value"));
            values.emplace_back(ParameterValue::create(measure));
        }
```
There is an easy workaround for the C++ user: define the parameter as a Measure, and not as an integer.
```c++
parameterValues.push_back(ParameterValue::create(Measure(6318)));
```
Taking into account that `dealWithEPSGCodeForInterpolationCRSParameter` is not called from the JSONParser, that makes the fix not very useful. 
The scope of the fix would go beyond the initial intention, that was just fixing the json (de)serialization.

**Comment by rouault** [comment]
You indeed spotted the critical places to change. I'v also make the choice of stripping the rather hacky "EPSG code for Horizontal CRS" parameter on import to set it as an interpolationCRS, which is IMHO the cleanest representation for it (otherwise the createOperations() logic would ignore it if just set as a parameter), and add-it back on export. Should be fixed per https://github.com/OSGeo/PROJ/pull/3695

Note: EPSG:6318 (NAD83(2011)) as an interpolation CRS for a UK vertical CRS seems suspicious...

**Comment by jjimenezshaw** [comment]
> Note: EPSG:6318 (NAD83(2011)) as an interpolation CRS for a UK vertical CRS seems suspicious...

EPSG:6318 was the one in my code where I found that something was failing. When I started the unit test I took `createVerticalCRS()` for simplification, without looking at the real CRS created. When I realized that (with the issue already created) I moved to EPSG:4258, but didn't change the issue.

**Comment by jjimenezshaw** [comment]
> You indeed spotted the critical places to change.

Thanks for the PR @rouault . I spotted _some_ of the critical places. Your solution it more complete than I was thinking on today.
