### ISSUE TITLE
Difference in Z result of ST_Transform (PROJ 6.0.0 vs V6.1.1) 

### ISSUE THREAD

**Issue by paoloromani** [OSGeo/proj.4#3702]
Query:
```
with geom as (
	select st_transform(
		st_geometryfromtext(
			'POINT Z(114.19515060316667 22.3979100265 81.8574198829997)',4326) ,2326)as a)
select st_x(a),st_y(a),st_z(a) from geom;
```

**First server**: (Z transformed    81.8574198829997->84.71958220563829)
Google Cloud SQL
"POSTGIS=""3.1.4 3.1.4"" [EXTENSION] PGSQL=""140"" GEOS=""3.5.0-CAPI-1.9.0 4392"" PROJ=""Rel. 6.0.0, March 1st, 2019"" LIBXML=""2.9.10"" LIBJSON=""0.15"" LIBPROTOBUF=""1.4.0"""

Result:
st_x                                  st_y                                  st_z
838149.9363960824	828737.9267898238	84.71958220563829

**Second server**: (Z not transformed    81.8574198829997->81.8574198829997)
Google Cloud SQL
"POSTGIS=""3.0.3 r3.0.3"" [EXTENSION] PGSQL=""130"" GEOS=""3.5.0-CAPI-1.9.0 4392"" PROJ=""6.1.1"" LIBXML=""2.9.4"" LIBJSON=""0.15"" LIBPROTOBUF=""1.4.1"" (core procs from ""3.0.0 r0"" need upgrade)"

Result:
st_x                                  st_y                                  st_z
838149.9363960418	828737.9267898289	81.8574198829997

The answer from the first server is correct for our job.
What can be done?

Thanks

**Comment by rouault** [comment]
Those PROJ 6.x versions are no longer supported. The currently supported version is 9.2
