### ISSUE TITLE
proj_context_set_autoclose_database() deprecation causes side effects without possible workaround

### ISSUE THREAD

**Issue by AlbanBERGERET-Epic** [OSGeo/proj.4#3709]
I recently upgraded a project from PROJ 7.2 to PROJ 9.1.1

Unfortunately, the way my application works requires that multiple processes are able to open the proj.db file at the same time. 
In the past, all was running fine, because the database context was closed with that proj_context_set_autoclose_database option, and no file handle was kept. 

After some debugging, I figured out that it's because this function doesn't do anything anymore in 9.1.1
Fine, and I understand the reason. 

However, there is no way to work around and close the connection manually. The cpp_context->closeDb(); is not exposed in the public API. 

If I understand it right, it should be closed when we destroy the context with proj_context_destroy, but for performance reasons, I keep a reference to a Projection (PJ*) to be reused several times, and I guess destroying the context will invalidate it. 

So ideally, can we expose a manual CloseDb for a context that would release the handle? 
It could be reopened during the next call to a proj_create_crs_to_crs.

**Comment by rouault** [comment]
> Unfortunately, the way my application works requires that multiple processes are able to open the proj.db file at the same time.

Why would you need to have to close the database to have multiple processes opening proj.db at the same time ?

**Comment by AlbanBERGERET-Epic** [comment]
To release the file handle. 
The file seems to be opened for writing, and two processes can't open it at the same time. In the past, closing the DB released the handle.

**Comment by rouault** [comment]
> The file seems to be opened for writing,

can you demonstrate that ? on which operating system ?
The file is opened in read-only:
https://github.com/OSGeo/PROJ/blob/700721eeafd239112f289bba12d08fc8844c376d/src/iso19111/factory.cpp#L334

**Comment by AlbanBERGERET-Epic** [comment]
Actually, I did some further analysis and this is a little bit more complicated. 

Our program (Unreal Engine) uses a version of SQlite with a file HAL to support several platforms. And that's it which created a Write file lock because even if we are interested in reading only, nothing guarantees that another process won't do edits on the database. 

It was not a problem until the deprecation of proj_context_set_autoclose_database(). 

I could reintroduce the former behavior with a local patch, but I was wondering why this has been deprecated. When not enabled by the end user, it makes no difference with the last behavior, so why removing the option to choose?

**Comment by rouault** [comment]
The rationale for the now no-op implementation of proj_context_set_autoclose_database() (and why it was initially implemented) is in https://github.com/OSGeo/PROJ/pull/2738. and it was initially implemented in https://github.com/OSGeo/PROJ/issues/1565 because in highly multi-theaded implementations, the initial implementation of 1 sqlite handle per PROJ_CONTEXT would blow the number of file descriptors opened
Re-introducing a autoclose mechanism (or a force close) could be non-trivial due to the now sharing of sqlite handles among PJ_CONTEXT*

**Comment by AlbanBERGERET-Epic** [comment]
Ok, thanks for all the explanations. I understand. 
I'll try to find another workaround. 

You can discard this issue. 
thanks
