### ISSUE TITLE
Skip proj.db generation during build

### ISSUE THREAD

**Issue by AndrewAtAvenza** [OSGeo/proj.4#3710]
I build PROJ for two different Android ABIs and it doesn't make sense to generate the proj.db both times. On my machine, it adds about 2.5 minutes to a 40s build time (per ABI). I was just tinkering with it and it seems like all that would be needed would be to add `option(GENERATE_PROJ_DB "Generate proj.db ON)` and wrap the EXE_SQLITE3 check & the `add_subdirectory(data)` with an if-statement based on `GENERATE_PROJ_DB`. I don't _think_ there's more to it than that, but someone better versed in this than I may see more complexity.

**Comment by dg0yt** [comment]
If you don't run CI for PROJ development (PROJ changes), shouldn't you just cache all artifacts between CI runs if build time is an issue?
At least you can put an existing proj.db into the build directory (or just `touch` the file path) between configure and make.

**Comment by AndrewAtAvenza** [comment]
We build PROJ as part of our build process because we build all our dependencies from source. Obviously it's possible to use pre-built binaries, but we prefer to have everything built as source. Truth be told, if we build the app in preparation for submission to one of the government clients we're _required_ to build everything from source for security reasons.

Anyways, it's not a huge deal, just felt like an easy addition for people who know what they're doing -- certainly it should be building proj.db by default. If there's resistance or no interest, I'll just add it manually when I update PROJ in the future.

**Comment by mwtoews** [comment]
In the old Autotools setup, there was a `PROJ_DB_CACHE_DIR` variable implemented [here](https://github.com/OSGeo/PROJ/blob/8.2/data/Makefile.am#L149-L174) (from #1446). This was lost during the CMake transition for 9.0 (as noted in #2688). Would a similar mechanism be of use?

**Comment by AndrewAtAvenza** [comment]
I'm terrible at reading scripts, but I think I can grasp the basics: basically, if you specify `PROJ_DB_CACHE_DIR` and that location exists, and it contains a proj.db, and the md5s of the source SQL match, then it skips generating the proj.db and copies that instead?

Yes, I think that would work too.

**Comment by dg0yt** [comment]
I didn't say you should use pre-built binaries. You could cache what you build from source, and you can still do a full rebuild for releases.

**Comment by AndrewAtAvenza** [comment]
My apologies then, I clearly misunderstood! I'm not sure I follow though? I'm talking about the full rebuild on release on my build machine -- that's where I'm looking to save the time on not re-generating proj.db.

I think the PROJ_DB_CACHE_DIR is superior to my original suggestion because it lets you do what I'd like to do and frankly easier. So maybe this issue is now a request to bring back PROJ_DB_CACHE_DIR? 😄
