### ISSUE TITLE
proj +proj=ortho (and some other projections) doesn't work

### ISSUE THREAD

**Issue by joa-quim** [OSGeo/proj.4#3719]
```
echo 100 76.47 | proj +proj=ortho
*       *

echo 76.47 100 | proj +proj=ortho
ortho: Invalid latitude
*       *
```

but longitudes < 90. do not error
```
echo 89 76.47 | proj +proj=ortho
1496709.43      6179197.30
```
Though I can't reproduce that result with GMT
```
echo 89 76.47 | mapproject -Jg0/0/1:1 -C -F -R85/95/0/80
1490298.55291   6194196.15712
```

Airy doesn't work either
```
echo 100 76.47 | proj +proj=airy
*       *
```

```
proj --version
Rel. 9.3.0, September 1st, 2023
(in fact, a master build)
```

**Comment by rouault** [comment]
Look at the drawing at https://proj.org/operations/projections/ortho.html. The orthographic projection can only map one hemisphere at a time.

cf
```
$ echo 100 76.47 | PROJ_DEBUG=3 bin/proj +proj=ortho
pj_open_lib(proj.ini): call fopen(/home/even/proj/install-proj-master/share/proj/proj.ini) - succeeded
pj_open_lib(proj.db): call fopen(/home/even/proj/install-proj-master/share/proj/proj.db) - succeeded
ortho: pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
ortho: pj_ellipsoid - final:    ellps=GRS80
ortho: Coordinate (100.000, 76.470) is on the unprojected hemisphere
*	*
```

**Comment by joa-quim** [comment]
Did not know that. And it means that I'm more or less screwed in using *ortho, airy* and some others from the Julia wrapper. Now I see where this error is coming from
```
julia> cl = coastlinesproj(proj="ortho");
┌ Warning: gdalvectortranslate returned a NULL pointer.
└ @ GMT.Gdal C:\Users\j\.julia\dev\GMT\src\gdal_tools.jl:13
```

Most projections work fine though. See example at https://forum.generic-mapping-tools.org/t/project-with-proj-and-plot-with-gmt/3724/4?u=joaquim

BTW, on Windows
```
echo 100 75 | PROJ_DEBUG=3 proj +proj=ortho +lon_0=90
'PROJ_DEBUG' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by joa-quim** [comment]
Sorry to continue this, but why does ``airy`` fails? (on linux now)
```
echo 100 75 | PROJ_DEBUG=3 proj +proj=airy
pj_open_lib(proj.db): call fopen(/usr/share/proj/proj.db) - succeeded
pj_open_lib(proj.ini): call fopen(/usr/share/proj/proj.ini) - succeeded
airy: pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
airy: pj_ellipsoid - final:    ellps=GRS80
*       *
```

**Comment by rouault** [comment]
> Sorry to continue this, but why does `airy` fails? (on linux now)

RTF(antastic)M: https://proj.org/operations/projections/airy.html

**Comment by joa-quim** [comment]
If they are to be ignored, they should be ignored silently by default. The way it is the GMT.jl julia wrapper (and other julia wrappers) error for all points, not only those *hidden on the other side*.
