### ISSUE TITLE
patch for data/CMakeLists.txt

### ISSUE THREAD

**Issue by nadyawilliams** [OSGeo/proj.4#3742]
#### Example of problem
When building proj from source  I need to configure with one prefix but do install with another. This is to ensure that configuration uses correct final paths settings but the install goes into a  "sandbox" as  it  is used for  a creation of an RPM. 
All works fine as expected  (our build system handles all spec files , etc). The only issue is the files that are generated during build in data/ are not getting installed where expected.  Here are the details:

```bash
#  configure and make, $APATH is set to needed path
mkdir builddir
cd builddir
cmake -DCMAKE_INSTALL_PREFIX=$APATH -DCMAKE_BUILD_TYPE=Release ..
make -j 8
# install, here $(ROOT) designates an additional path prefix, set in the environment 
cmake -DCMAKE_INSTALL_PREFIX=$(ROOT)/$APATH -P cmake_install.cmake
```
#### Problem description
All  files generated by build  (but those from data/) are installed as expected in `$(ROOT)/$APATH`.
However all files from data/ are getting installed in `$APATH` instead of `$(ROOT)/$PATH`

#### Expected Output
Files generated in  data/ (per data/CMakeLists.txt) need to be installed in `$(ROOT)/$APATH`

#### Environment Information
 - PROJ version 9.1.1
 - cmake 3.22.1
 - Operation System Information: Rocky 8.7

#### Installation method
From source using cmake
 
#### A simple patch fixes this issue
```bash  
--- PROJ-9.1.1/data/CMakeLists.txt	2022-12-01 01:51:00.000000000 -0800
+++ PROJ-9.1.1/data/CMakeLists.txt.new	2023-05-24 13:37:33.855510748 -0700
@@ -101,5 +101,5 @@
 )
 install(
   FILES ${ALL_DATA_FILE}
-  DESTINATION ${PROJ_DATA_PATH}
+  DESTINATION ${CMAKE_INSTALL_DATADIR}/proj
```

Here `${CMAKE_INSTALL_DATADIR}` is translated properly by cmake into `$APATH/share/`.
The `${PROJ_DATA_PATH}`  is defined  in the top level CMakeLists.txt as `set(PROJ_DATA_PATH "${CMAKE_INSTALL_FULL_DATADIR}/proj")` does not work.

**Comment by rouault** [comment]
I'm not a big fan of this. Basically if you change the value of CMAKE_INSTALL_PREFIX, you need to remove the CMakeCache.txt file.
You could potentially also use "make DESTDIR=${ROOT}" as a likely cleaner way of doing what you want . Cf https://cmake.org/cmake/help/latest/envvar/DESTDIR.html

**Comment by hobu** [comment]
DESTDIR is the way to do this, and it is what system packagers are hopefully using to manage their install prefixes differently than their configuration prefixes. There is no bug here and no development specifically needed by the PROJ project to support this.

**Comment by nadyawilliams** [comment]
> I'm not a big fan of this. Basically if you change the value of CMAKE_INSTALL_PREFIX, you need to remove the CMakeCache.txt file.
just doing a clean install removes any build files. This is why the build is in a separate directory anyway. Removing a cache file   is not a problem.

> You could potentially also use "make DESTDIR=${ROOT}" as a likely cleaner way of doing what you want . Cf https://cmake.org/cmake/help/latest/envvar/DESTDIR.html

I agree that "make DESTDIR=${ROOT}" is an appropriate way to  deal with install prefix  change but this is for autotools configure (and we use it all the time when building with  those tools).

Here I am trying to use the cmake provided concepts for both build and install.  Both commands as i outlined  above are standard and work for many other software packages without any issues.   

The setting for PROJ_DATA_PATH in top level CMakeLists.txt or in data/CMakeLists.txt does not handle  specifying additional prefix for install as it should. By comparison, your  man/CMakeLists.txt does this perfectly.

**Comment by mwtoews** [comment]
@nadyawilliams FYI your suggested patch was applied with #4843 targeted for PROJ 9.9.
