### ISSUE TITLE
Norwegian CD above ellipsoid grid file is outdated

### ISSUE THREAD

**Issue by eriksorngard** [OSGeo/proj.4#3745]
Latest PROJ data package (1.14) does not include the current version of the Norwegian "CD above ellipsoid" grid file. The supplied version is v2021a, but current version is v2023a.

**Comment by rouault** [comment]
CC @himsve

**Comment by himsve** [comment]
I have done the EPSG registration today and continuing with PROJ-DATA implementation next week.

**Comment by himsve** [comment]
The issue is handled at the PROJ-data branch [chartdatum_norway_v2023a](https://github.com/himsve/PROJ-data/tree/chartdatum_norway_v2023a).

Pull request is set on hold until the EPSG registration is accepted.

**Comment by rouault** [comment]
solved per https://github.com/OSGeo/PROJ/pull/3978
