### ISSUE TITLE
Offer Offline HTML documentation download

### ISSUE THREAD

**Issue by jidanni** [OSGeo/proj.4#3808]
In 
https://github.com/GenericMappingTools/gmt/issues/7597 we see Proj doesn't have a HTML Offline document set. Only PDF...

We also see a way of mentioning a wget way users could use to get an HTML set.

Maybe the Proj website should also mention such a method. Linux distributions can't always be counted on to include docs. And the user might in fact not even have any distribution installed, and just want the HTML documents, for offline perusal in the North Woods.

**Comment by mwtoews** [comment]
There is an option "Zipped HTML" ([docs](https://docs.readthedocs.io/en/stable/downloadable-documentation.html)), which can be added to the configuration.

**Comment by jidanni** [comment]
Also users getting
https://proj.org/en/latest/download.html#current-release
won't be downloading any documentation.

To get any documentation, they need to peek in the Read the Docs link at the bottom of the left panel.

Then they can find the PDF.

So maybe add a reminder there at https://proj.org/en/latest/download.html#current-release .

**Comment by mwtoews** [comment]
The merged PR also describes the offline docs, worded slightly differently for HTML and non-HTML (i.e. PDF) outputs.

**Comment by jidanni** [comment]
https://proj.org/_/downloads/en/9.3/htmlzip/ is the largest single HTML file on earth, maybe.

Sure would be nice to also have a tree available, just like when one reads it online.

Imagine online if it were just one big single index.html...

Surely there is some choice button that could be turned on to produce both the single file, and the tree. Thanks.
