### ISSUE TITLE
Example EPSG_4326_to_32631.cpp for 9.2.2 and 9.1.1 

### ISSUE THREAD

**Issue by davids91** [OSGeo/proj.4#3823]
I am trying to convert coordinates from a geodetic to a cartesian reference system; and found a nexample on just how to do that! Neat! 

Except when I try to compile it with 9.2.1 or 9.1.1 I am unable to because of some inconsistencies between master and theese branches. 

most notably here: 

https://github.com/OSGeo/PROJ/blob/5405125a6544126b86af3f2cee53d954e4eb28b5/include/proj/coordinateoperation.hpp#L154 

I would think this functionality is available for some time now, and an example would be really much appreciated! 
I'd like to convert WGS84 coordinates to EPSG:23700; Or a Europe based cartesian reference system available.

**Comment by kbevers** [comment]
An example of what your are trying to achieve would benefit this issue

**Comment by davids91** [comment]
Sure! Thanks for the tip! I'd like to convert WGS84 coordinates to EPSG:23700; Or a Europe based cartesian system available.
I'll extend the description too

**Comment by kbevers** [comment]
> I'd like to convert WGS84 coordinates to EPSG:23700; Or a Europe based cartesian system available

You can do that using `cs2cs`:

```
echo 46 20 | cs2cs EPSG:4326 EPSG:23700      
723793.67       73264.87 0.00
```

The docs for `cs2cs` includes similar examples, although not using these exact CRS's.

**Comment by davids91** [comment]
yes, but  I'd like to do it with the C++ API

**Comment by kbevers** [comment]
Ah, that's the sort of thing it would be smart to include in the description of your problem ;-)

See the examples at the bottom of https://proj.org/en/9.2/development/quickstart.html. Put the relevant EPSG labels into `proj_crs_to_crs()`.

**Comment by davids91** [comment]
Thanks I was able to get it working!
