### ISSUE TITLE
projinfo transformation from EPSG code

### ISSUE THREAD

**Issue by mwtoews** [OSGeo/proj.4#3829]
Let's take an example transformation [EPSG:9036](https://epsg.org/transformation_9036/index.html) or "IGS05 to IGS08 (1)" from source EPSG:9010 to target EPSG:6934.

Projinfo can query the first and only operation for this transformation object with:

    $ projinfo -s EPSG:9010 -t EPSG:6934

or directly with:

    $ projinfo "IGS05 to IGS08 (1)"

however the EPSG code for the transformation cannot be used for the "object_definition":

    $ projinfo EPSG:9036
    input string: parsing of user string failed: crs not found

Curiously, pyproj's [`Transformer.from_pipeline`](https://pyproj4.github.io/pyproj/stable/api/transformer.html#pyproj.transformer.Transformer.from_pipeline) seems to be able to use either the transformation name or EPSG code:
```python
from pyproj import Transformer

t1 = Transformer.from_pipeline("IGS05 to IGS08 (1)")
t2 = Transformer.from_pipeline("EPSG:9036")
assert t1 == t2
```

**Comment by rouault** [comment]
> however the EPSG code for the transformation cannot be used for the "object_definition":
> 
> ```
> $ projinfo EPSG:9036
> input string: parsing of user string failed: crs not found
> ```

because of the potential clashbetween different kind of objects (CRS and operations) having the same identifier, you need to be explicit when wanting operations:
```
projinfo -k operation EPSG:9036
```
or
```
projinfo urn:ogc:def:coordinateOperation:EPSG::9036
```

**Comment by mwtoews** [comment]
Thanks, I guess i didn't realise that the default [`-k` is `crs`](https://proj.org/en/9.2/apps/projinfo.html#cmdoption-projinfo-k). These more explicit object definitions are much better.
