### ISSUE TITLE
PROJ_DEBUG=ON?

### ISSUE THREAD

**Issue by hobu** [OSGeo/proj.4#3832]
A minor nit, but `PROJ_DEBUG`'s behavior isn't aligned with things like `CPL_DEBUG` for the situation of `PROJ_DEBUG=ON`. Instead, you should set `PROJ_DEBUG=2` to set a verbosity level AND debug output. 

The behavior is fine, but I would like to propose that `PROJ_DEBUG=ON` be accepted and it default to `PROJ_DEBUG=2` verbosity level.

**Comment by rouault** [comment]
i've also stumbled on this quite a few times. adressed in https://github.com/OSGeo/PROJ/pull/3835
