### ISSUE TITLE
missing indication about grids shift that are doesn't exist in the proj path

### ISSUE THREAD

**Issue by aharondavid** [OSGeo/proj.4#3845]
Hi 
proj version: 9.1

steps to reproduced:
1. load the following projection into `proj_create_from_wkt`:
`PROJCS["Tokyo / Japan Plane Rectangular CS XVI",GEOGCS["Tokyo",DATUM["Tokyo",SPHEROID["Bessel 1841",6377397.155,299.1528128,AUTHORITY["EPSG","7004"]],TOWGS84[-146.414,507.337,680.507,0,0,0,0],AUTHORITY["EPSG","6301"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4301"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",26],PARAMETER["central_meridian",124],PARAMETER["scale_factor",0.9999],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","30176"]]
`
2. out_warnings and out_grammar_errors are empty
3. expected result: `out_warnings `will include the missing grid - touhokutaiheiyouoki2011.gsb 
later, using this projection will failed because of missing grid - touhokutaiheiyouoki2011.gsb 
there is no way to know about missing grids in WKT before using it,
also `proj_coordoperation_get_grid_used` doesn't tell any info about that missing grid. 
4. more than that, when exporting this WKT to proj4 by GDAL.OGRSpatialReference.exportToProj4, we get a proj4 that is missing the grid part (`+geoidgrids`):
`+proj=tmerc +lat_0=26 +lon_0=124 +k=0.9999 +x_0=0 +y_0=0 +ellps=bessel +towgs84=-146.414,507.337,680.507,0,0,0,0 +units=m +no_defs`

**Comment by rouault** [comment]
I don't see any bug here:
- EPSG:30176 uses the Tokyo datum.
- touhokutaiheiyouoki2011.gsb is a transformation grid between JGD2000 to JGD2011, so not that datum
- it is not relevant to issue errors about missing grids when loading a WKT, especially when it doesn't mention grids, since grids are only needed when doing coordinate transformations, so not at the time a CRS is instanciated
- with PROJ >= 9.2, if you set the PROJ_ONLY_BEST_DEFAULT environment variable to YES (cf https://proj.org/en/9.2/development/reference/functions.html#c.proj_create_crs_to_crs_from_pj), you can get errors at transformation time, when a grid (that is available in the PROJ-data grids, which is not the case of touhokutaiheiyouoki2011.gsb, is missing)

**Comment by aharondavid** [comment]
Hello @rouault and thank you for your answer.

I am so sorry, the Projection is not as I reported above, here is the right Projection(**but it has the same behave as described above**):
```
PROJCS["JGD2000 / Japan Plane Rectangular CS IX",
    GEOGCS["JGD2000",
        DATUM["Japanese_Geodetic_Datum_2000",
            SPHEROID["GRS 1980",6378137,298.257222101,
                AUTHORITY["EPSG","7019"]],
            TOWGS84[0,0,0,0,0,0,0],
            AUTHORITY["EPSG","6612"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4612"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",36],
    PARAMETER["central_meridian",139.833333333333],
    PARAMETER["scale_factor",0.9999],
    PARAMETER["false_easting",0],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["Easting",EAST],
    AXIS["Northing",NORTH],
    AUTHORITY["EPSG","2451"]]
```
	
As you can see, it use in EPSG 4612 which is use touhokutaiheiyouoki2011.gsb:
```
...UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4612"]],...
```

but, again, exporting that WKT to proj4 doesn't include the that grid in `geoidgrids` and either `proj_coordoperation_get_grid_used` doesn't return that grid.
	
by the way, for unknown reason, `sahepfile `which has include that Projection and then loaded to GDAL, calling to `GDAL.Layer.GetNextFeature` cause to `proj_network_get_header_value_cbk_type` to be called by the PROJ,
that callback is asking for the touhokutaiheiyouoki2011.gsb grid.
Shapefile is attached.
[CenterOffset.zip](https://github.com/OSGeo/PROJ/files/12289926/CenterOffset.zip)
