### ISSUE TITLE
Undefined symbol: _pj_wkt1_error

### ISSUE THREAD

**Issue by Vishios13** [OSGeo/proj.4#3853]
#### Example of problem
Demonstrate the problem you have found, either by using PROJ tools like `cs2cs`, `cct` or `projinfo` **or** add a code snippet that highlights the problem using the PROJ C/C++ API.
A "Minimal, Complete and Verifiable Example" will make it much easier for maintainers to help you:
http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

```c
# Your code here

```
#### Problem description

[this should explain **why** the current behavior is a problem and why the expected output is a better solution.]

#### Environment Information
 - PROJ version (`proj`)
 - Operation System Information

#### Installation method
 - conda, apt-get, from source, etc...

**Comment by rouault** [comment]
Please describe what the problem is following the provided tempate

**Comment by Vishios13** [comment]
i am using this library for my ios project 

after installing the   pod 'proj4-ios', '~> 7.1'


then i am running that project and getting this error

Undefined symbol: _pj_wkt1_error

**Comment by rouault** [comment]
> the pod 'proj4-ios', '~> 7.1'

This binary build of PROJ isn't supported by the team here. Please reach to the maintainer of this pod
