### ISSUE TITLE
adding a vertical CS filters out some valid operations 

### ISSUE THREAD

**Issue by mitjap** [OSGeo/proj.4#3854]
This issue might be loosely similar to https://github.com/OSGeo/PROJ/issues/3837 but I am not sure. 

#### Example of problem

Transforing from PCS to PCS correctly lists 35 operations.
`./projinfo -s EPSG:3912 -t EPSG:3794 --summary --spatial-test intersects`

However if vertical CS is present in any way this is not the case, which I think is not correct. I expect this commands to also list 35 operations.
`./projinfo -s EPSG:3912 -t EPSG:3794 --summary --spatial-test intersects --3d` <- promoted to 3D
`./projinfo -s EPSG:3912 -t EPSG:3794+EPSG:8690 --summary --spatial-test intersects` <- use vertical CS
`./projinfo -s EPSG:3912 -t EPSG:10246 --summary --spatial-test intersects` <- use compound that is equivalent to `EPSG:3794+EPSG:8690`

#### Problem description

I don't think adding a vertical component should change the way horizontal component is transformed in this case. All missing operations are direct transformations from PCS to PCS (`Similarity transformation`). One that are listed in all scenarios are `Coordinate Frame rotation (geog2D domain)`

Note: PROJ 9.2 or later is required, those operation were not included in previous versions.

#### Expected Output
All commands to return list of 35 operations.

#### Environment Information
 - PROJ version 9.2 and latest
 - Fedora

#### Installation method
 - from source

**Comment by rouault** [comment]
ok, I see what you mean. Rather particular/advanced case with PCS<-->PCS transformations...
That said, I believe your commands are unlikely to be what you want:
* ``./projinfo -s EPSG:3912 -t EPSG:3794 --summary --spatial-test intersects --3d``
   --> this creates a ProjectedCRS with ellipsoidal height. Is that really what you want... ? This is extremely uncommon
* ``./projinfo -s EPSG:3912 -t EPSG:3794+EPSG:8690 --summary --spatial-test intersects ``
    --> this will be a 2D-only operation as EPSG:3912 is a 2D CRS. You could add --3d, but same as above case, unlikely to be what you want
* ``/projinfo -s EPSG:3912 -t EPSG:10246 --summary --spatial-test intersects``: same as previous case

**Comment by mitjap** [comment]
Yes this case is particular as our country is (I think) the only one that uses that specific transformation method. I guess that is also the reason why it was not implemented in PROJ until version 9.2. 

- I indeed forgot to add `--3d` to some of my commands.
`./projinfo -s EPSG:3912 -t EPSG:3794+EPSG:8690 --summary --spatial-test intersects --3d`
`./projinfo -s EPSG:3912 -t EPSG:10246 --summary --spatial-test intersects --3d`
which are equivalent and still does not produce expected output.

If I understand your comment correctly it is uncommon to perform transformations between 2D and 3D coordinate reference systems. To address this I have one last version that lists operations for Slovenia's legacy CRS (`EPSG:3912+EPSG:5779`) to its replacment CRS (`EPSG:3794+EPSG:8690`) so we have 3D->3D transformation.

`./projinfo -s EPSG:3912+EPSG:5779 -t EPSG:3794+EPSG:8690 --summary --spatial-test intersects`
which still does not produce expected output.


Like mentioned before there are 24 direct PCS->PCS transformation between `EPSG:3912` and `EPSG:3794` that I expect to be used. Is there a reason that adding a Vertical CRS to this transformation would prevent these direct transformation to be used?

**Comment by rouault** [comment]
> If I understand your comment correctly it is uncommon to perform transformations between 2D and 3D coordinate reference systems.

well, that was not my point, but if you mix 2D and 3D CRS, PROJ will only perform 2D transformations.

My point was that forcing a ProjectedCRS to be a 3D one, and thus with ellipsoidal height, is uncommon / dubious. CompoundCRS with a ProjectedCRS and a VerticalCRS (orthometric altitude), as EPSG:3912+EPSG:5779, are generally what you want to use.

> `./projinfo -s EPSG:3912+EPSG:5779 -t EPSG:3794+EPSG:8690 --summary --spatial-test intersects`

That makes more sense. However for the vertical part, there is no SVS2000 height to SVS2010 height transformation available in the PROJ database (actually the EPSG one), so there's no way for PROJ to propose a geodetic "approved" transformation for such CompoundCRS. At best it will assume that SVS2000 = SVS2010

>  Is there a reason that adding a Vertical CRS to this transformation would prevent these direct transformation to be used?

Ideally no, it is just that this particular use case has to be implemented
