### ISSUE TITLE
+x_0, +y_0, +k_0, +units: document order of operations

### ISSUE THREAD

**Issue by jidanni** [OSGeo/proj.4#3875]
On https://proj.org/en/9.2/usage/projections.html
there needs to be mention of the order of operations.

+x_0, +y_0, +k_0, +units

Say which ones are applied first and which ones are applied after.

Say which ones affect the others, and which are independent.

Say which are always in meters, and which become other units when +units
is used.

We see mention on
https://proj.org/en/9.2/usage/projections.html#false-easting-northing
but it also needs to be mentioned on the individual files like I once
tried to do in #3796.

Here are some of the related files: k_0.rst x_0.rst y_0.rst

And I'm guessing:
Order of operations: +k_0, then +x_0 and +y_0, then +units.

**Comment by rouault** [comment]
implemented in https://github.com/OSGeo/PROJ/pull/3877
