### ISSUE TITLE
Latitude precision differences between 6.3.2 and 9.2

### ISSUE THREAD

**Issue by sainsb** [OSGeo/proj.4#3890]
PLEASE FORGIVE IF DUPLICATE - I SEARCHED I SWEAR ❤️

We have recently upgraded our POSTGIS, GEOS, and PROJ dependencies from:

```
PostGIS 3.1.1
GEOS 3.8.1-CAPI-1.13.3
PROJ 6.3.2
```

to 

```
PostGIS 3.3
GEO 3.11.2-CAPI-1.17.2
PROJ 9.2.0
```

In doing so we have observed changes to the latitudes of stored geometry coordinates in the 11+ decimals range.
example:
before:
POINT(-122.9515534145578 44.86282878772594)
after:
POINT(-122.9515534145578 44.86282878772602)

Any assistance/explanation is appreciated.

**Comment by rouault** [comment]
you need to be much more explicit on your input coordinate, input CRS and output CRS. But yes it is expected that you can get differences depending on the content of the proj.db and grids you have installed

**Comment by sainsb** [comment]
Input Coordinate:
POINT (1364757.3768949211 445790.61352568865)

Input CRS:
https://spatialreference.org/ref/epsg/32026/
```
+proj=lcc +lat_1=44.33333333333334 +lat_2=46 +lat_0=43.66666666666666 +lon_0=-120.5 +x_0=609601.2192024384 +y_0=0 +ellps=clrk66 +towgs84=-8,159,175 +to_meter=0.3048006096012192 +no_defs
```
Output CRS
https://spatialreference.org/ref/epsg/4326/

What would I query in the proj.db?
How would I query the grids I have installed?

many thanks

**Comment by rouault** [comment]
what you can do is compare the output of "projinfo -s EPSG:32026 -t EPSG:4326 --spatial-test intersects" on the PROJ 6.3.2 and PROJ 9.2.0 install, but yes for NAD27 to WGS84 there were definitely new transformations added, so difference in results are expected

**Comment by sainsb** [comment]
We have compared the output of the command `projinfo -s EPSG:32026 -t EPSG:4326 --spatial-test intersects` on both installations. While we see the operations are ordered differently, after adjusting to match order, we do not see _any_ differences in the contents of the transformations themselves.
We did see missing grids in both instances and installed the missing grids in the 6.3 instance and DID NOT notice the coordinate change/adjustment.

Can you please inform us how the transformation is chosen? Is the differing order of operations between the two versions indicative of a new preferred approach? or is the order of operations benign and the transform operation is decided elsewise?

**Comment by sainsb** [comment]
`Update` When I reran this command specifying a bbox and after having loaded in the missing grid files, I definitely see the differences. Mainly the references to different grids.
