### ISSUE TITLE
Don't hardcode Krovak parameters

### ISSUE THREAD

**Issue by jidanni** [OSGeo/proj.4#3907]
We read https://manifold.net/doc/mfd9/krovak_oblique_conformal_conic_projection.htm
and it looks great. But in PROJ's version,
https://proj.org/en/9.3/operations/projections/krovak.html
> The latitude of pseudo standard parallel is hardcoded to 78.5° and the ellipsoid to Bessel.

How unfortunate.

Could these please just be made to be defaults, and not _hardcoded_.

Thus no scripts would be broken, and one could apply the projection to other than just one area of the earth.

Or, mention on the document how to workaround the hardcoding, via https://proj.org/en/9.3/operations/projections/ob_tran.html .

**Comment by rouault** [comment]
closing. No reason to use Krovak besides for former Czechoslovakia (I was told recently that for Czeckia or Slovakia taken seaparately Krovak is actually not optimal)
