### ISSUE TITLE
CMake infinite loop

### ISSUE THREAD

**Issue by Molochnik** [OSGeo/proj.4#3935]
When PROJ is placed to the subdirectory (e,g, `proj-9.3.0`) of the main directory with the main CMake file having the content below the process of building falls into an infinite loop:
```
cmake_minimum_required(VERSION 3.22 FATAL_ERROR)
set(CMAKE_C_COMPILER "/usr/bin/gcc")
set(CMAKE_CXX_COMPILER "/usr/bin/g++")
set(CMAKE_CXX_STANDARD 17)
add_subdirectory(proj-9.3.0)
```
[log.txt](https://github.com/OSGeo/PROJ/files/13197777/log.txt)

**Comment by rouault** [comment]
I could solve the issue by forcing the variable to be set into the CMake cache. Otherwise CMake seems to be confused:
```
set(CMAKE_C_COMPILER "/usr/bin/gcc" CACHE)
set(CMAKE_CXX_COMPILER "/usr/bin/g++" CACHE)
```
