### ISSUE TITLE
undefined reference to `pj_init_plus'

### ISSUE THREAD

**Issue by n1705771** [OSGeo/proj.4#3937]
```c
# Code here
```
#include <proj.h>
...
static void
mobgps_biascalc_init (MobGpsBiasCalc *self)
{
  //Initialize cartographic projections for latlng and Mercator coordinate systems
  if(!(self->pj_merc = pj_init_plus("+proj=merc +units=m +ellps=WGS84 +datum=WGS84"))) {
      g_message("Failed to initialize Mercator CS!");
  }
  if(!(self->pj_latlng = pj_init_plus("+proj=latlong +ellps=WGS84 +datum=WGS84"))) {
      g_message("Failed to initialize Lat Long CS!");
  }
}
...
```

#### Problem description
In my service, we use proj library and call function pj_init_plus, but during build, get error: undefined reference to `pj_init_plus'

#### Expect
pj_init_plus should be found

#### Environment Information
 - PROJ version (9.1.1)
 - Debian 12

#### Installation method
 - apt-get, from source

**Comment by rouault** [comment]
pj_init_plus() was in the legacy proj_api.h file that was removed in PROJ 8 : https://proj.org/en/9.3/news.html#id333
You need to migrate your code base to using proj.h functions. Sompe hints at https://proj.org/en/9.3/development/migration.html
