### ISSUE TITLE
GeoidGrids filename with spaces not accepted on windows

### ISSUE THREAD

**Issue by richy46** [OSGeo/proj.4#3942]
Using windows, binary downloaded from gisinternals.com. Version 3.7.1 GDAL (release-1928-x64-gdal-3-7-1-mapserver-8-0-1.zip).

When I use a file path for geoidgrids with a space in it the cs2cs program fails. 

For reference I used folder without spaces first.

`C:\GDAL\bin>cs2cs +proj=latlong +datum=WGS84  +to +ellps=WGS84 +geoid_crs=horizontal_crs +geoidgrids="C:\temp\dirnospace\egm96_15.gtx" +proj=longlat +towgs84=0,0,0 +type=crs
`
0.00    0.00 -17.16

This works ok

Then with spaces:

```
C:\GDAL\bin>cs2cs +proj=latlong +datum=WGS84  +to +ellps=WGS84 +geoid_crs=horizontal_crs +geoidgrids="C:\temp\dir with space\egm96_15.gtx" +proj=longlat +towgs84=0,0,0 +type=crs


vgridshift: could not find required grid(s).
pipeline: Pipeline: Bad step definition: inv (File not found or invalid)

*       * inf

```
This fails.

So this seems to be a regression as it was fixed years ago:
https://github.com/OSGeo/PROJ/issues/1152

**Comment by rouault** [comment]
This is just an issue with doing proper quoting with the Windows shell
You need to double quote the whole +geoidgrids=.... arguments, and then escape the quotes in it with ``\``, so:
```
cs2cs +proj=latlong +datum=WGS84  +to +ellps=WGS84 +geoid_crs=horizontal_crs "+geoidgrids=\"z:\with space\egm96_15.gtx\"" +proj=longlat +towgs84=0,0,0 +type=crs
```

**Comment by richy46** [comment]
Ok thank you. 
In old issue this is not mentioned this way however:
https://github.com/OSGeo/PROJ/issues/1152#issuecomment-430126656.

Maybe the documentation can be improved a bit...
