### ISSUE TITLE
output not as in documentation

### ISSUE THREAD

**Issue by pcace** [OSGeo/proj.4#3963]
hi there, i am trying to convert from EPSG:3068 to EPSG:25833 using cs2cs but get a not expected output: 

```
echo 16491.603515625,25592.033203125 | cs2cs "EPSG:3068" "EPSG:25833" 
366657.20       5815585.56 0.00,25592.033203125


```

what are the four numbers in the output? i was expecting 2 numbers like in the documentation and provided examples. 

if anyone could help me out what i am seeing here it would be great!

thanks a lot!

**Comment by busstoptaktik** [comment]
This is not a bug.

1. Remove the comma between your input coordinates
2. Read the manual - especially the pages about [community communication channels](https://proj.org/en/9.3/community/channels.html)
3. Understand that this kind of questions should be sent to the mailing list. Do not make irrelevant noise on github
