### ISSUE TITLE
Transform coordinates crash when demo uses omp parallel

### ISSUE THREAD

**Issue by autel-liuxiaozi** [OSGeo/proj.4#3976]
#### problem
Hi, I'm using gdal(3.0.0) to do a lot of coordinate transformations. In order to save time, omp parallel technology is used. when I select two coordinate systems HD1909 coordinate system(epsg: 3819)  and WGS 84 /UTM zone 48N(epsg:4536) for mutual conversion of coordinates，the code will crash.I think it’s a compatibility issue with the HD1909 coordinate system because there is no problem when using another coordinatesystem such as wgs84(epsg:4326).

Here is a very simple code to reproduce.

```c++
#include "gdal.h"
#include "ogr_spatialref.h"
#include <iostream>
using namespace std;
int main()
{
	GDALAllRegister();
	std::string gdal_data = "D:/gdal_data";  // your gdal data folder
	const char* paths[] = { gdal_folder.c_str(),nullptr };
	OSRSetPROJSearchPaths(paths);
	CPSSetConfigOption("GDAL_DATA", paths[0]);

	OGRSpatialReference spatial_reference1_, spatial_reference1_;
	spatial_reference1_.importFromEPSG(3819); // change 3819 to 4326 ,will be all good
	spatial_reference2_.importFromEPSG(32648);
	spatial_reference2_.SetAxisMappingStrategy(OAMS_TRADITIONAL_GIS_ORDER); // because 32648 is a projected coordinate system
	OGRCoordinateTransformation* transformer_ = OGRCreateCoordinateTransformation(&spatial_reference1_, &spatial_reference2_);
	std::function<void(double,double,double)> trans_func = 
		[&](double src_x, double src_y, double src_z)
	{
		transformer_->Transform(1, &src_x, &src_y, &src_z);
	}
#pragma omp parallel for schedule(dynamic,1)
	for (int i = 0; i < 1000000; i++)
	{
		double x, y, z;
		trans_func(27.525284521617660, 102.48065034715316, 1.0);
	}
	return 0;
}

```
#### Problem description
Like I said. The above code only needs to change 3819 to 4326 and everything will be fine. 
So I think there are some problems with the proj library's support for the 3819 coordinate system. Please check it, thank you all

#### Expected Output
stack information：
![企业微信截图_17017815969001](https://github.com/OSGeo/PROJ/assets/145082907/79234f1d-3141-43ce-85b9-a3090123bb08)
crashed line:
![企业微信截图_17017816244205](https://github.com/OSGeo/PROJ/assets/145082907/b4c5a482-5181-457a-a673-25903569f008)

#### Environment Information
 - gdal 3.0.0 using PROJ version (`6.3.2` or newest 9.3.0)
 - win10

#### Installation method
 - compile gdal(3.0.0) with proj(6.3.2 or newest 9.3.0) to do coordinate transform.

**Comment by rouault** [comment]
This is an OpenMP usage issue from yours. You can't use the same GDAL transformer object from several threads. You should have one transformer object per thread. The fact that it crashes for some transformation comes from the fact that those transformations modify their internal state during the transformation. This is totally expected.

**Comment by autel-liuxiaozi** [comment]
but why i use 4326 ,it's all good?

**Comment by rouault** [comment]
> but why i use 4326 ,it's all good?

I could explain with lengthy explanations, but I won't. That's mostly luck that it works. Follow my initial advice of using a transformation object per thread to be bullet proof.

**Comment by autel-liuxiaozi** [comment]
OK, thank you
