### ISSUE TITLE
URL in description is modified from source SQL statements

### ISSUE THREAD

**Issue by mwtoews** [OSGeo/proj.4#3996]
For example, see source SQL insert statement:
https://github.com/OSGeo/PROJ/blob/5587e5747f6c789a51e5d949cc0684a555cc5e44/data/sql/iau.sql#L51
which has:
> `'Source of IAU Coordinate systems: https://doi.org/10.1007/s10569-017-9805-5'`

this mysteriously gets modified for proj.db which has a description:
> `'Source of IAU Coordinate systems: doi://10.1007/s10569-017-9805-5'`

or
```bash
$ projinfo -k crs IAU_2015:1000 -o WKT2:2019
WKT2:2019 string:
GEOGCRS["Sun (2015) - Sphere / Ocentric",
    DATUM["Sun (2015) - Sphere",
        ELLIPSOID["Sun (2015) - Sphere",695700000,0,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Reference Meridian",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["IAU",1000,2015],
    REMARK["Source of IAU Coordinate systems: doi://10.1007/s10569-017-9805-5"]]
```
The [original URL](https://doi.org/10.1007/s10569-017-9805-5) should have been preserved.

**Comment by rouault** [comment]
> this mysteriously gets modified for proj.db which has a description:
> 
> > ``

huh! Both proj.db and WKT2 output have "https://doi.org/10.1007/s10569-017-9805-5" for me. https://spatialreference.org/ref/iau_2015/1000/prettywkt2.txt is also fine.
There must be something on your system that does that substitution...

**Comment by rouault** [comment]
wait, this was actually changed in 94be2c69c2cd0d0e1db332755ec105c9c65737c5 / 9.2.0  . You're looking at an ancient proj.db

**Comment by mwtoews** [comment]
Apologies, false alarm. It was PROJ 9.1 via conda.
