### ISSUE TITLE
Clean up sqlite3 further in CMake

### ISSUE THREAD

**Issue by ErixenCruz** [OSGeo/proj.4#4004]
https://github.com/OSGeo/PROJ/pull/3987 changed the CMake to link to the explicit target `SQLite::SQLite3` and find SQLite3, which makes use of CMake's built-in FindSQLite3 script instead of PROJ's. 

@mwtoews mentioned in the CMake 3.16 upgrade PR that there are some Sqlite3 configuration variables that should probably be adjusted or deprecated. https://github.com/OSGeo/PROJ/pull/3997#issuecomment-1886679622. Reading about [`find_path`](https://cmake.org/cmake/help/latest/command/find_path.html), which is called in the built-in FindSQLite3 script, the configuration variables might just have to be mapped to `SQLite3_ROOT`. A CMake expert may chime in here.

The other thing is that we can probably remove PROJ's [FindSqlite3](https://github.com/OSGeo/PROJ/blob/master/cmake/FindSqlite3.cmake) and rely entirely on built-in CMake.

**Comment by mwtoews** [comment]
Thanks @ErixenCruz , that's correct, I'm planning to replace cmake/FindSqlite3.cmake with the [FindSQLite3](https://cmake.org/cmake/help/latest/module/FindSQLite3.html) built-in. Everybody [usually] wins when bespoke/custom modules are replaced with better-known built-in modules.
