### ISSUE TITLE
Help installation 

### ISSUE THREAD

**Issue by saras82** [OSGeo/proj.4#4012]
Hi, I'm new to C++ development. I would like to use PROJ in Visual C++ 2019 to transform coordinates..but I have an error at runtime. 
I installed following these instructions:https://proj.org/en/9.3/install.html#building-on-windows-with-vcpkg-and-visual-studio-2017-or-2019   .
Then I added the include files and library directory.
When I compile...it's ok..But when I want to run it gives me an error that the .dll is missing...
However, when I also include the one containing the dll in the library paths, I get an error during compilation: Severity Code Description Project File Row Deletion status
Error LNK1107 corrupt or invalid file: unable to read in 0x328 proj_9_4.dll.

How can I solve it? 
Thanks in advance

**Comment by rouault** [comment]
Same type of question as https://github.com/OSGeo/gdal/issues/9134 . Sorry, but helping remotely people new to C++ development is beyond the scope of the support we can offer. You should seek for physical or online training on the topic to get you bootstrapped.

**Comment by saras82** [comment]
Could you suggest me a link where I can understand how to continue? I hope you can help me...I don't know how to proceed...

**Comment by rouault** [comment]
maybe https://www.google.com/search?q=tutorial+linking+to+external+library+in+visual+studio+c%2B%2B
