### ISSUE TITLE
Prime meridian inconsistency: Madrid

### ISSUE THREAD

**Issue by mwtoews** [OSGeo/proj.4#4029]
[Madrid (EPSG:8905)](https://epsg.org/prime-meridian_8905/Madrid.html) is defined as 3° 41' 14.55" W, which is different to PROJ's [3d41'16.58"W](https://github.com/OSGeo/PROJ/blob/50e8dd72bc569c2844ec1f52e9dee0446b809228/src/datums.cpp#L73) with a difference of 2.03" or [approximately](https://geographiclib.sourceforge.io/cgi-bin/GeodSolve?type=I&input=40.4168+3d41%2714.55%22W+40.4168+3d41%2716.58%22W&format=g&azi2=f&unroll=r&prec=3&radius=6378137&flattening=1%2F298.257223563&option=Submit) 47.859 m. It seems that [EPSG changed](https://epsg.org/closed-change-request/browse/id/2020.056) this value on 1 July 2020 with the comment:

> For meridian 8905, previous value in the EPSG record was 3°41'16.58"W. This was not used by any other EPSG entities.

I'm not sure what this means entirely, but is to worth changing or adding meridians for PROJ?

---

A related note for `madrid` is that it briefly had a typo of `3d41'16.48"W` which was fixed with 84b8264c62947bb73306be9c54487209939597dc but the old value has persisted in the [docs](https://github.com/OSGeo/PROJ/blob/50e8dd72bc569c2844ec1f52e9dee0446b809228/docs/source/usage/projections.rst) for a while. I'll fix these docs after resolving other prime meridian issues.

**Comment by rouault** [comment]
FWIW, when using EPSG CRS, PROJ will use the new value when going through PROJ4 strings:
```
$ bin/projinfo EPSG:2062
PROJ.4 string:
+proj=lcc +lat_1=40 +lat_0=40 +lon_0=0 +k_0=0.9988085293 +x_0=600000 +y_0=600000 +a=6378298.3 +rf=294.73 +pm=-3.687375 +units=m +no_defs +type=crs
```
So the change of the hardcoded +pm=madrid would affect only CRS definitions coming from PROJ.4 strings with explicit +pm=madrid

**Comment by mwtoews** [comment]
Closing, with the hard-coded `+pm=madrid` unchanged.

To use EPSG:8905, use `+pm=3d41'14.55"W`
