### ISSUE TITLE
Missing Paris RGS prime meridian?

### ISSUE THREAD

**Issue by mwtoews** [OSGeo/proj.4#4031]
[Paris (EPSG:8903)](https://epsg.org/prime-meridian_8903/Paris.html) defined as 2.5969213 grad (×9/10=2.3372291699999996 deg) is very close to [2d20'14.025"E](https://github.com/OSGeo/PROJ/blob/50e8dd72bc569c2844ec1f52e9dee0446b809228/src/datums.cpp#L71) (according to [GeodSolve](https://geographiclib.sourceforge.io/cgi-bin/GeodSolve?type=I&input=48.8566+2.3372291699999996+48.8566+2d20%2714.025%22E&format=g&azi2=f&unroll=r&prec=6&radius=6378137&flattening=1%2F298.257223563&option=Submit) the difference is 0.245 mm), so no real issue here.

[Paris RGS (EPSG:8914)](https://epsg.org/prime-meridian_8914/Paris-RGS.html) (RGS=Royal Geographical Society) defined as 2° 20' 13.95" E is 0.075" or [approximately](https://geographiclib.sourceforge.io/cgi-bin/GeodSolve?type=I&input=48.8566+2d20%2713.95%22E+48.8566+2d20%2714.025%22E&format=g&azi2=f&unroll=r&prec=3&radius=6378137&flattening=1%2F298.257223563&option=Submit) 1.529 m away from the Paris datum. According to the metadata, this datum was replaced by IGN in 1936 to the preferred EPSG:8903 Paris meridian.

Despite this note, should this meridian be added to PROJ as `paris_rgs`? Or ignored, as it's unlikely to be used?

**Comment by rouault** [comment]
I don't see a strong need to add that prime meridian as an hardcoded one. This must be used for old CRS only

**Comment by kbevers** [comment]
> I don't see a strong need to add that prime meridian as an hardcoded one. This must be used for old CRS only

I had the same thought when looking at the equivalent issue for the Copenhagen meridian (#4030). Removing these hardcoded values would be a good thing to do when the time comes for a 10.0.0 release.

**Comment by mwtoews** [comment]
Removing hardcoded prime meridians from [datums.cpp](https://github.com/OSGeo/PROJ/blob/50e8dd72bc569c2844ec1f52e9dee0446b809228/src/datums.cpp#L66-L83) could break things. Should `cs2cs -lm` be deprecated? Or with an explanatory note that this list is incomplete and/or a legacy thing? Or should a prime meridian be dynamically loaded from proj.db, e.g.

    cs2cs +proj=latlong +datum=WGS84 +to +proj=latlong +datum=WGS84 +pm=EPSG:8903

**Comment by rouault** [comment]
> Removing hardcoded prime meridians from [datums.cpp](https://github.com/OSGeo/PROJ/blob/50e8dd72bc569c2844ec1f52e9dee0446b809228/src/datums.cpp#L66-L83) could break things.

We can't remove them. Or that would completely break PROJ.4 strings. I'd say let's live with the existing ones, and don't add more

**Comment by kbevers** [comment]
> Or that would completely break PROJ.4 strings.

A guy can dream, right? ;)

> Should cs2cs -lm be deprecated?

I think that would be a good starting point. Then remove the option in 10.0 as well as hide everything related to the old datums and prime meridians from the surface.
