### ISSUE TITLE
Misleading Greenwich longitude values for prime_meridian from EPSG

### ISSUE THREAD

**Issue by mwtoews** [OSGeo/proj.4#4032]
The values in the `prime_meridian` table of `proj.db` are obtained from ESPG's data, and there is no issue with this conversion process into PROJ. However, these longitude values from EPSG are misleading, and I hope they are not used anywhere!

The issues is for all prime meridians (except Greenwich). For example, Athens:

- https://github.com/OSGeo/PROJ/blob/50e8dd72bc569c2844ec1f52e9dee0446b809228/data/sql/prime_meridian.sql#L15
- [Athens (EPSG:8912)](https://epsg.org/prime-meridian_8912/Athens.html) specifies 23° 42' 58.815" E

You can see that somehow 23° 42' 58.815" E → 23.4258815, whereas a proper decimal degrees conversion should be 23.7163375

I suspect this is known by EPSG? Either way, perhaps a note should be made somewhere in PROJ.

**Comment by rouault** [comment]
> I suspect this is known by EPSG? Either way, perhaps a note should be made somewhere in PROJ.

yes, this is an oddity of EPSG.  EPSG:9110 is "sexagesimal DMS".  Caused me some headaches during PROJ 6 development...

I don't see this is a bug though (except of EPSG to have invented that ugly beast) / not sure what we could do on PROJ side. There are a number of comments in the code regarding that

**Comment by mwtoews** [comment]
Thanks, I think I see a possible resolution to normalize these as decimal degrees, which can be done with scripts/build_db.py

The angle units are distinguished with uom_code 9110 for sexagesimal DMS and 9105 for grads. I'll have a crack at this at some time...

**Comment by rouault** [comment]
> The angle units are distinguished with uom_code 9110 for sexagesimal DMS and 9105 for grads.

We might probably normalize sexagesimal DMS as decimal degree (although I've a vague feeling that some surprises might occur), but we shouldn't do that for grads. We want the WKT output of EPSG:4807 "NTF (Paris)" to have a ``PRIMEM["Paris",2.5969213,ANGLEUNIT["grad",0.0157079632679489]]`` to be faithful to the definition. Changing that to degree *will* break things for sure

**Comment by rouault** [comment]
(I found an old commit b27efedef0b3deb488d322d42b3d5b652ab55662 of mine which shows at some point that epsg.org WKT output used sexagesimal DMS, which was super confusing. They eventually changed their WKT output to convert sexagesimal DSM to decimal degrees)

**Comment by mwtoews** [comment]
On further thought, it's probably best to not normalize anything, since uom_code is properly copied into prime_meridian. This indeed seems to be a "gotcha" to not assume floats are decimal degrees, which certainly applies in other spots.

**Comment by busstoptaktik** [comment]
> I don't see this is a bug though (except of EPSG to have invented that ugly beast) / not sure what we could do on PROJ side. There are a number of comments in the code regarding that

The "ugly beast" EPSG format seems to be constructed by dividing the [ISO-6709](https://en.wikipedia.org/wiki/ISO_6709) format by 100. The real ISO-format (aka NMEA format) is DDMM.mmm/DDMMSS.sss for latitude, DDDMM.mmm/DDDMMSS.sss for longitude - with prefix zeroes mandatory to discern correctly between degrees, minutes and seconds  (and prefix zeroes roundtrip badly through text-binary-text conversion
