### ISSUE TITLE
sqlite detection broken?

### ISSUE THREAD

**Issue by VictorEijkhout** [OSGeo/proj.4#4040]
Cmake fails with 
```
-- Looking for localeconv
-- Looking for localeconv - found
-- Looking for strerror
-- Looking for strerror - found
-- Looking for dladdr in dl
-- Looking for dladdr in dl - found
-- Looking for exp in m
-- Looking for exp in m - found
-- nlohmann/json: internal
CMake Error at CMakeLists.txt:181 (message):
  sqlite3 dependency not found!


CMake Error at CMakeLists.txt:187 (message):
  sqlite3 >= 3.11 required!
```

However:

```
[staff gdal:28] which sqlite3
/work2/00434/eijkhout/sqlite/installation-sqlite-3.43.0-stampede3-intel24/bin/sqlite3
[staff gdal:29] sqlite3 --version
3.43.0 2023-06-12 18:22:34 7ec4ab327decd6a5ee5e6a53f1489e17e0cdbb297945f9acc532b47d052eb7a9
```

**Comment by rouault** [comment]
Likely just a usage issue. You not only need a sqlite3 binary in the path, but you also need to indicate where to find sqlite3 include and library with https://proj.org/en/9.3/install.html#cmdoption-arg-SQLITE3_INCLUDE_DIR and https://proj.org/en/9.3/install.html#cmdoption-arg-SQLITE3_LIBRARY

**Comment by VictorEijkhout** [comment]
Actually, your CMake file has 
```
find_package(Sqlite3 REQUIRED)
if(NOT SQLITE3_FOUND)
  message(SEND_ERROR "sqlite3 dependency not found!")
endif()
```
and I get that message although 
```
[staff gdal:53] echo $PKG_CONFIG_PATH
/work2/00434/eijkhout/sqlite/installation-sqlite-3.43.0-stampede3-intel24/lib/pkgconfig:/work2/00434/eijkhout/jsonc/installation-jsonc-git-stampede3-intel24/lib64/pkgconfig:/opt/intel/oneapi/ccl/2021.11/lib/pkgconfig:/opt/intel/oneapi/mpi/2021.11/lib/pkgconfig:/opt/intel/oneapi/mkl/2024.0/lib/pkgconfig:/opt/intel/oneapi/ippcp/2021.9/lib/pkgconfig:/opt/intel/oneapi/inspector/2024.0/sdk/include/pkgconfig:/opt/intel/oneapi/inspector/2024.0/include/pkgconfig:/opt/intel/oneapi/dpl/2022.3/lib/pkgconfig:/scratch/projects/compilers/intel24.0/oneapi/dnnl/2024.0/lib/pkgconfig:/scratch/projects/compilers/intel24.0/oneapi/dal/2024.0/lib/pkgconfig:/opt/intel/oneapi/compiler/2024.0/lib/pkgconfig:/opt/intel/oneapi/tbb/2021.11/lib/pkgconfig

[staff gdal:54] ls /work2/00434/eijkhout/sqlite/installation-sqlite-3.43.0-stampede3-intel24/lib/pkgconfig
sqlite3.pc
```

Why is that not found / parsed?

I'll try the explicit options, but it would be nicer if `pkg_config` worked.

**Comment by mwtoews** [comment]
I don't believe pkg-config is used for finding Sqlite3. A reliable method is to set [`CMAKE_PREFIX_PATH`](https://proj.org/en/latest/install.html#cmdoption-arg-CMAKE_PREFIX_PATH) like this:

    cmake -DCMAKE_PREFIX_PATH=/work2/00434/eijkhout/sqlite/installation-sqlite-3.43.0-stampede3-intel24 ..

**Comment by Mosref** [comment]
Hello @mwtoews ! I tired to run the command of [CMAKE_PREFIX_PATH](https://proj.org/en/latest/install.html#cmdoption-arg-CMAKE_PREFIX_PATH) in my Developer Powershell on Visual Studio but I am still getting this error: Could NOT find SQLite3 (missing: SQLite3_INCLUDE_DIR SQLite3_LIBRARY) Do you have any idea how to solve this. Thank you in advance

**Comment by VictorEijkhout** [comment]
> I don't believe pkg-config is used for finding Sqlite3. A reliable method is to set [`CMAKE_PREFIX_PATH`](https://proj.org/en/latest/install.html#cmdoption-arg-CMAKE_PREFIX_PATH) like this:

That is very strange. Sqlite has a `.pc` file but not any `.cmake` files. Explain?

Btw, @Mosref setting expliclitly the include/lib paths (see above) does work. But you should not need to do that when there is a `.pc` file to be used.

**Comment by ErixenCruz** [comment]
CMake searches CMAKE_PREFIX_PATH. [FindSQLite3](https://github.com/Kitware/CMake/blob/master/Modules/FindSQLite3.cmake) calls [find_path](https://cmake.org/cmake/help/latest/command/find_path.html) to look for sqlite3.h. find_path looks through CMAKE_PREFIX_PATH, among [other things](https://cmake.org/cmake/help/latest/command/find_path.html#:~:text=If%20NO_DEFAULT_PATH%20is%20specified%2C%20then%20no%20additional%20paths%20are%20added%20to%20the%20search.%20If%20NO_DEFAULT_PATH%20is%20not%20specified%2C%20the%20search%20process%20is%20as%20follows%3A)

**Comment by VictorEijkhout** [comment]
Cmake searches the prefix path. *For what*? As far as I understand it searches for `.cmake` files, which sqlite does not provide. Correct me if I'm wrong.

**Comment by ErixenCruz** [comment]
> [FindSQLite3](https://github.com/Kitware/CMake/blob/master/Modules/FindSQLite3.cmake) calls [find_path](https://cmake.org/cmake/help/latest/command/find_path.html) to look for sqlite3.h.

it looks for sqlite3.h. There is also a find_library call there, so on linux this would search for sqlite3.a or sqlite.so (static and shared library files) i believe. for a better explanation, you can look at the cmake documentation for FindSQLite3, find_path, find_library. or there may be a cmake guide that puts it all together nicely somewhere

**Comment by rouault** [comment]
Closing as a 99.9% probability usage issue
