### ISSUE TITLE
Build error in src/transformations/gridshift.cpp after #4038

### ISSUE THREAD

**Issue by pjonsson** [OSGeo/proj.4#4046]
After @rouault  merged #4038, PROJ master fails building when building GDAL images.

#### Example of problem

```
[ 77%] Building CXX object src/CMakeFiles/proj.dir/transformations/hgridshift.cpp.o
[91m/proj/src/transformations/gridshift.cpp: In member function 'bool {anonymous}::gridshiftData::checkGridTypes(PJ*, bool&)':
/proj/src/transformations/gridshift.cpp:171:38: error: 'osgeo::proj::internal' has not been declared
  171 |             m_offsetX = osgeo::proj::internal::c_locale_stod(offsetX);
      |                                      ^~~~~~~~
/proj/src/transformations/gridshift.cpp:177:38: error: 'osgeo::proj::internal' has not been declared
  177 |             m_offsetY = osgeo::proj::internal::c_locale_stod(offsetY);
      |                                      ^~~~~~~~
[0m[91mmake[2]: *** [src/CMakeFiles/proj.dir/build.make:2484: src/CMakeFiles/proj.dir/transformations/gridshift.cpp.o] Error 1
```

#### Problem description

I haven't looked into the details but I think this is the same type of issue as #3842, GDAL redefines namespace names, so the code should use `NS_PROJ` as namespace name.

#### Environment Information
 - PROJ version: master
 - Operation System Information: Ubuntu 22.04 LTS as base for GDAL 3.8.3 image.

#### Installation method
 - What the build script from the GDAL repositiory does.

**Comment by jjimenezshaw** [comment]
@pjonsson Could you try with that branch? Thanks.

**Comment by pjonsson** [comment]
@jjimenezshaw unfortunately I don't have a development environment over the weekend. Your patch looks correct, so if it gets merged, I can let you know tomorrow if our nightly CI job passed. Otherwise I will try to get time to test your fix next week.

Thank you for the quick fix!

**Comment by jjimenezshaw** [comment]
@pjonsson Merged. You can have a look tomorrow.

**Comment by pjonsson** [comment]
@jjimenezshaw nightly passed, thank you for the quick fix!
