### ISSUE TITLE
Omerc doc patches ready

### ISSUE THREAD

**Issue by jidanni** [OSGeo/proj.4#4050]
In #4048, #4049 I make it super clear how the one point
and two point input methods of omerc connect. No longer will users
scratch their heads wondering if they really do.

I.e., adding vital "Rosetta stone connections" finally showing how one indeed can obtain the same output, using either method!

And in #4039 I submit my *coup de grâce*, setting the user straight
about proj's omerc two point method.

**Comment by kbevers** [comment]
There's really no need to open an issue saying that you've opened two other pull requests. Please limit the noise and make PR's that can stand by them selves.

**Comment by jidanni** [comment]
(Actually that's what I was planning to do. But after I issued the first pull request days passed, and I became convinced that nobody was ever going to look at it.

Because in my experience if I create an issue then it gets looked at, but not necessarily all pull requests.

Also, on one of the templates it says: "this pull request closes what issue?" So it sort of adds to the encouragement of creating a parent issue.)

**Comment by kbevers** [comment]
> But after I issued the first pull request days passed, and I became convinced that nobody was ever going to look at it.

A comment in the relevant PR will trigger a notification, it's entirely unnecessary to add more clutter to the issue tracker to get attention. In fact, it's very likely that the end result is that people will ignore or disregard you additions. In general, you've been very busy flooding both the issue tracker and pull request list lately. Personally I've come to ignore most of it as I often don't understand what your intention is or the issue/PR is of a questionable quality. My time is spent better elsewhere. It might be the case for others too. So maybe consider that the next time you think no one is going to look at your pull request.

> Also, on one of the templates it says: "this pull request closes what issue?" So it sort of adds to the encouragement of creating a parent issue.

That makes sense to do when there's already an existing issue describing the problem. There's not much sense in creating an issue *after* a PR has been opened.
