### ISSUE TITLE
Allow offline HTML doc download, but in individual files, not just one massive index.html

### ISSUE THREAD

**Issue by jidanni** [OSGeo/proj.4#4051]
On https://proj.org/ we can indeed download an HTML version of the manual for offline use,

![20240212T124235](https://github.com/OSGeo/PROJ/assets/1230959/6b87a2b2-c51e-401a-ae0c-0d89e103fc35)

Alas it is just one massive single HTML page. The largest HTML page
anybody has ever encountered, possibly.

However looking at e.g.,
https://stackoverflow.com/questions/32771287/download-html-as-separate-pages
https://github.com/sphinx-doc/sphinx/issues/10688
we see that separate HTML pages are also a possibility.

Just like the https://proj.org/ website itself has.

So please offer both types of HTML download.

- The current zip of one big index.html.

- A zip of the same tree, but each page in its original separate .html
  file.

Thanks.

**Comment by mwtoews** [comment]
Downloading separate HTML pages from RTD doesn't appear to be supported at the moment. An advantage of one large HTML doc is that you can easily search for content using the browser's search functionality.

However, the file size of images used for each projection is ~4x larger than they need to be, so I can see an enhancement to reduce the download size of doc outputs.

**Comment by jidanni** [comment]
I'm talking about one big zip, same size as the current zip, but inside that zip is a file system tree, and not just one index.html.

In fact it's just like if somebody ran a recursive wget spidering the site. And then tarred up the results into one big .tgz.

**Comment by jidanni** [comment]
Ah, on https://docs.generic-mapping-tools.org/dev/
in the lower left corner, one can download
https://docs.generic-mapping-tools.org/dev/gmt-docs-dev.zip
which is indeed ideal: individual files, with even a search
box (in its side panel) that works offline!

**Comment by kbevers** [comment]
@jidanni if this is important you, you can build the sphinx-docs yourself. In `docs/`

> make html

which will produce individual html files as you request. You may need to fiddle a bit with your environment, hints for that can be found in `docs/docbuild/Dockerfile`.

I'm closing this as it's not feasible for us to offer the docs in more ways than we already do.

**Comment by mwtoews** [comment]
For what it's worth, based on [this Q/A](https://superuser.com/a/642874/) it takes a few minutes to recursively gather everything, but it works just fine:
```bash
$ wget \
  --recursive \
  --no-clobber \
  --page-requisites \
  --convert-links \
  --html-extension \
  --restrict-file-names=windows \
  --no-parent \
  --domains proj.org \
  proj.org/en/latest/
```
And for other releases, replace `latest` with (e.g.) `9.3`

**Comment by jidanni** [comment]
It turns out for GDAL the ZIP already exits, but was simply not hyperlinked.
I fixed that via https://github.com/OSGeo/gdal/pull/9294 .

Most probably the same situation exists for PROJ, but the tree structure is different, causing me not to be able to find it.

And after I find it then I will think about where to put a link to it from... e.g.,
- https://readthedocs.org/projects/osgeo-proj/downloads/
- https://proj.org/en/9.3/index.html lower left corner
