### ISSUE TITLE
proj_factors in the C API does not properly return meridian convergence

### ISSUE THREAD

**Issue by bencooper222** [OSGeo/proj.4#4052]
#### Example of problem
I created a minimal example below (it doesn't include the memory management stuff my actual code has). proj_factors is not returning what I would expect.

```c
#include <iostream>
#include <ostream>
#include "proj.h"

int main() {
  PJ_CONTEXT* context = proj_context_create();

  auto from = "proj=utm +zone=10 +ellps=WGS84 +datum=WGS84 +units=m +no_defs +type=crs";
  auto to = "proj=longlat +datum=WGS84 +no_defs +type=crs";  // EPSG:4326

  auto from_crs = proj_create(context, from);
  auto to_crs = proj_create(context, to);

  PJ* transform = proj_create_crs_to_crs_from_pj(context, from_crs, to_crs, NULL, NULL);

  auto x = 587274.232025;
  auto y = 4140975.14908;
  auto input_coord = proj_coord(x, y, 0, 0);
  auto transform_res = proj_trans(transform, PJ_FWD, input_coord);

  std::cout << transform_res.xyz.y << " " << transform_res.xyz.x
            << std::endl;  // 37.4115,-122.014 which is correct.

  // https://proj.org/en/9.3/development/reference/functions.html#c.proj_factors says:

  // The input geodetic coordinate lp should be such that lp.lam is the longitude in radian, and
  // lp.phi the latitude in radian (thus independently of the definition of the base CRS, if P is a
  // projected CRS).
  PJ_COORD lp;
  lp.lpz.lam = proj_torad(transform_res.xyz.x);
  lp.lpz.phi = proj_torad(transform_res.xyz.y);

  auto factor_res = proj_factors(transform, lp);
  std::cout << factor_res.meridian_convergence << std::endl;  // returns -0 which is not correct.
  // GeographicLib::UTMUPS::Reverse(10,true,x,y returns 0.599188
  // https://geographiclib.sourceforge.io/2009-03/classGeographicLib_1_1UTMUPS.html#a7a9853d12095f33703660ca4985a571d
  return 0; 
}
```
#### Problem description

I expect that after a successful transformation and me following the instructions in the documentation to convert to radians, I get the correct meridian convergence.

#### Expected Output
0.599188

#### Environment Information
 - PROJ version (`proj`): 9.1.0
 - Operation System Information: Ubuntu 20.04.6

#### Installation method
 - https://download.osgeo.org/proj/proj-9.1.0.tar.gz

**Comment by benjamin-cooper-ai** [comment]
`echo 587274.232025 4140975.14908 | proj -I +proj=utm +zone=10 +ellps=WGS84 +datum=WGS84 +units=m +no_defs -f %.5f -SV` in the `osgeo/proj:9.1.0` docker image returns the correct answer.

I don't see why directly calling the library doesn't.

**Comment by jjimenezshaw** [comment]
The library is returning the angle in radians, while the app in degrees
https://github.com/OSGeo/PROJ/blob/master/src%2Fapps%2Fproj.cpp#L329

Is that the reason?

**Comment by benjamin-cooper-ai** [comment]
No, I changed that line to `std::cout << factor_res.meridian_convergence * 57.29<< std::endl;` and it still printed -0.

**Comment by busstoptaktik** [comment]
@bencooper222 The meridian convergence (and `proj_factors(...)` in general) makes sense for a *projection* from geographic coordinates to a projected space - not for a more generic *transformation* from whatever CRS to whichever other CRS.

If I understand your code correctly, what you want is

```C++
auto factor_res = proj_factors(from_crs, lp);
//                             ^^^^^^^^
```

**Comment by benjamin-cooper-ai** [comment]
That fixed my issue. Thanks.
