### ISSUE TITLE
undefined reference to `curl_easy_getinfo@CURL_OPENSSL_4'

### ISSUE THREAD

**Issue by iamgeoknight** [OSGeo/proj.4#4065]
I am getting following error while building proj from source using cmake

[  0%] Built target create_tmp_user_writable_dir
[  0%] Built target generate_proj_db
[  0%] Built target check_wkt1_grammar_md5
[  0%] Built target check_wkt2_grammar_md5
[ 72%] Built target proj
[ 73%] Built target cct
[ 74%] Built target cs2cs
[ 76%] Built target geod
[ 76%] Built target invgeod
[ 78%] Built target binproj
[ 78%] Built target invproj
[ 79%] Built target projinfo
[ 80%] Built target gie
[ 81%] Built target projsync
[ 82%] Built target geodtest
[ 83%] Built target geodsigntest
[ 83%] Linking CXX executable ../../bin/proj_errno_string_test
/usr/bin/ld: ../../lib/libproj.so.25.9.3.1: undefined reference to `curl_easy_getinfo@CURL_OPENSSL_4'
/usr/bin/ld: ../../lib/libproj.so.25.9.3.1: undefined reference to `curl_easy_perform@CURL_OPENSSL_4'
/usr/bin/ld: ../../lib/libproj.so.25.9.3.1: undefined reference to `curl_easy_setopt@CURL_OPENSSL_4'
/usr/bin/ld: ../../lib/libproj.so.25.9.3.1: undefined reference to `curl_easy_init@CURL_OPENSSL_4'
/usr/bin/ld: ../../lib/libproj.so.25.9.3.1: undefined reference to `curl_easy_cleanup@CURL_OPENSSL_4'
collect2: error: ld returned 1 exit status

**Comment by rouault** [comment]
Looks like a build issue on your side. Perhaps something with your curl installation.
