### ISSUE TITLE
Converting Proj4string to EPSG - getting null value

### ISSUE THREAD

**Issue by vivek1272001** [OSGeo/proj.4#4068]
I am trying to extract epsg from proj4string using the proj4 library but I am not able to extract the epsg, I am getting NULL value.
I am using the below code for the conversion:  

    PJ_CONTEXT* c = proj_context_create();
    int epsg{0};
    std::string proj4  = "+proj=utm +ellps=WGS84 +datum=WGS84 +units=m +no_defs +zone=21";
    PJ* pj = proj_create(c, proj4.c_str());
    if (pj != nullptr) {
          auto get_code= proj_get_id_code(pj, 0);
          if (get_code=  != nullptr) {
                epsg = atoi(code);
          }
          proj_destroy(pj);
    }
    proj_context_destroy(c);

I am getting a null value in get_code. 
I have prjo4 library installed and is working fine for any other conversion for example I can get proj4 string by giving the epsg but in reverse I am not able to get it.

**Comment by rouault** [comment]
change

> std::string proj4  = "+proj=utm +ellps=WGS84 +datum=WGS84 +units=m +no_defs +zone=21";
to

> std::string proj4  = "+proj=utm +ellps=WGS84 +datum=WGS84 +units=m +no_defs +zone=21 +type=crs";

and use ``proj_identify`` (https://proj.org/en/9.3/development/reference/functions.html#c.proj_identify) to match this CRS definition against known ones. Cf https://github.com/OSGeo/PROJ/blob/3c7e4ee32822d8f2250ecb8327727f9d129e8a77/test/unit/test_c_api.cpp#L2297 for related unit tests

**Comment by vivek1272001** [comment]
It worked. Thanks!
