### ISSUE TITLE
preparing the cache.db with the necessary grid shift parts required for projecting from the source to the destination within a defined area

### ISSUE THREAD

**Issue by aharondavid** [OSGeo/proj.4#4069]
I possess the well-known text (WKT) representations for both the source and destination coordinates. 
How can I organize the cache.db with the necessary grid shift parts required for projecting from the source to the destination within a defined area? 
My objective is to guarantee that the grid shift data is readily available and stored in the cache.db to prevent the need for downloading it "

**Comment by rouault** [comment]
> My objective is to guarantee that the grid shift data is readily available and stored in the cache.db to prevent the need for downloading it "

Use https://proj.org/en/9.3/apps/projsync.html

**Comment by aharondavid** [comment]
Thanks !
