### ISSUE TITLE
Default version in proj.org is 9.3

### ISSUE THREAD

**Issue by jjimenezshaw** [OSGeo/proj.4#4070]
Links without a version are currently going to 9.3

https://proj.org/news.html
goes to https://proj.org/en/9.3/news.html

#### Expected Output
https://proj.org/en/9.4/news.html or https://proj.org/en/stable/news.html or even https://proj.org/en/latest/news.html

#### Environment Information
 - PROJ version (`proj`): webpage

**Comment by rouault** [comment]
Should be fixed now, and I've updated HOWTO_RELEASE in https://github.com/OSGeo/PROJ/pull/4073 with the missing step

@mwtoews Do you know if that could be configured in the .readthedocs.yaml or some other file we can keep in PROJ git repo, instead of having to go through readthedocs.org UI ?

**Comment by kbevers** [comment]
Ah, that's the purpose of the redirect. I had a hunch it needed to be updated but it didn't seem necesary as proj.org was redirected to v. 9.4. Thanks for clearing that up.
