### ISSUE TITLE
Controlling Grid Shifts  (PROJ-data) size by selecting resolution

### ISSUE THREAD

**Issue by aharondavid** [OSGeo/proj.4#4078]
The  files in PROJ-data has some resolution, is it possible to download all the PROJ-data files by controlling the  resolution?
suppose the I want all PROJ-data with a low resolution for decrease the size of PROJ-data.

**Comment by rouault** [comment]
closing for same reason at https://github.com/OSGeo/PROJ/issues/4077#issuecomment-1987277854

**Comment by rouault** [comment]
you're actually looking for the resampling capabilities of https://gdal.org/programs/gdal_translate.html . But you may also hopefully realize that at some point, either by the specificity of the question or the repetition of them, you cross the line of the acceptable "feature request", and are rather looking for consultancy, which github issues aren't for.

**Comment by aharondavid** [comment]
> But you may also hopefully realize that at some point, either by the specificity of the question or the repetition of them, you cross the line of the acceptable "feature request", and are rather looking for consultancy, which github issues aren't for.

You absolutely right, sorry!
