### ISSUE TITLE
Windows installer is broken

### ISSUE THREAD

**Issue by Plopkonijn** [OSGeo/proj.4#4099]
When running the installation command as shown on the website:
```c
osgeo4w-setup.exe -q -k -r -A -s https://download.osgeo.org/osgeo4w/v2/ -P proj
```
It results in:
```
Environment variable 'PATH' length exceeds 1024
```

**Comment by rouault** [comment]
This is an issue specific to the OSGeo4W installer, and not PROJ itself. Soo it should be reported at https://trac.osgeo.org/osgeo4w/report

**Comment by Plopkonijn** [comment]
Ah yes thanks, the site is terrible..
