### ISSUE TITLE
Transformation from Gauß Krüger (EPSG:31256) coordinates to WGS84 (EPSG:4326) ?

### ISSUE THREAD

**Issue by Mosref** [OSGeo/proj.4#4123]
I am trying to perform a transformation from Gauß Krüger coordinates  (EPSG:31256) to WGS84 (EPSG:4326) . As inputs I have easting and northing values and as an output I want to get longitude and latitude values but the problem is I am not getting the right results. Can anyone help me solve the problem. Here is the C++ code that I am using: `
#include <iostream>
#include <iomanip>
#include <proj.h>

int main() {
    // Create the context
    PJ_CONTEXT* C = proj_context_create();

    // Create a transformation object using the provided PROJ string for the custom Gauss-Krüger system
    PJ* P = proj_create(C, "+proj=tmerc +lat_0=0 +lon_0=16.3333333333333 +k=1 +x_0=750000 +y_0=-5000000 +ellps=bessel +towgs84=577.326,90.129,463.919,5.137,1.474,5.297,2.4232 +units=m +no_defs +type=crs");
    if (P == nullptr) {
        std::cerr << "Failed to create transformation object.\n";
        return 1;
    }

    // Create the transformation object from the custom Gauss-Krüger system to WGS 84
    PJ* P_to_WGS84 = proj_create_crs_to_crs_from_pj(C, P, proj_create(C, "+proj=longlat +datum=WGS84 +no_defs +type=crs"), nullptr, nullptr);
    if (P_to_WGS84 == nullptr) {
        std::cerr << "Failed to create transformation object to WGS 84.\n";
        proj_destroy(P);
        proj_context_destroy(C);
        return 1;
    }
    
    // Input coordinates for transformation (Gauß-Krüger)
    double easting = 3358; // Adjusted for example; please verify correctness
    double northing = 341086;

    // Prepare the input
    PJ_COORD c_in;
    c_in.xy.x = easting;
    c_in.xy.y = northing;

    // Perform the transformation
    PJ_COORD c_out = proj_trans(P_to_WGS84, PJ_FWD, c_in);

    // Output the result
    std::cout << std::fixed << std::setprecision(6);
    std::cout << "Longitude: " << c_out.lp.lam << ", Latitude: " << c_out.lp.phi << std::endl;

    // Clean up
    proj_destroy(P);
    proj_destroy(P_to_WGS84);
    proj_context_destroy(C);

    return 0;
}`

**Comment by rouault** [comment]
the PROJ string you use for EPSG:31256 is incorrect. It shouldn't have a "+x_0=750000" term. 

Once that is corrected I get the same result with your program and cs2cs
```
$ ./mytest 
Longitude: 16.377314, Latitude: 48.208168
$ echo 341086 3358 | bin/cs2cs -d 6 EPSG:31256 EPSG:4326
48.208168	16.377314 0.000000
```

You may also directly use proj_create(ctxt, "EPSG:XXXX"), but be careful to use the CRS axis order then (which is northing/easting for EPSG:31256 and latitude/longitude for EPSG:4326), or wrap the transformation returned by proj_create_crs_to_crs_from_pj() with [proj_normalize_for_visualization()](https://proj.org/en/9.4/development/reference/functions.html#c.proj_normalize_for_visualization)

**Comment by Mosref** [comment]
Hello Mr. Rouault,
Thank you for your response!
I tried to change the PROJ string prameter and removed the  "+x_0=750000" term so that it looks like this right now `PJ* P = proj_create(C, "+proj=tmerc +lat_0=0 +lon_0=16.3333333333333 +k=1 +x_0=0 +y_0=-5000000 +ellps=bessel +towgs84=577.326,90.129,463.919,5.137,1.474,5.297,2.4232 +units=m +no_defs +type=crs");
    ` but it is still giving me wrong results.( I am getting negative results Longitude: -163.621670 Latitude: -48.208678 when I input easting:3358 and northing: 341086
Could you kindly offer further insights or suggestions to rectify this issue?
Thanks in advance.
