### ISSUE TITLE
User writable directory

### ISSUE THREAD

**Issue by dvargas74** [OSGeo/proj.4#4142]
Hi,

I would need to know if there is any API function to set up the user writable folder directly. On Android system, the default one, /tmp/proj, cannot be created and the files cannot be downloaded.

Thanks!

**Comment by rouault** [comment]
There's no C function for that, but that can be controlled through environment variable as documented in https://proj.org/en/9.4/resource_files.html#where-are-proj-resource-files-looked-for. So on Android, you might set the XDG_DATA_HOME env variable and the directory will be ``${XDG_DATA_HOME}/proj``

**Comment by dvargas74** [comment]
Thank you @rouault

During this morning, while waiting for the answer, I could check that. Setting up the enviroment variable programatically works.

Regards,
