### ISSUE TITLE
Geoid model list for a specific area

### ISSUE THREAD

**Issue by dvargas74** [OSGeo/proj.4#4152]
Hi!

Is there any way, with C API, to get  the geoid or "geoid_like" list for a specific area?

For instance, for Spain, alternatives to EGM08_REDNAP.txt and Global EGM2008 amd EGM96

What the difference between "geoid_model" table and the geoids from "grid_transformation" table?

Thanks,

**Comment by jjimenezshaw** [comment]
Geoid model (as a concept) is more attached to a vertical coordinate reference system. More in detail to the transformation from a geographic 3D system (with ellipsoidal heights) to a compound system (that has the vertical CRS). (Like https://epsg.org/transformation_9605/ETRS89-to-ETRS89-Alicante-height-1.html )
So the question should be IMO, which vertical system I have/want to use (Alicante height probably in your case), and how to use "its" geoid model.

With PROJ, if you have the grid files in the proper location, a transformation to EPSG:4258+5782 (or any projected variation) will use the Spanish geoid model automatically.

In some few countries there are several versions of the geoid model for the same vertical CRS, like NAVD88 in North America. The table geoid_model assigns names to the different geoid modelsfor those different transformations, like GEOID18 or GEOID12B.

The table grid_transformations has the transformations that use a grid, not only geoid models.

**Comment by jjimenezshaw** [comment]
PS if you are working in Spain out of the peninsula, there are different vertical CRSs for each island. They all use the EGM08-REDNAP model. In the Canary Islands notice that the geographic system is different! (They are not in the European tectonic plate)

**Comment by dvargas74** [comment]
Javier, thank you for your quick reply,

I would need to know, when showing the vertical CRS list to the user, the associated geoid file, if exists. Users used to know EGM08-REDNAP instead of Alicante height. We develop software for surveyors and they ask for this.

How can I get the transformation grid name for a CRS? 

For Mexico, for instance, the geoid model is GGM10 and the CRS is NAVD88 height.

**Comment by rouault** [comment]
> How can I get the transformation grid name for a CRS?

You can't get it for a CRS, but if you ask to transform a vertical CRS to a geographical CRS, then you can use the following functions:

proj_create_operations, proj_list_get_count, proj_list_get, proj_list_destroy, proj_coordoperation_get_grid_used_count, proj_coordoperation_get_grid_used

**Comment by dvargas74** [comment]
Thank you again, it's clear

I'm currently using those functions and I can get the grids but I wanted to know if it was possible for a CRS, based on database queries, without doing any coordinate operations. Now it's clear, 

Thanks,
