### ISSUE TITLE
Interrupted Mollweide gives wrong result on inverse projections of some lat/lons.

### ISSUE THREAD

**Issue by shortjonescipher** [OSGeo/proj.4#4155]
#### Example of problem

```c
>>> p = Proj('+proj=imoll +R=1')
>>> p(-37.5, 7.5)
(-0.7576285842105634, 0.1452338366477549)
>>> p(-0.7576285842105634, 0.1452338366477549, inverse=True)
(inf, inf)
```
Sorry this is in pyproj but when I raised it with them they said the behavior is consistent with PROJ:
```c
echo -37.5 7.5 | proj +proj=imoll +R=1
-0.76	0.15
echo -0.7576285842105634 0.1452338366477549 | proj -Iv +proj=imoll +R=1
*	*
```
#### Problem description

The inverse projection should match the forward projection. The (inf, inf) or (*, *)result causes some parts of a world image based on the inverse projection to be missing. This lat/lon is just an example, several others are also affected.

#### Expected Output
-37.5 7.5
#### Environment Information

Sorry, PROJ not installed, using it via pyproj.

#### Installation method

N/A

**Comment by jjimenezshaw** [comment]
I got a longer output using PROJ 9.4.0:

```
echo -0.7576285842105634 0.1452338366477549 | ./proj -Iv +proj=imoll +R=1
#Interrupted Mollweide
#	PCyl, Sph
# +proj=imoll +R=1 +break_cs2cs_recursion
#--- following specified but NOT used
# +ellps=GRS80
*	*
```

**Comment by jjimenezshaw** [comment]
@erykoff added this projection not so long ago. Maybe he/she can explain  the details of the zone selection in the inverse transformation. I do not have clear the values for the false easting set for each zone, and how it may collide with the zone selection. In this case the longitude -37.5 deg is clearly in zone 2 (looking at the ascii art graph), but the x value `-0.7576285842105634` is filtered as zone 1.

**Comment by erykoff** [comment]
"Not long ago" in PROJ terms is March 2022.  😂 

Thanks for pointing this out.  I was cribbing from the `igh` code which I think only works by coincidence.  I am now figuring out the correct offsets.

**Comment by erykoff** [comment]
This should be fixed with #4159.  Thanks for pointing this out!

**Comment by busstoptaktik** [comment]
> "Not long ago" in PROJ terms is March 2022. 😂

@erykoff - compared to PROJ's total lifetime of around **40 years**, anything less than 40 **months** is hardly a split-second 😊

**Comment by jjimenezshaw** [comment]
Is there an easy way to see this projection in qgis? (With the openstreetmap for instance)
