### ISSUE TITLE
"proj_grid_info" C API function fails with grid "test_gridshift_projected.tif"

### ISSUE THREAD

**Issue by dvargas74** [OSGeo/proj.4#4160]

**Comment by kbevers** [comment]
Please include additional information that can help debug this issue

**Comment by dvargas74** [comment]
The grid is included in data/tests folder. It's part of the testing files in PROJ.

GTiffHGridShiftSet::open return nullptr with log error "IFD 0 has channel descriptions, but no longitude_offset/latitude_offset channel"

I think that the problem is that this grid is a eating/northing grid and it's not recognized.

**Comment by rouault** [comment]
This is kind of expected, and I don't think we can fix it without breaking the PROJ API/ABI given that the PJ_GRID_INFO structure  members were designed for grid registered in geodetic coordinates.

proj_grid_info() not working on grids registered in a projected CRS doesn't prevent PROJ from using them though.

Details about such grid could be found using GDAL API for example

**Comment by dvargas74** [comment]
It's clear. Thank you.
