### ISSUE TITLE
HEPOS GGRS87 shift grid

### ISSUE THREAD

**Issue by dvargas74** [OSGeo/proj.4#4161]
Hi,

Would it be possible to add HEPOS shift grid to PROJ data?

It's a shift grid file with easting / northing offsets. If I'm not wrong, this kind of grids are supported from PROJ v9.4.0

**Comment by kbevers** [comment]
Start here https://github.com/OSGeo/PROJ-data/blob/master/CONTRIBUTING.md over at the PROJ-data repository.

**Comment by dvargas74** [comment]
Thank you, I'll follow the steps in the document to try to add it.

**Comment by jjimenezshaw** [comment]
Hi @dvargas74 
I have been researching about this grid shift. One important question is the license to distribute the grid file. Do you have any contact in HEPOS that could clarify that?
The files are available in their web page, but no mention to the license (as usual).
If you prefer, you can contact me directly.

**Comment by dvargas74** [comment]
Hi Javier, I'll contact you directly.
