### ISSUE TITLE
"No inverse method available"

### ISSUE THREAD

**Issue by dvargas74** [OSGeo/proj.4#4165]
Hi,

I'm testing projected grids and I'm getting error 2048 - No inverse method available.

What is wrong in this pipeline?

+proj=pipeline +step +proj=tmerc lat_0=0 lon_0=24 k=0.9996 x_0=500000 y_0=0 ellps=GRS80 +step +proj=gridshift +grids=projected_grid.tif

**Comment by dvargas74** [comment]
I get an test error when running "gie" program with "gridshift.gie" file for the operation:

 "operation   +proj=gridshift +grids=tests/test_gridshift_projected.tif"

gridshift: Invalid latitude

I'm using PROJ v9.4.0

**Comment by rouault** [comment]
> I get an test error when running "gie" program with "gridshift.gie" file for the operation:

I suspect some misconfiguration in your system. Are you sure you aren't mixing PROJ versions?

**Comment by dvargas74** [comment]
This is the header obtained when running "projinfo" and "proj" programs:

Rel. 9.4.0, March 1st, 2024

All tests are succeeded except the one for this operation

On the other hand, here a piece of code for debugging this issue:

PJ_COORD source = proj_coord(-598000.000, -1160020.000, 0.000, 0);
PJ_CONTEXT* context = proj_context_create();
PJ *pj = proj_create(context, "+proj=gridshift +grids=test_gridshift_projected.tif");
double x = proj_roundtrip(pj, PJ_DIRECTION::PJ_FWD, 1, &source);

Should be right? What about the pipeline at the beginning of this conversation?

**Comment by rouault** [comment]
> Should be right? What about the pipeline at the beginning of this conversation?

both looks OK

**Comment by dvargas74** [comment]
Then, what could be the problem? 
This is very important for us. Any idea about what I can do?
Does the code above work fine on your end?

**Comment by rouault** [comment]
> Does the code above work fine on your end?

yes, it does (and the related tests runs fine on the continuation integration on all major platforms):

I've just successfully tested the following:
```
$ cat test.cpp
#include <stdio.h>
#include <proj.h>

int main() {
    PJ_COORD source = proj_coord(-598000.000, -1160020.000, 0.000, 0);
    PJ_CONTEXT* context = proj_context_create();
    PJ *pj = proj_create(context, "+proj=gridshift +grids=test_gridshift_projected.tif");
    PJ_COORD res = proj_trans(pj, PJ_FWD, source);
    printf("%f %f\n", res.xy.x, res.xy.y);
    PJ_COORD res2 = proj_trans(pj, PJ_INV, res);
    printf("%f %f\n", res2.xy.x, res2.xy.y);

    return 0;
}

$ g++ -I../src test.cpp -o mytest -Llib -lproj && LD_LIBRARY_PATH=$PWD/lib PROJ_DATA=data/for_tests/tests:data PROJ_DEBUG=ON ./mytest 
pj_open_lib(proj.ini): call fopen(data/proj.ini) - succeeded
pj_open_lib(proj.db): call fopen(data/proj.db) - succeeded
pj_open_lib(test_gridshift_projected.tif): call fopen(data/for_tests/tests/test_gridshift_projected.tif) - succeeded
-5597999.884995 -6160019.977850
-598000.000000 -1160020.000000
```

> Then, what could be the problem?

I don't know. I'm pretty bad at diagnosing issues I can't reproduce locally. Maybe compare the log messages you get by setting PROJ_DEBUG=ON with the ones above. Otherwise I have nothing better to suggest than running through a debugger and stepping ...

**Comment by dvargas74** [comment]
Thank you so much for your help. I'll check, again, everything on my end.
