### ISSUE TITLE
General grid shift issue

### ISSUE THREAD

**Issue by dvargas74** [OSGeo/proj.4#4173]
Hi,

I'm using a local grid (created by me) in GeoTIFF format. Its TYPE is HORIZONTAL_OFFSET and it's referenced in a projected CRS.

The PROJ version is 9.4.1 and it's running on Windows 11.

This is the pipeline I'm using for testing the grid:

"+proj=pipeline +step +proj=unitconvert +xy_in=deg +z_in=m +xy_out=rad +z_out=m +step +proj=tmerc +lat_0=0 +lon_0=24 +k=0.9996 +x_0=500000 +y_0=-2000000 +ellps=GRS80 +step +proj=gridshift +grids=mygrid.tif"

The calculations are right but ONLY if Network Capabilities are DISABLED. 

After debugging, I could see this code in function PJ* pj_obj_create, in c_api.cpp file.

```c
if (proj_context_is_network_enabled(ctx)) {
    ctx->defer_grid_opening = true;
}
```

This condition seems to assign invalid units to the PJ object in function PJ *PJ_TRANSFORMATION(gridshift, 0), in gridshift.cpp file. 

ONLY if Network Capabilities are enabled.

```c

...
bool isProjectedCoord = false;
if (P->ctx->defer_grid_opening) {
    Q->m_defer_grid_opening = true;
}
...
 if (isProjectedCoord) {
     P->left = PJ_IO_UNITS_PROJECTED;
     P->right = PJ_IO_UNITS_PROJECTED;
 } else {
     P->left = PJ_IO_UNITS_RADIANS;
     P->right = PJ_IO_UNITS_RADIANS;
 }
...
```

The error code I get is 1025: Invalid PROJ string syntax.

**Comment by rouault** [comment]
Fix queued in https://github.com/OSGeo/PROJ/pull/4174
You can workaround the issue by adding +coord_type=projected as an extra parameter of +proj=gridshift

**Comment by dvargas74** [comment]
Thank you @rouault, it worked adding "coord_type" parameter. As I could check, it's not in PROJ documentation yet, right?

**Comment by rouault** [comment]
> As I could check, it's not in PROJ documentation yet, right?

yes, on purpose. I was hesitant documenting that

**Comment by dvargas74** [comment]
Thank you @rouault
