### ISSUE TITLE
Doc Helmert: rotation matrix

### ISSUE THREAD

**Issue by rouault** [OSGeo/proj.4#4178]
It has been reported to me by email the following regarding helmert.rst:

"I believe the last matrix should be RZ in https://github.com/OSGeo/PROJ/blob/9.4/docs/source/operations/transformations/helmert.rst?plain=1#L322.  Actually I suspect ```R=RZ*RY*RX``` as in geodesy, per IOGP GN373-07-2, “in general, with three rotations about the X, Y and Z axes respectively, the order in which the rotations are applied is significant. By convention, the rotations are first about the X-axis, then the Y-axis, then the Z-axis… "

@kbevers  I see you've authored that piece of doc. There's obviously a mistake, but I'm not sure about the order of matrix multiplication.

**Comment by kbevers** [comment]
Yeah, it should by `R=Rz*Ry*Rx`.

**Comment by busstoptaktik** [comment]
At least R = Rz*(Ry*Rx) replicates the resulting matrix in [Guidance Note 7-2](https://www.iogp.org/wp-content/uploads/2019/09/373-07-02.pdf), p. 105. We, however, seem to use the opposite sign convention of GN7-2 (which is just a matter of whether the matrix is expressed as in the frame rotation, GN7-2, or the position vector rotation, PROJ docs, case).
