### ISSUE TITLE
Google marks proj.org as potentially hacked, recommends against visiting it

### ISSUE THREAD

**Issue by netthier** [OSGeo/proj.4#4182]
#### Problem description

Not sure if this is really an actionable bug report, but Google says that https://proj.org "may be hacked":
![image](https://github.com/OSGeo/PROJ/assets/66856670/45ec661b-0f7d-4693-a28a-03dab190a3e3)

The link leads here: https://support.google.com/websearch/answer/190597, where Google recommends to not visit the site and lists steps to solve this issue.

This may discourage potential and existing users from accessing the website.

#### Expected Output

I'd expect that to not be there

**Comment by hobu** [comment]
I wonder if this is due to us having both proj.org and proj4.org as served domains via [RTD](https://readthedocs.org) (the infra that hosts proj.org)

![image](https://github.com/OSGeo/PROJ/assets/87751/d817ed63-534a-4853-8948-8fff93a58831)

**Comment by jjimenezshaw** [comment]
To get more data I was trying to add it the the Google Console. However the TXT entry in the DNS as verification code is not possible with readthedocs:
https://trac.osgeo.org/osgeo/ticket/3211

Searching a bit (probably not enough) I found this:
https://webmasters.stackexchange.com/questions/142501/how-do-i-add-a-google-search-console-verification-meta-tag-to-a-read-the-docs-pa

In readthedocs itself they mention Google Search Console, but not too much :'(
https://docs.readthedocs.io/en/stable/guides/technical-docs-seo-guide.html#search-engine-feedback

How can we add the verification code?
"Add the following to your ‘root’ index.rst file"... do we have a root location? I don't know if it will work with the 302 redirect we have to proj.org/en/9.4

-- edit --
Looking at https://support.google.com/webmasters/answer/9008080#html_verification&zippy=%2Chtml-tag , if I understood correctly only the "HTML tag" method may work.

**Comment by jjimenezshaw** [comment]
Once verified in google search console, the "Security Issues" sections says:
```
Hacked: URL injection

Description
These pages appear to be created by a hacker in order to spam search results.
 [Learn more](https://support.google.com/webmasters/answer/9044101#hacked-url-injection)

Sample URLs
17 May 2024https://www.proj.org/tews/video-barh-sa7ad_1.html
20 May 2024https://www.proj.org/mex/video-zmk-vs-borkan6.html
16 May 2024https://www.proj.org/tews/video-barh-sa7ad_19.html
25 May 2024https://www.proj.org/mex/video-zmk-vs-borkan15.html?jaja
1 Jul 2024https://www.proj.org/tews/video-barh-sa7ad_17.html
21 May 2024https://www.proj.org/mex/video-zmk-vs-borkan12.html
20 May 2024https://www.proj.org/mex/video-zmk-vs-borkan11.html
1 Jul 2024https://www.proj.org/mex/video-zmk-vs-borkan9.html
19 May 2024https://www.proj.org/mex/video-zmk-vs-borkan4.html
17 May 2024https://www.proj.org/tews/video-barh-sa7ad_14.html
16 May 2024https://www.proj.org/tews/video-zamalek-berkane_11.html
2 Jun 2024https://www.proj.org/mex/video-zmk-vs-borkan4.html?jaja
```
Do we know how did it happen? Should we inform RTD?
See that the URLs have `www`, that is not the case for our page.

**Comment by rouault** [comment]
Wouldn't Google be confused by that weird page that contains parts of those dummy links: https://github.com/kikosaad2024/adhd/blob/b2cf9c1bcb6be4b50ecc28e49daa1d23a6e903cd/news/tews/gaaa5.xml#L12 ?
Not sure if it is just a coincidence, but that repo seems to be handled by RtD too: https://github.com/kikosaad2024/adhd/blob/main/.readthedocs.yaml
/me confused

**Comment by hobu** [comment]
> that repo seems to be handled by RtD too

I think someone should file a ticket with RTD here. They must have a bug in their regexes that make their virtual hosts.

**Comment by rouault** [comment]
I've filed https://github.com/readthedocs/readthedocs.org/issues/11450

**Comment by hobu** [comment]
Does google still mark this as sus after the change to add www.proj.org to the RTD config?

**Comment by netthier** [comment]
I can't reproduce the issue anymore, seems like it's fixed on my end at least.

**Comment by rouault** [comment]
> I can't reproduce the issue anymore

me neither, seems to have been solved.  maybe we can close this?

**Comment by jjimenezshaw** [comment]
We can choose it. On Thursday at home I will check what the search console says.

**Comment by jjimenezshaw** [comment]
Google search console now says that there is no security issue.
I hope I will be notified directly if it happens again.
