### ISSUE TITLE
Help with compiling PROJ 5.1.0 with JNI on windows

### ISSUE THREAD

**Issue by Teyson** [OSGeo/proj.4#4188]
Hi,
This is not a bug report as such, it is more of a question.

I am working on a project that uses a legacy version of PROJ, 5.1.0. Until now all developers have been using linux machines, and we have had the compiled files shared between us. But now we have swapped all developers to windows machines and therefore we need to recompile on windows.

I am trying to compile it using cmake to do the compile. However I can't seem to find in your installation guide how to compile with the JNI wrapper. I can find ways to do it with nmake, there it seems like I can add the --with-jni argument to the compile. How do I do that with cmake?

**Comment by Teyson** [comment]
When compiling I get this output:
```
cmake ..
CMake Deprecation Warning at CMakeLists.txt:12 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
--
-- Configuring PROJ:
--
-- PROJ_VERSION                             = 5.0.0
-- PROJ_ABI_VERSION                         = 5_0
-- WARNING:
-- Could not determine compiler toolset name to set PROJ_COMPILER_NAME variable.
-- WARNING:
-- Could not determine platform name to set PROJ_COMPILER_NAME variable.
-- PROJ_PLATFORM_NAME                       = win32
-- PROJ_COMPILER_NAME                       =
-- PROJ_TESTS                               = ON
--
-- Configuring proj library:
--
-- JNI_SUPPORT                              = OFF
-- PROJ_CORE_TARGET                         = proj
-- PROJ_CORE_TARGET_OUTPUT_NAME             = proj_5_0
-- PROJ_LIBRARY_TYPE                        = STATIC
-- PROJ_LIBRARIES                           = proj
-- Configuring done (0.3s)
-- Generating done (0.2s)
```

Here I'm guessing I would like to see `JNI_SUPPORT = ON`

**Comment by rouault** [comment]
sorry we no longer provide support for those ancient PROJ versions
