### ISSUE TITLE
I'm cross-compiling, tried 9.3.1, 9.3.0, 9.0.0, and sqlite cross-compilation and local compilation all failed, don't know why the build failed

### ISSUE THREAD

**Issue by hopeyl** [OSGeo/proj.4#4191]
![image](https://github.com/OSGeo/PROJ/assets/84188706/cee40231-6d79-4d0c-bef3-00165029f6b7)
![image](https://github.com/OSGeo/PROJ/assets/84188706/78e783c0-2631-4d40-bb9d-66b6d444ea75)

**Comment by rouault** [comment]
The EXE_SQLITE3 variable must actually point to a SQLite3 executable of the architecture you build on (likely x86_64), not on the target architecture for which you build for (arm64).

**Comment by jjimenezshaw** [comment]
Just to explain why (I had the same problem years ago):
Sqlite3 is needed for two things. During the build process, proj.db is created. There you need the host version of the executable. 
Later at runtime the library will need to read proj.db. For that the target version of sqlite3 library is needed.

**Comment by rouault** [comment]
https://github.com/OSGeo/PROJ/pull/4192 should help clarifying
