### ISSUE TITLE
Error with sqlite link in cross-compilation

### ISSUE THREAD

**Issue by hopeyl** [OSGeo/proj.4#4193]
I'm cross-compiling (dev is x86_64, target is arm64) and I've specified -DEXE_SQLITE3=/home/lzj/sqlite3/bin/sqlite3 (x86 compiled sqlite), -DSQLITE3_INCLUDE_DIR=/home/lzj/arm/sqlite3/include (arm64 compiled sqlite)  -DSQLITE3_LIBRARY=/home/lzj/arm/sqlite3/lib/libsqlite3.so (sqlite compiled by arm64), but still get an error, please help me see what the problem is
![image](https://github.com/OSGeo/PROJ/assets/84188706/738f923e-3611-4455-a1a3-74f4054bd4d0)

![image](https://github.com/OSGeo/PROJ/assets/84188706/a242c34b-bf76-4574-893f-8b4476bc1ede)
![image](https://github.com/OSGeo/PROJ/assets/84188706/0cb23c34-9cd2-434d-866d-8f31cf09a8f6)

**Comment by hopeyl** [comment]
It has been solved, and it is necessary to add the runtime link path in cmakelists.txt, `set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -wl,-rpath=${CMAKE_INSTALL_PREFIX}/lib")`, thanks for the answer last time.

**Comment by hopeyl** [comment]
However, I don't know if these warnings have a bad effect, since my cross-compiler version is 7.5.
![image](https://github.com/OSGeo/PROJ/assets/84188706/02152661-3a18-4ff5-a773-09c90717cd26)

**Comment by rouault** [comment]
> However, I don't know if these warnings have a bad effect, since my cross-compiler version is 7.5.

no, they are fine. This is just GCC warning about recent ABI changes done on their side. If you build everything with the same compiler, there's no issue
