### ISSUE TITLE
Error initializing invproj 9.1.1 with epsg PROJ_USE_PROJ4_INIT_RULES=YES 

### ISSUE THREAD

**Issue by bigopensky** [OSGeo/proj.4#4194]
#### Initialization of proj 9.1.1 with EPSG:NUM under Debian 6.1 fails

```
PROJ_USE_PROJ4_INIT_RULES=YES  invproj +init=epsg:32632
Rel. 9.1.1, December 1st, 2022
<invproj>: 
can't initialize operations that take non-angular input coordinates
program abnormally terminated
```

#### Environment

```
uname -a 
Linux test 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux
```

**Comment by rouault** [comment]
Support for passing CRS by codes was added in PROJ 9.3.0 per https://github.com/OSGeo/PROJ/commit/fde3d58e4af51f8e6c9cafeeb2b0299ab1218d91

$ echo 500000 0 | bin/invproj epsg:32632 
9dE	0dN


But you can also use cs2cs in a similar way:

$ echo 500000 0 | bin/cs2cs EPSG:32632
0dN	9dE 0.000

**Comment by bigopensky** [comment]
Do we have a regression?

PROJ_USE_PROJ4_INIT_RULES=YES  proj +init=epsg:32632
Rel. 9.6.0, March 15th, 2025
<proj>: 
can't initialize operations that take non-angular input coordinates. Try cct.
program abnormally terminated

uname -a
Linux thermal 6.12.48+deb13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.12.48-1 (2025-09-20) x86_64 GNU/Linux

As far as I can see we have no epsg file in /usr/share/proj.
