### ISSUE TITLE
Proj paramater string with "significant" or "junk" parameters returns incorrect transformation results for EPSG:4326 to some projected coordinate systems

### ISSUE THREAD

**Issue by oshawa-connection** [OSGeo/proj.4#4203]
This is related to [this issue](https://github.com/MapServer/MapServer/issues/7019) and [this PR](https://github.com/MapServer/MapServer/pull/7074) where mapserver, when returning map images in EPSG:4326 reading from a data source with certain projected CRS's, creates a bounding box that is "shifted", thus returning an incomplete set of features.

#### Example of problem
```shell
#our coordinates, somewhere in England
>cat test.txt
-1.019596665258943 52.47685985709986

#The 'correct' result 
>cs2cs +init=epsg:4326 +to +init=epsg:27700 test.txt
466685.8763237389, 286999.5190773061

# With +over applied, this is 'correct' and returns the same as above:
>cs2cs +init=epsg:4326 +over +to +init=epsg:27700 test.txt
466685.8763237389, 286999.5190773061

# now add extra "junk" parameter that is considered "significant" by io.cpp createFromPROJString
# point result is incorrect - it is shifted.
# This is what mapserver uses
>cs2cs +init=epsg:4326 +over +epsgaxis=ne +to +init=epsg:27700 test.txt
466580.48331214394, 287040.781993807 <----- Incorrect result! We expect this to be the same as the first example

# Same deal but with a different "junk" parameter 
>cs2cs +init=epsg:4326 +over +foo=bar +to +init=epsg:27700 test.txt
466580.48331214394, 287040.781993807 <----- Incorrect result! We expect this to be the same as the first example

# Just the junk parameter now:
>cs2cs +init=epsg:4326 +foo=bar +to +init=epsg:27700 test.txt
466580.48331214394, 287040.781993807 <----- Incorrect result! We expect this to be the same as the first example

```

Adding in "junk" parameters results in proj returning different and incorrect results, when we would expect the results to be the same.

This is a problem because mapserver using proj V9 upwards adds `+over` to proj parameter strings, as well as adding a mapserver specific parameter: `+epsgaxis=ne` which triggers the bug.

As we can see [here](https://github.com/OSGeo/PROJ/blob/cce46228bde5b7dfa6d3b9048865f43dfbbeda30/src/iso19111/io.cpp#L12247) during the projection construction, proj treats the "junk" parameters as significant, which causes it to build the projection using a different method. 

I am not sure of the best way to approach a fix. A quick and simple fix would be to add "epsgaxis" to the list of "insignificant keys" here: 

https://github.com/OSGeo/PROJ/blob/cce46228bde5b7dfa6d3b9048865f43dfbbeda30/src/iso19111/io.cpp#L12252

which would cover the mapserver use case at least. However, I don't know if other proj users are suffering from this too in their use cases and whether its worth attacking the more deep seated issue. 

I only tested that the problem existed when transforming EPSG:4326 to all projected coordinate systems defined in proj.db. Some projected coordinate systems are unaffected, but a significant number were. I could not find a pattern to which systems were affected and which weren't. EPSG:27700 is an example of an affected one.

#### Environment Information

- PROJ version (`proj`) 9.4.1

**Comment by rouault** [comment]
> I am not sure of the best way to approach a fix. A quick and simple fix would be to add "epsgaxis" to the list of "insignificant keys" here:

That's the best fix I can think of. Done in https://github.com/OSGeo/PROJ/pull/4204

**Comment by rouault** [comment]
closing as wont fix
