### ISSUE TITLE
rHEALPix projection behaviour at lon = -180 deg

### ISSUE THREAD

**Issue by ndemaio** [OSGeo/proj.4#4214]
Hi all, I noticed something unexpected when I tried the rhealpix projection at a longitude of -180 deg:

```
echo -180 74.39069094879065 | proj +proj=rhealpix +ellps=WGS84 | invproj +proj=rhealpix +ellps=WGS84

               179d59'59.999"E 74d23'26.487"N
```
I realise that the longitude of the result is very close to what went in. But note the flipped sign.

Is this a behaviour you’d expect? If so, would you have any recommendations of how to handle the fact that the sign gets inverted?

We’re currently evaluating whether it makes sense to switch from a Python implementation of the healpix/rhealpix projections to those provided by PROJ. The sign change making our existing tests fail and blocking progress on reaching a decision.

I’ve tried the incantation above with PROJ versions 9.3.0 and 9.4.1, getting identical results.

Any advice would be appreciated!

**Comment by kbevers** [comment]
By default `proj` truncates the result to two decimalplaces if you don't ask for more. Increase the accuracy of the coordinate output and you get about as close to your starting point as you can expect:

```bash
$ echo -180 74.39069094879065 | proj -d 15 +proj=rhealpix +ellps=WGS84 | invproj -d 15 +proj=rhealpix +ellps=WGS84                                   [21:08:42]
-180.000000000000085    74.390690948040316
```
