### ISSUE TITLE
Request to Include Burkina Faso Transverse Mercator (BFTM) Projection System in Future Updates

### ISSUE THREAD

**Issue by Kapson-kreate** [OSGeo/proj.4#4232]
**Request for Adding a New Coordinate Reference System (CRS)**

I am requesting that the coordinate reference system (CRS) for Burkina Faso be considered for inclusion in future updates of the PROJ library.

Burkina Faso has adopted a custom projection system called BFTM (Burkina Faso Transverse Mercator) due to the limitations and distortions of the UTM projection. The parameters for this projection are as follows:

- **Geodetic Datum**: ITRF 2008
- **Ellipsoid**: GRS80
- **Central Meridian**: -1.5°
- **Prime Meridian**: Greenwich 0
- **False Easting**: x0 = 600,000.00 m
- **False Northing**: y0 = 0.00 m
- **Scale Factor**: 0.9996

This projection is essentially an expanded UTM zone 30 to fit the entire country into a single zone.

Here is the CRS in WKT format:

PROJCS["BFTM30", GEOGCS["WGS 84", DATUM["ITRF_2008", SPHEROID["GRS 1980",6378137,298.257222101, AUTHORITY["EPSG","7019"]],
TOWGS84[0,0,0,0,0,0,0],
AUTHORITY["EPSG","1149"]],
PRIMEM["Greenwich",0, AUTHORITY["EPSG","8901"]],
UNIT["degree",0.0174532925199433, AUTHORITY["EPSG","9122"]],
AUTHORITY["EPSG","4149"]],
PROJECTION["Transverse_Mercator"],
PARAMETER["latitude_of_origin",0],
PARAMETER["central_meridian",-1.5],
PARAMETER["scale_factor",0.9996],
PARAMETER["false_easting",600000],
PARAMETER["false_northing",0],
UNIT["metre",1, AUTHORITY["EPSG","9001"]],
AXIS["Easting",EAST],
AXIS["Northing",NORTH],
AUTHORITY["EPSG","32630"]]

**Comment by jjimenezshaw** [comment]
Hi @Kapson-kreate 
PROJ is based mainly in data from EPSG
You should do this request at https://epsg.org/dataset-change-requests.html
Once it is in EPSG, it will be automatically included in PROJ and also in any other software that uses EPSG (when they update).

**Comment by Kapson-kreate** [comment]
Hi, tank for answer
