### ISSUE TITLE
gdaltransform: tool is not selecting the appropriate operation candidate (linked to PROJ too)

### ISSUE THREAD

**Issue by CharlesPapasodoro** [OSGeo/proj.4#4239]
### What is the bug?

Using the following gdaltransform operation, I obtain a Z value that is ~16 cm off to what I should normally obtain. 
gdaltransform -s_srs "EPSG:3413+4979" -t_srs "EPSG:3413+6647"
-3229385.9 5406.8 686.8906
-3229385.9 5406.8 679.655

Using projinfo on this transformation, I see 3 operation candidates: the first one seems the appropriate one (because it's using the CGG2013_i08.tif geoid grid that fits with the horizontal crs and has no ballpark transformation), while the 2 others are not and furthermore they contain ballpark transformations. 

Digging deeper, using the proj pipeline produced by projinfo with gdaltransform (with the -ct switch), I found out that the second operation (with ballpark transformation) was seemingly chosen from the start, instead of the first operation. 

Shouldn't GDAL/proj select by default the operation candidate that has no ballpark transformation and that contains the appropriate grids?

The problem also occurs with other gdal tools (e.g. gdalwarp), as well as with cs2cs from PROJ.

### Steps to reproduce the issue

---Basic operation

gdaltransform -s_srs "EPSG:3413+4979" -t_srs "EPSG:3413+6647"

-3229385.9 5406.8 686.8906
-3229385.9 5406.8 679.655

---Tranformation with the proj pipeline of the first candidate operation (pipeline obtained via projinfo). I believe this should be the right operation to choose.

gdaltransform -ct "+proj=pipeline +step +inv +proj=stere +lat_0=90 +lat_ts=70 +lon_0=-45 +x_0=0 +y_0=0 +ellps=WGS84 +step +inv +proj=vgridshift +grids=ca_nrc_CGG2013i08.tif  +multiplier=1 +step +proj=stere +lat_0=90 +lat_ts=70 +lon_0=-45 +x_0=0 +y_0=0 +ellps=WGS84"

-3229385.9 5406.8 686.8906
-3229385.9 5406.8 679.494

---Tranformation with the proj pipeline of the second candidate operation (pipeline obtained via projinfo). Result is identical to the basic operation results, even though this transformation is not using the right grid and has ballpark transformation.

gdaltransform -ct "+proj=pipeline +step +inv +proj=stere +lat_0=90 +lat_ts=70 +lon_0=-45 +x_0=0 +y_0=0 +ellps=WGS84 +step +inv +proj=vgridshift +grids=ca_nrc_CGG2013n83.tif +multiplier=1 +step +proj=stere +lat_0=90 +lat_ts=70 +lon_0=-45 +x_0=0 +y_0=0 +ellps=WGS84

-3229385.9 5406.8 686.8906
-3229385.9 5406.8 679.655

### Versions and provenance

Windows 10
GDAL 3.9.0, released 2024/05/07
PROJ: Rel. 9.4.0, March 1st, 2024

**Comment by rouault** [comment]
Can be replicated with:
```
$ echo -3229385.9 5406.8 686.8906 | PROJ_NETWORK=ON PROJ_DEBUG=ON bin/cs2cs -d 3 "EPSG:3413+4979" "EPSG:3413+6647"
[...]
Using coordinate operation Inverse of US NSIDC Sea Ice polar stereographic north + Inverse of Null geographic offset from WGS 84 (geog2D) to WGS 84 (geog3D) + Inverse of NAD83(2011) to WGS 84 (1) + Inverse of Conversion from NAD83(2011) (geocentric) to NAD83(2011) (geog2D) + Inverse of NAD83(CSRS)v6 to NAD83(2011) (1) + Inverse of Conversion from NAD83(CSRS)v6 (geog3D) to NAD83(CSRS)v6 (geocentric) + NAD83(CSRS)v6 to CGVD2013(CGG2013) height (1) + Inverse of Conversion from NAD83(CSRS)v6 (geocentric) to NAD83(CSRS)v6 (geog2D) + NAD83(CSRS)v6 to NAD83(2011) (1) + Inverse of Conversion from NAD83(2011) (geog2D) to NAD83(2011) (geocentric) + NAD83(2011) to WGS 84 (1) + US NSIDC Sea Ice polar stereographic north
pj_open_lib(ca_nrc_CGG2013n83.tif): call fopen(ca_nrc_CGG2013n83.tif) - failed
pj_open_lib(CGG2013n83.gtx): call fopen(CGG2013n83.gtx) - failed
Using https://cdn.proj.org/ca_nrc_CGG2013n83.tif
-3229385.900	5406.800 679.655
```

The thing is that the transformation using +grids=ca_nrc_CGG2013i08.tif (the first one listed) has a computed accuracy of 4.05 m, whereas the second one, using +grids=ca_nrc_CGG2013n83.tif has an accuracy of 4.03 m. Hence it is selected. It is listed as seond by projinfo because it has a smaller area of use than the first one, but once we know the coordinate to transform, and if it falls into the second one, it is used as being slighlty more accurate.

So PROJ behave as "expected" here

**Comment by CharlesPapasodoro** [comment]
Thanks Even for the quick response.

I understand PROJ's behavior. However, I am wondering how the accuracy of each operation was obtained or calculated? I don't understand how the accuracy of an operation containing ballpark transformations could be better than that of an operation without ballpark transformations.

From NRCan's GPS.H web tool, the uncertainty for both geoid grids in this region is far less than that, at about 2.4 cm (for both grids).
![gps h](https://github.com/user-attachments/assets/a1fd5fa5-e3e8-4c4a-b2e0-089d27c8425e)

**Comment by rouault** [comment]
> However, I am wondering how the accuracy of each operation was obtained or calculated?

Just adding the accuracy of each of the chained transformations

> I don't understand how the accuracy of an operation containing ballpark transformations

There's no ballpark transformation in the one using any of those grids, only registered no-op datum transformation between a number of the used datums

> From NRCan's GPS.H web tool,

Does the NRCan tool uses a WGS 84 datum ?  I doubt so. This is what causes the additional inaccuracies in PROJ

PROJ cannot do better in automated mode for such a complex transformation where it has to infer a lot of intermediate steps. To get a "better" result (is it sure that the one you want is the right one?), you'd need to tweak the PROJ database to register the exact transformation for your (source, target) tuple.

**Comment by CharlesPapasodoro** [comment]
> Does the NRCan tool uses a WGS 84 datum ? I doubt so. This is what causes the additional inaccuracies in PROJ

By the two geoids, I meant CGG2013 referenced to ITRF2008 and CGG2013 referenced to NAD83(CSRS).

> is it sure that the one you want is the right one?

I'm not 100% certain that operation 1 (using the CGG2013 grid referenced to ITRF2008) is the most accurate for our purposes, but my understanding is that it would be. ITRF2008 is typically better aligned with WGS84 (the dataset's horizontal reference system) than NAD83(CSRS), which may contain local specificities. I'll contact NRCan Geodetic Survey to be sure and I'll be okay for the next steps.

Thank you for your help!

**Comment by rouault** [comment]
> By the two geoids, I meant CGG2013 referenced to ITRF2008 and CGG2013 referenced to NAD83(CSRS).

I understand that, but EPSG:3413+4979 to EPSG:3413+6647 involves the WGS 84 datum ensemble, which has an intrinsic inaccuracy of 2 m, and not one of its realization in the source CRS. And generally transformations for national datums do not exist from/to the WGS 84 datum ensemble, or with a degraded accuracy

**Comment by CharlesPapasodoro** [comment]
Just an FYI, NRCan's geodetic team confirmed that the appropriate operation here is the one using the CGG2013 geoid referenced to ITRF2008. WGS84 and ITRF08 are well aligned, while NAD83CSRS and ITRF08 have an origin difference of 2.2m. We'll select this operation for our conversion. Thanks again.

**Comment by rouault** [comment]
> Just an FYI, NRCan's geodetic team confirmed that the appropriate operation here is the one using the CGG2013 geoid referenced to ITRF2008. WGS84 and ITRF08 are well aligned, while NAD83CSRS and ITRF08 have an origin difference of 2.2m. 

PROJ could potentially give better results if NRCan would also register a transformation using the CGG2013_i08 grid from WGS 84 (EPSG:4979) to EPSG:6647

**Comment by CharlesPapasodoro** [comment]
Hello Even, just to close this case, NRCan's geodetic team responded that they prefer not to register this transformation due to the intrinsic 2m inaccuracy of WGS84 datum ensemble. Moreover, the ITRF version is intended only for scientific purposes and the official use is with the NAD83(CSRS) version.
