### ISSUE TITLE
EPSG 2326 crashing

### ISSUE THREAD

**Issue by Julien-Yellowscan** [OSGeo/proj.4#4243]
When processing a dataset and projecting points with proj, I encountered a case where, if I use EPSG:2326, I will end up with a crash when calling proj_trans. 
When using other projections, everything happens as expected and I end up with correct results. If I create a custom projection using the proj string associated with EPSG:2326, it's also working perfectly fine.

I unfortunately cannot create a simple exemple to share but this is perfectly reproductible with all the datasets I'm using. EPSG:2362 is crashing everytime but at random points in the processing

If someone wants to look into it I can share more details

Best !

**Comment by jjimenezshaw** [comment]
> I unfortunately cannot create a simple exemple to share but this is perfectly reproductible 

Without an example it is really difficult to say anything.

> with all the datasets I'm using.

That sounds like all your datasets have the same problem.


You are not even mentioning how are you using PROJ!

**Comment by rouault** [comment]
@Julien-Yellowscan Basic usage works fine for me. Cf below
```
$ echo 819069.8 836694.05 | bin/cs2cs -d 8 EPSG:2326 EPSG:4326
22.31060243	114.18100933 0.00000000

$ echo 22.31060243 114.18100933  | bin/cs2cs -d 2 EPSG:4326 EPSG:2326 
819069.80	836694.05 0.00
```

**Comment by rouault** [comment]
@Julien-Yellowscan Any update on how to exactly reproduce your issue?

**Comment by Julien-Yellowscan** [comment]
Sorry I couldn't find the time to reproduce it yet but I will keep you posted asap 🫡
Thank you all for being so responsive

**Comment by Daniel-Huff** [comment]
@rouault  using cs2cs, i can get right tranform. But when using some code i write
 ```
std::vector<osg::Vec3d> convertToEPSG2326(const std::vector<Vertex>& vertices) {
    PJ_CONTEXT* C = proj_context_create();
    PJ* P = proj_create_crs_to_crs(C, "EPSG:4326", "EPSG:2326", nullptr);
    PJ* P_for_GIS = proj_normalize_for_visualization(C, P);

    std::vector<osg::Vec3d> projectedVertices;

    for (const auto& v : vertices) {
        PJ_COORD input;
        input.lpzt.lam = proj_torad(v.lon);  // 经度
        input.lpzt.phi = proj_torad(v.lat);  // 纬度
        input.lpzt.z = v.alt;  // 高度

        PJ_COORD output = proj_trans(P_for_GIS, PJ_FWD, input);
        projectedVertices.push_back(osg::Vec3d(output.xyz.x, output.xyz.y, output.xyz.z));
    }

    proj_destroy(P);
    proj_context_destroy(C);

    return projectedVertices;
}
```
i can not get right result, is there some wrong i made

**Comment by Daniel-Huff** [comment]
![image](https://github.com/user-attachments/assets/c22286f2-85d9-4348-9620-2bea9248a024)

**Comment by rouault** [comment]
Instead of
> input.lpzt.lam = proj_torad(v.lon);  // 经度
>        input.lpzt.phi = proj_torad(v.lat);  // 纬度
>        input.lpzt.z = v.alt;  // 高度

use:
```
input.v[0] = v.lat;   // in degree
input.v[1] = v.lon;   // in degree
input.v[2] = v.alt;
input.v[3] = HUGE_VAL; // coordinate epoch unknown
```
since EPSG:4326 is defined as being (lat, lon) ordered.

**Comment by rouault** [comment]
Ah sorry, my above post is incorrect since you've used proj_normalize_for_visualization(). So either you remove it, and above snippet will be fine, or you keep it, but switches lat and lon. But in any case, they must be in degree

**Comment by Daniel-Huff** [comment]
![mmexport1726158960984](https://github.com/user-attachments/assets/a60355f1-24e0-470a-b256-b27d28411549)
Tks for your reply, solved my problem immediately.

**Comment by jjimenezshaw** [comment]
@Julien-Yellowscan mentioned "crashing". Is that what you had, @Daniel-Huff ? Or had you just wrong results?

Using the wrong input produces a "wrong" output... but it should not _crash_ (just because the input is in radians). Anyhow, we do not know what @Julien-Yellowscan was doing exactly. (Or are you two connected?)

**Comment by Daniel-Huff** [comment]
Yes, I just got the wrong result, all the code executed smoothly, no crashing.
thank you again
