### ISSUE TITLE
Vertical transformations advices for PROJ >= 9.1 version

### ISSUE THREAD

**Issue by cdouliac** [OSGeo/proj.4#4261]
Hello, I would like some precision about CRS conversions.

I'm aware that there are some changes about vertical transformations with PROJ >= 9.1 as stated here : https://github.com/OSGeo/PROJ/pull/3119
Or here : https://proj.org/en/9.4/apps/cs2cs.html#cmdoption-cs2cs-3d "Starting with PROJ 9.1, both CRS need to be 3D for vertical transformation to possibly happen."
I tested it and I recreated the behavior of pre 9.1 and post 9.1 versions : 

-PROJ 8.2.0 : 
echo 0 0 1000 | cs2cs +proj=longlat +datum=WGS84 +geoidgrids=/proj-build/data/for_tests/egm96_15.tif +vunits=m +no_defs +type=crs +to +proj=longlat +datum=WGS84 +no_defs +type=crs -f "%.14f"
0.00000000000000        0.00000000000000 1017.16157913208008

-PROJ 9.2.0
echo 0 0 1000 | cs2cs +proj=longlat +datum=WGS84 +geoidgrids=/proj-build/data/for_tests/egm96_15.tif +vunits=m +no_defs +type=crs +to +proj=longlat +datum=WGS84 +no_defs +type=crs -f "%.14f"
0.00000000000000        0.00000000000000 1000.00000000000000

I would like to have some advice to get the past behavior, sometimes I need to do theses vertical transformations.
I have found some tips here : https://github.com/OSGeo/PROJ/pull/3119#issuecomment-1069313458 and here https://github.com/OSGeo/PROJ/pull/3119#issuecomment-1069272183.
From theses comments I understood that I need to promote theses CRS to 3D, more precisely the PJ_TYPE_GEOGRAPHIC_2D_CRS and PJ_TYPE_PROJECTED_CRS types.

Did I understood the comments right? Are there any other cases (types) that I should take care the same way? Should I only look for the type of CRS or is there other information that I need to look for? 
My main goal is to get the past behavior.

**Comment by busstoptaktik** [comment]
Github issues is for reporting issues. Usage questions belong on the PROJ mailing list. See https://proj.org/en/9.5/community/channels.html

**Comment by cdouliac** [comment]
Oh sorry for the inconvenience

**Comment by busstoptaktik** [comment]
@cdouliac - don't worry. It is just much more likely you will get a relevant reply on the mailing list
