### ISSUE TITLE
Projection parameter(s) missing from WKT string output

### ISSUE THREAD

**Issue by jgale011** [OSGeo/proj.4#4317]
#### Problem summary

After importing [this](https://github.com/user-attachments/files/17680619/longitude_param_modified_wkt.txt) WKT2 string and then requesting a WKT2 string output, the output's Latitude of natural origin projection parameter is missing.  

Initially discovered using GDAL's SetFromUserInput to create an OGRSpatialReference, then output using exportToWkt.

Below I've reproduced this without GDAL using projinfo.

```c
projinfo @longitude_param_modified_wkt.txt
PROJ.4 string:
+proj=eqc +lat_ts=0 +lat_0=0 +lon_0=92 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs +type=crs

WKT2:2019 string:
PROJCRS["",
    BASEGEOGCRS["WGS 84",
        ENSEMBLE["World Geodetic System 1984 ensemble",
            MEMBER["World Geodetic System 1984 (Transit)"],
            MEMBER["World Geodetic System 1984 (G730)"],
            MEMBER["World Geodetic System 1984 (G873)"],
            MEMBER["World Geodetic System 1984 (G1150)"],
            MEMBER["World Geodetic System 1984 (G1674)"],
            MEMBER["World Geodetic System 1984 (G1762)"],
            MEMBER["World Geodetic System 1984 (G2139)"],
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]],
            ENSEMBLEACCURACY[2.0]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]]],
    CONVERSION["",
        METHOD["Equidistant Cylindrical (Spherical)"],
        PARAMETER["Longitude of natural origin",92,
            ANGLEUNIT["degree",0.0174532925199433]],
        PARAMETER["False easting",0,
            LENGTHUNIT["metre",1]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1]]],
    CS[Cartesian,2],
        AXIS["easting (X)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["northing (Y)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]]]

```

#### Problem description

This WKT2 string was created by modifying the Longitude of natural origin projection parameter of EPSG:32662.  The original WKT2 string had a Latitude of natural origin parameter.  When requesting WKT2 output from projinfo, this parameter is missing.

Looking into this a bit, I found another projection method that seems to be showing a similar looking phenomenon.  If I modify the Longitude of topocentric origin projection parameter of a WKT2 string created from ESRI:54049 or ESRI:53049, the False easting and False northing parameters disappear from the output WKT2 string.

#### Expected Output

The WKT strings were expected to maintain the same set of projection parameters as their originals.

#### Environment Information

- PROJ version 9.3.1
- Reproduced on Windows, Ubuntu, Debian

**Comment by rouault** [comment]
This is by design. The Latitude of origin in this projection method is a PROJ extension compared to the parameters allowed in the EPSG formulas. So if its value is 0, which is its default value, we optimize it away to fit within the EPSG framework.

**Comment by jgale011** [comment]
Interesting.  Thanks for the insight.  Is that true for the Vertical Perspective case in the description too?  

Are there ways to know whether the parameter is a PROJ extension or from the EPSG formula?

**Comment by rouault** [comment]
> Are there ways to know whether the parameter is a PROJ extension or from the EPSG formula?

the magic of open source: look at the only source of truth... the source code :-) :-)

For eqc: https://github.com/OSGeo/PROJ/blob/9f2289cfdca3dbb69444e6f1ef5ab18906f17dfc/src/iso19111/operation/parammappings.cpp#L277
For vertical perspective: https://github.com/OSGeo/PROJ/blob/9f2289cfdca3dbb69444e6f1ef5ab18906f17dfc/src/iso19111/operation/parammappings.cpp#L547

**Comment by jgale011** [comment]
> the source code :-) :-)

True. Thanks again for the explanation. The behavior was unexpected, but now that I understand what is happening, I see why this isn't a bug.
