### ISSUE TITLE
ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db

### ISSUE THREAD

**Issue by dylowens** [OSGeo/proj.4#4351]
### Example of Problem

When using the `gdal_translate` tool with GDAL and PROJ installed via Conda, I encounter the following error while attempting to georeference an image:

Command:
gdal_translate -a_srs EPSG:4326 -gcp 43 45.5625 -119.96858531559471 41.9704999608133 -gcp 49 208.5625 -120.02357213221137 39.03621210671773 C:/Projects/Nevada_Image.png output.tif

Error Output:
Input file size is 598, 766
ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db

---

### Minimal, Complete and Verifiable Example

The following C code snippet reproduces the issue by using the PROJ API to create a CRS from EPSG:4326. The problem occurs when PROJ cannot locate the `proj.db` database file, despite the environment variable `PROJ_LIB` being correctly set.

#include <stdio.h>
#include <proj.h>

int main() {
    PJ_CONTEXT *ctx = proj_context_create();
    if (!ctx) {
        fprintf(stderr, "Failed to create PROJ context\n");
        return 1;
    }

    PJ *crs = proj_create(ctx, "EPSG:4326");
    if (!crs) {
        fprintf(stderr, "Failed to create CRS: %s\n", proj_errno_string(proj_context_errno(ctx)));
        proj_context_destroy(ctx);
        return 1;
    }

    printf("CRS successfully created: %s\n", proj_get_name(crs));

    proj_destroy(crs);
    proj_context_destroy(ctx);
    return 0;
}

Compile the code with:
gcc -o proj_test proj_test.c -lproj

Run the program:
./proj_test

Expected Output:
CRS successfully created: WGS 84

Actual Output:
Failed to create CRS: proj_create_from_database: Cannot find proj.db

---

### Problem Description

The issue stems from PROJ's inability to locate the `proj.db` database file.

I have ensured the following:
1. The `PROJ_LIB` environment variable is correctly set to the directory containing `proj.db`.
2. The file `proj.db` exists in the specified directory.

However, the error persists.

---

### Expected Output

The georeferencing operation or CRS creation should succeed without errors, as the `proj.db` file is present and accessible at the location specified by `PROJ_LIB`.

### Environment Information

- **PROJ Version**: 9.5.1
- **GDAL Version**: 3.9.3
- **Operating System**: Windows 10 (64-bit)
- **Installation Method**: Conda (channel: conda-forge)

Environment Variables:
PROJ_LIB=C:\path\anaconda3\Library\share\proj
GDAL_DATA=C:\path\anaconda3\Library\share\gdal

---

### Installation Method

Installed using Conda:

conda install -c conda-forge gdal=3.9.3 proj=9.5.1
 
Is anyone else encountering this error?

**Comment by dylowens** [comment]
Help is appreciated!

**Comment by rouault** [comment]
PROJ_LIB has now been deprecated, although it should still work. PROJ_DATA is the new recommended name. By chance, don't you have both in your environment ?

**Comment by rouault** [comment]
@dylowens ping

**Comment by dylowens** [comment]
Sorry for the late response. I updated the environment variable to for PROJ_DATA and the proj.db file was found. I am not sure why it was not working with PROJ_LIB as you said it should still work. But either way, setting the PROJ_DATA variable to the proj.db file path solved the problem. Thanks!
