### ISSUE TITLE
Why ”+towgs84“ doesn't work?

### ISSUE THREAD

**Issue by HlKun** [OSGeo/proj.4#4360]
**Problem description**

![0](https://github.com/user-attachments/assets/acf2fd96-dbe3-4492-b300-b0f5c383960d)

![1](https://github.com/user-attachments/assets/d1f91167-ad7f-462b-8cb5-2e09606d377e)

**Environment Information**
PROJ version (proj) 9.5.0
Operation System Information W11

**Installation method**
from source

**Comment by rouault** [comment]
try adding +towgs84=0,0,0 to the CRS that lacks a +towgs84 clause
